const maleNames = [
    { name: "Grommash", meaning: "Fierce hammer" },
    { name: "Durotan", meaning: "Strong as stone" },
    { name: "Orgrim", meaning: "Fearless leader" },
    { name: "Kargath", meaning: "Blood warrior" },
    { name: "Blackhand", meaning: "Dark fist" },
    { name: "Garrosh", meaning: "Iron heart" },
    { name: "Morgash", meaning: "Death bringer" },
    { name: "Grimgor", meaning: "Tough and grim" },
    { name: "Skarsnik", meaning: "Sharp mind" },
    { name: "Gorbad", meaning: "Great rage" },
    { name: "Azog", meaning: "Cruel one" },
    { name: "Bolg", meaning: "Strong arm" },
    { name: "Shagrat", meaning: "Red blade" },
    { name: "Gothmog", meaning: "Dark lord" },
    { name: "Lurtz", meaning: "Hunter" },
    { name: "Ugluk", meaning: "Ugly but strong" },
    { name: "Mauhur", meaning: "Dark spirit" },
    { name: "Sharku", meaning: "Old wolf" },
    { name: "Zog", meaning: "Battle leader" },
    { name: "Grak", meaning: "Crusher" },
    { name: "Korg", meaning: "Rock" },
    { name: "Ruk", meaning: "Destroyer" },
    { name: "Thrak", meaning: "Thunder" },
    { name: "Morg", meaning: "Death" },
    { name: "Harg", meaning: "Hateful" },
    { name: "Karg", meaning: "Boar" },
    { name: "Varg", meaning: "Wolf" },
    { name: "Grol", meaning: "Fat but strong" },
    { name: "Drog", meaning: "Ogre" },
    { name: "Torg", meaning: "Giant" },
    { name: "Bor", meaning: "Strong" },
    { name: "Grim", meaning: "Gloomy" },
    { name: "Rok", meaning: "Stone" },
    { name: "Vrok", meaning: "Twisted" },
    { name: "Krok", meaning: "Crooked" },
    { name: "Mrok", meaning: "Dark" },
    { name: "Brok", meaning: "Bad" },
    { name: "Frok", meaning: "Ugly" },
    { name: "Grok", meaning: "Understand" },
    { name: "Zrok", meaning: "Angry" },
    { name: "Arg", meaning: "Sharp" },
    { name: "Sarg", meaning: "Deadly" },
    { name: "Marg", meaning: "Horse" },
    { name: "Harg", meaning: "Hammer" },
    { name: "Garg", meaning: "Roar" },
    { name: "Narg", meaning: "Furious" },
    { name: "Parg", meaning: "Crash" },
    { name: "Targ", meaning: "Bite" },
    { name: "Warg", meaning: "Wolf" },
    { name: "Yarg", meaning: "Shout" },
    { name: "Zarg", meaning: "Destroy" },
    { name: "Gurgrim", meaning: "Grim bear" },
    { name: "Korgath", meaning: "Rock tooth" },
    { name: "Morgul", meaning: "Dark sorcery" },
    { name: "Raknar", meaning: "Blood nose" },
    { name: "Skullgrin", meaning: "Skull smile" },
    { name: "Bonecrusher", meaning: "Bone breaker" },
    { name: "Bloodaxe", meaning: "Bloody axe" },
    { name: "Ironfist", meaning: "Iron hand" },
    { name: "Darkthroat", meaning: "Dark voice" },
    { name: "Gorehide", meaning: "Bloody skin" },
    { name: "Slagg", meaning: "Dirty" },
    { name: "Krath", meaning: "Death" },
    { name: "Zarath", meaning: "Tyrant" },
    { name: "Narath", meaning: "Strong" },
    { name: "Marath", meaning: "Great" },
    { name: "Karath", meaning: "Cruel" },
    { name: "Varath", meaning: "Powerful" },
    { name: "Torath", meaning: "Mighty" },
    { name: "Lorath", meaning: "Fierce" },
    { name: "Korath", meaning: "Brave" },
    { name: "Morath", meaning: "Evil" },
    { name: "Gorath", meaning: "Tough" },
    { name: "Horath", meaning: "Horrible" },
    { name: "Norath", meaning: "North" },
    { name: "Borath", meaning: "Strong" },
    { name: "Dorath", meaning: "Dark" },
    { name: "Rorath", meaning: "Roaring" },
    { name: "Vorath", meaning: "Hungry" },
    { name: "Xorath", meaning: "Deadly" },
    { name: "Zorath", meaning: "Wild" },
    { name: "Grimskar", meaning: "Grim scar" },
    { name: "Bloodsnarl", meaning: "Bloody snarl" },
    { name: "Ironjaw", meaning: "Iron jaw" },
    { name: "Stonefist", meaning: "Stone hand" },
    { name: "Darkblade", meaning: "Dark sword" },
    { name: "Skullcrusher", meaning: "Skull breaker" },
    { name: "Goreaxe", meaning: "Bloody axe" },
    { name: "Tuskfang", meaning: "Tusk tooth" },
    { name: "Ragefist", meaning: "Angry hand" },
    { name: "Deathgrin", meaning: "Death smile" },
    { name: "Morgash", meaning: "Dark ash" },
    { name: "Grakath", meaning: "Crush tooth" },
    { name: "Korgash", meaning: "Rock ash" },
    { name: "Rokash", meaning: "Stone ash" },
    { name: "Vorgash", meaning: "Twisted ash" },
    { name: "Morgath", meaning: "Dark tooth" },
    { name: "Gorgath", meaning: "Monster tooth" },
    { name: "Horgath", meaning: "Horror tooth" },
    { name: "Korgath", meaning: "Rock tooth" },
    { name: "Rorgath", meaning: "Roar tooth" },
    { name: "Sorgath", meaning: "Evil tooth" },
    { name: "Torgath", meaning: "Giant tooth" },
    { name: "Worgath", meaning: "Wolf tooth" },
    { name: "Zorgath", meaning: "Destructive tooth" },
    { name: "Grimmok", meaning: "Grim orc" },
    { name: "Kormok", meaning: "Rock orc" },
    { name: "Rommok", meaning: "Roar orc" },
    { name: "Trommok", meaning: "Thunder orc" },
    { name: "Vommok", meaning: "Twisted orc" },
    { name: "Zommok", meaning: "Wild orc" },
    { name: "Grimzog", meaning: "Grim beast" },
    { name: "Korzog", meaning: "Rock beast" },
    { name: "Rorzog", meaning: "Roar beast" },
    { name: "Torzog", meaning: "Thunder beast" },
    { name: "Vorzog", meaning: "Twisted beast" },
    { name: "Zorzog", meaning: "Wild beast" },
    { name: "Gorbag", meaning: "Old orc" },
    { name: "Sharku", meaning: "Old wolf" },
    { name: "Ufthak", meaning: "Strong arm" },
    { name: "Mauhur", meaning: "Dark spirit" },
    { name: "Lugdush", meaning: "Red eye" },
    { name: "Malak", meaning: "Angel of death" },
    { name: "Nazg", meaning: "Ringwraith" },
    { name: "Pash", meaning: "Bad" },
    { name: "Zash", meaning: "Angry" },
    { name: "Kash", meaning: "Cruel" },
    { name: "Rash", meaning: "Quick" },
    { name: "Mash", meaning: "Crush" },
    { name: "Gash", meaning: "Cut" },
    { name: "Hash", meaning: "Hatred" },
    { name: "Vash", meaning: "Hunger" },
    { name: "Dash", meaning: "Run" },
    { name: "Tash", meaning: "Destroy" },
    { name: "Skarr", meaning: "Scar" },
    { name: "Karr", meaning: "Cut" },
    { name: "Rarr", meaning: "Roar" },
    { name: "Tarr", meaning: "Tar" },
    { name: "Warr", meaning: "War" },
    { name: "Zarr", meaning: "Anger" },
    { name: "Farr", meaning: "Far" },
    { name: "Harr", meaning: "Harsh" },
    { name: "Jarr", meaning: "Jarring" },
    { name: "Marr", meaning: "Bitter" },
    { name: "Narr", meaning: "Fool" },
    { name: "Parr", meaning: "Speak" },
    { name: "Quarr", meaning: "Question" },
    { name: "Sarr", meaning: "Snarl" },
    { name: "Varr", meaning: "Wolf" },
    { name: "Yarr", meaning: "Shout" },
    { name: "Zarr", meaning: "Anger" }
];

const femaleNames = [
    { name: "Gromma", meaning: "Fierce mother" },
    { name: "Durotah", meaning: "Strong stone" },
    { name: "Orgrina", meaning: "Fearless queen" },
    { name: "Kargatha", meaning: "Blood maiden" },
    { name: "Blackhanda", meaning: "Dark fist" },
    { name: "Garrosha", meaning: "Iron heart" },
    { name: "Morgasha", meaning: "Death bringer" },
    { name: "Grimgora", meaning: "Tough and grim" },
    { name: "Skarsnika", meaning: "Sharp mind" },
    { name: "Gorbada", meaning: "Great rage" },
    { name: "Azoga", meaning: "Cruel one" },
    { name: "Bolga", meaning: "Strong arm" },
    { name: "Shagrata", meaning: "Red blade" },
    { name: "Gothmoga", meaning: "Dark lady" },
    { name: "Lurtza", meaning: "Hunter" },
    { name: "Ugluka", meaning: "Ugly but strong" },
    { name: "Mauhura", meaning: "Dark spirit" },
    { name: "Sharkua", meaning: "Old wolf" },
    { name: "Zoga", meaning: "Battle leader" },
    { name: "Grakka", meaning: "Crusher" },
    { name: "Korgga", meaning: "Rock" },
    { name: "Rukka", meaning: "Destroyer" },
    { name: "Thrakka", meaning: "Thunder" },
    { name: "Morgga", meaning: "Death" },
    { name: "Hargga", meaning: "Hateful" },
    { name: "Kargga", meaning: "Boar" },
    { name: "Vargga", meaning: "Wolf" },
    { name: "Grolla", meaning: "Fat but strong" },
    { name: "Drogga", meaning: "Ogre" },
    { name: "Torgga", meaning: "Giant" },
    { name: "Borra", meaning: "Strong" },
    { name: "Grimma", meaning: "Gloomy" },
    { name: "Rokka", meaning: "Stone" },
    { name: "Vrokka", meaning: "Twisted" },
    { name: "Krokka", meaning: "Crooked" },
    { name: "Mrokka", meaning: "Dark" },
    { name: "Brokka", meaning: "Bad" },
    { name: "Frokka", meaning: "Ugly" },
    { name: "Grokka", meaning: "Understand" },
    { name: "Zrokka", meaning: "Angry" },
    { name: "Arga", meaning: "Sharp" },
    { name: "Sarga", meaning: "Deadly" },
    { name: "Marga", meaning: "Horse" },
    { name: "Harga", meaning: "Hammer" },
    { name: "Garga", meaning: "Roar" },
    { name: "Narga", meaning: "Furious" },
    { name: "Parga", meaning: "Crash" },
    { name: "Targa", meaning: "Bite" },
    { name: "Warga", meaning: "Wolf" },
    { name: "Yarga", meaning: "Shout" },
    { name: "Zarga", meaning: "Destroy" },
    { name: "Gurgrima", meaning: "Grim bear" },
    { name: "Korgatha", meaning: "Rock tooth" },
    { name: "Morgula", meaning: "Dark sorcery" },
    { name: "Raknara", meaning: "Blood nose" },
    { name: "Skullgrina", meaning: "Skull smile" },
    { name: "Bonecrushera", meaning: "Bone breaker" },
    { name: "Bloodaxea", meaning: "Bloody axe" },
    { name: "Ironfista", meaning: "Iron hand" },
    { name: "Darkthroata", meaning: "Dark voice" },
    { name: "Gorehidea", meaning: "Bloody skin" },
    { name: "Slagga", meaning: "Dirty" },
    { name: "Kratha", meaning: "Death" },
    { name: "Zaratha", meaning: "Tyrant" },
    { name: "Naratha", meaning: "Strong" },
    { name: "Maratha", meaning: "Great" },
    { name: "Karatha", meaning: "Cruel" },
    { name: "Varatha", meaning: "Powerful" },
    { name: "Toratha", meaning: "Mighty" },
    { name: "Loratha", meaning: "Fierce" },
    { name: "Koratha", meaning: "Brave" },
    { name: "Moratha", meaning: "Evil" },
    { name: "Goratha", meaning: "Tough" },
    { name: "Horatha", meaning: "Horrible" },
    { name: "Noratha", meaning: "North" },
    { name: "Boratha", meaning: "Strong" },
    { name: "Doratha", meaning: "Dark" },
    { name: "Roratha", meaning: "Roaring" },
    { name: "Voratha", meaning: "Hungry" },
    { name: "Xoratha", meaning: "Deadly" },
    { name: "Zoratha", meaning: "Wild" },
    { name: "Grimskara", meaning: "Grim scar" },
    { name: "Bloodsnarla", meaning: "Bloody snarl" },
    { name: "Ironjawa", meaning: "Iron jaw" },
    { name: "Stonefista", meaning: "Stone hand" },
    { name: "Darkbladea", meaning: "Dark sword" },
    { name: "Skullcrushera", meaning: "Skull breaker" },
    { name: "Goreaxea", meaning: "Bloody axe" },
    { name: "Tuskfanga", meaning: "Tusk tooth" },
    { name: "Ragefista", meaning: "Angry hand" },
    { name: "Deathgrina", meaning: "Death smile" },
    { name: "Morgasha", meaning: "Dark ash" },
    { name: "Grakatha", meaning: "Crush tooth" },
    { name: "Korgasha", meaning: "Rock ash" },
    { name: "Rokasha", meaning: "Stone ash" },
    { name: "Vorgasha", meaning: "Twisted ash" },
    { name: "Morgatha", meaning: "Dark tooth" },
    { name: "Gorgatha", meaning: "Monster tooth" },
    { name: "Horgatha", meaning: "Horror tooth" },
    { name: "Korgatha", meaning: "Rock tooth" },
    { name: "Rorgatha", meaning: "Roar tooth" },
    { name: "Sorgatha", meaning: "Evil tooth" },
    { name: "Torgatha", meaning: "Giant tooth" },
    { name: "Worgatha", meaning: "Wolf tooth" },
    { name: "Zorgatha", meaning: "Destructive tooth" },
    { name: "Grimmoka", meaning: "Grim orc" },
    { name: "Kormoka", meaning: "Rock orc" },
    { name: "Rommoka", meaning: "Roar orc" },
    { name: "Trommoka", meaning: "Thunder orc" },
    { name: "Vommoka", meaning: "Twisted orc" },
    { name: "Zommoka", meaning: "Wild orc" },
    { name: "Grimzoga", meaning: "Grim beast" },
    { name: "Korzoga", meaning: "Rock beast" },
    { name: "Rorzoga", meaning: "Roar beast" },
    { name: "Torzoga", meaning: "Thunder beast" },
    { name: "Vorzoga", meaning: "Twisted beast" },
    { name: "Zorzoga", meaning: "Wild beast" },
    { name: "Gorbaga", meaning: "Old orc" },
    { name: "Sharkua", meaning: "Old wolf" },
    { name: "Ufthaka", meaning: "Strong arm" },
    { name: "Mauhura", meaning: "Dark spirit" },
    { name: "Lugduska", meaning: "Red eye" },
    { name: "Malaka", meaning: "Angel of death" },
    { name: "Nazga", meaning: "Ringwraith" },
    { name: "Pasha", meaning: "Bad" },
    { name: "Zasha", meaning: "Angry" },
    { name: "Kasha", meaning: "Cruel" },
    { name: "Rasha", meaning: "Quick" },
    { name: "Masha", meaning: "Crush" },
    { name: "Gasha", meaning: "Cut" },
    { name: "Hasha", meaning: "Hatred" },
    { name: "Vasha", meaning: "Hunger" },
    { name: "Dasha", meaning: "Run" },
    { name: "Tasha", meaning: "Destroy" },
    { name: "Skarra", meaning: "Scar" },
    { name: "Karra", meaning: "Cut" },
    { name: "Rarra", meaning: "Roar" },
    { name: "Tarra", meaning: "Tar" },
    { name: "Warra", meaning: "War" },
    { name: "Zarra", meaning: "Anger" },
    { name: "Farra", meaning: "Far" },
    { name: "Harrra", meaning: "Harsh" },
    { name: "Jarra", meaning: "Jarring" },
    { name: "Marra", meaning: "Bitter" },
    { name: "Narra", meaning: "Fool" },
    { name: "Parra", meaning: "Speak" },
    { name: "Quarra", meaning: "Question" },
    { name: "Sarra", meaning: "Snarl" },
    { name: "Varra", meaning: "Wolf" },
    { name: "Yarra", meaning: "Shout" },
    { name: "Zarra", meaning: "Anger" }
];

let currentMode = 'random';

document.querySelectorAll('.mode-btn').forEach(btn => {
    btn.addEventListener('click', function() {
        document.querySelectorAll('.mode-btn').forEach(b => b.classList.remove('active'));
        this.classList.add('active');
        currentMode = this.dataset.mode;
    });
});

function generateNames() {
    const grid = document.getElementById('namesGrid');
    grid.innerHTML = '';
    
    let names = [];
    
    if (currentMode === 'male') {
        names = shuffleArray([...maleNames]).slice(0, 16).map(n => ({...n, gender: 'Male'}));
    } else if (currentMode === 'female') {
        names = shuffleArray([...femaleNames]).slice(0, 16).map(n => ({...n, gender: 'Female'}));
    } else {
        const allNames = [
            ...maleNames.map(n => ({...n, gender: 'Male'})),
            ...femaleNames.map(n => ({...n, gender: 'Female'}))
        ];
        names = shuffleArray(allNames).slice(0, 16);
    }
    
    names.forEach((item, index) => {
        const card = document.createElement('div');
        card.className = 'name-card';
        card.style.opacity = '0';
        card.style.transform = 'translateY(20px)';
        card.innerHTML = `
            <div class="name-text">${item.name}</div>
            <div class="name-gender">${item.gender}</div>
            <div class="name-meaning">${item.meaning}</div>
        `;
        grid.appendChild(card);
        
        setTimeout(() => {
            card.style.transition = 'all 0.3s ease';
            card.style.opacity = '1';
            card.style.transform = 'translateY(0)';
        }, index * 40);
    });
}

function shuffleArray(array) {
    for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]];
    }
    return array;
}