const maleNames = [
    { name: "ShadowHunter", meaning: "Hunter of darkness" },
    { name: "NinjaBlade", meaning: "Silent warrior" },
    { name: "DragonSlayer", meaning: "Killer of dragons" },
    { name: "FireMaster", meaning: "Controller of fire" },
    { name: "IceKing", meaning: "Ruler of ice" },
    { name: "ThunderStorm", meaning: "Power of storms" },
    { name: "DarkKnight", meaning: "Mysterious warrior" },
    { name: "GhostRider", meaning: "Spectral rider" },
    { name: "AlphaWolf", meaning: "Leader of the pack" },
    { name: "RedPhoenix", meaning: "Rising from ashes" },
    { name: "BlueDragon", meaning: "Mystical beast" },
    { name: "BlackPanther", meaning: "Stealthy predator" },
    { name: "SilverFox", meaning: "Cunning and wise" },
    { name: "GoldenEagle", meaning: "King of the sky" },
    { name: "CrimsonTiger", meaning: "Fierce warrior" },
    { name: "ViperStrike", meaning: "Deadly attack" },
    { name: "RavenClaw", meaning: "Wise and sharp" },
    { name: "WolfPack", meaning: "Strong together" },
    { name: "StormChaser", meaning: "Fearless adventurer" },
    { name: "NightStalker", meaning: "Hunter of the night" },
    { name: "DeathBringer", meaning: "Harvester of souls" },
    { name: "SoulReaper", meaning: "Collector of spirits" },
    { name: "BloodThirsty", meaning: "Hungry for battle" },
    { name: "FistOfFury", meaning: "Unstoppable force" },
    { name: "IronFist", meaning: "Strong as steel" },
    { name: "SteelHeart", meaning: "Brave and strong" },
    { name: "StoneGrip", meaning: "Unyielding power" },
    { name: "LightningBolt", meaning: "Fast and powerful" },
    { name: "FlameThrower", meaning: "Master of fire" },
    { name: "FrostBite", meaning: "Cold and deadly" },
    { name: "ShadowCloak", meaning: "Hidden in darkness" },
    { name: "DarkVision", meaning: "Sees in night" },
    { name: "NightOwl", meaning: "Wise and watchful" },
    { name: "DawnBringer", meaning: "Brings new day" },
    { name: "SunRise", meaning: "Hope and light" },
    { name: "MoonLight", meaning: "Calm and mysterious" },
    { name: "StarLight", meaning: "Shining bright" },
    { name: "GalaxyKnight", meaning: "Warrior of space" },
    { name: "CosmicForce", meaning: "Universal power" },
    { name: "VoidWalker", meaning: "Travels through nothing" },
    { name: "DimensionJump", meaning: "Moves between worlds" },
    { name: "TimeKeeper", meaning: "Guardian of time" },
    { name: "SpacePilot", meaning: "Explorer of stars" },
    { name: "AlienHunter", meaning: "Seeks extraterrestrials" },
    { name: "ZombieSlayer", meaning: "Fights undead" },
    { name: "VampireKiller", meaning: "Defeats darkness" },
    { name: "WerewolfHunter", meaning: "Chases beasts" },
    { name: "GhostBuster", meaning: "Captures spirits" },
    { name: "DemonSlayer", meaning: "Destroys evil" },
    { name: "AngelWarrior", meaning: "Divine fighter" },
    { name: "GodOfWar", meaning: "Legendary warrior" },
    { name: "LegendMaker", meaning: "Creates stories" },
    { name: "MythicHero", meaning: "Hero of tales" },
    { name: "EpicGamer", meaning: "Master of games" },
    { name: "ProPlayer", meaning: "Expert competitor" },
    { name: "GameChanger", meaning: "Transforms the game" },
    { name: "VictoryLover", meaning: "Always wins" },
    { name: "ChampionKing", meaning: "Ruler of arena" },
    { name: "TrophyHunter", meaning: "Collector of wins" },
    { name: "ScoreMaster", meaning: "Top of leaderboard" },
    { name: "RankLegend", meaning: "Highest tier" },
    { name: "ElitePlayer", meaning: "Best of the best" },
    { name: "SuperGamer", meaning: "Extraordinary player" },
    { name: "MegaPlayer", meaning: "Mighty competitor" },
    { name: "UltraGamer", meaning: "Ultimate player" },
    { name: "OmegaPlayer", meaning: "Last and best" },
    { name: "AlphaGamer", meaning: "First and top" },
    { name: "BetaPlayer", meaning: "Testing the game" },
    { name: "GammaGamer", meaning: "Strong player" },
    { name: "DeltaPlayer", meaning: "Changing the game" },
    { name: "SigmaGamer", meaning: "Independent player" },
    { name: "ZetaPlayer", meaning: "Powerful player" },
    { name: "EtaGamer", meaning: "Energetic player" },
    { name: "ThetaPlayer", meaning: "Thoughtful player" },
    { name: "IotaGamer", meaning: "Small but mighty" },
    { name: "KappaPlayer", meaning: "Triumphant player" },
    { name: "LambdaGamer", meaning: "Logical player" },
    { name: "MuPlayer", meaning: "Measured player" },
    { name: "NuGamer", meaning: "New player" },
    { name: "XiPlayer", meaning: "Mystic player" },
    { name: "OmicronGamer", meaning: "Small but powerful" },
    { name: "PiPlayer", meaning: "Calculating player" },
    { name: "RhoPlayer", meaning: "Rushing player" },
    { name: "SigmaGamer", meaning: "Sigma male player" },
    { name: "TauPlayer", meaning: "Tau player" },
    { name: "UpsilonPlayer", meaning: "Shaped player" },
    { name: "PhiPlayer", meaning: "Golden player" },
    { name: "ChiPlayer", meaning: "Chi energy player" },
    { name: "PsiPlayer", meaning: "Psychic player" },
    { name: "OmegaPlayer", meaning: "Final player" },
    { name: "AresPlayer", meaning: "God of war player" },
    { name: "ZeusPlayer", meaning: "King of gods player" },
    { name: "PoseidonPlayer", meaning: "God of sea player" },
    { name: "HadesPlayer", meaning: "God of underworld player" },
    { name: "ApolloPlayer", meaning: "God of sun player" },
    { name: "ArtemisPlayer", meaning: "Goddess of hunt player" },
    { name: "AthenaPlayer", meaning: "Goddess of wisdom player" },
    { name: "AphroditePlayer", meaning: "Goddess of love player" },
    { name: "HephaestusPlayer", meaning: "God of forge player" },
    { name: "HermesPlayer", meaning: "Messenger of gods player" },
    { name: "DionysusPlayer", meaning: "God of wine player" },
    { name: "HeraPlayer", meaning: "Queen of gods player" },
    { name: "DemeterPlayer", meaning: "Goddess of harvest player" },
    { name: "HestiaPlayer", meaning: "Goddess of hearth player" },
    { name: "PersephonePlayer", meaning: "Queen of underworld player" },
    { name: "HerculesPlayer", meaning: "Hero player" },
    { name: "PerseusPlayer", meaning: "Slayer of monsters player" },
    { name: "TheseusPlayer", meaning: "Hero of Athens player" },
    { name: "JasonPlayer", meaning: "Leader of Argonauts player" },
    { name: "OdysseusPlayer", meaning: "Clever hero player" },
    { name: "AchillesPlayer", meaning: "Greatest warrior player" },
    { name: "HectorPlayer", meaning: "Prince of Troy player" },
    { name: "ParisPlayer", meaning: "Princes kidnapper player" },
    { name: "HelenPlayer", meaning: "Face that launched ships player" },
    { name: "MenelausPlayer", meaning: "King of Sparta player" },
    { name: "AgamemnonPlayer", meaning: "King of Mycenae player" },
    { name: "ClytemnestraPlayer", meaning: "Wife of Agamemnon player" },
    { name: "OrestesPlayer", meaning: "Son of Agamemnon player" },
    { name: "ElectraPlayer", meaning: "Daughter of Agamemnon player" },
    { name: "IphigeniaPlayer", meaning: "Sacrificed daughter player" },
    { name: "AndromachePlayer", meaning: "Wife of Hector player" },
    { name: "BriseisPlayer", meaning: "Prize of Achilles player" },
    { name: "ChryseisPlayer", meaning: "Prize of Agamemnon player" },
    { name: "CalypsoPlayer", meaning: "Nymph of Ogygia player" },
    { name: "CircePlayer", meaning: "Witch of Aeaea player" },
    { name: "PenelopePlayer", meaning: "Faithful wife player" },
    { name: "TelemachusPlayer", meaning: "Son of Odysseus player" },
    { name: "AthenaPlayer", meaning: "Goddess of war player" },
    { name: "AphroditePlayer", meaning: "Goddess of beauty player" },
    { name: "HeraPlayer", meaning: "Queen of Olympus player" },
    { name: "ArtemisPlayer", meaning: "Goddess of wild player" },
    { name: "DemeterPlayer", meaning: "Goddess of grain player" },
    { name: "HestiaPlayer", meaning: "Goddess of home player" },
    { name: "PersephonePlayer", meaning: "Queen of dead player" },
    { name: "AphroditePlayer", meaning: "Goddess of love player" },
    { name: "AthenaPlayer", meaning: "Goddess of wisdom player" },
    { name: "ArtemisPlayer", meaning: "Goddess of hunt player" },
    { name: "HeraPlayer", meaning: "Queen of gods player" },
    { name: "DemeterPlayer", meaning: "Goddess of harvest player" },
    { name: "HestiaPlayer", meaning: "Goddess of hearth player" },
    { name: "PersephonePlayer", meaning: "Queen of underworld player" },
    { name: "ZeusPlayer", meaning: "King of sky player" },
    { name: "PoseidonPlayer", meaning: "God of ocean player" },
    { name: "HadesPlayer", meaning: "God of underworld player" },
    { name: "AresPlayer", meaning: "God of war player" },
    { name: "ApolloPlayer", meaning: "God of sun player" },
    { name: "HermesPlayer", meaning: "God of speed player" },
    { name: "HephaestusPlayer", meaning: "God of fire player" },
    { name: "DionysusPlayer", meaning: "God of wine player" },
    { name: "HeraclesPlayer", meaning: "Strongest hero player" },
    { name: "PerseusPlayer", meaning: "Gorgon slayer player" },
    { name: "BellerophonPlayer", meaning: "Pegasus rider player" },
    { name: "OrpheusPlayer", meaning: "Great musician player" },
    { name: "TheseusPlayer", meaning: "Minotaur slayer player" },
    { name: "JasonPlayer", meaning: "Golden fleece seeker player" },
    { name: "AtalantaPlayer", meaning: "Fastest runner player" },
    { name: "MeleagerPlayer", meaning: "Boar hunter player" },
    { name: "CastorPlayer", meaning: "Twin brother player" },
    { name: "PolluxPlayer", meaning: "Twin brother player" },
    { name: "HeraclesPlayer", meaning: "12 labors player" },
    { name: "PerseusPlayer", meaning: "Medusa slayer player" },
    { name: "BellerophonPlayer", meaning: "Chimera slayer player" },
    { name: "OrpheusPlayer", meaning: "Underworld musician player" },
    { name: "TheseusPlayer", meaning: "Labyrinth explorer player" },
    { name: "JasonPlayer", meaning: "Argonaut leader player" },
    { name: "AtalantaPlayer", meaning: "Huntress player" },
    { name: "MeleagerPlayer", meaning: "Calydonian boar slayer player" },
    { name: "CastorPlayer", meaning: "Horseman player" },
    { name: "PolluxPlayer", meaning: "Boxer player" }
];

const femaleNames = [
    { name: "ShadowQueen", meaning: "Queen of darkness" },
    { name: "NinjaPrincess", meaning: "Silent royal warrior" },
    { name: "DragonSlayeress", meaning: "Female dragon killer" },
    { name: "FireGoddess", meaning: "Goddess of fire" },
    { name: "IceQueen", meaning: "Ruler of ice and snow" },
    { name: "ThunderGoddess", meaning: "Goddess of storms" },
    { name: "DarkPrincess", meaning: "Mysterious royal" },
    { name: "GhostRideress", meaning: "Spectral female rider" },
    { name: "AlphaWolfess", meaning: "Female leader of pack" },
    { name: "RedPhoenixQueen", meaning: "Queen of rebirth" },
    { name: "BlueDragoness", meaning: "Female mystical beast" },
    { name: "BlackPantheress", meaning: "Stealthy female predator" },
    { name: "SilverVixen", meaning: "Cunning and wise female" },
    { name: "GoldenHawk", meaning: "Queen of the sky" },
    { name: "CrimsonTigress", meaning: "Fierce female warrior" },
    { name: "ViperQueen", meaning: "Deadly female leader" },
    { name: "RavenWing", meaning: "Wise and sharp female" },
    { name: "WolfPackQueen", meaning: "Female leader together" },
    { name: "StormChaseress", meaning: "Fearless female adventurer" },
    { name: "NightStalkeress", meaning: "Female hunter of the night" },
    { name: "DeathBringeress", meaning: "Female harvester of souls" },
    { name: "SoulReaperess", meaning: "Female collector of spirits" },
    { name: "BloodThirstyQueen", meaning: "Hungry for battle female" },
    { name: "FistOfFuryess", meaning: "Unstoppable female force" },
    { name: "IronFistQueen", meaning: "Strong as steel female" },
    { name: "SteelHeartQueen", meaning: "Brave and strong female" },
    { name: "StoneGripQueen", meaning: "Unyielding power female" },
    { name: "LightningFlash", meaning: "Fast and powerful female" },
    { name: "FlameThroweress", meaning: "Female master of fire" },
    { name: "FrostBiteQueen", meaning: "Cold and deadly female" },
    { name: "ShadowCloakess", meaning: "Hidden in darkness female" },
    { name: "DarkVisionQueen", meaning: "Sees in night female" },
    { name: "NightOwlQueen", meaning: "Wise and watchful female" },
    { name: "DawnBringeress", meaning: "Brings new day female" },
    { name: "SunRiseQueen", meaning: "Hope and light female" },
    { name: "MoonLightQueen", meaning: "Calm and mysterious female" },
    { name: "StarLightQueen", meaning: "Shining bright female" },
    { name: "GalaxyQueen", meaning: "Female warrior of space" },
    { name: "CosmicGoddess", meaning: "Universal female power" },
    { name: "VoidWalkerss", meaning: "Travels through nothing female" },
    { name: "DimensionJumpess", meaning: "Moves between worlds female" },
    { name: "TimeKeeperess", meaning: "Guardian of time female" },
    { name: "SpacePilotess", meaning: "Explorer of stars female" },
    { name: "AlienHunteress", meaning: "Seeks extraterrestrials female" },
    { name: "ZombieSlayeress", meaning: "Fights undead female" },
    { name: "VampireKilleress", meaning: "Defeats darkness female" },
    { name: "WerewolfHunteress", meaning: "Chases beasts female" },
    { name: "GhostBusteress", meaning: "Captures spirits female" },
    { name: "DemonSlayeress", meaning: "Destroys evil female" },
    { name: "AngelWarrioress", meaning: "Divine female fighter" },
    { name: "GoddessOfWar", meaning: "Legendary female warrior" },
    { name: "LegendMakeress", meaning: "Creates stories female" },
    { name: "MythicHeroine", meaning: "Heroine of tales female" },
    { name: "EpicGameress", meaning: "Master of games female" },
    { name: "ProPlayeress", meaning: "Expert competitor female" },
    { name: "GameChangeress", meaning: "Transforms the game female" },
    { name: "VictoryLoveress", meaning: "Always wins female" },
    { name: "ChampionQueen", meaning: "Ruler of arena female" },
    { name: "TrophyHunteress", meaning: "Collector of wins female" },
    { name: "ScoreMistress", meaning: "Top of leaderboard female" },
    { name: "RankLegendess", meaning: "Highest tier female" },
    { name: "ElitePlayeress", meaning: "Best of the best female" },
    { name: "SuperGameress", meaning: "Extraordinary player female" },
    { name: "MegaPlayeress", meaning: "Mighty competitor female" },
    { name: "UltraGameress", meaning: "Ultimate player female" },
    { name: "OmegaPlayeress", meaning: "Last and best female" },
    { name: "AlphaGameress", meaning: "First and top female" },
    { name: "BetaPlayeress", meaning: "Testing the game female" },
    { name: "GammaGameress", meaning: "Strong player female" },
    { name: "DeltaPlayeress", meaning: "Changing the game female" },
    { name: "SigmaGameress", meaning: "Independent player female" },
    { name: "ZetaPlayeress", meaning: "Powerful player female" },
    { name: "EtaGameress", meaning: "Energetic player female" },
    { name: "ThetaPlayeress", meaning: "Thoughtful player female" },
    { name: "IotaGameress", meaning: "Small but mighty female" },
    { name: "KappaPlayeress", meaning: "Triumphant player female" },
    { name: "LambdaGameress", meaning: "Logical player female" },
    { name: "MuPlayeress", meaning: "Measured player female" },
    { name: "NuGameress", meaning: "New player female" },
    { name: "XiPlayeress", meaning: "Mystic player female" },
    { name: "OmicronGameress", meaning: "Small but powerful female" },
    { name: "PiPlayeress", meaning: "Calculating player female" },
    { name: "RhoPlayeress", meaning: "Rushing player female" },
    { name: "SigmaGameress", meaning: "Sigma female player" },
    { name: "TauPlayeress", meaning: "Tau player female" },
    { name: "UpsilonPlayeress", meaning: "Shaped player female" },
    { name: "PhiPlayeress", meaning: "Golden player female" },
    { name: "ChiPlayeress", meaning: "Chi energy player female" },
    { name: "PsiPlayeress", meaning: "Psychic player female" },
    { name: "OmegaPlayeress", meaning: "Final player female" },
    { name: "AthenaPlayeress", meaning: "Goddess of wisdom female player" },
    { name: "AphroditePlayeress", meaning: "Goddess of love female player" },
    { name: "ArtemisPlayeress", meaning: "Goddess of hunt female player" },
    { name: "HeraPlayeress", meaning: "Queen of gods female player" },
    { name: "DemeterPlayeress", meaning: "Goddess of harvest female player" },
    { name: "HestiaPlayeress", meaning: "Goddess of hearth female player" },
    { name: "PersephonePlayeress", meaning: "Queen of underworld female player" },
    { name: "HelenPlayeress", meaning: "Face that launched ships female player" },
    { name: "AndromachePlayeress", meaning: "Wife of Hector female player" },
    { name: "BriseisPlayeress", meaning: "Prize of Achilles female player" },
    { name: "ChryseisPlayeress", meaning: "Prize of Agamemnon female player" },
    { name: "CalypsoPlayeress", meaning: "Nymph of Ogygia female player" },
    { name: "CircePlayeress", meaning: "Witch of Aeaea female player" },
    { name: "PenelopePlayeress", meaning: "Faithful wife female player" },
    { name: "AtalantaPlayeress", meaning: "Fastest runner female player" },
    { name: "MedeaPlayeress", meaning: "Witch of Colchis female player" },
    { name: "AriadnePlayeress", meaning: "Princess of Crete female player" },
    { name: "DaedalusPlayeress", meaning: "Inventor of labyrinth female player" },
    { name: "IcarusPlayeress", meaning: "Flew too close to sun female player" },
    { name: "PandoraPlayeress", meaning: "Opened the box female player" },
    { name: "EchoPlayeress", meaning: "Voice of the mountains female player" },
    { name: "NarcissusPlayeress", meaning: "In love with reflection female player" },
    { name: "SisyphusPlayeress", meaning: "Rolled boulder up hill female player" },
    { name: "TantalusPlayeress", meaning: "Tantalized forever female player" },
    { name: "PrometheusPlayeress", meaning: "Stole fire from gods female player" },
    { name: "EpimetheusPlayeress", meaning: "Hindsight is 20/20 female player" },
    { name: "PandoraPlayeress", meaning: "Gift to humanity female player" },
    { name: "AthenaPlayeress", meaning: "Wisdom goddess player female" },
    { name: "AphroditePlayeress", meaning: "Love goddess player female" },
    { name: "ArtemisPlayeress", meaning: "Hunt goddess player female" },
    { name: "HeraPlayeress", meaning: "Marriage goddess player female" },
    { name: "DemeterPlayeress", meaning: "Harvest goddess player female" },
    { name: "HestiaPlayeress", meaning: "Home goddess player female" },
    { name: "PersephonePlayeress", meaning: "Spring goddess player female" },
    { name: "AphroditePlayeress", meaning: "Beauty goddess player female" },
    { name: "AthenaPlayeress", meaning: "War goddess player female" },
    { name: "ArtemisPlayeress", meaning: "Wild goddess player female" },
    { name: "HeraPlayeress", meaning: "Olympus queen player female" },
    { name: "DemeterPlayeress", meaning: "Grain goddess player female" },
    { name: "HestiaPlayeress", meaning: "Hearth goddess player female" },
    { name: "PersephonePlayeress", meaning: "Underworld queen player female" },
    { name: "ZeusPlayeress", meaning: "Sky queen player female" },
    { name: "PoseidonPlayeress", meaning: "Ocean goddess player female" },
    { name: "HadesPlayeress", meaning: "Underworld goddess player female" },
    { name: "AresPlayeress", meaning: "War goddess player female" },
    { name: "ApolloPlayeress", meaning: "Sun goddess player female" },
    { name: "HermesPlayeress", meaning: "Speed goddess player female" },
    { name: "HephaestusPlayeress", meaning: "Fire goddess player female" },
    { name: "DionysusPlayeress", meaning: "Wine goddess player female" },
    { name: "HeraclesPlayeress", meaning: "Strongest heroine player female" },
    { name: "PerseusPlayeress", meaning: "Gorgon slayeress player female" },
    { name: "BellerophonPlayeress", meaning: "Pegasus rideress player female" },
    { name: "OrpheusPlayeress", meaning: "Great musicianess player female" },
    { name: "TheseusPlayeress", meaning: "Minotaur slayeress player female" },
    { name: "JasonPlayeress", meaning: "Golden fleece seekeress player female" },
    { name: "AtalantaPlayeress", meaning: "Fastest runneress player female" },
    { name: "MeleagerPlayeress", meaning: "Boar hunteress player female" },
    { name: "CastorPlayeress", meaning: "Twin sister player female" },
    { name: "PolluxPlayeress", meaning: "Twin sister player female" },
    { name: "HeraclesPlayeress", meaning: "12 laborsess player female" },
    { name: "PerseusPlayeress", meaning: "Medusa slayeress player female" },
    { name: "BellerophonPlayeress", meaning: "Chimera slayeress player female" },
    { name: "OrpheusPlayeress", meaning: "Underworld musicianess player female" },
    { name: "TheseusPlayeress", meaning: "Labyrinth exploress player female" },
    { name: "JasonPlayeress", meaning: "Argonaut leaderess player female" },
    { name: "AtalantaPlayeress", meaning: "Huntressess player female" },
    { name: "MeleagerPlayeress", meaning: "Calydonian boar slayeress player female" },
    { name: "CastorPlayeress", meaning: "Horsemaness player female" },
    { name: "PolluxPlayeress", meaning: "Boxeress player female" }
];

let currentMode = 'random';

document.querySelectorAll('.mode-btn').forEach(btn => {
    btn.addEventListener('click', function() {
        document.querySelectorAll('.mode-btn').forEach(b => b.classList.remove('active'));
        this.classList.add('active');
        currentMode = this.dataset.mode;
    });
});

function generateNames() {
    const grid = document.getElementById('namesGrid');
    grid.innerHTML = '';
    
    let names = [];
    
    if (currentMode === 'male') {
        names = shuffleArray([...maleNames]).slice(0, 16).map(n => ({...n, gender: 'Male'}));
    } else if (currentMode === 'female') {
        names = shuffleArray([...femaleNames]).slice(0, 16).map(n => ({...n, gender: 'Female'}));
    } else {
        const allNames = [
            ...maleNames.map(n => ({...n, gender: 'Male'})),
            ...femaleNames.map(n => ({...n, gender: 'Female'}))
        ];
        names = shuffleArray(allNames).slice(0, 16);
    }
    
    names.forEach((item, index) => {
        const card = document.createElement('div');
        card.className = 'name-card';
        card.style.opacity = '0';
        card.style.transform = 'translateY(20px)';
        card.innerHTML = `
            <div class="name-text">${item.name}</div>
            <div class="name-gender">${item.gender}</div>
            <div class="name-meaning">${item.meaning}</div>
        `;
        grid.appendChild(card);
        
        setTimeout(() => {
            card.style.transition = 'all 0.3s ease';
            card.style.opacity = '1';
            card.style.transform = 'translateY(0)';
        }, index * 40);
    });
}

function shuffleArray(array) {
    for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]];
    }
    return array;
}