const maleNames = [
    { name: "Astran", meaning: "Star walker" },
    { name: "Lunaris", meaning: "Moon child" },
    { name: "Nocturne", meaning: "Night dweller" },
    { name: "Thalyn", meaning: "Shadow blade" },
    { name: "Kaelis", meaning: "Moonlight" },
    { name: "Vethir", meaning: "Dark forest" },
    { name: "Zevran", meaning: "Night storm" },
    { name: "Calen", meaning: "Moon singer" },
    { name: "Morrath", meaning: "Shadow lord" },
    { name: "Darian", meaning: "Dark heart" },
    { name: "Raelis", meaning: "Star gaze" },
    { name: "Faelar", meaning: "Moon path" },
    { name: "Kaelthas", meaning: "Moon prince" },
    { name: "Valen", meaning: "Night warrior" },
    { name: "Tyrande", meaning: "Moon guard" },
    { name: "Malfurion", meaning: "Night ruler" },
    { name: "Illidan", meaning: "Storm of night" },
    { name: "Cenarius", meaning: "Forest guardian" },
    { name: "Broll", meaning: "Dark brother" },
    { name: "Teldrassil", meaning: "Dream tree" },
    { name: "Sylvanas", meaning: "Lady of the night" },
    { name: "Maiev", meaning: "Shadow hunter" },
    { name: "Shandris", meaning: "Night blade" },
    { name: "Varo", meaning: "Dark one" },
    { name: "Moren", meaning: "Night shadow" },
    { name: "Kael", meaning: "Moon" },
    { name: "Lirael", meaning: "Star song" },
    { name: "Corvin", meaning: "Raven" },
    { name: "Darius", meaning: "Dark king" },
    { name: "Elarion", meaning: "Star child" },
    { name: "Fenris", meaning: "Wolf of night" },
    { name: "Gareth", meaning: "Spear of shadows" },
    { name: "Haldir", meaning: "Hidden watcher" },
    { name: "Ithil", meaning: "Moon" },
    { name: "Joren", meaning: "Forest soul" },
    { name: "Kaelan", meaning: "Moon light" },
    { name: "Lothar", meaning: "Wolf warrior" },
    { name: "Miren", meaning: "Dark sea" },
    { name: "Nathanos", meaning: "Hunter of night" },
    { name: "Oron", meaning: "Shadow mountain" },
    { name: "Phael", meaning: "Dark flame" },
    { name: "Quel", meaning: "High" },
    { name: "Raven", meaning: "Dark bird" },
    { name: "Soren", meaning: "Dark dream" },
    { name: "Talon", meaning: "Shadow claw" },
    { name: "Uldren", meaning: "Ancient shadow" },
    { name: "Vaelen", meaning: "Moon born" },
    { name: "Warden", meaning: "Guardian of night" },
    { name: "Xavius", meaning: "Nightmare lord" },
    { name: "Ysera", meaning: "Dream walker" },
    { name: "Zendik", meaning: "Dark path" },
    { name: "Althar", meaning: "Star guard" },
    { name: "Belthar", meaning: "Moon shield" },
    { name: "Calthar", meaning: "Shadow blade" },
    { name: "Dalthar", meaning: "Night edge" },
    { name: "Elthar", meaning: "Star edge" },
    { name: "Felthar", meaning: "Dark edge" },
    { name: "Galthar", meaning: "Moon edge" },
    { name: "Halthar", meaning: "Shadow edge" },
    { name: "Ilthar", meaning: "Night edge" },
    { name: "Jalthar", meaning: "Star edge" },
    { name: "Kalthar", meaning: "Dark edge" },
    { name: "Lalthar", meaning: "Moon edge" },
    { name: "Malthar", meaning: "Shadow edge" },
    { name: "Nalthar", meaning: "Night edge" },
    { name: "Olthar", meaning: "Star edge" },
    { name: "Plthar", meaning: "Dark edge" },
    { name: "Qalthar", meaning: "Moon edge" },
    { name: "Ralthar", meaning: "Shadow edge" },
    { name: "Salthar", meaning: "Night edge" },
    { name: "Talthar", meaning: "Star edge" },
    { name: "Ulthar", meaning: "Dark edge" },
    { name: "Vlthar", meaning: "Moon edge" },
    { name: "Walthar", meaning: "Shadow edge" },
    { name: "Xalthar", meaning: "Night edge" },
    { name: "Yalthar", meaning: "Star edge" },
    { name: "Zalthar", meaning: "Dark edge" },
    { name: "Aelir", meaning: "Moon ray" },
    { name: "Belir", meaning: "Star ray" },
    { name: "Celir", meaning: "Shadow ray" },
    { name: "Delir", meaning: "Night ray" },
    { name: "Eelir", meaning: "Dark ray" },
    { name: "Felir", meaning: "Moon ray" },
    { name: "Gelir", meaning: "Star ray" },
    { name: "Helir", meaning: "Shadow ray" },
    { name: "Ielir", meaning: "Night ray" },
    { name: "Jelir", meaning: "Dark ray" },
    { name: "Kelir", meaning: "Moon ray" },
    { name: "Lelir", meaning: "Star ray" },
    { name: "Melir", meaning: "Shadow ray" },
    { name: "Nelir", meaning: "Night ray" },
    { name: "Oelir", meaning: "Dark ray" },
    { name: "Pelir", meaning: "Moon ray" },
    { name: "Qelir", meaning: "Star ray" },
    { name: "Relir", meaning: "Shadow ray" },
    { name: "Selir", meaning: "Night ray" },
    { name: "Telir", meaning: "Dark ray" },
    { name: "Uelir", meaning: "Moon ray" },
    { name: "Velir", meaning: "Star ray" },
    { name: "Welir", meaning: "Shadow ray" },
    { name: "Xelir", meaning: "Night ray" },
    { name: "Yelir", meaning: "Dark ray" },
    { name: "Zelir", meaning: "Moon ray" },
    { name: "Aevan", meaning: "Evening star" },
    { name: "Bevan", meaning: "Night star" },
    { name: "Cevan", meaning: "Dark star" },
    { name: "Devan", meaning: "Moon star" },
    { name: "Eevan", meaning: "Shadow star" },
    { name: "Fevan", meaning: "Night star" },
    { name: "Gevan", meaning: "Dark star" },
    { name: "Hevan", meaning: "Moon star" },
    { name: "Ievan", meaning: "Shadow star" },
    { name: "Jevan", meaning: "Night star" },
    { name: "Kevan", meaning: "Dark star" },
    { name: "Levan", meaning: "Moon star" },
    { name: "Mevan", meaning: "Shadow star" },
    { name: "Nevan", meaning: "Night star" },
    { name: "Oevan", meaning: "Dark star" },
    { name: "Pevan", meaning: "Moon star" },
    { name: "Qevan", meaning: "Shadow star" },
    { name: "Revan", meaning: "Night star" },
    { name: "Sevan", meaning: "Dark star" },
    { name: "Tevan", meaning: "Moon star" },
    { name: "Uevan", meaning: "Shadow star" },
    { name: "Vevan", meaning: "Night star" },
    { name: "Wevan", meaning: "Dark star" },
    { name: "Xevan", meaning: "Moon star" },
    { name: "Yevan", meaning: "Shadow star" },
    { name: "Zevan", meaning: "Night star" },
    { name: "Arthas", meaning: "Frozen throne" },
    { name: "Bolvar", meaning: "Dark soul" },
    { name: "Cairne", meaning: "Bloodhoof" },
    { name: "Durotan", meaning: "Strong as stone" },
    { name: "Eitrigg", meaning: "Honor bound" },
    { name: "Furion", meaning: "Night elf" },
    { name: "Grommash", meaning: "Fierce hammer" },
    { name: "Hellscream", meaning: "Loud roar" },
    { name: "Illidan", meaning: "Betrayer" },
    { name: "Jaina", meaning: "Proud lady" }
];

const femaleNames = [
    { name: "Astrana", meaning: "Star walker" },
    { name: "Lunara", meaning: "Moon child" },
    { name: "Nocturna", meaning: "Night dweller" },
    { name: "Thalyna", meaning: "Shadow blade" },
    { name: "Kaelisa", meaning: "Moonlight" },
    { name: "Vethira", meaning: "Dark forest" },
    { name: "Zevrana", meaning: "Night storm" },
    { name: "Calena", meaning: "Moon singer" },
    { name: "Morratha", meaning: "Shadow lady" },
    { name: "Dariana", meaning: "Dark heart" },
    { name: "Raelisa", meaning: "Star gaze" },
    { name: "Faelara", meaning: "Moon path" },
    { name: "Kaelthasa", meaning: "Moon princess" },
    { name: "Valena", meaning: "Night warrior" },
    { name: "Tyranda", meaning: "Moon guard" },
    { name: "Malfuriona", meaning: "Night ruler" },
    { name: "Illidana", meaning: "Storm of night" },
    { name: "Cenaria", meaning: "Forest guardian" },
    { name: "Brolla", meaning: "Dark sister" },
    { name: "Teldrassila", meaning: "Dream tree" },
    { name: "Sylvanasa", meaning: "Lady of the night" },
    { name: "Maieva", meaning: "Shadow hunter" },
    { name: "Shandrisa", meaning: "Night blade" },
    { name: "Varona", meaning: "Dark one" },
    { name: "Morena", meaning: "Night shadow" },
    { name: "Kaela", meaning: "Moon" },
    { name: "Liraela", meaning: "Star song" },
    { name: "Corvina", meaning: "Raven" },
    { name: "Dariusa", meaning: "Dark queen" },
    { name: "Elariona", meaning: "Star child" },
    { name: "Fenrisa", meaning: "Wolf of night" },
    { name: "Garethna", meaning: "Spear of shadows" },
    { name: "Haldira", meaning: "Hidden watcher" },
    { name: "Ithila", meaning: "Moon" },
    { name: "Jorena", meaning: "Forest soul" },
    { name: "Kaelana", meaning: "Moon light" },
    { name: "Lothara", meaning: "Wolf warrior" },
    { name: "Mirena", meaning: "Dark sea" },
    { name: "Nathanosa", meaning: "Hunter of night" },
    { name: "Orona", meaning: "Shadow mountain" },
    { name: "Phaela", meaning: "Dark flame" },
    { name: "Quela", meaning: "High" },
    { name: "Ravena", meaning: "Dark bird" },
    { name: "Sorena", meaning: "Dark dream" },
    { name: "Talona", meaning: "Shadow claw" },
    { name: "Uldrena", meaning: "Ancient shadow" },
    { name: "Vaelena", meaning: "Moon born" },
    { name: "Wardena", meaning: "Guardian of night" },
    { name: "Xaviusa", meaning: "Nightmare lady" },
    { name: "Ysera", meaning: "Dream walker" },
    { name: "Zendika", meaning: "Dark path" },
    { name: "Althara", meaning: "Star guard" },
    { name: "Belthara", meaning: "Moon shield" },
    { name: "Calthara", meaning: "Shadow blade" },
    { name: "Dalthara", meaning: "Night edge" },
    { name: "Elthara", meaning: "Star edge" },
    { name: "Felthara", meaning: "Dark edge" },
    { name: "Galthara", meaning: "Moon edge" },
    { name: "Halthara", meaning: "Shadow edge" },
    { name: "Ilthara", meaning: "Night edge" },
    { name: "Jalthara", meaning: "Star edge" },
    { name: "Kalthara", meaning: "Dark edge" },
    { name: "Lalthara", meaning: "Moon edge" },
    { name: "Malthara", meaning: "Shadow edge" },
    { name: "Nalthara", meaning: "Night edge" },
    { name: "Olthara", meaning: "Star edge" },
    { name: "Plthara", meaning: "Dark edge" },
    { name: "Qalthara", meaning: "Moon edge" },
    { name: "Ralthara", meaning: "Shadow edge" },
    { name: "Salthara", meaning: "Night edge" },
    { name: "Talthara", meaning: "Star edge" },
    { name: "Ulthara", meaning: "Dark edge" },
    { name: "Vlthara", meaning: "Moon edge" },
    { name: "Walthara", meaning: "Shadow edge" },
    { name: "Xalthara", meaning: "Night edge" },
    { name: "Yalthara", meaning: "Star edge" },
    { name: "Zalthara", meaning: "Dark edge" },
    { name: "Aelira", meaning: "Moon ray" },
    { name: "Belira", meaning: "Star ray" },
    { name: "Celira", meaning: "Shadow ray" },
    { name: "Delira", meaning: "Night ray" },
    { name: "Eelira", meaning: "Dark ray" },
    { name: "Felira", meaning: "Moon ray" },
    { name: "Gelira", meaning: "Star ray" },
    { name: "Helira", meaning: "Shadow ray" },
    { name: "Ielira", meaning: "Night ray" },
    { name: "Jelira", meaning: "Dark ray" },
    { name: "Kelira", meaning: "Moon ray" },
    { name: "Lelira", meaning: "Star ray" },
    { name: "Melira", meaning: "Shadow ray" },
    { name: "Nelira", meaning: "Night ray" },
    { name: "Oelira", meaning: "Dark ray" },
    { name: "Pelira", meaning: "Moon ray" },
    { name: "Qelira", meaning: "Star ray" },
    { name: "Relira", meaning: "Shadow ray" },
    { name: "Selira", meaning: "Night ray" },
    { name: "Telira", meaning: "Dark ray" },
    { name: "Uelira", meaning: "Moon ray" },
    { name: "Velira", meaning: "Star ray" },
    { name: "Welira", meaning: "Shadow ray" },
    { name: "Xelira", meaning: "Night ray" },
    { name: "Yelira", meaning: "Dark ray" },
    { name: "Zelira", meaning: "Moon ray" },
    { name: "Aevana", meaning: "Evening star" },
    { name: "Bevana", meaning: "Night star" },
    { name: "Cevana", meaning: "Dark star" },
    { name: "Devana", meaning: "Moon star" },
    { name: "Eevana", meaning: "Shadow star" },
    { name: "Fevana", meaning: "Night star" },
    { name: "Gevana", meaning: "Dark star" },
    { name: "Hevana", meaning: "Moon star" },
    { name: "Ievana", meaning: "Shadow star" },
    { name: "Jevana", meaning: "Night star" },
    { name: "Kevana", meaning: "Dark star" },
    { name: "Levana", meaning: "Moon star" },
    { name: "Mevana", meaning: "Shadow star" },
    { name: "Nevana", meaning: "Night star" },
    { name: "Oevana", meaning: "Dark star" },
    { name: "Pevana", meaning: "Moon star" },
    { name: "Qevana", meaning: "Shadow star" },
    { name: "Revana", meaning: "Night star" },
    { name: "Sevana", meaning: "Dark star" },
    { name: "Tevana", meaning: "Moon star" },
    { name: "Uevana", meaning: "Shadow star" },
    { name: "Vevana", meaning: "Night star" },
    { name: "Wevana", meaning: "Dark star" },
    { name: "Xevana", meaning: "Moon star" },
    { name: "Yevana", meaning: "Shadow star" },
    { name: "Zevana", meaning: "Night star" },
    { name: "Arthasia", meaning: "Frozen queen" },
    { name: "Bolvara", meaning: "Dark soul" },
    { name: "Cairnea", meaning: "Bloodhoof" },
    { name: "Durotana", meaning: "Strong as stone" },
    { name: "Eitrigga", meaning: "Honor bound" },
    { name: "Furiona", meaning: "Night elf" },
    { name: "Grommasha", meaning: "Fierce hammer" },
    { name: "Hellscreama", meaning: "Loud roar" },
    { name: "Illidana", meaning: "Betrayer" },
    { name: "Jaina", meaning: "Proud lady" }
];

let currentMode = 'random';

document.querySelectorAll('.mode-btn').forEach(btn => {
    btn.addEventListener('click', function() {
        document.querySelectorAll('.mode-btn').forEach(b => b.classList.remove('active'));
        this.classList.add('active');
        currentMode = this.dataset.mode;
    });
});

function generateNames() {
    const grid = document.getElementById('namesGrid');
    grid.innerHTML = '';
    
    let names = [];
    
    if (currentMode === 'male') {
        names = shuffleArray([...maleNames]).slice(0, 16).map(n => ({...n, gender: 'Male'}));
    } else if (currentMode === 'female') {
        names = shuffleArray([...femaleNames]).slice(0, 16).map(n => ({...n, gender: 'Female'}));
    } else {
        const allNames = [
            ...maleNames.map(n => ({...n, gender: 'Male'})),
            ...femaleNames.map(n => ({...n, gender: 'Female'}))
        ];
        names = shuffleArray(allNames).slice(0, 16);
    }
    
    names.forEach((item, index) => {
        const card = document.createElement('div');
        card.className = 'name-card';
        card.style.opacity = '0';
        card.style.transform = 'translateY(20px)';
        card.innerHTML = `
            <div class="name-text">${item.name}</div>
            <div class="name-gender">${item.gender}</div>
            <div class="name-meaning">${item.meaning}</div>
        `;
        grid.appendChild(card);
        
        setTimeout(() => {
            card.style.transition = 'all 0.3s ease';
            card.style.opacity = '1';
            card.style.transform = 'translateY(0)';
        }, index * 40);
    });
}

function shuffleArray(array) {
    for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]];
    }
    return array;
}