const maleNames = [
    { name: "Gror Ironfist", meaning: "Fierce warrior with iron grip" },
    { name: "Bjorn Stormcaller", meaning: "Bear who summons storms" },
    { name: "Thorgar Bloodaxe", meaning: "Warrior of blood and steel" },
    { name: "Korgan Stonebreaker", meaning: "Breaker of mountains" },
    { name: "Drogan Firebeard", meaning: "Red-bearded warrior" },
    { name: "Gimble Steeltoe", meaning: "Stubborn fighter" },
    { name: "Hakon Wolfsbane", meaning: "Slayer of wolves" },
    { name: "Jorn Thunderheart", meaning: "Heart like thunder" },
    { name: "Magnar Ironvein", meaning: "Iron flows in his veins" },
    { name: "Olaf Stormbringer", meaning: "Brings storms to battle" },
    { name: "Rurik Broadaxe", meaning: "Wielder of massive axe" },
    { name: "Sven Warhammer", meaning: "Master of the hammer" },
    { name: "Torbjorn Bloodthirst", meaning: "Craves battle" },
    { name: "Ulric Skullcrusher", meaning: "Crusher of enemies" },
    { name: "Vladimir Ironwill", meaning: "Unbreakable will" },
    { name: "Wulfgar Giantbane", meaning: "Slayer of giants" },
    { name: "Xander Steelbrow", meaning: "Hard as steel" },
    { name: "Yorik Darkaxe", meaning: "Shadow warrior" },
    { name: "Zoltan Flamehand", meaning: "Wields fire in battle" },
    { name: "Arnar Frostbeard", meaning: "Cold northern warrior" },
    { name: "Baldur Ironhide", meaning: "Skin like iron" },
    { name: "Cnut Battleborn", meaning: "Born for battle" },
    { name: "Dagmar Warcry", meaning: "Voice that strikes fear" },
    { name: "Erik Bloodaxe", meaning: "Bloody warrior" },
    { name: "Finn Ironfury", meaning: "Furious fighter" },
    { name: "Gareth Stormblade", meaning: "Sword like storm" },
    { name: "Harald Broadshoulder", meaning: "Strong and powerful" },
    { name: "Ivar Bonebreaker", meaning: "Breaks bones with ease" },
    { name: "Jarl Thunderfist", meaning: "Fists like thunder" },
    { name: "Kael Ironhelm", meaning: "Protected by iron" },
    { name: "Loki Stormcaller", meaning: "Calls storms to aid him" },
    { name: "Marek Bloodscar", meaning: "Bears scars of battle" },
    { name: "Njal Ironjaw", meaning: "Strong as iron" },
    { name: "Odin Warhammer", meaning: "Divine warrior" },
    { name: "Pallin Steelheart", meaning: "Heart of steel" },
    { name: "Quinn Fireaxe", meaning: "Axe burns with fire" },
    { name: "Raven Battleaxe", meaning: "Dark warrior" },
    { name: "Sigmund Ironfist", meaning: "Iron fist of battle" },
    { name: "Torgrim Bloodaxe", meaning: "Bloody axe warrior" },
    { name: "Ulfric Stormcloak", meaning: "Wears storm as cloak" },
    { name: "Vargr Wolfheart", meaning: "Heart of wolf" },
    { name: "Werner Steelvein", meaning: "Steel in his blood" },
    { name: "Xavier Ironhand", meaning: "Iron-handed fighter" },
    { name: "Yngvar Battlecry", meaning: "Shouts battle cry" },
    { name: "Zane Firebrand", meaning: "Burns with passion" },
    { name: "Alaric Ironbrow", meaning: "Iron on his brow" },
    { name: "Bram Bloodthirst", meaning: "Craves blood in battle" },
    { name: "Corin Steelaxe", meaning: "Steel axe warrior" },
    { name: "Darius Stormfist", meaning: "Fist like storm" },
    { name: "Edric Ironhide", meaning: "Hide of iron" },
    { name: "Fergus Warhammer", meaning: "Wields warhammer" },
    { name: "Gareth Ironwill", meaning: "Iron willpower" },
    { name: "Hiram Bloodaxe", meaning: "Axe drips blood" },
    { name: "Ingmar Stormcaller", meaning: "Calls the storm" },
    { name: "Jasper Steelheart", meaning: "Heart of steel" },
    { name: "Kael Bloodscar", meaning: "Scarred warrior" },
    { name: "Lorne Ironfist", meaning: "Iron fist fighter" },
    { name: "Mason Stonebreaker", meaning: "Breaks stone" },
    { name: "Nathan Stormblade", meaning: "Sword of storm" },
    { name: "Owen Ironhelm", meaning: "Iron helmet" },
    { name: "Percy Firebeard", meaning: "Red beard of fire" },
    { name: "Quentin Wolfsbane", meaning: "Bane of wolves" },
    { name: "Ralph Thunderheart", meaning: "Thunder in heart" },
    { name: "Sean Ironvein", meaning: "Iron in veins" },
    { name: "Todd Bloodaxe", meaning: "Bloody axe" },
    { name: "Ulrich Stormbringer", meaning: "Brings storms" },
    { name: "Victor Steelbrow", meaning: "Steel brow" },
    { name: "William Giantbane", meaning: "Bane of giants" },
    { name: "Adam Ironfist", meaning: "Iron fist" },
    { name: "Brian Stormcaller", meaning: "Storm caller" },
    { name: "Colin Bloodaxe", meaning: "Bloody axe" },
    { name: "Dylan Stonebreaker", meaning: "Stone breaker" },
    { name: "Evan Firebeard", meaning: "Fire beard" },
    { name: "Frank Wolfsbane", meaning: "Wolf bane" },
    { name: "Gary Thunderheart", meaning: "Thunder heart" },
    { name: "Henry Ironvein", meaning: "Iron vein" },
    { name: "Isaac Stormbringer", meaning: "Storm bringer" },
    { name: "Jack Broadaxe", meaning: "Broad axe" },
    { name: "Kevin Warhammer", meaning: "Warhammer" },
    { name: "Larry Skullcrusher", meaning: "Skull crusher" },
    { name: "Mike Ironwill", meaning: "Iron will" },
    { name: "Nick Giantbane", meaning: "Giant bane" },
    { name: "Oscar Steeltoe", meaning: "Steel toe" },
    { name: "Paul Bloodthirst", meaning: "Blood thirst" },
    { name: "Richard Steelbrow", meaning: "Steel brow" },
    { name: "Sam Darkaxe", meaning: "Dark axe" },
    { name: "Tom Flamehand", meaning: "Flame hand" },
    { name: "Umar Frostbeard", meaning: "Frost beard" },
    { name: "Victor Ironhide", meaning: "Iron hide" },
    { name: "Wesley Battleborn", meaning: "Battle born" },
    { name: "Xavier Warcry", meaning: "War cry" },
    { name: "Youssef Bloodaxe", meaning: "Bloody axe" },
    { name: "Zach Stormblade", meaning: "Storm blade" },
    { name: "Aaron Ironfist", meaning: "Iron fist" },
    { name: "Ben Steelheart", meaning: "Steel heart" },
    { name: "Chris Bloodscar", meaning: "Blood scar" },
    { name: "Dan Ironhelm", meaning: "Iron helm" },
    { name: "Eddie Fireaxe", meaning: "Fire axe" },
    { name: "Fred Stormcloak", meaning: "Storm cloak" },
    { name: "George Wolfheart", meaning: "Wolf heart" },
    { name: "Harry Steelvein", meaning: "Steel vein" },
    { name: "Ivan Battlecry", meaning: "Battle cry" },
    { name: "John Firebrand", meaning: "Fire brand" },
    { name: "Ken Ironbrow", meaning: "Iron brow" },
    { name: "Larry Bloodthirst", meaning: "Blood thirst" },
    { name: "Mark Steelaxe", meaning: "Steel axe" },
    { name: "Nick Stormfist", meaning: "Storm fist" },
    { name: "Oscar Ironhide", meaning: "Iron hide" },
    { name: "Phil Warhammer", meaning: "Warhammer" },
    { name: "Rob Bloodaxe", meaning: "Bloody axe" },
    { name: "Steve Stonebreaker", meaning: "Stone breaker" },
    { name: "Tim Stormcaller", meaning: "Storm caller" },
    { name: "Uri Steelheart", meaning: "Steel heart" },
    { name: "Vince Ironwill", meaning: "Iron will" },
    { name: "Will Giantbane", meaning: "Giant bane" },
    { name: "Alex Wolfsbane", meaning: "Wolf bane" },
    { name: "Benny Thunderheart", meaning: "Thunder heart" },
    { name: "Chad Ironvein", meaning: "Iron vein" },
    { name: "Dave Stormbringer", meaning: "Storm bringer" },
    { name: "Eric Broadaxe", meaning: "Broad axe" },
    { name: "Frank Skullcrusher", meaning: "Skull crusher" },
    { name: "Greg Steelbrow", meaning: "Steel brow" },
    { name: "Hal Darkaxe", meaning: "Dark axe" },
    { name: "Ian Flamehand", meaning: "Flame hand" },
    { name: "Jeff Frostbeard", meaning: "Frost beard" },
    { name: "Kenny Battleborn", meaning: "Battle born" },
    { name: "Lee Warcry", meaning: "War cry" },
    { name: "Matt Bloodscar", meaning: "Blood scar" },
    { name: "Neil Ironhelm", meaning: "Iron helm" },
    { name: "Ollie Fireaxe", meaning: "Fire axe" },
    { name: "Pete Stormcloak", meaning: "Storm cloak" },
    { name: "Ralph Wolfheart", meaning: "Wolf heart" },
    { name: "Scott Steelvein", meaning: "Steel vein" },
    { name: "Ted Battlecry", meaning: "Battle cry" },
    { name: "Uriah Firebrand", meaning: "Fire brand" },
    { name: "Vic Ironbrow", meaning: "Iron brow" },
    { name: "Walt Bloodthirst", meaning: "Blood thirst" },
    { name: "Andy Steelaxe", meaning: "Steel axe" },
    { name: "Billy Stormfist", meaning: "Storm fist" },
    { name: "Cory Ironhide", meaning: "Iron hide" },
    { name: "Danny Warhammer", meaning: "Warhammer" },
    { name: "Ernie Bloodaxe", meaning: "Bloody axe" },
    { name: "Floyd Stonebreaker", meaning: "Stone breaker" },
    { name: "Gene Stormcaller", meaning: "Storm caller" },
    { name: "Hank Steelheart", meaning: "Steel heart" },
    { name: "Ike Ironwill", meaning: "Iron will" },
    { name: "Jake Giantbane", meaning: "Giant bane" },
    { name: "Kirk Wolfsbane", meaning: "Wolf bane" },
    { name: "Lou Thunderheart", meaning: "Thunder heart" },
    { name: "Mike Ironvein", meaning: "Iron vein" },
    { name: "Norm Stormbringer", meaning: "Storm bringer" },
    { name: "Ozzie Broadaxe", meaning: "Broad axe" },
    { name: "Pat Skullcrusher", meaning: "Skull crusher" },
    { name: "Ray Steelbrow", meaning: "Steel brow" },
    { name: "Sid Darkaxe", meaning: "Dark axe" },
    { name: "Todd Flamehand", meaning: "Flame hand" },
    { name: "Wes Frostbeard", meaning: "Frost beard" },
    { name: "Al Battleborn", meaning: "Battle born" },
    { name: "Bo Warcry", meaning: "War cry" },
    { name: "Chip Bloodscar", meaning: "Blood scar" },
    { name: "Don Ironhelm", meaning: "Iron helm" },
    { name: "Earl Fireaxe", meaning: "Fire axe" },
    { name: "Gus Stormcloak", meaning: "Storm cloak" },
    { name: "Guy Wolfheart", meaning: "Wolf heart" },
    { name: "Jesse Steelvein", meaning: "Steel vein" },
    { name: "Marty Battlecry", meaning: "Battle cry" },
    { name: "Syd Firebrand", meaning: "Fire brand" },
    { name: "Tyler Ironbrow", meaning: "Iron brow" },
    { name: "Val Bloodthirst", meaning: "Blood thirst" },
    { name: "Bud Steelaxe", meaning: "Steel axe" },
    { name: "Cal Stormfist", meaning: "Storm fist" },
    { name: "Max Ironhide", meaning: "Iron hide" },
    { name: "Rex Warhammer", meaning: "Warhammer" }
];

const femaleNames = [
    { name: "Brunhilde Ironfist", meaning: "Armed princess" },
    { name: "Hilda Stormcaller", meaning: "Battle maiden" },
    { name: "Sigrid Bloodaxe", meaning: "Victory maiden" },
    { name: "Gudrun Stonebreaker", meaning: "Divine secret" },
    { name: "Lagertha Firebeard", meaning: "She who teaches" },
    { name: "Torvi Steeltoe", meaning: "Thor's gift" },
    { name: "Aslaug Wolfsbane", meaning: "Divine strength" },
    { name: "Ragna Thunderheart", meaning: "Warrior queen" },
    { name: "Gunnhild Ironvein", meaning: "Battle maiden" },
    { name: "Ingrid Stormbringer", meaning: "Beautiful" },
    { name: "Astrid Broadaxe", meaning: "Divine strength" },
    { name: "Brynhild Warhammer", meaning: "Armed princess" },
    { name: "Freya Bloodthirst", meaning: "Goddess of love and war" },
    { name: "Helga Skullcrusher", meaning: "Holy" },
    { name: "Maja Ironwill", meaning: "Great" },
    { name: "Rita Giantbane", meaning: "Pearl" },
    { name: "Saga Steelbrow", meaning: "Storyteller" },
    { name: "Thora Darkaxe", meaning: "Thor's gift" },
    { name: "Ulla Flamehand", meaning: "Will" },
    { name: "Vera Frostbeard", meaning: "True" },
    { name: "Alva Ironhide", meaning: "Elf" },
    { name: "Bertha Battleborn", meaning: "Bright" },
    { name: "Cecilia Warcry", meaning: "Blind" },
    { name: "Diana Bloodaxe", meaning: "Divine" },
    { name: "Elena Ironfury", meaning: "Light" },
    { name: "Frida Stormblade", meaning: "Peace" },
    { name: "Gerda Broadshoulder", meaning: "Protection" },
    { name: "Hildegard Bonebreaker", meaning: "Battle enclosure" },
    { name: "Inge Thunderfist", meaning: "Hero's daughter" },
    { name: "Jutta Ironhelm", meaning: "Woman" },
    { name: "Klara Stormcaller", meaning: "Clear" },
    { name: "Maren Bloodscar", meaning: "Of the sea" },
    { name: "Nanna Ironjaw", meaning: "Courage" },
    { name: "Oddny Warhammer", meaning: "New beginning" },
    { name: "Petra Steelheart", meaning: "Rock" },
    { name: "Qetesh Fireaxe", meaning: "Divine" },
    { name: "Raven Battleaxe", meaning: "Dark bird" },
    { name: "Signe Ironfist", meaning: "Victory" },
    { name: "Thorborg Bloodaxe", meaning: "Thor's protection" },
    { name: "Ulrika Stormcloak", meaning: "Wolf ruler" },
    { name: "Vesna Wolfheart", meaning: "Spring" },
    { name: "Wynona Steelvein", meaning: "First born" },
    { name: "Xena Ironhand", meaning: "Stranger" },
    { name: "Ylva Battlecry", meaning: "She-wolf" },
    { name: "Zara Firebrand", meaning: "Princess" },
    { name: "Anna Ironbrow", meaning: "Grace" },
    { name: "Bella Bloodthirst", meaning: "Beautiful" },
    { name: "Clara Steelaxe", meaning: "Clear" },
    { name: "Dora Stormfist", meaning: "Gift" },
    { name: "Erika Ironhide", meaning: "Ruler" },
    { name: "Fiona Warhammer", meaning: "Fair" },
    { name: "Greta Ironwill", meaning: "Pearl" },
    { name: "Hanna Bloodaxe", meaning: "Favor" },
    { name: "Ida Stormcaller", meaning: "Hardworking" },
    { name: "Jenny Steelheart", meaning: "God is gracious" },
    { name: "Karla Bloodscar", meaning: "Strong" },
    { name: "Lena Ironhelm", meaning: "Light" },
    { name: "Mia Fireaxe", meaning: "Mine" },
    { name: "Nina Stormcloak", meaning: "Little girl" },
    { name: "Olivia Wolfheart", meaning: "Olive tree" },
    { name: "Paula Steelvein", meaning: "Small" },
    { name: "Quinn Battlecry", meaning: "Wise" },
    { name: "Rachel Firebrand", meaning: "Ewe" },
    { name: "Sara Ironbrow", meaning: "Princess" },
    { name: "Tanya Bloodthirst", meaning: "Fairy queen" },
    { name: "Ursula Steelaxe", meaning: "Little bear" },
    { name: "Violet Stormfist", meaning: "Purple flower" },
    { name: "Wilma Ironhide", meaning: "Resolute protector" },
    { name: "Abby Warhammer", meaning: "Father rejoiced" },
    { name: "Brenda Bloodaxe", meaning: "Sword" },
    { name: "Carol Stormcaller", meaning: "Joy" },
    { name: "Debbie Steelheart", meaning: "Bee" },
    { name: "Edna Bloodscar", meaning: "Pleasure" },
    { name: "Florence Ironhelm", meaning: "Flowering" },
    { name: "Gladys Fireaxe", meaning: "Princess" },
    { name: "Helen Stormcloak", meaning: "Light" },
    { name: "Iris Wolfheart", meaning: "Rainbow" },
    { name: "Jean Steelvein", meaning: "God is gracious" },
    { name: "Kerry Battlecry", meaning: "Black" },
    { name: "Laura Firebrand", meaning: "Laurel" },
    { name: "Margaret Ironbrow", meaning: "Pearl" },
    { name: "Nancy Bloodthirst", meaning: "Grace" },
    { name: "Olive Steelaxe", meaning: "Olive tree" },
    { name: "Pam Stormfist", meaning: "All sweetness" },
    { name: "Ruth Ironhide", meaning: "Compassionate" },
    { name: "Sally Warhammer", meaning: "Princess" },
    { name: "Teresa Bloodaxe", meaning: "Harvester" },
    { name: "Ursula Stormcaller", meaning: "Little bear" },
    { name: "Violet Steelheart", meaning: "Purple flower" },
    { name: "Amy Bloodscar", meaning: "Beloved" },
    { name: "Bonnie Ironhelm", meaning: "Pretty" },
    { name: "Cheryl Fireaxe", meaning: "Beloved" },
    { name: "Donna Stormcloak", meaning: "Lady" },
    { name: "Elsie Wolfheart", meaning: "God is my oath" },
    { name: "Frances Steelvein", meaning: "Free" },
    { name: "Gloria Battlecry", meaning: "Glory" },
    { name: "Holly Firebrand", meaning: "Holly tree" },
    { name: "Ida Ironbrow", meaning: "Hardworking" },
    { name: "Joan Bloodthirst", meaning: "God is gracious" },
    { name: "Kelly Steelaxe", meaning: "Warrior" },
    { name: "Lisa Stormfist", meaning: "God is my oath" },
    { name: "Mary Ironhide", meaning: "Wished-for child" },
    { name: "Nina Warhammer", meaning: "Little girl" },
    { name: "Opal Bloodaxe", meaning: "Gemstone" },
    { name: "Pamela Stormcaller", meaning: "All sweetness" },
    { name: "Rita Steelheart", meaning: "Pearl" },
    { name: "Sue Bloodscar", meaning: "Lily" },
    { name: "Tina Ironhelm", meaning: "Follower" },
    { name: "Viola Fireaxe", meaning: "Violet" },
    { name: "Angie Stormcloak", meaning: "Messenger" },
    { name: "Bernice Wolfheart", meaning: "Victory bringer" },
    { name: "Crystal Steelvein", meaning: "Ice" },
    { name: "Diane Battlecry", meaning: "Divine" },
    { name: "Erica Firebrand", meaning: "Ruler" },
    { name: "Faith Ironbrow", meaning: "Trust" },
    { name: "Georgia Bloodthirst", meaning: "Farmer" },
    { name: "Hope Steelaxe", meaning: "Desire" },
    { name: "Ivy Stormfist", meaning: "Climbing plant" },
    { name: "Jackie Ironhide", meaning: "Supplanter" },
    { name: "Kim Warhammer", meaning: "Royal fortress" },
    { name: "Leslie Bloodaxe", meaning: "Joy" },
    { name: "Mandy Stormcaller", meaning: "Love" },
    { name: "Nicole Steelheart", meaning: "Victory of the people" },
    { name: "Olivia Bloodscar", meaning: "Olive tree" },
    { name: "Peggy Ironhelm", meaning: "Pearl" },
    { name: "Rebecca Fireaxe", meaning: "Bind" },
    { name: "Samantha Stormcloak", meaning: "Listener" },
    { name: "Tammy Wolfheart", meaning: "Palm tree" },
    { name: "Valerie Steelvein", meaning: "Strong" },
    { name: "Angela Battlecry", meaning: "Messenger" },
    { name: "Brandy Firebrand", meaning: "Fire" },
    { name: "Crystal Ironbrow", meaning: "Ice" },
    { name: "Denise Bloodthirst", meaning: "Dionysus" },
    { name: "Elaine Steelaxe", meaning: "Light" },
    { name: "Ethel Stormfist", meaning: "Noble" },
    { name: "Faye Ironhide", meaning: "Faith" },
    { name: "Gail Warhammer", meaning: "Joy" },
    { name: "Hazel Bloodaxe", meaning: "Hazel tree" },
    { name: "Irma Stormcaller", meaning: "Universal" },
    { name: "Judy Steelheart", meaning: "Praise" },
    { name: "Kay Bloodscar", meaning: "Pure" },
    { name: "Louise Ironhelm", meaning: "Renowned warrior" },
    { name: "Marge Fireaxe", meaning: "Pearl" },
    { name: "Mia Stormcloak", meaning: "Mine" },
    { name: "Nell Wolfheart", meaning: "Light" },
    { name: "Ona Steelvein", meaning: "One" },
    { name: "Patsy Battlecry", meaning: "Noble" },
    { name: "Renee Firebrand", meaning: "Reborn" },
    { name: "Sandy Ironbrow", meaning: "Defender" },
    { name: "Tess Bloodthirst", meaning: "Harvester" },
    { name: "Willow Steelaxe", meaning: "Slender tree" },
    { name: "Dora Stormfist", meaning: "Gift" },
    { name: "Ella Ironhide", meaning: "Light" },
    { name: "Gwen Warhammer", meaning: "Blessed ring" },
    { name: "May Bloodaxe", meaning: "Great" },
    { name: "Rose Stormcaller", meaning: "Flower" },
    { name: "Lila Steelheart", meaning: "Night" },
    { name: "Ruby Bloodscar", meaning: "Red gem" },
    { name: "Clara Ironhelm", meaning: "Clear" },
    { name: "Etta Fireaxe", meaning: "Ruler" },
    { name: "Lulu Stormcloak", meaning: "Pearl" },
    { name: "Maisie Wolfheart", meaning: "Pearl" },
    { name: "Sadie Steelvein", meaning: "Princess" },
    { name: "Effie Battlecry", meaning: "Well-spoken" },
    { name: "Lottie Firebrand", meaning: "Free man" },
    { name: "Mabel Ironbrow", meaning: "Lovable" },
    { name: "Nellie Bloodthirst", meaning: "Light" },
    { name: "Queenie Steelaxe", meaning: "Queen" },
    { name: "Dot Stormfist", meaning: "Gift of God" },
    { name: "Kitty Ironhide", meaning: "Pure" },
    { name: "Betty Warhammer", meaning: "God is my oath" },
    { name: "Flo Bloodaxe", meaning: "Flowering" },
    { name: "Aggie Stormcaller", meaning: "Good" },
    { name: "Annie Steelheart", meaning: "Grace" },
    { name: "Bess Bloodscar", meaning: "God is my oath" },
    { name: "Nell Ironhelm", meaning: "Light" },
    { name: "Hattie Fireaxe", meaning: "Ruler" },
    { name: "Mollie Stormcloak", meaning: "Star of the sea" },
    { name: "Lizzie Wolfheart", meaning: "God is my oath" },
    { name: "Tilly Steelvein", meaning: "Battle" },
    { name: "Polly Battlecry", meaning: "Star of the sea" },
    { name: "Dolly Firebrand", meaning: "Gift of God" },
    { name: "Sally Ironbrow", meaning: "Princess" },
    { name: "Nelly Bloodthirst", meaning: "Light" },
    { name: "Winnie Steelaxe", meaning: "Friend of peace" },
    { name: "Gerty Stormfist", meaning: "Spear" },
    { name: "Hettie Ironhide", meaning: "Ruler" },
    { name: "Lily Warhammer", meaning: "Pure" },
    { name: "Millie Bloodaxe", meaning: "Strength" },
    { name: "Tessie Stormcaller", meaning: "Harvester" },
    { name: "Effie Steelheart", meaning: "Well-spoken" },
    { name: "Belle Bloodscar", meaning: "Beautiful" },
    { name: "Cora Ironhelm", meaning: "Maiden" },
    { name: "Ella Fireaxe", meaning: "Light" },
    { name: "Hilda Stormcloak", meaning: "Battle woman" },
    { name: "Ida Wolfheart", meaning: "Hardworking" },
    { name: "Maggie Steelvein", meaning: "Pearl" },
    { name: "Ruth Battlecry", meaning: "Compassionate" },
    { name: "Susie Firebrand", meaning: "Lily" },
    { name: "Annie Ironbrow", meaning: "Grace" },
    { name: "Daisy Bloodthirst", meaning: "Day's eye" },
    { name: "Kitty Steelaxe", meaning: "Pure" },
    { name: "Maisie Stormfist", meaning: "Pearl" },
    { name: "Rose Ironhide", meaning: "Flower" }
];

let currentMode = 'random';

document.querySelectorAll('.mode-btn').forEach(btn => {
    btn.addEventListener('click', function() {
        document.querySelectorAll('.mode-btn').forEach(b => b.classList.remove('active'));
        this.classList.add('active');
        currentMode = this.dataset.mode;
    });
});

function generateNames() {
    const grid = document.getElementById('namesGrid');
    grid.innerHTML = '';
    
    let names = [];
    
    if (currentMode === 'male') {
        names = shuffleArray([...maleNames]).slice(0, 16).map(n => ({...n, gender: 'Male'}));
    } else if (currentMode === 'female') {
        names = shuffleArray([...femaleNames]).slice(0, 16).map(n => ({...n, gender: 'Female'}));
    } else {
        const allNames = [
            ...maleNames.map(n => ({...n, gender: 'Male'})),
            ...femaleNames.map(n => ({...n, gender: 'Female'}))
        ];
        names = shuffleArray(allNames).slice(0, 16);
    }
    
    names.forEach((item, index) => {
        const card = document.createElement('div');
        card.className = 'name-card';
        card.style.opacity = '0';
        card.style.transform = 'translateY(20px)';
        card.innerHTML = `
            <div class="name-text">${item.name}</div>
            <div class="name-gender">${item.gender}</div>
            <div class="name-meaning">${item.meaning}</div>
        `;
        grid.appendChild(card);
        
        setTimeout(() => {
            card.style.transition = 'all 0.3s ease';
            card.style.opacity = '1';
            card.style.transform = 'translateY(0)';
        }, index * 40);
    });
}

function shuffleArray(array) {
    for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]];
    }
    return array;
}

