const maleNames = [
    { name: "Thalion", meaning: "Hero, valiant one" },
    { name: "Elrond", meaning: "Star dome, vault of heaven" },
    { name: "Legolas", meaning: "Green leaves" },
    { name: "Thranduil", meaning: "Vigorous spring" },
    { name: "Gil-galad", meaning: "Star of radiance" },
    { name: "Fingolfin", meaning: "Finwë's son, wise one" },
    { name: "Finrod", meaning: "Mighty descendant" },
    { name: "Celeborn", meaning: "Silver tree" },
    { name: "Glorfindel", meaning: "Golden-haired" },
    { name: "Ecthelion", meaning: "Fountain lord" },
    { name: "Fëanor", meaning: "Spirit of fire" },
    { name: "Maedhros", meaning: "Well-formed one" },
    { name: "Curufin", meaning: "Skilled son" },
    { name: "Celegorm", meaning: "Hasty one" },
    { name: "Caranthir", meaning: "Red-faced" },
    { name: "Amrod", meaning: "Hill climber" },
    { name: "Amras", meaning: "Wanderer" },
    { name: "Turgon", meaning: "Victorious commander" },
    { name: "Fingon", meaning: "Valiant one" },
    { name: "Aegnor", meaning: "Fell fire" },
    { name: "Angrod", meaning: "Iron-noble" },
    { name: "Orodreth", meaning: "Golden king" },
    { name: "Denethor", meaning: "Sorrowful" },
    { name: "Thingol", meaning: "Grey-cloak" },
    { name: "Beren", meaning: "Bold one" },
    { name: "Tuor", meaning: "Strength" },
    { name: "Eärendil", meaning: "Sea lover" },
    { name: "Elros", meaning: "Star foam" },
    { name: "Haldir", meaning: "Tall one" },
    { name: "Elladan", meaning: "Elf-man" },
    { name: "Elrohir", meaning: "Elf-knight" },
    { name: "Gildor", meaning: "Star lord" },
    { name: "Círdan", meaning: "Shipwright" },
    { name: "Erestor", meaning: "Noble one" },
    { name: "Galdor", meaning: "Tree lord" },
    { name: "Lindir", meaning: "Song lord" },
    { name: "Rúmil", meaning: "Secret one" },
    { name: "Daeron", meaning: "Great one" },
    { name: "Beleg", meaning: "Mighty" },
    { name: "Mablung", meaning: "Heavy-handed" },
    { name: "Aeglos", meaning: "Snowthorn" },
    { name: "Gelmir", meaning: "Joyous one" },
    { name: "Arminas", meaning: "Royal tower" },
    { name: "Gwindor", meaning: "Wind lord" },
    { name: "Oropher", meaning: "Beech king" },
    { name: "Amdir", meaning: "Looking up" },
    { name: "Malbeth", meaning: "Gold word" },
    { name: "Celepharn", meaning: "Silver rock" },
    { name: "Eärnur", meaning: "Sea king" },
    { name: "Faramir", meaning: "Jewel hunter" },
    { name: "Boromir", meaning: "Faithful jewel" },
    { name: "Isildur", meaning: "Servant of the moon" },
    { name: "Anárion", meaning: "Sun son" },
    { name: "Elendil", meaning: "Star friend" },
    { name: "Amandil", meaning: "Blessed friend" },
    { name: "Númendil", meaning: "West friend" },
    { name: "Valandil", meaning: "Power friend" },
    { name: "Ohtar", meaning: "Warrior" },
    { name: "Mithrellas", meaning: "Grey leaf" },
    { name: "Thoron", meaning: "Eagle" },
    { name: "Elenion", meaning: "Star son" },
    { name: "Calenardhon", meaning: "Green province" },
    { name: "Firiel", meaning: "Mortal one" },
    { name: "Ornendil", meaning: "Tree friend" },
    { name: "Eärnil", meaning: "Sea lover" },
    { name: "Telumehtar", meaning: "Orion" },
    { name: "Vorondil", meaning: "Faithful friend" },
    { name: "Mardil", meaning: "Home friend" },
    { name: "Eradan", meaning: "Elf man" },
    { name: "Beregond", meaning: "Fierce stone" },
    { name: "Bergil", meaning: "Fierce leaf" },
    { name: "Damrod", meaning: "Hammerer" },
    { name: "Duinhir", meaning: "River lord" },
    { name: "Dúnedain", meaning: "West men" },
    { name: "Golasgil", meaning: "Leaf warden" },
    { name: "Hirluin", meaning: "Pale blue" },
    { name: "Ingold", meaning: "Yew gold" },
    { name: "Iorlas", meaning: "Old leaf" },
    { name: "Longo", meaning: "Heavy" },
    { name: "Moril", meaning: "Dark one" },
    { name: "Nardol", meaning: "Fire head" },
    { name: "Narthad", meaning: "Saddle" },
    { name: "Ragnor", meaning: "Wanderer" },
    { name: "Rodwen", meaning: "Noble maiden" },
    { name: "Sador", meaning: "Faithful" },
    { name: "Tindor", meaning: "Star lord" },
    { name: "Voronwë", meaning: "Faithful one" },
    { name: "Alatar", meaning: "Wayfarer" },
    { name: "Pallando", meaning: "Helper" },
    { name: "Orome", meaning: "Horn blower" },
    { name: "Tulkas", meaning: "Strong one" },
    { name: "Ulmo", meaning: "Pourer" },
    { name: "Aulë", meaning: "Maker" },
    { name: "Námo", meaning: "Judge" },
    { name: "Ilmarë", meaning: "Sky maiden" },
    { name: "Melkor", meaning: "Mighty one" },
    { name: "Manwë", meaning: "Blessed one" },
    { name: "Varda", meaning: "Exalted" },
    { name: "Yavanna", meaning: "Giver of fruits" },
    { name: "Arien", meaning: "Maiden of fire" },
    { name: "Tilion", meaning: "Hunter" },
    { name: "Eönwë", meaning: "Host of mana" },
    { name: "Ilmatar", meaning: "Mother of stars" },
    { name: "Míriel", meaning: "Jewel of light" },
    { name: "Rúmil", meaning: "Lore master" },
    { name: "Pengolodh", meaning: "Golden skill" },
    { name: "Quennar", meaning: "Ever-young" },
    { name: "Orophin", meaning: "Mountain peak" },
    { name: "Nimrodel", meaning: "Lady of the cave" },
    { name: "Halmir", meaning: "Helmet glory" },
    { name: "Galdor", meaning: "Tree voice" },
    { name: "Hirwing", meaning: "Lord of birds" },
    { name: "Falathrim", meaning: "Elves of the shore" },
    { name: "Círdan", meaning: "Ship builder" },
    { name: "Voronor", meaning: "Faithful mountain" },
    { name: "Thalantar", meaning: "Renewed lord" },
    { name: "Cormarë", meaning: "Lord of councils" },
    { name: "Aicanar", meaning: "Mountain dweller" },
    { name: "Naimon", meaning: "Sage" },
    { name: "Lalaith", meaning: "Laughter" },
    { name: "Nauriel", meaning: "Fire maiden" },
    { name: "Tinúviel", meaning: "Nightingale" },
    { name: "Aranrúth", meaning: "King's wrath" },
    { name: "Dor-Fuinn", meaning: "Land of sorrow" },
    { name: "Edhelharn", meaning: "Elf-jewel" },
    { name: "Gwareth", meaning: "Stone hill" },
    { name: "Lothron", meaning: "Flower" },
    { name: "Nantath", meaning: "Dream" },
    { name: "Orchaldor", meaning: "Oak lord" },
    { name: "Pelinor", meaning: "Heavenly" },
    { name: "Rimlad", meaning: "The wild" },
    { name: "Sorontil", meaning: "Storm tower" },
    { name: "Tinwaldis", meaning: "Little maiden" },
    { name: "Uilos", meaning: "Eternal bloom" },
    { name: "Varin", meaning: "Firm" },
    { name: "Wilwarin", meaning: "Butterfly" },
    { name: "Yavannie", meaning: "Fruit giver" },
    { name: "Aerim", meaning: "Oak lover" },
    { name: "Belecthor", meaning: "Silver lord" },
    { name: "Celehdil", meaning: "Star friend" },
    { name: "Dairil", meaning: "Noble" },
    { name: "Egalmoth", meaning: "Great jewel" },
    { name: "Fastitocalon", meaning: "Turtle" },
    { name: "Gothmog", meaning: "Battle scrap" },
    { name: "Hirilorn", meaning: "Lady tree" },
    { name: "Imrahil", meaning: "Elf of the tower" },
    { name: "Landroval", meaning: "Sky height" },
    { name: "Mithrandir", meaning: "Grey pilgrim" },
    { name: "Nogrod", meaning: "Northern forge" },
    { name: "Olórin", meaning: "Dream maker" },
    { name: "Palantir", meaning: "Far-sighted" },
    { name: "Radagast", meaning: "Care giver" },
    { name: "Saruman", meaning: "Man of skill" },
    { name: "Tar-Meneldur", meaning: "High heaven" },
    { name: "Valandur", meaning: "Faithful king" },
    { name: "Westar", meaning: "West" },
    { name: "Yavannamíre", meaning: "Fruit lover" },
    { name: "Zaraphin", meaning: "Star of dawn" },
    { name: "Aelduin", meaning: "River of elves" },
    { name: "Borthand", meaning: "Letter friend" },
    { name: "Celebdil", meaning: "Silver mount" },
    { name: "Dolmed", meaning: "Wet head" },
    { name: "Eldar", meaning: "People of stars" },
    { name: "Falas", meaning: "Shore" },
    { name: "Gandalf", meaning: "Wand elf" },
    { name: "Hithlomir", meaning: "Hidden valley" },
    { name: "Imladris", meaning: "Deep valley" },
    { name: "Lairelassë", meaning: "Golden leaf" },
    { name: "Mithrim", meaning: "Grey region" },
    { name: "Nargothrond", meaning: "Underground palace" },
    { name: "Orodruin", meaning: "Mountain of fire" },
    { name: "Periannath", meaning: "Half-elves" },
    { name: "Quenya", meaning: "Elvish tongue" },
    { name: "Rivendell", meaning: "Deep dell" },
    { name: "Silmaril", meaning: "Radiant gem" },
    { name: "Taniquetil", meaning: "High peak" },
    { name: "Umanyar", meaning: "Awakening" }
];

const femaleNames = [
    { name: "Galadriel", meaning: "Maiden crowned with radiance" },
    { name: "Arwen", meaning: "Noble maiden" },
    { name: "Lúthien", meaning: "Enchantress" },
    { name: "Celebrían", meaning: "Silver queen" },
    { name: "Elbereth", meaning: "Star queen" },
    { name: "Aredhel", meaning: "Noble elf" },
    { name: "Idril", meaning: "Sparkling brilliance" },
    { name: "Nimrodel", meaning: "Lady of the white cave" },
    { name: "Nerdanel", meaning: "Wise one" },
    { name: "Varda", meaning: "Exalted one" },
    { name: "Yavanna", meaning: "Giver of fruits" },
    { name: "Nienna", meaning: "Weeper" },
    { name: "Estë", meaning: "Rest, healing" },
    { name: "Vairë", meaning: "Weaver" },
    { name: "Nessa", meaning: "Young one" },
    { name: "Uinen", meaning: "Sea lady" },
    { name: "Melian", meaning: "Gift of love" },
    { name: "Míriel", meaning: "Jewel of light" },
    { name: "Indis", meaning: "Bride" },
    { name: "Anairë", meaning: "Holiest one" },
    { name: "Eärwen", meaning: "Sea maiden" },
    { name: "Morwen", meaning: "Dark maiden" },
    { name: "Nienor", meaning: "Mourning" },
    { name: "Finduilas", meaning: "Golden stream" },
    { name: "Silmaríë", meaning: "Jewel of pure light" },
    { name: "Elwing", meaning: "Star foam" },
    { name: "Nimloth", meaning: "White blossom" },
    { name: "Tindómiel", meaning: "Twilight daughter" },
    { name: "Amarie", meaning: "Beautiful one" },
    { name: "Elenwë", meaning: "Star being" },
    { name: "Itaril", meaning: "Sparkling star" },
    { name: "Lalwen", meaning: "Laughing maiden" },
    { name: "Nellas", meaning: "Leaf maiden" },
    { name: "Rían", meaning: "Crowned one" },
    { name: "Lothíriel", meaning: "Flower queen" },
    { name: "Aranel", meaning: "Noble king" },
    { name: "Artanis", meaning: "Noble woman" },
    { name: "Earame", meaning: "Sea jewel" },
    { name: "Elenil", meaning: "Star daughter" },
    { name: "Elensë", meaning: "Star being" },
    { name: "Elentári", meaning: "Star queen" },
    { name: "Elmare", meaning: "Star home" },
    { name: "Eltariel", meaning: "Star maiden" },
    { name: "Emerwen", meaning: "Princess" },
    { name: "Enerdhil", meaning: "Sun flower" },
    { name: "Enel", meaning: "First one" },
    { name: "Enelde", meaning: "First three" },
    { name: "Erendis", meaning: "Lonely wife" },
    { name: "Erendë", meaning: "Iron being" },
    { name: "Erien", meaning: "Iron maiden" },
    { name: "Eriol", meaning: "Iron leaf" },
    { name: "Eruanne", meaning: "God's gift" },
    { name: "Erulaidë", meaning: "God's lady" },
    { name: "Eruviel", meaning: "God's daughter" },
    { name: "Essë", meaning: "Name" },
    { name: "Estellë", meaning: "Hope" },
    { name: "Etya", meaning: "Little one" },
    { name: "Falastur", meaning: "Sea lord" },
    { name: "Faniel", meaning: "Sun daughter" },
    { name: "Fanuir", meaning: "Sun lord" },
    { name: "Fanuilos", meaning: "White spirit" },
    { name: "Fealóce", meaning: "Spirit wave" },
    { name: "Fëa", meaning: "Spirit" },
    { name: "Fëanturi", meaning: "Spirit masters" },
    { name: "Findë", meaning: "Hair" },
    { name: "Findel", meaning: "Hair one" },
    { name: "Findui", meaning: "Golden one" },
    { name: "Finellach", meaning: "Golden flame" },
    { name: "Finelote", meaning: "Golden flower" },
    { name: "Finyë", meaning: "Small hair" },
    { name: "Firim", meaning: "Mortal ones" },
    { name: "Fíriel", meaning: "Mortal maiden" },
    { name: "Fírima", meaning: "Mortal" },
    { name: "Fírimë", meaning: "Mortality" },
    { name: "Formenos", meaning: "Northern fortress" },
    { name: "Forod", meaning: "North region" },
    { name: "Forochel", meaning: "Northern ice" },
    { name: "Forostar", meaning: "Northern lands" },
    { name: "Fortar", meaning: "North lord" },
    { name: "Ilmarë", meaning: "Sky maiden" },
    { name: "Arien", meaning: "Fire maiden" },
    { name: "Tilion", meaning: "Huntress" },
    { name: "Varda", meaning: "Star queen" },
    { name: "Elen", meaning: "Star" },
    { name: "Silmarie", meaning: "Light jewel" },
    { name: "Aelin", meaning: "Lake" },
    { name: "Alassë", meaning: "Joy" },
    { name: "Alcarinë", meaning: "Glorious" },
    { name: "Amit", meaning: "Beloved" },
    { name: "Amloth", meaning: "Shadow" },
    { name: "Anastaryel", meaning: "Spark of starlight" },
    { name: "Anairë", meaning: "Holy maiden" },
    { name: "Andra", meaning: "Queen" },
    { name: "Anor", meaning: "Sun" },
    { name: "Aredhel", meaning: "Noble spirit" },
    { name: "Argel", meaning: "Morn" },
    { name: "Arien", meaning: "Spark of fire" },
    { name: "Atar", meaning: "Father" },
    { name: "Cala", meaning: "Light" },
    { name: "Celeborn", meaning: "Silver tree" },
    { name: "Celebrindal", meaning: "Silver grace" },
    { name: "Celenia", meaning: "Moon lady" },
    { name: "Dae", meaning: "Day" },
    { name: "Dael", meaning: "Grace" },
    { name: "Dair", meaning: "Fire" },
    { name: "Dancann", meaning: "Swift" },
    { name: "Delian", meaning: "Blessed" },
    { name: "Ear", meaning: "Sea" },
    { name: "Eärildë", meaning: "Sea child" },
    { name: "Eärwen", meaning: "Sea maiden" },
    { name: "Edhell", meaning: "Elf" },
    { name: "Edhellis", meaning: "Elf maiden" },
    { name: "Edra", meaning: "Wealth" },
    { name: "Eirien", meaning: "Healer" },
    { name: "Elanor", meaning: "Star sun" },
    { name: "Elanoriel", meaning: "Star sun maiden" },
    { name: "Elariel", meaning: "Star maiden" },
    { name: "Eldalótë", meaning: "Elf blossom" },
    { name: "Eldarón", meaning: "Elf lord" },
    { name: "Eldrin", meaning: "Elf seer" },
    { name: "Elen", meaning: "Star" },
    { name: "Eleniel", meaning: "Star daughter" },
    { name: "Elentari", meaning: "Star queen" },
    { name: "Elin", meaning: "Star" },
    { name: "Elith", meaning: "Hope" },
    { name: "Elivë", meaning: "Star wave" },
    { name: "Ellan", meaning: "Star" },
    { name: "Elo", meaning: "Sky" },
    { name: "Enel", meaning: "One" },
    { name: "Enerdhil", meaning: "Golden" },
    { name: "Eru", meaning: "God" },
    { name: "Este", meaning: "Rest" },
    { name: "Fael", meaning: "Cave" },
    { name: "Faelyn", meaning: "Cave pool" },
    { name: "Fair", meaning: "Fair" },
    { name: "Falas", meaning: "Shore" },
    { name: "Fan", meaning: "Beard" },
    { name: "Fanel", meaning: "Moor" },
    { name: "Fanya", meaning: "Moor" },
    { name: "Fëa", meaning: "Soul" },
    { name: "Findis", meaning: "Silver" },
    { name: "Finduilas", meaning: "Golden water" },
    { name: "Fin", meaning: "Hair" },
    { name: "Fína", meaning: "Swan" },
    { name: "Firiel", meaning: "Mortal maiden" },
    { name: "Flída", meaning: "Archer" },
    { name: "Galad", meaning: "Light" },
    { name: "Galadhon", meaning: "Light forest" },
    { name: "Galadriel", meaning: "Crowned maiden" },
    { name: "Galdor", meaning: "Tree voice" },
    { name: "Gálya", meaning: "Joy" },
    { name: "Gildis", meaning: "Sparkle" },
    { name: "Glorien", meaning: "Golden" },
    { name: "Glorindë", meaning: "Golden flower" },
    { name: "Haer", meaning: "Home" },
    { name: "Hal", meaning: "Star" },
    { name: "Haldir", meaning: "Tall" },
    { name: "Híril", meaning: "Lady" },
    { name: "Ial", meaning: "Maiden" },
    { name: "Iaman", meaning: "Jewel" },
    { name: "Iaramë", meaning: "Blossom" },
    { name: "Iaur", meaning: "Old" },
    { name: "Idril", meaning: "Sparkle" },
    { name: "Ilmarë", meaning: "Sky" },
    { name: "Imbel", meaning: "Foam" },
    { name: "Imdrassil", meaning: "Dream tree" },
    { name: "Immil", meaning: "Maiden" },
    { name: "Ir", meaning: "Lady" },
    { name: "Irin", meaning: "Jewel" },
    { name: "Isil", meaning: "Moon" },
    { name: "Ithil", meaning: "Moon" },
    { name: "Ivann", meaning: "Gift" },
    { name: "Lair", meaning: "Lady" },
    { name: "Lalaith", meaning: "Laughter" },
    { name: "Laly", meaning: "Joy" },
    { name: "Laurelin", meaning: "Golden song" },
    { name: "Legolas", meaning: "Green leaves" },
    { name: "Lir", meaning: "Song" },
    { name: "Liss", meaning: "Blossom" },
    { name: "Lith", meaning: "Snow" },
    { name: "Loth", meaning: "Flower" },
    { name: "Lúthien", meaning: "Enchanter" },
    { name: "Maeg", meaning: "Maiden" },
    { name: "Mály", meaning: "Maiden" },
    { name: "Mardil", meaning: "Beloved" },
    { name: "Mel", meaning: "Love" },
    { name: "Melian", meaning: "Beloved" },
    { name: "Mell", meaning: "Beloved" },
    { name: "Mellon", meaning: "Treasure" },
    { name: "Menel", meaning: "Sky" },
    { name: "Meril", meaning: "Maiden" },
    { name: "Míriel", meaning: "Jewel" },
    { name: "Mith", meaning: "Grey" },
    { name: "Mithril", meaning: "Grey jewel" },
    { name: "Mor", meaning: "Dark" },
    { name: "Morwen", meaning: "Dark maiden" },
    { name: "Nair", meaning: "Pure" },
    { name: "Nairel", meaning: "Pure star" },
    { name: "Námo", meaning: "Judge" },
    { name: "Nell", meaning: "Bird" },
    { name: "Nellas", meaning: "Leaf maiden" },
    { name: "Nerdanel", meaning: "Wise" },
    { name: "Nim", meaning: "Lady" },
    { name: "Nimrodel", meaning: "Cave lady" },
    { name: "Nir", meaning: "Jewel" },
    { name: "Nor", meaning: "Home" },
    { name: "Nín", meaning: "Maiden" },
    { name: "Ol", meaning: "Dream" },
    { name: "Olor", meaning: "Spirit" },
    { name: "Olos", meaning: "Spirit" },
    { name: "Onen", meaning: "Maiden" },
    { name: "Or", meaning: "Gold" },
    { name: "Orop", meaning: "Forest" },
    { name: "Orophin", meaning: "Forest bird" },
    { name: "Rána", meaning: "Sun" },
    { name: "Rhos", meaning: "Rose" },
    { name: "Ril", meaning: "Jewel" },
    { name: "Rim", meaning: "Sky" },
    { name: "Sal", meaning: "Light" },
    { name: "Sil", meaning: "Light" },
    { name: "Silmarie", meaning: "Light jewel" },
    { name: "Sínerë", meaning: "Holy" },
    { name: "Sir", meaning: "Water" },
    { name: "Siril", meaning: "Water jewel" },
    { name: "Sul", meaning: "Song" },
    { name: "Súl", meaning: "Wind" },
    { name: "Tári", meaning: "Queen" },
    { name: "Tin", meaning: "Night" },
    { name: "Tinúviel", meaning: "Nightingale" },
    { name: "Tir", meaning: "Watch" },
    { name: "Uol", meaning: "Dream" },
    { name: "Ull", meaning: "Night" },
    { name: "Van", meaning: "Fair" },
    { name: "Vána", meaning: "Beautiful" },
    { name: "Var", meaning: "Star" },
    { name: "Varda", meaning: "Star queen" },
    { name: "Vëann", meaning: "Maiden" },
    { name: "Wil", meaning: "Maiden" },
    { name: "Yal", meaning: "Star" },
    { name: "Yavie", meaning: "Fruit" }
];

let currentMode = 'random';

document.querySelectorAll('.mode-btn').forEach(btn => {
    btn.addEventListener('click', function() {
        document.querySelectorAll('.mode-btn').forEach(b => b.classList.remove('active'));
        this.classList.add('active');
        currentMode = this.dataset.mode;
    });
});

function generateNames() {
    const grid = document.getElementById('namesGrid');
    grid.innerHTML = '';
    
    let names = [];
    
    if (currentMode === 'male') {
        names = shuffleArray([...maleNames]).slice(0, 16).map(n => ({...n, gender: 'Male'}));
    } else if (currentMode === 'female') {
        names = shuffleArray([...femaleNames]).slice(0, 16).map(n => ({...n, gender: 'Female'}));
    } else {
        const allNames = [
            ...maleNames.map(n => ({...n, gender: 'Male'})),
            ...femaleNames.map(n => ({...n, gender: 'Female'}))
        ];
        names = shuffleArray(allNames).slice(0, 16);
    }
    
    names.forEach((item, index) => {
        const card = document.createElement('div');
        card.className = 'name-card';
        card.style.opacity = '0';
        card.style.transform = 'translateY(20px)';
        card.innerHTML = `
            <div class="name-text">${item.name}</div>
            <div class="name-gender">${item.gender}</div>
            <div class="name-meaning">${item.meaning}</div>
        `;
        grid.appendChild(card);
        
        setTimeout(() => {
            card.style.transition = 'all 0.3s ease';
            card.style.opacity = '1';
            card.style.transform = 'translateY(0)';
        }, index * 40);
    });
}

function shuffleArray(array) {
    for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]];
    }
    return array;
}