const maleNames = [
    { name: "Aiden Blackwolf", meaning: "Little fire with dark wolf spirit" },
    { name: "Blake Shadowfang", meaning: "Dark one with shadowy teeth" },
    { name: "Cole Howlingmoon", meaning: "Coal-black howler of the moon" },
    { name: "Draven Nightclaw", meaning: "Night hunter with deadly claws" },
    { name: "Ethan Silverpaw", meaning: "Silver wolf with noble spirit" },
    { name: "Finn Wolfheart", meaning: "Courageous with wolf spirit" },
    { name: "Grayson Ironfang", meaning: "Son of the gray wolf" },
    { name: "Hunter Moonshade", meaning: "Hunter under the moon's shadow" },
    { name: "Ivan Wildfang", meaning: "Wild one with fierce teeth" },
    { name: "Jack Darkhowl", meaning: "Dark howler of the night" },
    { name: "Kai Stormwolf", meaning: "Wolf born of storms" },
    { name: "Liam Greypaw", meaning: "Protector with gray wolf paws" },
    { name: "Mason Fanglore", meaning: "Mason of the wolf legends" },
    { name: "Nash Nightstalker", meaning: "Night hunter in darkness" },
    { name: "Orion Wolfsbane", meaning: "Hunter who fights wolves" },
    { name: "Pierce Darkmane", meaning: "Piercing dark wolf mane" },
    { name: "Quinn Shadowpack", meaning: "Shadow of the wolf pack" },
    { name: "Rhys Ironclaw", meaning: "Red-haired with iron claws" },
    { name: "Seth Moonhunter", meaning: "Hunter under the moonlight" },
    { name: "Troy Wildstorm", meaning: "Fierce warrior of the wild" },
    { name: "Ulric Blackblood", meaning: "Ruler of dark lineage" },
    { name: "Vance Silverhowl", meaning: "Silver voice howler" },
    { name: "Wyatt Fangstrike", meaning: "One who strikes with fangs" },
    { name: "Xander Beastcaller", meaning: "Summoner of the beast within" },
    { name: "Yale Darkpaw", meaning: "One-footed in darkness" },
    { name: "Zane Moonshadow", meaning: "Shadow cast by the moon" },
    { name: "Aaron Wolfrunner", meaning: "Runner with wolves" },
    { name: "Brandon Nightfury", meaning: "Fury of the night" },
    { name: "Cody Wolfsnap", meaning: "Wolf who snaps" },
    { name: "Derek Stormfang", meaning: "Storm-bringer with fangs" },
    { name: "Eli Houndmaster", meaning: "Master of hounds" },
    { name: "Floyd Darkfur", meaning: "One with dark fur" },
    { name: "Gage Ironpaw", meaning: "One who measures with iron paws" },
    { name: "Hayes Wildclaw", meaning: "Wild one with claws" },
    { name: "Ivan Moonstrider", meaning: "Moon walker" },
    { name: "Jace Shadowfur", meaning: "Shadow with fur" },
    { name: "Kade Nightrunner", meaning: "Runner through night" },
    { name: "Landon Wolfsong", meaning: "Song of the wolf" },
    { name: "Maddox Beastheart", meaning: "Heart of the beast" },
    { name: "Nate Darkhowler", meaning: "Dark one who howls" },
    { name: "Owen Moonclaw", meaning: "Claw of the moon" },
    { name: "Paul Wildblood", meaning: "Wild one by blood" },
    { name: "Quinn Ashfang", meaning: "Wolf of the ashes" },
    { name: "Rex Ironwolf", meaning: "King of iron wolves" },
    { name: "Sam Wolfbane", meaning: "Poison to wolves" },
    { name: "Tanner Darkmane", meaning: "Tanner of dark mane" },
    { name: "Uriah Nightwolf", meaning: "Servant of night wolf" },
    { name: "Vince Moonshade", meaning: "Shadow of the moon" },
    { name: "Wade Silverclaw", meaning: " Wade of the silver claw" },
    { name: "Xavier Fangmaster", meaning: "Master of fangs" },
    { name: "Yale Furball", meaning: "Ball of fur" },
    { name: "Zeke Blackstorm", meaning: "Black storm bringer" },
    { name: "Axel Howlbringer", meaning: "One who brings howls" },
    { name: "Blaze Darkpaws", meaning: "Blazing dark paws" },
    { name: "Cage Moonbeast", meaning: "Caged moon beast" },
    { name: "Dale Nightstalker", meaning: "Dweller in night" },
    { name: "Earl Wolfsbane", meaning: "Noble wolf killer" },
    { name: "Fox Darkrunner", meaning: "Clever dark runner" },
    { name: "Gus Ironhowl", meaning: "Gus with iron howl" },
    { name: "Heath Moonshadow", meaning: "Heath of moon shadow" },
    { name: "Idris Wolfheart", meaning: "Lord with wolf heart" },
    { name: "Jasper Stonefang", meaning: "Jasper stone fangs" },
    { name: "Kane Blackclaw", meaning: "Battle dark claw" },
    { name: "Lars Stormhowl", meaning: "Son of storm howl" },
    { name: "Milo Wildpaw", meaning: "Merciful wild paw" },
    { name: "Nico Shadowpack", meaning: "Victory of shadow pack" },
    { name: "Odin Nightfury", meaning: "Fury of the night god" },
    { name: "Peter Moonfangs", meaning: "Rock with moon fangs" },
    { name: "Ron Wildstorm", meaning: "Giant wild storm" },
    { name: "Samson Darkfur", meaning: "Sun-like dark fur" },
    { name: "Troy Beastmaster", meaning: "Fierce beast master" },
    { name: "Ulf Blackhowl", meaning: "Wolf of black howl" },
    { name: "Victor Ironclaw", meaning: "Conqueror with iron claws" },
    { name: "Wolf Moonhunter", meaning: "Guardian moon hunter" },
    { name: "Yuri Darkpaw", meaning: "Farmer of dark paw" },
    { name: "Zeke Stormwolf", meaning: "God strengthens storm wolf" },
    { name: "Axel Silverfang", meaning: "Father of peace silver fang" },
    { name: "Brock Darkmane", meaning: "Badger with dark mane" },
    { name: "Cain Wolfsnap", meaning: "Spear wolf snap" },
    { name: "Drew Howlstorm", meaning: "Wise howl storm" },
    { name: "Evan Moonclaw", meaning: "Gracious moon claw" },
    { name: "Frost Nightwolf", meaning: "Frost of night wolf" },
    { name: "Gale Silverpaw", meaning: "Fast one with silver paw" },
    { name: "Hank Darkfang", meaning: "Rules with dark fang" },
    { name: "Ian Beastcaller", meaning: "God is gracious beast" },
    { name: "Jax Wolfshadow", meaning: "God has been gracious wolf shadow" },
    { name: "Knox Ironhowl", meaning: "Round-topped iron howl" },
    { name: "Logan Nightstalker", meaning: "Little hollow night stalker" },
    { name: "Marko Darkblood", meaning: "Dedicated to war dark blood" },
    { name: "Neil Wolfrunner", meaning: "Champion wolf runner" },
    { name: "Olaf Stormclaw", meaning: "Ancestor's descendant storm claw" },
    { name: "Patch Wildfang", meaning: "Patch of wild fang" },
    { name: "Rory Moonshade", meaning: "Red king moon shade" },
    { name: "Sven Ironwolf", meaning: "Youth iron wolf" },
    { name: "Toby Shadowpaw", meaning: "God is good shadow paw" },
    { name: "Ulric Blackstorm", meaning: "Ruler of black storm" },
    { name: "Valo Darkhowler", meaning: "Brave dark howler" },
    { name: "Wolfgang Furheart", meaning: "Wolf path fierce heart" },
    { name: "Yuri Wolfsong", meaning: "Farmer wolf song" },
    { name: "Zara Beastfang", meaning: "Eastern wolf beast fang" },
    { name: "Arlo Nightfury", meaning: "Fortress of night fury" },
    { name: "Boris Stormwolf", meaning: "Battle fury storm wolf" },
    { name: "Cyrus Darkclaw", meaning: "Sun dark claw" },
    { name: "Drake Moonfang", meaning: "Dragon moon fang" },
    { name: "Emil Ironpaw", meaning: "Rival iron paw" },
    { name: "Flynn Shadowhowl", meaning: "Son of the bright one shadow howl" },
    { name: "Glen Darkfur", meaning: "Valley of dark fur" },
    { name: "Haze Moonshade", meaning: "Obscured moon shade" },
    { name: "Ivar Blackfang", meaning: "Yew warrior black fang" },
    { name: "Jared Wolfbane", meaning: "Cry of despair wolf bane" },
    { name: "Kade Wildstorm", meaning: "Barbed wild storm" },
    { name: "Lars Silverclaw", meaning: "Crowned with laurel silver claw" },
    { name: "Mace Nightstalker", meaning: "Club weapon night stalker" },
    { name: "Nalo Darkmane", meaning: "Winner dark mane" },
    { name: "Orlo Wolfsong", meaning: "Golden wolf song" },
    { name: "Pike Stormfang", meaning: "Pointed weapon storm fang" },
    { name: "Rafe Ironhowl", meaning: "Wolf counsel iron howl" },
    { name: "Slade Beastmaster", meaning: "Child of the valley beast master" },
    { name: "Tore Nightwolf", meaning: "Thor battle night wolf" },
    { name: "Umber Darkpaw", meaning: "Shadow color dark paw" },
    { name: "Venn Moonhunter", meaning: "Friend moon hunter" },
    { name: "Wulf Blackhowl", meaning: "Wolf black howl" },
    { name: "Yago Stormclaw", meaning: "Supplanter storm claw" },
    { name: "Zeno Silverpaw", meaning: "Gift of Zeus silver paw" },
    { name: "Bram Darkfang", meaning: "Raven dark fang" },
    { name: "Cael Wolfshadow", meaning: "Slender wolf shadow" },
    { name: "Dunn Howlbringer", meaning: "Brown-haired howl bringer" },
    { name: "Eron Moonbeast", meaning: "Lone warrior moon beast" },
    { name: "Fenn Stormrunner", meaning: "From the marsh storm runner" },
    { name: "Garth Ironwolf", meaning: "Keeper of the garden iron wolf" },
    { name: "Harl Darkstorm", meaning: "Army ruler dark storm" },
    { name: "Ike Nightfury", meaning: "Money will come night fury" },
    { name: "Jock Wolfbane", meaning: "May God be gracious wolf bane" },
    { name: "Kane Blackclaw", meaning: "Battle dark claw" },
    { name: "Lars Stormhowl", meaning: "Son of storm howl" },
    { name: "Milo Wildpaw", meaning: "Merciful wild paw" },
    { name: "Nico Shadowpack", meaning: "Victory of shadow pack" },
    { name: "Odin Nightfury", meaning: "Fury of the night god" },
    { name: "Peter Moonfangs", meaning: "Rock with moon fangs" },
    { name: "Ron Wildstorm", meaning: "Giant wild storm" },
    { name: "Samson Darkfur", meaning: "Sun-like dark fur" },
    { name: "Troy Beastmaster", meaning: "Fierce beast master" },
    { name: "Ulf Blackhowl", meaning: "Wolf of black howl" },
    { name: "Victor Ironclaw", meaning: "Conqueror with iron claws" },
    { name: "Wolf Moonhunter", meaning: "Guardian moon hunter" },
    { name: "Yuri Darkpaw", meaning: "Farmer of dark paw" },
    { name: "Zeke Stormwolf", meaning: "God strengthens storm wolf" },
    { name: "Axel Silverfang", meaning: "Father of peace silver fang" },
    { name: "Brock Darkmane", meaning: "Badger with dark mane" },
    { name: "Cain Wolfsnap", meaning: "Spear wolf snap" },
    { name: "Drew Howlstorm", meaning: "Wise howl storm" },
    { name: "Evan Moonclaw", meaning: "Gracious moon claw" },
    { name: "Frost Nightwolf", meaning: "Frost of night wolf" },
    { name: "Gale Silverpaw", meaning: "Fast one with silver paw" },
    { name: "Hank Darkfang", meaning: "Rules with dark fang" },
    { name: "Ian Beastcaller", meaning: "God is gracious beast" },
    { name: "Jax Wolfshadow", meaning: "God has been gracious wolf shadow" }
];

const femaleNames = [
    { name: "Luna Shadowbane", meaning: "Moon goddess of shadow" },
    { name: "Raven Nightclaw", meaning: "Dark bird of night claws" },
    { name: "Freya Wolfsong", meaning: "Noble lady wolf song" },
    { name: "Astrid Silverfang", meaning: "Divine strength silver fang" },
    { name: "Sasha Darkhowl", meaning: "Defender of mankind dark howl" },
    { name: "Lyra Moonpaw", meaning: "Lyre player moon paw" },
    { name: "Vera Nightstorm", meaning: "Faithful night storm" },
    { name: "Ivy Wildfang", meaning: "Ivy plant wild fang" },
    { name: "Willa Wolfsbane", meaning: "Willow wolf poison" },
    { name: "Hazel Shadowfur", meaning: "Hazel nut shadow fur" },
    { name: "Onyx Darkclaw", meaning: "Gem of night dark claw" },
    { name: "Cora Moonhowl", meaning: "Maiden moon howl" },
    { name: "Nova Starfang", meaning: "New star fang" },
    { name: "Mira Nightpaw", meaning: "Wonderful night paw" },
    { name: "Lacy Wildclaw", meaning: "Alice-like wild claw" },
    { name: "Gwen Stormwolf", meaning: "Fair circle storm wolf" },
    { name: "Nyx Darkmoon", meaning: "Night goddess dark moon" },
    { name: "Eira Frostfang", meaning: "Snow frost fang" },
    { name: "Tess Nighthunter", meaning: "Harvester night hunter" },
    { name: "Wynne Silverpaw", meaning: "White shield silver paw" },
    { name: "Shay Darkstorm", meaning: "Hawk-like dark storm" },
    { name: "Rae Moonshade", meaning: "Radiant moon shade" },
    { name: "Faye Wolfrunner", meaning: "Fairy wolf runner" },
    { name: "Lark Shadowfur", meaning: "Bird of dawn shadow fur" },
    { name: "Sage Nightfang", meaning: "Wise one night fang" },
    { name: "Zara Blackclaw", meaning: "Princess black claw" },
    { name: "Sari Stormhowl", meaning: "Princess storm howl" },
    { name: "Reese Moonclaw", meaning: "Ardent one moon claw" },
    { name: "Briar Wildpaw", meaning: "Thorny wild paw" },
    { name: "Misty Darkmane", meaning: "Covered with mist dark mane" },
    { name: "Fern Moonfur", meaning: "Adventure seeker moon fur" },
    { name: "Dawn Silverhowl", meaning: "Daybreak silver howl" },
    { name: "Eve Nightstalker", meaning: "Living one night stalker" },
    { name: "Ava Wolfheart", meaning: "Life wolf heart" },
    { name: "Lia Darkblood", meaning: "Bringer of joy dark blood" },
    { name: "Kira Stormfang", meaning: "Ruler storm fang" },
    { name: "Zoe Nightwolf", meaning: "Life night wolf" },
    { name: "Nia Moonhunter", meaning: "Purpose moon hunter" },
    { name: "Mia Darkpaw", meaning: "Mine dark paw" },
    { name: "Elena Wolfsong", meaning: "Shining light wolf song" },
    { name: "Sera Nightfury", meaning: "Seraphine night fury" },
    { name: "Kara Darkhowl", meaning: "Beloved dark howl" },
    { name: "Nora Moonbeast", meaning: "Honor moon beast" },
    { name: "Tara Shadowclaw", meaning: "Hill star shadow claw" },
    { name: "Lina Silverfang", meaning: "Tender silver fang" },
    { name: "Maya Nightstorm", meaning: "Dreamer night storm" },
    { name: "Sia Darkpaws", meaning: "Dwarf dark paws" },
    { name: "Rhea Wolfrunner", meaning: "Flowing stream wolf runner" },
    { name: "Kyla Stormclaw", meaning: "Narrow straight storm claw" },
    { name: "Veda Nightfang", meaning: "Knowledge night fang" },
    { name: "Luna Blackwolf", meaning: "Moon black wolf" },
    { name: "Fawn Silverpaw", meaning: "Young deer silver paw" },
    { name: "Brin Darkhowl", meaning: "Hill stream dark howl" },
    { name: "Uma Moonstorm", meaning: "Sprout moon storm" },
    { name: "Ada Wildfang", meaning: "Noble nature wild fang" },
    { name: "Val Wildclaw", meaning: "Strength wild claw" },
    { name: "Sable Darkfur", meaning: "Black fur beauty" },
    { name: "Iris Nightpaw", meaning: "Rainbow night paw" },
    { name: "Rose Moonhowl", meaning: "Flower moon howl" },
    { name: "Jade Stormfang", meaning: "Stone of healing storm fang" },
    { name: "Ruby Darkclaw", meaning: "Red gemstone dark claw" },
    { name: "Opal Shadowpaw", meaning: "Jewel of shadows shadow paw" },
    { name: "Pearl Silverhowl", meaning: "Precious pearl silver howl" },
    { name: "Vera Nighthunter", meaning: "True night hunter" },
    { name: "Celeste Moonwolf", meaning: "Heavenly moon wolf" },
    { name: "Astra Darkstar", meaning: "Stars dark star" },
    { name: "Luna Eclipse", meaning: "Moon eclipse" },
    { name: "Skye Stormrunner", meaning: "High ground storm runner" },
    { name: "Reign Blackmane", meaning: "Rule black mane" },
    { name: "Vixen Darkfur", meaning: "Clever woman dark fur" },
    { name: "Wolf Red", meaning: "Wolf color red" },
    { name: "Rowan Silverclaw", meaning: "Little red one silver claw" },
    { name: "Willow Graymoon", meaning: "Willow tree gray moon" },
    { name: "Aspen Nightfang", meaning: "Tree of asp night fang" },
    { name: "Cedar Darkpaw", meaning: "Tree cedar dark paw" },
    { name: "Sierra Wolfsong", meaning: "Mountain range wolf song" },
    { name: "Winter Stormhowl", meaning: "Cold season storm howl" },
    { name: "Autumn Darkfur", meaning: "Season of falling dark fur" },
    { name: "Spring Moonshade", meaning: "Season of growth moon shade" },
    { name: "Summer Wildfang", meaning: "Warmest season wild fang" },
    { name: "Ash Moonshadow", meaning: "Ash tree moon shadow" },
    { name: "Ember Nightfire", meaning: "Sparks night fire" },
    { name: "Flame Darkclaw", meaning: "Fire dark claw" },
    { name: "Blaze Stormpaw", meaning: "Fire storm paw" },
    { name: "Spark Nighthowl", meaning: "Electrical night howl" },
    { name: "Glow Silvermoon", meaning: "Brightness silver moon" },
    { name: "Shine Darkfur", meaning: "Brightness dark fur" },
    { name: "Gleam Moonbeast", meaning: "Brightness moon beast" },
    { name: "Glint Nightstalker", meaning: "Glitter night stalker" },
    { name: "Shimmer Wildfang", meaning: "Glittering wild fang" },
    { name: "Dusk Moonclaw", meaning: "Twilight moon claw" },
    { name: "Dawn Silverfang", meaning: "Daybreak silver fang" },
    { name: "Twilight Darkwolf", meaning: "Half-light dark wolf" },
    { name: "Midnight Nightstorm", meaning: "Middle of night night storm" },
    { name: "Noon Sunwolf", meaning: "Midday sun wolf" },
    { name: "Eve Eveningstar", meaning: "Evening evening star" },
    { name: "Luna Blackmoon", meaning: "Moon black moon" },
    { name: "Raven Moonshade", meaning: "Dark bird moon shade" },
    { name: "Hawk Stormwing", meaning: "Bird of prey storm wing" },
    { name: "Eagle Nighteye", meaning: "Bird eagle night eye" },
    { name: "Falcon Darktalon", meaning: "Bird falcon dark talon" },
    { name: "Kestrel Moonwing", meaning: "Small hawk moon wing" },
    { name: "Osprey Wolfclaw", meaning: "Sea hawk wolf claw" },
    { name: "Kite Silverfeather", meaning: "Bird kite silver feather" },
    { name: "Vole Darkburrow", meaning: "Small rodent dark burrow" },
    { name: "Hare Moonrunner", meaning: "Rabbit moon runner" },
    { name: "Fox Shadowpaw", meaning: "Wild dog shadow paw" },
    { name: "Lynx Nightstalker", meaning: "Wild cat night stalker" },
    { name: "Panther Darkfur", meaning: "Large wild cat dark fur" },
    { name: "Jaguar Stormfang", meaning: "Spotted cat storm fang" },
    { name: "Cougar Moonpaw", meaning: "Mountain lion moon paw" },
    { name: "Bobcat Wildclaw", meaning: "Wild cat wild claw" },
    { name: "Coyote Desertwolf", meaning: "Prairie wolf desert wolf" },
    { name: "Hyena Laughinghowl", meaning: "Laughing hyena howl" },
    { name: "Wolfgang Furheart", meaning: "Wolf path fierce heart" },
    { name: "Yuri Wolfsong", meaning: "Farmer wolf song" },
    { name: "Zara Beastfang", meaning: "Eastern wolf beast fang" },
    { name: "Arlo Nightfury", meaning: "Fortress of night fury" },
    { name: "Boris Stormwolf", meaning: "Battle fury storm wolf" },
    { name: "Cyrus Darkclaw", meaning: "Sun dark claw" },
    { name: "Drake Moonfang", meaning: "Dragon moon fang" },
    { name: "Emil Ironpaw", meaning: "Rival iron paw" },
    { name: "Flynn Shadowhowl", meaning: "Son of the bright one shadow howl" },
    { name: "Glen Darkfur", meaning: "Valley of dark fur" },
    { name: "Haze Moonshade", meaning: "Obscured moon shade" },
    { name: "Ivar Blackfang", meaning: "Yew warrior black fang" },
    { name: "Jared Wolfbane", meaning: "Cry of despair wolf bane" },
    { name: "Kade Wildstorm", meaning: "Barbed wild storm" },
    { name: "Lars Silverclaw", meaning: "Crowned with laurel silver claw" },
    { name: "Mace Nightstalker", meaning: "Club weapon night stalker" },
    { name: "Nalo Darkmane", meaning: "Winner dark mane" },
    { name: "Orlo Wolfsong", meaning: "Golden wolf song" },
    { name: "Pike Stormfang", meaning: "Pointed weapon storm fang" },
    { name: "Rafe Ironhowl", meaning: "Wolf counsel iron howl" },
    { name: "Slade Beastmaster", meaning: "Child of the valley beast master" },
    { name: "Tore Nightwolf", meaning: "Thor battle night wolf" },
    { name: "Umber Darkpaw", meaning: "Shadow color dark paw" },
    { name: "Venn Moonhunter", meaning: "Friend moon hunter" },
    { name: "Wulf Blackhowl", meaning: "Wolf black howl" },
    { name: "Yago Stormclaw", meaning: "Supplanter storm claw" },
    { name: "Zeno Silverpaw", meaning: "Gift of Zeus silver paw" },
    { name: "Bram Darkfang", meaning: "Raven dark fang" },
    { name: "Cael Wolfshadow", meaning: "Slender wolf shadow" },
    { name: "Dunn Howlbringer", meaning: "Brown-haired howl bringer" },
    { name: "Eron Moonbeast", meaning: "Lone warrior moon beast" },
    { name: "Fenn Stormrunner", meaning: "From the marsh storm runner" },
    { name: "Garth Ironwolf", meaning: "Keeper of the garden iron wolf" },
    { name: "Harl Darkstorm", meaning: "Army ruler dark storm" },
    { name: "Ike Nightfury", meaning: "Money will come night fury" },
    { name: "Jock Wolfbane", meaning: "May God be gracious wolf bane" },
    { name: "Kane Blackclaw", meaning: "Battle dark claw" },
    { name: "Lars Stormhowl", meaning: "Son of storm howl" },
    { name: "Milo Wildpaw", meaning: "Merciful wild paw" },
    { name: "Nico Shadowpack", meaning: "Victory of shadow pack" },
    { name: "Odin Nightfury", meaning: "Fury of the night god" },
    { name: "Peter Moonfangs", meaning: "Rock with moon fangs" },
    { name: "Ron Wildstorm", meaning: "Giant wild storm" },
    { name: "Samson Darkfur", meaning: "Sun-like dark fur" },
    { name: "Troy Beastmaster", meaning: "Fierce beast master" },
    { name: "Ulf Blackhowl", meaning: "Wolf of black howl" },
    { name: "Victor Ironclaw", meaning: "Conqueror with iron claws" },
    { name: "Wolf Moonhunter", meaning: "Guardian moon hunter" }
];

let currentMode = 'random';

function shuffleArray(array) {
    for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]];
    }
    return array;
}

document.querySelectorAll('.mode-btn').forEach(btn => {
    btn.addEventListener('click', function() {
        document.querySelectorAll('.mode-btn').forEach(b => b.classList.remove('active'));
        this.classList.add('active');
        currentMode = this.dataset.mode;
    });
});

function generateNames() {
    const grid = document.getElementById('namesGrid');
    grid.innerHTML = '';
    
    let names = [];
    
    if (currentMode === 'male') {
        names = shuffleArray([...maleNames]).slice(0, 16).map(n => ({...n, gender: 'Male'}));
    } else if (currentMode === 'female') {
        names = shuffleArray([...femaleNames]).slice(0, 16).map(n => ({...n, gender: 'Female'}));
    } else {
        const allNames = [...maleNames.map(n => ({...n, gender: 'Male'})), ...femaleNames.map(n => ({...n, gender: 'Female'}))];
        names = shuffleArray(allNames).slice(0, 16);
    }
    
    names.forEach(nameData => {
        const card = document.createElement('div');
        card.className = 'name-card';
        card.innerHTML = `
            <div class="name-text">${nameData.name}</div>
            <div class="name-gender">${nameData.gender} Werewolf</div>
            <div class="name-meaning">${nameData.meaning}</div>
        `;
        grid.appendChild(card);
    });
}

