const maleNames = [
    { name: "Darth Malachor", meaning: "Dark destroyer" },
    { name: "Darth Vexis", meaning: "Shadow of vengeance" },
    { name: "Darth Kaelus", meaning: "Lord of pain" },
    { name: "Darth Nihilus", meaning: "Emptiness incarnate" },
    { name: "Darth Bane", meaning: "Bringer of ruin" },
    { name: "Darth Plagueis", meaning: "Master of corruption" },
    { name: "Darth Sidious", meaning: "Hidden master" },
    { name: "Darth Vader", meaning: "Dark father" },
    { name: "Darth Maul", meaning: "Savage warrior" },
    { name: "Darth Tyranus", meaning: "Tyrant lord" },
    { name: "Darth Revan", meaning: "Redeemed conqueror" },
    { name: "Darth Malak", meaning: "Fallen champion" },
    { name: "Darth Sion", meaning: "Immortal pain" },
    { name: "Darth Traya", meaning: "Betrayal incarnate" },
    { name: "Darth Nyriss", meaning: "Eternal shadow" },
    { name: "Darth Scabrous", meaning: "Ancient horror" },
    { name: "Darth Ruin", meaning: "Bringer of destruction" },
    { name: "Darth Cognus", meaning: "Dark knowledge" },
    { name: "Darth Desolous", meaning: "Agent of despair" },
    { name: "Darth Andeddu", meaning: "Immortal king" },
    { name: "Darth Tenebrous", meaning: "Master of shadows" },
    { name: "Darth Wyyrlok", meaning: "Keeper of secrets" },
    { name: "Darth Krayt", meaning: "Dragon of darkness" },
    { name: "Darth Talon", meaning: "Sharp predator" },
    { name: "Darth Rictus", meaning: "Grinning terror" },
    { name: "Darth Havok", meaning: "Chaos unleashed" },
    { name: "Darth Vowrawn", meaning: "Eternal oath" },
    { name: "Darth Baras", meaning: "Power incarnate" },
    { name: "Darth Angral", meaning: "Wrathful lord" },
    { name: "Darth Marr", meaning: "Dark judgment" },
    { name: "Darth Nox", meaning: "Night incarnate" },
    { name: "Darth Acina", meaning: "Storm bringer" },
    { name: "Darth Ravage", meaning: "Ruthless conqueror" },
    { name: "Darth Soverus", meaning: "Ancient wisdom" },
    { name: "Darth Jadus", meaning: "Master of fear" },
    { name: "Darth Chratis", meaning: "Dark scholar" },
    { name: "Darth Zash", meaning: "Ambitious sorceress" },
    { name: "Darth Arkos", meaning: "Shadow flame" },
    { name: "Darth Malgus", meaning: "Unyielding warrior" },
    { name: "Darth Acharon", meaning: "River of death" },
    { name: "Darth Azariah", meaning: "Dark prophet" },
    { name: "Darth Bandon", meaning: "Fallen apprentice" },
    { name: "Darth Caelestis", meaning: "Dark heavens" },
    { name: "Darth Decimus", meaning: "Tenth terror" },
    { name: "Darth Erebus", meaning: "Primordial darkness" },
    { name: "Darth Fulminaris", meaning: "Lightning lord" },
    { name: "Darth Gravid", meaning: "Mad visionary" },
    { name: "Darth Haze", meaning: "Obscuring shadow" },
    { name: "Darth Ignis", meaning: "Dark fire" },
    { name: "Darth Jover", meaning: "Dark schemer" },
    { name: "Darth Kallus", meaning: "Fierce destroyer" },
    { name: "Darth Lachesis", meaning: "Fate weaver" },
    { name: "Darth Mortis", meaning: "Death incarnate" },
    { name: "Darth Nostrem", meaning: "Ancient power" },
    { name: "Darth Obsidian", meaning: "Dark glass" },
    { name: "Darth Phobos", meaning: "Fear master" },
    { name: "Darth Quintus", meaning: "Fifth darkness" },
    { name: "Darth Rancor", meaning: "Bitter hatred" },
    { name: "Darth Solus", meaning: "Lone predator" },
    { name: "Darth Tormund", meaning: "Dark thunder" },
    { name: "Darth Umbra", meaning: "Shadow walker" },
    { name: "Darth Vexar", meaning: "Dark venom" },
    { name: "Darth Xarion", meaning: "Cosmic terror" },
    { name: "Darth Yularen", meaning: "Ancient sage" },
    { name: "Darth Zorath", meaning: "Dark flame" },
    { name: "Darth Arctis", meaning: "Frozen darkness" },
    { name: "Darth Belis", meaning: "War bringer" },
    { name: "Darth Caelum", meaning: "Dark sky" },
    { name: "Darth Draven", meaning: "Shadow hunter" },
    { name: "Darth Exar", meaning: "Dark star" },
    { name: "Darth Ferox", meaning: "Fierce warrior" },
    { name: "Darth Gethin", meaning: "Dark blade" },
    { name: "Darth Hadeon", meaning: "Underworld lord" },
    { name: "Darth Icarus", meaning: "Fallen ambition" },
    { name: "Darth Jareth", meaning: "Dark ruler" },
    { name: "Darth Krosis", meaning: "Sorrow incarnate" },
    { name: "Darth Lethos", meaning: "Dark oblivion" },
    { name: "Darth Mordis", meaning: "Death whisper" },
    { name: "Darth Naxus", meaning: "Dark nexus" },
    { name: "Darth Orpheus", meaning: "Dark melody" },
    { name: "Darth Pyros", meaning: "Flame of hatred" },
    { name: "Darth Quorath", meaning: "Ancient evil" },
    { name: "Darth Raze", meaning: "Total destruction" },
    { name: "Darth Stryfe", meaning: "Eternal conflict" },
    { name: "Darth Thanatos", meaning: "Death personified" },
    { name: "Darth Ulric", meaning: "Dark wolf" },
    { name: "Darth Valtor", meaning: "Shadow lord" },
    { name: "Darth Wraith", meaning: "Spectral terror" },
    { name: "Darth Xul", meaning: "Dark void" },
    { name: "Darth Yorn", meaning: "Ancient fury" },
    { name: "Darth Zephyr", meaning: "Dark wind" },
    { name: "Darth Abyss", meaning: "Bottomless darkness" },
    { name: "Darth Brimstone", meaning: "Fire and brimstone" },
    { name: "Darth Carnage", meaning: "Mass destruction" },
    { name: "Darth Dread", meaning: "Fear incarnate" },
    { name: "Darth Eclipse", meaning: "Darkened light" },
    { name: "Darth Fang", meaning: "Sharp predator" },
    { name: "Darth Gloom", meaning: "Eternal darkness" },
    { name: "Darth Hex", meaning: "Dark curse" },
    { name: "Darth Inferno", meaning: "Raging fire" },
    { name: "Darth Jinx", meaning: "Dark omen" },
    { name: "Darth Krane", meaning: "Dark raven" },
    { name: "Darth Lurk", meaning: "Hidden menace" },
    { name: "Darth Maelstrom", meaning: "Chaotic storm" },
    { name: "Darth Nexus", meaning: "Dark convergence" },
    { name: "Darth Onyx", meaning: "Black stone" },
    { name: "Darth Phantom", meaning: "Ghostly terror" },
    { name: "Darth Quake", meaning: "Earth shaker" },
    { name: "Darth Reaper", meaning: "Death bringer" },
    { name: "Darth Scourge", meaning: "Divine punishment" },
    { name: "Darth Tempest", meaning: "Violent storm" },
    { name: "Darth Vortex", meaning: "Spinning darkness" },
    { name: "Darth Wrath", meaning: "Unbridled fury" },
    { name: "Darth Xander", meaning: "Dark defender" },
    { name: "Darth Ymir", meaning: "Primordial giant" },
    { name: "Darth Zenith", meaning: "Dark peak" },
    { name: "Darth Acheron", meaning: "River of woe" },
    { name: "Darth Balthazar", meaning: "Dark king" },
    { name: "Darth Cimmerian", meaning: "Eternal night" },
    { name: "Darth Damocles", meaning: "Impending doom" },
    { name: "Darth Enigma", meaning: "Dark mystery" },
    { name: "Darth Fenrir", meaning: "Dark wolf" },
    { name: "Darth Gorgon", meaning: "Petrifying gaze" },
    { name: "Darth Hades", meaning: "Lord of underworld" },
    { name: "Darth Ixion", meaning: "Eternal torment" },
    { name: "Darth Juggernaut", meaning: "Unstoppable force" },
    { name: "Darth Kronos", meaning: "Time destroyer" },
    { name: "Darth Leviathan", meaning: "Sea monster" },
    { name: "Darth Morpheus", meaning: "Dream lord" },
    { name: "Darth Nemesis", meaning: "Inevitable vengeance" },
    { name: "Darth Oblivion", meaning: "Total nothingness" },
    { name: "Darth Pandora", meaning: "Opened evil" },
    { name: "Darth Ragnarok", meaning: "End of worlds" },
    { name: "Darth Serpentis", meaning: "Dark serpent" },
    { name: "Darth Tartarus", meaning: "Deepest abyss" },
    { name: "Darth Umbriel", meaning: "Shadow angel" },
    { name: "Darth Valkor", meaning: "Dark valkyrie" },
    { name: "Darth Wyrm", meaning: "Ancient dragon" },
    { name: "Darth Xerxes", meaning: "Dark emperor" },
    { name: "Darth Zagan", meaning: "Demon king" },
    { name: "Darth Amon", meaning: "Hidden darkness" },
    { name: "Darth Belial", meaning: "Worthless one" },
    { name: "Darth Chaos", meaning: "Primordial disorder" },
    { name: "Darth Dagon", meaning: "Sea demon" },
    { name: "Darth Erebos", meaning: "Deep darkness" },
    { name: "Darth Gorgoth", meaning: "Ancient terror" },
    { name: "Darth Hazor", meaning: "Dark fortress" },
    { name: "Darth Iblis", meaning: "The tempter" },
    { name: "Darth Jormungandr", meaning: "World serpent" },
    { name: "Darth Kael", meaning: "Dark warrior" },
    { name: "Darth Legion", meaning: "Many as one" },
    { name: "Darth Moloch", meaning: "Dark sacrifice" },
    { name: "Darth Nyx", meaning: "Night goddess" },
    { name: "Darth Osiris", meaning: "Dark judge" },
    { name: "Darth Paimon", meaning: "Dark herald" },
    { name: "Darth Qliphoth", meaning: "Dark shell" },
    { name: "Darth Raziel", meaning: "Dark secret" },
    { name: "Darth Samael", meaning: "Venom of god" },
    { name: "Darth Tiamat", meaning: "Chaos dragon" },
    { name: "Darth Uriel", meaning: "Dark flame" },
    { name: "Darth Vesper", meaning: "Evening star" },
    { name: "Darth Xulthar", meaning: "Dark summoner" },
    { name: "Darth Yggdrasil", meaning: "World tree" },
    { name: "Darth Zariel", meaning: "Fallen angel" },
    { name: "Darth Azazel", meaning: "Scapegoat" },
    { name: "Darth Baal", meaning: "Dark lord" },
    { name: "Darth Cthulhu", meaning: "Sleeping horror" },
    { name: "Darth Diablo", meaning: "Dark devil" },
    { name: "Darth Eligor", meaning: "Dark knight" },
    { name: "Darth Fenris", meaning: "Dark wolf" },
    { name: "Darth Geryon", meaning: "Three-bodied giant" },
    { name: "Darth Hecate", meaning: "Dark magic" },
    { name: "Darth Iscariot", meaning: "The betrayer" },
    { name: "Darth Jabberwock", meaning: "Dark beast" },
    { name: "Darth Keres", meaning: "Death spirit" },
    { name: "Darth Lilith", meaning: "Night monster" },
    { name: "Darth Mephisto", meaning: "Dark deceiver" },
    { name: "Darth Nergal", meaning: "Lord of plague" },
    { name: "Darth Orobas", meaning: "Dark prince" },
    { name: "Darth Purgatory", meaning: "Eternal suffering" },
    { name: "Darth Ravana", meaning: "Ten-headed king" },
    { name: "Darth Sargeras", meaning: "Dark titan" },
    { name: "Darth Thoth", meaning: "Dark wisdom" },
    { name: "Darth Uroboros", meaning: "Eternal cycle" },
    { name: "Darth Vritra", meaning: "Dark serpent" },
    { name: "Darth Xibalba", meaning: "Place of fear" },
    { name: "Darth Yogsothoth", meaning: "Gate keeper" },
    { name: "Darth Zaganar", meaning: "Dark fire" },
    { name: "Darth Abaddon", meaning: "Angel of abyss" },
    { name: "Darth Baphomet", meaning: "Dark idol" },
    { name: "Darth Choronzon", meaning: "Dark disperser" },
    { name: "Darth Dagonis", meaning: "Dark sea" },
    { name: "Darth Eblis", meaning: "Dark tempter" },
    { name: "Darth Forneus", meaning: "Dark sea monster" },
    { name: "Darth Gremory", meaning: "Dark duchess" },
    { name: "Darth Huitzil", meaning: "Dark hummingbird" },
    { name: "Darth Ipos", meaning: "Dark count" },
    { name: "Darth Jinn", meaning: "Dark spirit" },
    { name: "Darth Kuthumi", meaning: "Dark master" },
    { name: "Darth Lamia", meaning: "Dark seductress" },
    { name: "Darth Mammon", meaning: "Dark greed" },
    { name: "Darth Naberius", meaning: "Dark marquis" },
    { name: "Darth Orobax", meaning: "Dark truth" },
    { name: "Darth Phenex", meaning: "Dark phoenix" },
    { name: "Darth Qalupalik", meaning: "Dark sea spirit" },
    { name: "Darth Raum", meaning: "Dark earl" },
    { name: "Darth Shax", meaning: "Dark voice" },
    { name: "Darth Tenebris", meaning: "Darkness itself" },
    { name: "Darth Uvall", meaning: "Dark duke" },
    { name: "Darth Vepar", meaning: "Dark sea guide" },
    { name: "Darth Xaphan", meaning: "Dark fire starter" },
    { name: "Darth Yagael", meaning: "Dark avenger" },
    { name: "Darth Zepar", meaning: "Dark warrior" }
];

const femaleNames = [
    { name: "Darth Talia", meaning: "Dark blossom" },
    { name: "Darth Nyssa", meaning: "Shadow queen" },
    { name: "Darth Vespera", meaning: "Evening darkness" },
    { name: "Darth Selene", meaning: "Dark moon" },
    { name: "Darth Morgana", meaning: "Dark sorceress" },
    { name: "Darth Lilith", meaning: "Night demon" },
    { name: "Darth Ravenna", meaning: "Dark raven" },
    { name: "Darth Seraphina", meaning: "Fallen angel" },
    { name: "Darth Calypso", meaning: "Dark enchantress" },
    { name: "Darth Isolde", meaning: "Dark ice" },
    { name: "Darth Morgath", meaning: "Dark crown" },
    { name: "Darth Thalia", meaning: "Dark bloom" },
    { name: "Darth Vexia", meaning: "Dark venom" },
    { name: "Darth Zephyra", meaning: "Dark wind" },
    { name: "Darth Azura", meaning: "Dark sky" },
    { name: "Darth Bellatrix", meaning: "Female warrior" },
    { name: "Darth Circe", meaning: "Dark enchantress" },
    { name: "Darth Drusilla", meaning: "Dark strength" },
    { name: "Darth Elara", meaning: "Dark star" },
    { name: "Darth Freya", meaning: "Dark goddess" },
    { name: "Darth Galatea", meaning: "Dark beauty" },
    { name: "Darth Hecuba", meaning: "Dark queen" },
    { name: "Darth Ione", meaning: "Dark violet" },
    { name: "Darth Jynx", meaning: "Dark curse" },
    { name: "Darth Kaelia", meaning: "Dark warrior" },
    { name: "Darth Lysandra", meaning: "Dark liberator" },
    { name: "Darth Medusa", meaning: "Dark gaze" },
    { name: "Darth Nocturna", meaning: "Dark night" },
    { name: "Darth Ophelia", meaning: "Dark sorrow" },
    { name: "Darth Persephone", meaning: "Dark underworld" },
    { name: "Darth Quorra", meaning: "Dark flame" },
    { name: "Darth Rhiannon", meaning: "Dark horse" },
    { name: "Darth Sable", meaning: "Dark black" },
    { name: "Darth Tenebrae", meaning: "Dark shadows" },
    { name: "Darth Umbra", meaning: "Dark shade" },
    { name: "Darth Vesper", meaning: "Dark evening" },
    { name: "Darth Xandra", meaning: "Dark defender" },
    { name: "Darth Yara", meaning: "Dark water" },
    { name: "Darth Zara", meaning: "Dark princess" },
    { name: "Darth Alecto", meaning: "Dark fury" },
    { name: "Darth Belladonna", meaning: "Dark beauty" },
    { name: "Darth Cassandra", meaning: "Dark prophecy" },
    { name: "Darth Desdemona", meaning: "Dark fate" },
    { name: "Darth Electra", meaning: "Dark amber" },
    { name: "Darth Furies", meaning: "Dark vengeance" },
    { name: "Darth Grimhilde", meaning: "Dark battle" },
    { name: "Darth Helle", meaning: "Dark fire" },
    { name: "Darth Iris", meaning: "Dark rainbow" },
    { name: "Darth Juno", meaning: "Dark queen" },
    { name: "Darth Kali", meaning: "Dark goddess" },
    { name: "Darth Lamia", meaning: "Dark seductress" },
    { name: "Darth Morrigan", meaning: "Dark phantom" },
    { name: "Darth Nemesis", meaning: "Dark vengeance" },
    { name: "Darth Olympe", meaning: "Dark mountain" },
    { name: "Darth Pandora", meaning: "Dark mystery" },
    { name: "Darth Ravana", meaning: "Dark king" },
    { name: "Darth Stheno", meaning: "Dark power" },
    { name: "Darth Theia", meaning: "Dark divine" },
    { name: "Darth Ursula", meaning: "Dark sea" },
    { name: "Darth Vexia", meaning: "Dark poison" },
    { name: "Darth Xena", meaning: "Dark warrior" },
    { name: "Darth Yara", meaning: "Dark butterfly" },
    { name: "Darth Zephyrine", meaning: "Dark west wind" },
    { name: "Darth Abigail", meaning: "Dark joy" },
    { name: "Darth Beatrice", meaning: "Dark blessed" },
    { name: "Darth Carmilla", meaning: "Dark vampire" },
    { name: "Darth Delilah", meaning: "Dark temptress" },
    { name: "Darth Elvira", meaning: "Dark truth" },
    { name: "Darth Faustina", meaning: "Dark fortune" },
    { name: "Darth Gorgona", meaning: "Dark gorgon" },
    { name: "Darth Hestia", meaning: "Dark hearth" },
    { name: "Darth Invidia", meaning: "Dark envy" },
    { name: "Darth Javert", meaning: "Dark justice" },
    { name: "Darth Kassandra", meaning: "Dark prophetess" },
    { name: "Darth Lorelei", meaning: "Dark siren" },
    { name: "Darth Maleficent", meaning: "Dark evil" },
    { name: "Darth Narcissa", meaning: "Dark vanity" },
    { name: "Darth Octavia", meaning: "Dark eighth" },
    { name: "Darth Phaedra", meaning: "Dark bright" },
    { name: "Darth Ragnhild", meaning: "Dark battle" },
    { name: "Darth Salome", meaning: "Dark peace" },
    { name: "Darth Tisiphone", meaning: "Dark avenger" },
    { name: "Darth Undine", meaning: "Dark wave" },
    { name: "Darth Volumnia", meaning: "Dark strength" },
    { name: "Darth Xiomara", meaning: "Dark battle" },
    { name: "Darth Yelena", meaning: "Dark light" },
    { name: "Darth Zoraida", meaning: "Dark enchantress" },
    { name: "Darth Aella", meaning: "Dark whirlwind" },
    { name: "Darth Brunnhilde", meaning: "Dark armor" },
    { name: "Darth Clytemnestra", meaning: "Dark fame" },
    { name: "Darth Druella", meaning: "Dark strength" },
    { name: "Darth Erinyes", meaning: "Dark fury" },
    { name: "Darth Fiammetta", meaning: "Dark flame" },
    { name: "Darth Griselda", meaning: "Dark battle" },
    { name: "Darth Hypatia", meaning: "Dark wisdom" },
    { name: "Darth Iphigenia", meaning: "Dark born" },
    { name: "Darth Jezebel", meaning: "Dark exalted" },
    { name: "Darth Kriemhild", meaning: "Dark mask" },
    { name: "Darth Lysippe", meaning: "Dark dissolver" },
    { name: "Darth Medb", meaning: "Dark queen" },
    { name: "Darth Nefertiti", meaning: "Dark beauty" },
    { name: "Darth Olympia", meaning: "Dark mountain" },
    { name: "Darth Penthesilea", meaning: "Dark sorrow" },
    { name: "Darth Roxelana", meaning: "Dark dawn" },
    { name: "Darth Semiramis", meaning: "Dark dove" },
    { name: "Darth Theodora", meaning: "Dark gift" },
    { name: "Darth Ursa", meaning: "Dark bear" },
    { name: "Darth Vespera", meaning: "Dark evening" },
    { name: "Darth Xanthe", meaning: "Dark golden" },
    { name: "Darth Ygraine", meaning: "Dark mother" },
    { name: "Darth Zenobia", meaning: "Dark life" },
    { name: "Darth Acantha", meaning: "Dark thorn" },
    { name: "Darth Brynhild", meaning: "Dark battle" },
    { name: "Darth Cirilla", meaning: "Dark circle" },
    { name: "Darth Dracena", meaning: "Dark dragon" },
    { name: "Darth Eurydice", meaning: "Dark justice" },
    { name: "Darth Freyja", meaning: "Dark lady" },
    { name: "Darth Gwendolyn", meaning: "Dark ring" },
    { name: "Darth Helga", meaning: "Dark holy" },
    { name: "Darth Isolde", meaning: "Dark ice" },
    { name: "Darth Jocasta", meaning: "Dark joy" },
    { name: "Darth Katerina", meaning: "Dark pure" },
    { name: "Darth Leandra", meaning: "Dark lion" },
    { name: "Darth Morgause", meaning: "Dark sea" },
    { name: "Darth Nymeria", meaning: "Dark warrior" },
    { name: "Darth Olympe", meaning: "Dark heaven" },
    { name: "Darth Philomela", meaning: "Dark song" },
    { name: "Darth Rhiannon", meaning: "Dark queen" },
    { name: "Darth Sigrid", meaning: "Dark victory" },
    { name: "Darth Thessaly", meaning: "Dark land" },
    { name: "Darth Ulfhild", meaning: "Dark wolf" },
    { name: "Darth Valeska", meaning: "Dark glory" },
    { name: "Darth Xanthippe", meaning: "Dark horse" },
    { name: "Darth Yvaine", meaning: "Dark star" },
    { name: "Darth Zephyrine", meaning: "Dark wind" },
    { name: "Darth Astarte", meaning: "Dark goddess" },
    { name: "Darth Bathory", meaning: "Dark countess" },
    { name: "Darth Circe", meaning: "Dark witch" },
    { name: "Darth Damaris", meaning: "Dark gentle" },
    { name: "Darth Ereshkigal", meaning: "Dark underworld" },
    { name: "Darth Furies", meaning: "Dark vengeance" },
    { name: "Darth Gorgo", meaning: "Dark terror" },
    { name: "Darth Hecate", meaning: "Dark magic" },
    { name: "Darth Inanna", meaning: "Dark queen" },
    { name: "Darth Jezebeth", meaning: "Dark demon" },
    { name: "Darth Keres", meaning: "Dark death" },
    { name: "Darth Lilim", meaning: "Dark night" },
    { name: "Darth Morrigan", meaning: "Dark phantom" },
    { name: "Darth Norn", meaning: "Dark fate" },
    { name: "Darth Oread", meaning: "Dark mountain" },
    { name: "Darth Persephone", meaning: "Dark queen" },
    { name: "Darth Queen Mab", meaning: "Dark fairy" },
    { name: "Darth Ravena", meaning: "Dark raven" },
    { name: "Darth Siren", meaning: "Dark song" },
    { name: "Darth Tiamat", meaning: "Dark chaos" },
    { name: "Darth Undine", meaning: "Dark water" },
    { name: "Darth Valkyrie", meaning: "Dark chooser" },
    { name: "Darth Witch", meaning: "Dark magic" },
    { name: "Darth Xibalba", meaning: "Dark underworld" },
    { name: "Darth Yara-ma", meaning: "Dark vampire" },
    { name: "Darth Zorya", meaning: "Dark star" },
    { name: "Darth Abyssia", meaning: "Dark depth" },
    { name: "Darth Banshee", meaning: "Dark wail" },
    { name: "Darth Charybdis", meaning: "Dark whirlpool" },
    { name: "Darth Darkh", meaning: "Dark gift" },
    { name: "Darth Echidna", meaning: "Dark mother" },
    { name: "Darth Famine", meaning: "Dark hunger" },
    { name: "Darth Gloom", meaning: "Dark shadow" },
    { name: "Darth Harpy", meaning: "Dark snatcher" },
    { name: "Darth Inferna", meaning: "Dark fire" },
    { name: "Darth Jinx", meaning: "Dark curse" },
    { name: "Darth Kraken", meaning: "Dark sea" },
    { name: "Darth Lich", meaning: "Dark undead" },
    { name: "Darth Malice", meaning: "Dark hatred" },
    { name: "Darth Nightmare", meaning: "Dark dream" },
    { name: "Darth Obsidia", meaning: "Dark stone" },
    { name: "Darth Phantom", meaning: "Dark ghost" },
    { name: "Darth Quake", meaning: "Dark tremor" },
    { name: "Darth Reaper", meaning: "Dark death" },
    { name: "Darth Scourge", meaning: "Dark plague" },
    { name: "Darth Tempest", meaning: "Dark storm" },
    { name: "Darth Vortex", meaning: "Dark spiral" },
    { name: "Darth Wraith", meaning: "Dark spirit" },
    { name: "Darth Xena", meaning: "Dark warrior" },
    { name: "Darth Ymir", meaning: "Dark giant" },
    { name: "Darth Zenith", meaning: "Dark peak" },
    { name: "Darth Abyss", meaning: "Dark void" },
    { name: "Darth Brimstone", meaning: "Dark fire" },
    { name: "Darth Carnage", meaning: "Dark slaughter" },
    { name: "Darth Dread", meaning: "Dark fear" },
    { name: "Darth Eclipse", meaning: "Dark shadow" },
    { name: "Darth Fang", meaning: "Dark bite" },
    { name: "Darth Gloom", meaning: "Dark night" },
    { name: "Darth Hex", meaning: "Dark spell" },
    { name: "Darth Inferno", meaning: "Dark flame" },
    { name: "Darth Jinx", meaning: "Dark hex" },
    { name: "Darth Krane", meaning: "Dark crow" },
    { name: "Darth Lurk", meaning: "Dark hide" },
    { name: "Darth Maelstrom", meaning: "Dark chaos" },
    { name: "Darth Nexus", meaning: "Dark center" },
    { name: "Darth Onyx", meaning: "Dark gem" },
    { name: "Darth Phantom", meaning: "Dark shade" },
    { name: "Darth Quake", meaning: "Dark shake" },
    { name: "Darth Reaper", meaning: "Dark harvest" },
    { name: "Darth Scourge", meaning: "Dark whip" },
    { name: "Darth Tempest", meaning: "Dark rage" },
    { name: "Darth Vortex", meaning: "Dark spin" },
    { name: "Darth Wrath", meaning: "Dark fury" },
    { name: "Darth Xander", meaning: "Dark shield" },
    { name: "Darth Ymir", meaning: "Dark frost" },
    { name: "Darth Zenith", meaning: "Dark height" }
];

let currentMode = 'random';

document.querySelectorAll('.mode-btn').forEach(btn => {
    btn.addEventListener('click', function() {
        document.querySelectorAll('.mode-btn').forEach(b => b.classList.remove('active'));
        this.classList.add('active');
        currentMode = this.dataset.mode;
    });
});

function shuffleArray(arr) {
    for (let i = arr.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [arr[i], arr[j]] = [arr[j], arr[i]];
    }
    return arr;
}

function generateNames() {
    const grid = document.getElementById('namesGrid');
    grid.innerHTML = '';
    
    let names = [];
    
    if (currentMode === 'male') {
        names = shuffleArray([...maleNames]).slice(0, 16).map(n => ({...n, gender: 'Male'}));
    } else if (currentMode === 'female') {
        names = shuffleArray([...femaleNames]).slice(0, 16).map(n => ({...n, gender: 'Female'}));
    } else {
        const allNames = [
            ...maleNames.map(n => ({...n, gender: 'Male'})),
            ...femaleNames.map(n => ({...n, gender: 'Female'}))
        ];
        names = shuffleArray(allNames).slice(0, 16);
    }
    
    names.forEach((item, index) => {
        const card = document.createElement('div');
        card.className = 'name-card';
        card.innerHTML = `
            <div class="name-text">${item.name}</div>
            <div class="name-gender">${item.gender}</div>
            <div class="name-meaning">${item.meaning}</div>
        `;
        grid.appendChild(card);
    });
}

