const maleNames = [
    { name: "Ulfric Stormcloak", meaning: "Wolf-Ruler Storm-Cloak" },
    { name: "Balgruuf the Greater", meaning: "Bold-Gruff the Great" },
    { name: "Jarl Balgruuf", meaning: "Earl Bold-Gruff" },
    { name: "Erik the Slayer", meaning: "Erik the Killer" },
    { name: "Ralof", meaning: "Wanderer" },
    { name: "Hadvar", meaning: "Warrior" },
    { name: "Torygg", meaning: "King" },
    { name: "Vignar Grey-Mane", meaning: "Wanderer Grey-Mane" },
    { name: "Idgrod Ravencrone", meaning: "Idle-Goddess Raven-Crone" },
    { name: "Skald", meaning: "Poet-Singer" },
    { name: "Hrongar", meaning: "Strong-Spear" },
    { name: "Olaf One-Eye", meaning: "Olaf the One-Eyed" },
    { name: "Yngvar", meaning: "Yngvi's Warrior" },
    { name: "Jorrvaskr", meaning: "Yore-Wolf" },
    { name: "Tolfdir", meaning: "Wolf-Dir" },
    { name: "Farengar Secret-Fire", meaning: "Far-Edge Secret-Fire" },
    { name: "Farkas", meaning: "Wolf" },
    { name: "Vilkas", meaning: "Wolf" },
    { name: "Aela the Huntress", meaning: "Aela the Huntress" },
    { name: "Kodlak Whitemane", meaning: "Kodlak White-Mane" },
    { name: "Sven", meaning: "Young Man" },
    { name: "Hroar", meaning: "Roar" },
    { name: "Gerdur", meaning: "Spear-Daughter" },
    { name: "Hilda", meaning: "Battle" },
    { name: "Borg", meaning: "Fortress" },
    { name: "Gunnar", meaning: "Warrior" },
    { name: "Harald", meaning: "Army-Ruler" },
    { name: "Sigurd", meaning: "Victory-Guard" },
    { name: "Ragnar", meaning: "Warrior" },
    { name: "Erikson", meaning: "Son of Erik" },
    { name: "Olafson", meaning: "Son of Olaf" },
    { name: "Haraldson", meaning: "Son of Harald" },
    { name: "Sigurdson", meaning: "Son of Sigurd" },
    { name: "Ragnarson", meaning: "Son of Ragnar" },
    { name: "Gunnarson", meaning: "Son of Gunnar" },
    { name: "Bjornson", meaning: "Son of Bjorn" },
    { name: "Magnusson", meaning: "Son of Magnus" },
    { name: "Ivarsson", meaning: "Son of Ivar" },
    { name: "Larsen", meaning: "Son of Lars" },
    { name: "Nilsen", meaning: "Son of Nils" },
    { name: "Andersson", meaning: "Son of Anders" },
    { name: "Jonsson", meaning: "Son of Jon" },
    { name: "Pettersen", meaning: "Son of Petter" },
    { name: "Karlsson", meaning: "Son of Karl" },
    { name: "Olavson", meaning: "Son of Olav" },
    { name: "Torstein", meaning: "Thor's Stone" },
    { name: "Svenn", meaning: "Young Man" },
    { name: "Eirik", meaning: "Eternal Ruler" },
    { name: "Jens", meaning: "God is Gracious" },
    { name: "Knut", meaning: "Knot" },
    { name: "Magnus", meaning: "Great" },
    { name: "Ole", meaning: "Wealth" },
    { name: "Per", meaning: "Rock" },
    { name: "Stian", meaning: "Stone" },
    { name: "Tore", meaning: "Thor's Warrior" },
    { name: "Trygve", meaning: "True" },
    { name: "Arne", meaning: "Eagle" },
    { name: "Bjarne", meaning: "Bear" },
    { name: "Dag", meaning: "Day" },
    { name: "Einar", meaning: "One Warrior" },
    { name: "Frode", meaning: "Wise" },
    { name: "Geir", meaning: "Spear" },
    { name: "Hakon", meaning: "High Son" },
    { name: "Ingvar", meaning: "Ing's Warrior" },
    { name: "Johan", meaning: "God is Gracious" },
    { name: "Kalle", meaning: "Strong" },
    { name: "Lars", meaning: "Crowned with Laurels" },
    { name: "Morten", meaning: "Death" },
    { name: "Niels", meaning: "Victory of the People" },
    { name: "Olav", meaning: "Ancestor's Relic" },
    { name: "Peder", meaning: "Rock" },
    { name: "Rune", meaning: "Secret" },
    { name: "Sindre", meaning: "Defender" },
    { name: "Terje", meaning: "Thor's Spear" },
    { name: "Ulf", meaning: "Wolf" },
    { name: "Vegard", meaning: "Protection" },
    { name: "Arvid", meaning: "Eagle Tree" },
    { name: "Eivind", meaning: "Ever Victorious" },
    { name: "Henrik", meaning: "Home Ruler" },
    { name: "Jonas", meaning: "Dove" },
    { name: "Kristian", meaning: "Follower of Christ" },
    { name: "Mats", meaning: "Gift of God" },
    { name: "Nikolai", meaning: "Victory of the People" },
    { name: "Oliver", meaning: "Olive Tree" },
    { name: "Simon", meaning: "Heard" },
    { name: "Alexander", meaning: "Defender of Men" },
    { name: "Benjamin", meaning: "Son of the Right Hand" },
    { name: "Daniel", meaning: "God is My Judge" },
    { name: "David", meaning: "Beloved" },
    { name: "Elias", meaning: "Yahweh is God" },
    { name: "Gabriel", meaning: "God is My Strength" },
    { name: "Isaac", meaning: "He Laughs" },
    { name: "Jacob", meaning: "Supplanter" },
    { name: "Julian", meaning: "Youthful" },
    { name: "Liam", meaning: "Strong-Willed Warrior" },
    { name: "Lucas", meaning: "Bringer of Light" },
    { name: "Noah", meaning: "Rest" },
    { name: "Oscar", meaning: "Divine Spear" },
    { name: "Samuel", meaning: "Name of God" },
    { name: "William", meaning: "Resolute Protector" },
    { name: "Adam", meaning: "Man" },
    { name: "Adrian", meaning: "Dark" },
    { name: "Aksel", meaning: "Peaceful Ruler" },
    { name: "Anton", meaning: "Priceless" },
    { name: "August", meaning: "Venerable" },
    { name: "Axel", meaning: "Father of Peace" },
    { name: "Casper", meaning: "Treasure" },
    { name: "Emil", meaning: "Rival" },
    { name: "Filip", meaning: "Friend of Horses" },
    { name: "Fredrik", meaning: "Peaceful Ruler" },
    { name: "Gustav", meaning: "Staff of the Goths" },
    { name: "Hampus", meaning: "Home" },
    { name: "Isak", meaning: "Laughter" },
    { name: "Jakob", meaning: "Supplanter" },
    { name: "Joel", meaning: "Yahweh is God" },
    { name: "Johan", meaning: "God is Gracious" },
    { name: "Jonas", meaning: "Dove" },
    { name: "Julius", meaning: "Youthful" },
    { name: "Linus", meaning: "Flax" },
    { name: "Ludvig", meaning: "Famous Warrior" },
    { name: "Malcolm", meaning: "Disciple of Saint Columba" },
    { name: "Martin", meaning: "Warlike" },
    { name: "Max", meaning: "Greatest" },
    { name: "Melker", meaning: "King" },
    { name: "Milo", meaning: "Soldier" },
    { name: "Olle", meaning: "Wealth" },
    { name: "Oscar", meaning: "Divine Spear" },
    { name: "Patrik", meaning: "Noble" },
    { name: "Pontus", meaning: "Sea" },
    { name: "Robin", meaning: "Famous" },
    { name: "Samuel", meaning: "Name of God" },
    { name: "Sander", meaning: "Defender of Men" },
    { name: "Sebastian", meaning: "From Sebaste" },
    { name: "Stellan", meaning: "Calm" },
    { name: "Theodor", meaning: "Gift of God" },
    { name: "Valter", meaning: "Ruler of the Army" },
    { name: "Viktor", meaning: "Conqueror" },
    { name: "Adam", meaning: "First Man" },
    { name: "Albin", meaning: "White" },
    { name: "Andreas", meaning: "Manly" },
    { name: "Anton", meaning: "Inestimable" },
    { name: "Benjamin", meaning: "Son of the Right Hand" },
    { name: "Carl", meaning: "Free Man" },
    { name: "Charlie", meaning: "Free Man" },
    { name: "Christoffer", meaning: "Bearer of Christ" },
    { name: "Daniel", meaning: "God is My Judge" },
    { name: "David", meaning: "Beloved" },
    { name: "Erik", meaning: "Eternal Ruler" },
    { name: "Felix", meaning: "Happy" },
    { name: "Gabriel", meaning: "Hero of God" },
    { name: "Gustav", meaning: "Staff of the Goths" },
    { name: "Henry", meaning: "Ruler of the Household" },
    { name: "Hugo", meaning: "Mind" },
    { name: "Ian", meaning: "God is Gracious" },
    { name: "Jakob", meaning: "Holder of the Heel" },
    { name: "Jesper", meaning: "God Shall Add" },
    { name: "Johan", meaning: "God is Gracious" },
    { name: "Karl", meaning: "Free Man" },
    { name: "Kevin", meaning: "Handsome" },
    { name: "Liam", meaning: "Strong-Willed Warrior" },
    { name: "Lucas", meaning: "Light" },
    { name: "Marcus", meaning: "Warlike" },
    { name: "Maximilian", meaning: "Greatest" },
    { name: "Noah", meaning: "Rest" },
    { name: "Oskar", meaning: "Divine Spear" },
    { name: "Philip", meaning: "Lover of Horses" },
    { name: "Robin", meaning: "Famous" },
    { name: "Simon", meaning: "Heard" },
    { name: "Theodor", meaning: "Gift of God" },
    { name: "William", meaning: "Will" },
    { name: "Alexander", meaning: "Defender of Mankind" },
    { name: "Benjamin", meaning: "Son of the Right Hand" },
    { name: "Christopher", meaning: "Bearer of Christ" },
    { name: "Daniel", meaning: "God is My Judge" },
    { name: "Elijah", meaning: "Yahweh is God" },
    { name: "Ethan", meaning: "Strong" },
    { name: "James", meaning: "Supplanter" },
    { name: "Jacob", meaning: "Holder of the Heel" },
    { name: "Logan", meaning: "Little Hollow" },
    { name: "Mason", meaning: "Stone Worker" },
    { name: "Michael", meaning: "Who is Like God?" },
    { name: "Noah", meaning: "Rest" },
    { name: "Oliver", meaning: "Olive Tree" },
    { name: "Owen", meaning: "Young Warrior" },
    { name: "Samuel", meaning: "Name of God" },
    { name: "William", meaning: "Will" },
    { name: "Aiden", meaning: "Little Fire" },
    { name: "Benjamin", meaning: "Son of the Right Hand" },
    { name: "Caleb", meaning: "Faithful" },
    { name: "Dylan", meaning: "Son of the Sea" },
    { name: "Ethan", meaning: "Strong" },
    { name: "Gabriel", meaning: "Hero of God" },
    { name: "Henry", meaning: "Ruler of the Household" },
    { name: "Isaac", meaning: "He Laughs" },
    { name: "Jack", meaning: "God is Gracious" },
    { name: "Jackson", meaning: "Son of Jack" },
    { name: "James", meaning: "Supplanter" },
    { name: "Jacob", meaning: "Holder of the Heel" },
    { name: "Jayden", meaning: "Thankful" },
    { name: "Liam", meaning: "Strong-Willed Warrior" },
    { name: "Lucas", meaning: "Light" },
    { name: "Mason", meaning: "Stone Worker" },
    { name: "Matthew", meaning: "Gift of God" },
    { name: "Michael", meaning: "Who is Like God?" },
    { name: "Noah", meaning: "Rest" },
    { name: "Oliver", meaning: "Olive Tree" },
    { name: "Owen", meaning: "Young Warrior" },
    { name: "Samuel", meaning: "Name of God" },
    { name: "Sebastian", meaning: "From Sebaste" },
    { name: "William", meaning: "Will" },
    { name: "Alexander", meaning: "Defender of Mankind" },
    { name: "Benjamin", meaning: "Son of the Right Hand" },
    { name: "Christopher", meaning: "Bearer of Christ" },
    { name: "Daniel", meaning: "God is My Judge" },
    { name: "Elijah", meaning: "Yahweh is God" },
    { name: "Ethan", meaning: "Strong" },
    { name: "James", meaning: "Supplanter" },
    { name: "Jacob", meaning: "Holder of the Heel" },
    { name: "Logan", meaning: "Little Hollow" },
    { name: "Mason", meaning: "Stone Worker" },
    { name: "Michael", meaning: "Who is Like God?" },
    { name: "Noah", meaning: "Rest" },
    { name: "Oliver", meaning: "Olive Tree" },
    { name: "Owen", meaning: "Young Warrior" },
    { name: "Samuel", meaning: "Name of God" },
    { name: "William", meaning: "Will" },
    { name: "Arnar", meaning: "Eagle" },
    { name: "Bjarki", meaning: "Little Bear" },
    { name: "Egil", meaning: "Edge of Sword" },
    { name: "Fjalar", meaning: "Bird" },
    { name: "Gisli", meaning: "Hostage" },
    { name: "Halli", meaning: "Rock" },
    { name: "Ingi", meaning: "Ing's Warrior" },
    { name: "Jorund", meaning: "Sword of the Jarl" },
    { name: "Kjartan", meaning: "Cart Maker" },
    { name: "Laufey", meaning: "Tree Island" },
    { name: "Magnus", meaning: "Great" },
    { name: "Njord", meaning: "Nordic God" },
    { name: "Oddr", meaning: "Point of Spear" },
    { name: "Ragnvald", meaning: "Powerful Ruler" },
    { name: "Sigbjorn", meaning: "Victory Bear" },
    { name: "Thorir", meaning: "Thor's Warrior" },
    { name: "Ulfarr", meaning: "Wolf Warrior" },
    { name: "Valdimar", meaning: "Famous Ruler" },
    { name: "Asbjorn", meaning: "God Bear" },
    { name: "Bjarni", meaning: "Bear" },
    { name: "Eiríkr", meaning: "Eternal Ruler" },
    { name: "Frodi", meaning: "Wise" },
    { name: "Geirmund", meaning: "Spear Protection" },
    { name: "Haraldr", meaning: "Army Ruler" },
    { name: "Ingvarr", meaning: "Ing's Warrior" },
    { name: "Jón", meaning: "God is Gracious" },
    { name: "Ketill", meaning: "Cauldron" },
    { name: "Leif", meaning: "Descendant" },
    { name: "Magnús", meaning: "Great" },
    { name: "Ólafr", meaning: "Ancestor's Relic" },
    { name: "Rúrik", meaning: "Famous Ruler" },
    { name: "Sigurðr", meaning: "Victory Guardian" },
    { name: "Þórir", meaning: "Thor's Warrior" },
    { name: "Úlfr", meaning: "Wolf" },
    { name: "Vésteinn", meaning: "Holy Stone" },
    { name: "Ásgeir", meaning: "Divine Spear" },
    { name: "Bergþór", meaning: "Mountain Thor" },
    { name: "Dagfinn", meaning: "Day Finn" },
    { name: "Einar", meaning: "Single Warrior" },
    { name: "Gunnar", meaning: "Warrior" },
    { name: "Halldór", meaning: "Rock Door" },
    { name: "Jóhann", meaning: "God is Gracious" },
    { name: "Kolbeinn", meaning: "Coal Bear" },
    { name: "Magnús", meaning: "Great" },
    { name: "Ólafur", meaning: "Ancestor's Relic" },
    { name: "Páll", meaning: "Small" },
    { name: "Sigurður", meaning: "Victory Guardian" },
    { name: "Stefán", meaning: "Crown" },
    { name: "Tómas", meaning: "Twin" },
    { name: "Valur", meaning: "Falcon" },
    { name: "Arnór", meaning: "Eagle Warrior" },
    { name: "Brynjar", meaning: "Armor Warrior" },
    { name: "Davíð", meaning: "Beloved" },
    { name: "Eyjólfur", meaning: "Island Wolf" },
    { name: "Friðrik", meaning: "Peace Ruler" },
    { name: "Guðmundur", meaning: "God Protection" },
    { name: "Haraldur", meaning: "Army Ruler" },
    { name: "Ísak", meaning: "Laughter" },
    { name: "Jónas", meaning: "Dove" },
    { name: "Kristján", meaning: "Follower of Christ" },
    { name: "Lárus", meaning: "Laurel" },
    { name: "Marteinn", meaning: "Warlike" },
    { name: "Óskar", meaning: "Divine Spear" },
    { name: "Róbert", meaning: "Bright Fame" },
    { name: "Sævar", meaning: "Sea Guardian" },
    { name: "Tryggvi", meaning: "True" },
    { name: "Viðar", meaning: "Tree Warrior" },
    { name: "Árni", meaning: "Eagle" },
    { name: "Björn", meaning: "Bear" },
    { name: "Eirík", meaning: "Eternal Ruler" },
    { name: "Gísli", meaning: "Hostage" },
    { name: "Hafþór", meaning: "Sea Thor" },
    { name: "Ingólfur", meaning: "Ing's Wolf" },
    { name: "Jökull", meaning: "Glacier" },
    { name: "Kári", meaning: "Storm" },
    { name: "Magnús", meaning: "Great" },
    { name: "Nökkvi", meaning: "Dark" },
    { name: "Óttar", meaning: "Wealthy" },
    { name: "Ragnar", meaning: "Warrior" },
    { name: "Sigurður", meaning: "Victory Guardian" },
    { name: "Þorsteinn", meaning: "Thor's Stone" },
    { name: "Ungþór", meaning: "Young Thor" },
    { name: "Vagn", meaning: "Wagon" },
    { name: "Alf", meaning: "Elf" },
    { name: "Brage", meaning: "Poetry" },
    { name: "Dag", meaning: "Day" },
    { name: "Egil", meaning: "Edge" },
    { name: "Frode", meaning: "Wise" },
    { name: "Gudbrand", meaning: "God Sword" },
    { name: "Halfdan", meaning: "Half Dane" },
    { name: "Ivar", meaning: "Arch" },
    { name: "Jarl", meaning: "Earl" },
    { name: "Knut", meaning: "Knot" },
    { name: "Loke", meaning: "Trickster" },
    { name: "Magne", meaning: "Great" },
    { name: "Odin", meaning: "Frenzy" },
    { name: "Rune", meaning: "Secret" },
    { name: "Sven", meaning: "Young" },
    { name: "Thor", meaning: "Thunder" },
    { name: "Ulf", meaning: "Wolf" },
    { name: "Valdemar", meaning: "Famous Ruler" },
    { name: "Bror", meaning: "Brother" },
    { name: "Einar", meaning: "Single Warrior" },
    { name: "Gunnar", meaning: "Warrior" },
    { name: "Håkan", meaning: "High Son" },
    { name: "Ingemar", meaning: "Ing's Famous" },
    { name: "Jan", meaning: "God is Gracious" },
    { name: "Karl", meaning: "Free Man" },
    { name: "Lars", meaning: "Crowned with Laurels" },
    { name: "Nils", meaning: "Victory of the People" },
    { name: "Olle", meaning: "Wealth" },
    { name: "Rolf", meaning: "Wolf" },
    { name: "Stig", meaning: "Path" },
    { name: "Torbjörn", meaning: "Thor's Bear" },
    { name: "Urban", meaning: "Urban" },
    { name: "Vincent", meaning: "Conqueror" },
    { name: "Åke", meaning: "Ancestor" },
    { name: "Bengt", meaning: "Blessed" },
    { name: "Dan", meaning: "Judge" },
    { name: "Erik", meaning: "Eternal Ruler" },
    { name: "Georg", meaning: "Farmer" },
    { name: "Henrik", meaning: "Home Ruler" },
    { name: "Johan", meaning: "God is Gracious" },
    { name: "Kurt", meaning: "Courteous" },
    { name: "Mats", meaning: "Gift of God" },
    { name: "Oscar", meaning: "Divine Spear" },
    { name: "Peter", meaning: "Rock" },
    { name: "Roger", meaning: "Famous Spear" },
    { name: "Sten", meaning: "Stone" },
    { name: "Tomas", meaning: "Twin" },
    { name: "Werner", meaning: "Protector" },
    { name: "Åke", meaning: "Ancestor" },
    { name: "Bertil", meaning: "Bright" },
    { name: "Carl", meaning: "Free Man" },
    { name: "Dag", meaning: "Day" },
    { name: "Egil", meaning: "Edge" },
    { name: "Folke", meaning: "People" },
    { name: "Gösta", meaning: "Guest" },
    { name: "Hugo", meaning: "Mind" },
    { name: "Ivar", meaning: "Arch" },
    { name: "Jonas", meaning: "Dove" },
    { name: "Kjell", meaning: "Kettle" },
    { name: "Lennart", meaning: "Strong as a Lion" },
    { name: "Mårten", meaning: "Warlike" },
    { name: "Ove", meaning: "Island" },
    { name: "Rune", meaning: "Secret" },
    { name: "Sven", meaning: "Young" },
    { name: "Ture", meaning: "True" },
    { name: "Ulf", meaning: "Wolf" },
    { name: "Viktor", meaning: "Conqueror" },
    { name: "Adam", meaning: "First Man" },
    { name: "Anders", meaning: "Manly" },
    { name: "Anton", meaning: "Inestimable" },
    { name: "Benjamin", meaning: "Son of the Right Hand" },
    { name: "David", meaning: "Beloved" },
    { name: "Erik", meaning: "Eternal Ruler" },
    { name: "Fredrik", meaning: "Peaceful Ruler" },
    { name: "Gustav", meaning: "Staff of the Goths" },
    { name: "Henrik", meaning: "Home Ruler" },
    { name: "Johan", meaning: "God is Gracious" },
    { name: "Karl", meaning: "Free Man" },
    { name: "Lars", meaning: "Crowned with Laurels" },
    { name: "Magnus", meaning: "Great" },
    { name: "Nils", meaning: "Victory of the People" },
    { name: "Oscar", meaning: "Divine Spear" },
    { name: "Peter", meaning: "Rock" },
    { name: "Samuel", meaning: "Name of God" },
    { name: "Sten", meaning: "Stone" },
    { name: "Tomas", meaning: "Twin" },
    { name: "Ulf", meaning: "Wolf" },
    { name: "Viktor", meaning: "Conqueror" },
    { name: "William", meaning: "Will" },
    { name: "Alexander", meaning: "Defender of Mankind" },
    { name: "Benjamin", meaning: "Son of the Right Hand" },
    { name: "Christopher", meaning: "Bearer of Christ" },
    { name: "Daniel", meaning: "God is My Judge" },
    { name: "Elijah", meaning: "Yahweh is God" },
    { name: "Ethan", meaning: "Strong" },
    { name: "James", meaning: "Supplanter" },
    { name: "Jacob", meaning: "Holder of the Heel" },
    { name: "Logan", meaning: "Little Hollow" },
    { name: "Mason", meaning: "Stone Worker" },
    { name: "Michael", meaning: "Who is Like God?" },
    { name: "Noah", meaning: "Rest" },
    { name: "Oliver", meaning: "Olive Tree" },
    { name: "Owen", meaning: "Young Warrior" },
    { name: "Samuel", meaning: "Name of God" },
    { name: "William", meaning: "Will" },
    { name: "Aidan", meaning: "Little Fire" },
    { name: "Benjamin", meaning: "Son of the Right Hand" },
    { name: "Caleb", meaning: "Faithful" },
    { name: "Dylan", meaning: "Son of the Sea" },
    { name: "Ethan", meaning: "Strong" },
    { name: "Gabriel", meaning: "Hero of God" },
    { name: "Henry", meaning: "Ruler of the Household" },
    { name: "Isaac", meaning: "He Laughs" },
    { name: "Jack", meaning: "God is Gracious" },
    { name: "Jackson", meaning: "Son of Jack" },
    { name: "James", meaning: "Supplanter" },
    { name: "Jacob", meaning: "Holder of the Heel" },
    { name: "Jayden", meaning: "Thankful" },
    { name: "Liam", meaning: "Strong-Willed Warrior" },
    { name: "Lucas", meaning: "Light" },
    { name: "Mason", meaning: "Stone Worker" },
    { name: "Matthew", meaning: "Gift of God" },
    { name: "Michael", meaning: "Who is Like God?" },
    { name: "Noah", meaning: "Rest" },
    { name: "Oliver", meaning: "Olive Tree" },
    { name: "Owen", meaning: "Young Warrior" },
    { name: "Samuel", meaning: "Name of God" },
    { name: "Sebastian", meaning: "From Sebaste" },
    { name: "William", meaning: "Will" }
];

const femaleNames = [
    { name: "Lydia", meaning: "From Lydia" },
    { name: "Mjoll the Lioness", meaning: "Mjoll the Lioness" },
    { name: "Aela the Huntress", meaning: "Aela the Huntress" },
    { name: "Serana", meaning: "Star" },
    { name: "Isran", meaning: "Iron" },
    { name: "Valerica", meaning: "Strong" },
    { name: "Fura", meaning: "Fox" },
    { name: "Gunmar", meaning: "War Famous" },
    { name: "Sif", meaning: "Bride" },
    { name: "Freya", meaning: "Lady" },
    { name: "Idun", meaning: "Ever Young" },
    { name: "Hel", meaning: "Death" },
    { name: "Skadi", meaning: "Damage" },
    { name: "Sigyn", meaning: "Victory Friend" },
    { name: "Brynhildr", meaning: "Armor Battle" },
    { name: "Gudrun", meaning: "Divine Secret" },
    { name: "Hilda", meaning: "Battle" },
    { name: "Ravenna", meaning: "Raven" },
    { name: "Corvina", meaning: "Raven" },
    { name: "Stella", meaning: "Star" },
    { name: "Astra", meaning: "Star" },
    { name: "Nova", meaning: "New" },
    { name: "Lirael", meaning: "Night Song" },
    { name: "Morrigan", meaning: "Phantom Queen" },
    { name: "Badb", meaning: "Battle Crow" },
    { name: "Macha", meaning: "Battle" },
    { name: "Danu", meaning: "Mother" },
    { name: "Arianrhod", meaning: "Silver Wheel" },
    { name: "Rhiannon", meaning: "Divine Queen" },
    { name: "Blodeuwedd", meaning: "Flower Face" },
    { name: "Ceridwen", meaning: "Blessed" },
    { name: "Bridget", meaning: "Exalted" },
    { name: "Brigid", meaning: "High" },
    { name: "Aine", meaning: "Splendor" },
    { name: "Cliodhna", meaning: "Shapely" },
    { name: "Deirdre", meaning: "Sorrow" },
    { name: "Niamh", meaning: "Bright" },
    { name: "Aoife", meaning: "Radiance" },
    { name: "Grainne", meaning: "Love" },
    { name: "Mairead", meaning: "Pearl" },
    { name: "Siobhan", meaning: "God is Gracious" },
    { name: "Eithne", meaning: "Kernel" },
    { name: "Saoirse", meaning: "Freedom" },
    { name: "Orla", meaning: "Golden Princess" },
    { name: "Una", meaning: "One" },
    { name: "Roisin", meaning: "Little Rose" },
    { name: "Caoimhe", meaning: "Gentle" },
    { name: "Maeve", meaning: "Intoxicating" },
    { name: "Fiona", meaning: "Fair" },
    { name: "Brianna", meaning: "Strong" },
    { name: "Sorcha", meaning: "Bright" },
    { name: "Megan", meaning: "Pearl" },
    { name: "Katie", meaning: "Pure" },
    { name: "Lauren", meaning: "Laurel" },
    { name: "Rachel", meaning: "Ewe" },
    { name: "Sarah", meaning: "Princess" },
    { name: "Emma", meaning: "Universal" },
    { name: "Olivia", meaning: "Olive" },
    { name: "Sophia", meaning: "Wisdom" },
    { name: "Isabella", meaning: "God is My Oath" },
    { name: "Mia", meaning: "Mine" },
    { name: "Ava", meaning: "Birdlike" },
    { name: "Lily", meaning: "Pure" },
    { name: "Zoe", meaning: "Life" },
    { name: "Evelyn", meaning: "Wished for Child" },
    { name: "Abigail", meaning: "Father's Joy" },
    { name: "Emily", meaning: "Industrious" },
    { name: "Harper", meaning: "Harp Player" },
    { name: "Amelia", meaning: "Industrious" },
    { name: "Elizabeth", meaning: "God is My Oath" },
    { name: "Sofia", meaning: "Wisdom" },
    { name: "Madison", meaning: "Son of Maud" },
    { name: "Avery", meaning: "Elf Ruler" },
    { name: "Ella", meaning: "Light" },
    { name: "Scarlett", meaning: "Red" },
    { name: "Victoria", meaning: "Victory" },
    { name: "Grace", meaning: "Elegance" },
    { name: "Chloe", meaning: "Young Green Shoot" },
    { name: "Camila", meaning: "Young Priestess" },
    { name: "Penelope", meaning: "Weaver" },
    { name: "Riley", meaning: "Courageous" },
    { name: "Aria", meaning: "Air" },
    { name: "Luna", meaning: "Moon" },
    { name: "Layla", meaning: "Night" },
    { name: "Mila", meaning: "Gracious" },
    { name: "Nora", meaning: "Honor" },
    { name: "Hazel", meaning: "Light Brown" },
    { name: "Ella", meaning: "Beautiful Fairy Woman" },
    { name: "Ellie", meaning: "Light" },
    { name: "Aurora", meaning: "Dawn" },
    { name: "Savannah", meaning: "Treeless Plain" },
    { name: "Brooklyn", meaning: "Broken Land" },
    { name: "Bella", meaning: "Beautiful" },
    { name: "Claire", meaning: "Clear" },
    { name: "Lucy", meaning: "Light" },
    { name: "Eleanor", meaning: "Light" },
    { name: "Hannah", meaning: "Favor" },
    { name: "Lillian", meaning: "Pure" },
    { name: "Addison", meaning: "Son of Adam" },
    { name: "Aubrey", meaning: "Elf Ruler" },
    { name: "Stella", meaning: "Star" },
    { name: "Natalie", meaning: "Birthday" },
    { name: "Zara", meaning: "Princess" },
    { name: "Leah", meaning: "Delicate" },
    { name: "Audrey", meaning: "Noble Strength" },
    { name: "Eva", meaning: "Life" },
    { name: "Ruby", meaning: "Red Gem" },
    { name: "Lila", meaning: "Night" },
    { name: "Piper", meaning: "Flute Player" },
    { name: "Maya", meaning: "Great" },
    { name: "Isla", meaning: "Island" },
    { name: "Violet", meaning: "Purple" },
    { name: "Mackenzie", meaning: "Child of the Wise Leader" },
    { name: "Madeline", meaning: "High Tower" },
    { name: "Charlotte", meaning: "Free Man" },
    { name: "Isabelle", meaning: "God is My Oath" },
    { name: "Grace", meaning: "Charm" },
    { name: "Olivia", meaning: "Peace" },
    { name: "Sophie", meaning: "Wisdom" },
    { name: "Chloe", meaning: "Bloom" },
    { name: "Amelia", meaning: "Work" },
    { name: "Lola", meaning: "Sorrow" },
    { name: "Evie", meaning: "Life" },
    { name: "Poppy", meaning: "Red Flower" },
    { name: "Freya", meaning: "Noble" },
    { name: "Ava", meaning: "Bird" },
    { name: "Isla", meaning: "Island" },
    { name: "Mia", meaning: "Mine" },
    { name: "Sophia", meaning: "Wisdom" },
    { name: "Grace", meaning: "Elegance" },
    { name: "Olivia", meaning: "Olive Tree" },
    { name: "Emily", meaning: "Industrious" },
    { name: "Amelia", meaning: "Hardworking" },
    { name: "Isabella", meaning: "Devoted to God" },
    { name: "Victoria", meaning: "Victory" },
    { name: "Charlotte", meaning: "Strong" },
    { name: "Harriet", meaning: "Ruler" },
    { name: "Alice", meaning: "Noble" },
    { name: "Daisy", meaning: "Day's Eye" },
    { name: "Eleanor", meaning: "Light" },
    { name: "Beatrice", meaning: "Happy" },
    { name: "Clara", meaning: "Clear" },
    { name: "Mabel", meaning: "Lovely" },
    { name: "Matilda", meaning: "Mighty" },
    { name: "Ethel", meaning: "Noble" },
    { name: "Agnes", meaning: "Pure" },
    { name: "Edith", meaning: "Rich" },
    { name: "Florence", meaning: "Flowering" },
    { name: "Gertrude", meaning: "Spear Strength" },
    { name: "Hilda", meaning: "Battle" },
    { name: "Ida", meaning: "Hardworking" },
    { name: "Josephine", meaning: "God Will Increase" },
    { name: "Katherine", meaning: "Pure" },
    { name: "Louise", meaning: "Renowned Warrior" },
    { name: "Margaret", meaning: "Pearl" },
    { name: "Nancy", meaning: "Grace" },
    { name: "Olive", meaning: "Olive Tree" },
    { name: "Patricia", meaning: "Noble" },
    { name: "Queenie", meaning: "Queen" },
    { name: "Rachel", meaning: "Ewe" },
    { name: "Sally", meaning: "Princess" },
    { name: "Theresa", meaning: "Reaper" },
    { name: "Ursula", meaning: "Little Bear" },
    { name: "Vera", meaning: "True" },
    { name: "Wendy", meaning: "Friend" },
    { name: "Xenia", meaning: "Hospitality" },
    { name: "Yvonne", meaning: "Yew" },
    { name: "Zelda", meaning: "Gray Fighting Maid" },
    { name: "Anastasia", meaning: "Resurrection" },
    { name: "Beatrice", meaning: "Blessed" },
    { name: "Cecilia", meaning: "Blind" },
    { name: "Diana", meaning: "Divine" },
    { name: "Eugenia", meaning: "Noble" },
    { name: "Francesca", meaning: "Free" },
    { name: "Gabriella", meaning: "God is My Strength" },
    { name: "Henrietta", meaning: "Ruler" },
    { name: "Ivy", meaning: "Climbing Plant" },
    { name: "Jacqueline", meaning: "Supplanter" },
    { name: "Katherine", meaning: "Pure" },
    { name: "Larissa", meaning: "Citadel" },
    { name: "Monica", meaning: "Advisor" },
    { name: "Nicole", meaning: "Victory" },
    { name: "Olivia", meaning: "Olive" },
    { name: "Penelope", meaning: "Weaver" },
    { name: "Quinn", meaning: "Fifth" },
    { name: "Ruth", meaning: "Compassionate" },
    { name: "Serena", meaning: "Calm" },
    { name: "Tessa", meaning: "Harvester" },
    { name: "Una", meaning: "Unity" },
    { name: "Valerie", meaning: "Strong" },
    { name: "Wanda", meaning: "Wanderer" },
    { name: "Xandra", meaning: "Protector" },
    { name: "Yvette", meaning: "Yew" },
    { name: "Zinnia", meaning: "Flower" },
    { name: "Agnesdottir", meaning: "Daughter of Agnes" },
    { name: "Brigiddottir", meaning: "Daughter of Brigid" },
    { name: "Eirsdottir", meaning: "Daughter of Eir" },
    { name: "Friggadottir", meaning: "Daughter of Frigga" },
    { name: "Gunnhildr", meaning: "War Battle" },
    { name: "Hildadottir", meaning: "Daughter of Hilda" },
    { name: "Ingidottir", meaning: "Daughter of Ingi" },
    { name: "Jorundsdottir", meaning: "Daughter of Jorund" },
    { name: "Kjelladottir", meaning: "Daughter of Kjell" },
    { name: "Laufeydottir", meaning: "Daughter of Laufey" },
    { name: "Magnhild", meaning: "Great Battle" },
    { name: "Njorddottir", meaning: "Daughter of Njord" },
    { name: "Oddrdottir", meaning: "Daughter of Oddr" },
    { name: "Ragnvaldsdottir", meaning: "Daughter of Ragnvald" },
    { name: "Sigbjorndottir", meaning: "Daughter of Sigbjorn" },
    { name: "Thorirdottir", meaning: "Daughter of Thorir" },
    { name: "Ulfarrdottir", meaning: "Daughter of Ulfarr" },
    { name: "Valdimardottir", meaning: "Daughter of Valdimar" },
    { name: "Asbjorndottir", meaning: "Daughter of Asbjorn" },
    { name: "Bjarnadottir", meaning: "Daughter of Bjarni" },
    { name: "Eiriksdottir", meaning: "Daughter of Eirik" },
    { name: "Frodidottir", meaning: "Daughter of Frodi" },
    { name: "Geirmundsdottir", meaning: "Daughter of Geirmund" },
    { name: "Haraldsdottir", meaning: "Daughter of Harald" },
    { name: "Ingvarrdottir", meaning: "Daughter of Ingvarr" },
    { name: "Jonadottir", meaning: "Daughter of Jon" },
    { name: "Ketildottir", meaning: "Daughter of Ketill" },
    { name: "Leifdottir", meaning: "Daughter of Leif" },
    { name: "Magnusdottir", meaning: "Daughter of Magnus" },
    { name: "Olafsdottir", meaning: "Daughter of Olaf" },
    { name: "Rurikdottir", meaning: "Daughter of Rurik" },
    { name: "Sigurdsdottir", meaning: "Daughter of Sigurd" },
    { name: "Thorisdottir", meaning: "Daughter of Thorir" },
    { name: "Ulfrdottir", meaning: "Daughter of Ulf" },
    { name: "Vesteinndottir", meaning: "Daughter of Vesteinn" },
    { name: "Asgeirdottir", meaning: "Daughter of Asgeir" },
    { name: "Bergthordottir", meaning: "Daughter of Bergthor" },
    { name: "Dagfinnsdottir", meaning: "Daughter of Dagfinn" },
    { name: "Einardottir", meaning: "Daughter of Einar" },
    { name: "Gunnardottir", meaning: "Daughter of Gunnar" },
    { name: "Halldordottir", meaning: "Daughter of Halldor" },
    { name: "Johannsdottir", meaning: "Daughter of Johann" },
    { name: "Kolbeinadottir", meaning: "Daughter of Kolbeinn" },
    { name: "Olafurdottir", meaning: "Daughter of Olafur" },
    { name: "Palldottir", meaning: "Daughter of Pall" },
    { name: "Sigurdsdottir", meaning: "Daughter of Sigurdur" },
    { name: "Stefandottir", meaning: "Daughter of Stefan" },
    { name: "Tomasdottir", meaning: "Daughter of Tomas" },
    { name: "Valurdottir", meaning: "Daughter of Valur" },
    { name: "Arnordottir", meaning: "Daughter of Arnor" },
    { name: "Brynjardottir", meaning: "Daughter of Brynjar" },
    { name: "Davidsdottir", meaning: "Daughter of David" },
    { name: "Eyjolfurdottir", meaning: "Daughter of Eyjolfur" },
    { name: "Fridrikdottir", meaning: "Daughter of Fridrik" },
    { name: "Gudmundsdottir", meaning: "Daughter of Gudmundur" },
    { name: "Haraldurdottir", meaning: "Daughter of Haraldur" },
    { name: "Isakdottir", meaning: "Daughter of Isak" },
    { name: "Jonasdottir", meaning: "Daughter of Jonas" },
    { name: "Kristjandottir", meaning: "Daughter of Kristjan" },
    { name: "Larusdottir", meaning: "Daughter of Larus" },
    { name: "Marteindottir", meaning: "Daughter of Marteinn" },
    { name: "Oskardottir", meaning: "Daughter of Oskar" },
    { name: "Roberttdottir", meaning: "Daughter of Robert" },
    { name: "Saevardottir", meaning: "Daughter of Saevar" },
    { name: "Tryggvidottir", meaning: "Daughter of Tryggvi" },
    { name: "Vidardottir", meaning: "Daughter of Vidar" },
    { name: "Arnidottir", meaning: "Daughter of Arni" },
    { name: "Bjorndottir", meaning: "Daughter of Bjorn" },
    { name: "Eiriksdottir", meaning: "Daughter of Eirik" },
    { name: "Gislidottir", meaning: "Daughter of Gisli" },
    { name: "Hafthordottir", meaning: "Daughter of Hafthor" },
    { name: "Ingolfurdottir", meaning: "Daughter of Ingolfur" },
    { name: "Jokuldottir", meaning: "Daughter of Jokull" },
    { name: "Karidottir", meaning: "Daughter of Kari" },
    { name: "Nökkvidottir", meaning: "Daughter of Nokkvi" },
    { name: "Ottardottir", meaning: "Daughter of Ottar" },
    { name: "Ragnardottir", meaning: "Daughter of Ragnar" },
    { name: "Sigurdsdottir", meaning: "Daughter of Sigurdur" },
    { name: "Thorsteindottir", meaning: "Daughter of Thorsteinn" },
    { name: "Ungthordottir", meaning: "Daughter of Ungthor" },
    { name: "Vagnsdottir", meaning: "Daughter of Vagn" },
    { name: "Alfdottir", meaning: "Daughter of Alf" },
    { name: "Bragedottir", meaning: "Daughter of Brage" },
    { name: "Dagdottir", meaning: "Daughter of Dag" },
    { name: "Egildottir", meaning: "Daughter of Egil" },
    { name: "Frodedottir", meaning: "Daughter of Frode" },
    { name: "Gudbranddottir", meaning: "Daughter of Gudbrand" },
    { name: "Halfdandottir", meaning: "Daughter of Halfdan" },
    { name: "Ivardsdottir", meaning: "Daughter of Ivar" },
    { name: "Jarldottir", meaning: "Daughter of Jarl" },
    { name: "Knuttdottir", meaning: "Daughter of Knut" },
    { name: "Lokedottir", meaning: "Daughter of Loke" },
    { name: "Magnedottir", meaning: "Daughter of Magne" },
    { name: "Odindottir", meaning: "Daughter of Odin" },
    { name: "Runadottir", meaning: "Daughter of Rune" },
    { name: "Svendottir", meaning: "Daughter of Sven" },
    { name: "Thordottir", meaning: "Daughter of Thor" },
    { name: "Ulfdottir", meaning: "Daughter of Ulf" },
    { name: "Valdemardottir", meaning: "Daughter of Valdemar" },
    { name: "Broradottir", meaning: "Daughter of Bror" },
    { name: "Einardottir", meaning: "Daughter of Einar" },
    { name: "Gunnardottir", meaning: "Daughter of Gunnar" },
    { name: "Hakandottir", meaning: "Daughter of Hakan" },
    { name: "Ingemardottir", meaning: "Daughter of Ingemar" },
    { name: "Jandottir", meaning: "Daughter of Jan" },
    { name: "Karlsdottir", meaning: "Daughter of Karl" },
    { name: "Larsdottir", meaning: "Daughter of Lars" },
    { name: "Nilsdottir", meaning: "Daughter of Nils" },
    { name: "Olledottir", meaning: "Daughter of Olle" },
    { name: "Rolfsdottir", meaning: "Daughter of Rolf" },
    { name: "Stigdottir", meaning: "Daughter of Stig" },
    { name: "Torbjorndottir", meaning: "Daughter of Torbjorn" },
    { name: "Urbandsdottir", meaning: "Daughter of Urban" },
    { name: "Vincentdottir", meaning: "Daughter of Vincent" },
    { name: "Akedottir", meaning: "Daughter of Ake" },
    { name: "Bengtsdottir", meaning: "Daughter of Bengt" },
    { name: "Dandottir", meaning: "Daughter of Dan" },
    { name: "Georgsdottir", meaning: "Daughter of Georg" },
    { name: "Henriksdottir", meaning: "Daughter of Henrik" },
    { name: "Johansdottir", meaning: "Daughter of Johan" },
    { name: "Kurtsdottir", meaning: "Daughter of Kurt" },
    { name: "Matsdottir", meaning: "Daughter of Mats" },
    { name: "Oscardottir", meaning: "Daughter of Oscar" },
    { name: "Petersdottir", meaning: "Daughter of Peter" },
    { name: "Rogersdottir", meaning: "Daughter of Roger" },
    { name: "Stensdottir", meaning: "Daughter of Sten" },
    { name: "Tomasdottir", meaning: "Daughter of Tomas" },
    { name: "Wernersdottir", meaning: "Daughter of Werner" },
    { name: "Akedottir", meaning: "Daughter of Ake" },
    { name: "Bertildottir", meaning: "Daughter of Bertil" },
    { name: "Carlsdottir", meaning: "Daughter of Carl" },
    { name: "Dagdottir", meaning: "Daughter of Dag" },
    { name: "Egildottir", meaning: "Daughter of Egil" },
    { name: "Folkedottir", meaning: "Daughter of Folke" },
    { name: "Gostadottir", meaning: "Daughter of Gosta" },
    { name: "Hugodottir", meaning: "Daughter of Hugo" },
    { name: "Ivardsdottir", meaning: "Daughter of Ivar" },
    { name: "Jonasdottir", meaning: "Daughter of Jonas" },
    { name: "Kjelldottir", meaning: "Daughter of Kjell" },
    { name: "Lennartdottir", meaning: "Daughter of Lennart" },
    { name: "Martendottir", meaning: "Daughter of Marten" },
    { name: "Ovedottir", meaning: "Daughter of Ove" },
    { name: "Runadottir", meaning: "Daughter of Rune" },
    { name: "Svendottir", meaning: "Daughter of Sven" },
    { name: "Turedottir", meaning: "Daughter of Ture" },
    { name: "Ulfdottir", meaning: "Daughter of Ulf" },
    { name: "Viktorsdottir", meaning: "Daughter of Viktor" },
    { name: "Adamsdottir", meaning: "Daughter of Adam" },
    { name: "Anderssdottir", meaning: "Daughter of Anders" },
    { name: "Antonsdottir", meaning: "Daughter of Anton" },
    { name: "Benjaminsdottir", meaning: "Daughter of Benjamin" },
    { name: "Davidsdottir", meaning: "Daughter of David" },
    { name: "Eriksdottir", meaning: "Daughter of Erik" },
    { name: "Fredriksdottir", meaning: "Daughter of Fredrik" },
    { name: "Gustavsdottir", meaning: "Daughter of Gustav" },
    { name: "Henriksdottir", meaning: "Daughter of Henrik" },
    { name: "Johansdottir", meaning: "Daughter of Johan" },
    { name: "Karlsdottir", meaning: "Daughter of Karl" },
    { name: "Larsdottir", meaning: "Daughter of Lars" },
    { name: "Magnusdottir", meaning: "Daughter of Magnus" },
    { name: "Nilsdottir", meaning: "Daughter of Nils" },
    { name: "Oscardottir", meaning: "Daughter of Oscar" },
    { name: "Petersdottir", meaning: "Daughter of Peter" },
    { name: "Samuelsdottir", meaning: "Daughter of Samuel" },
    { name: "Stensdottir", meaning: "Daughter of Sten" },
    { name: "Tomasdottir", meaning: "Daughter of Tomas" },
    { name: "Ulfdottir", meaning: "Daughter of Ulf" },
    { name: "Viktorsdottir", meaning: "Daughter of Viktor" },
    { name: "Williamsdottir", meaning: "Daughter of William" },
    { name: "Alexandersdottir", meaning: "Daughter of Alexander" },
    { name: "Benjaminsdottir", meaning: "Daughter of Benjamin" },
    { name: "Christophersdottir", meaning: "Daughter of Christopher" },
    { name: "Danielsdottir", meaning: "Daughter of Daniel" },
    { name: "Elijahsdottir", meaning: "Daughter of Elijah" },
    { name: "Ethansdottir", meaning: "Daughter of Ethan" },
    { name: "Jamesdottir", meaning: "Daughter of James" },
    { name: "Jacobsdottir", meaning: "Daughter of Jacob" },
    { name: "Logansdottir", meaning: "Daughter of Logan" },
    { name: "Masonsdottir", meaning: "Daughter of Mason" },
    { name: "Michaelsdottir", meaning: "Daughter of Michael" },
    { name: "Noahsdottir", meaning: "Daughter of Noah" },
    { name: "Oliversdottir", meaning: "Daughter of Oliver" },
    { name: "Owensdottir", meaning: "Daughter of Owen" },
    { name: "Samuelsdottir", meaning: "Daughter of Samuel" },
    { name: "Williamsdottir", meaning: "Daughter of William" },
    { name: "Aidansdottir", meaning: "Daughter of Aidan" },
    { name: "Calebsdottir", meaning: "Daughter of Caleb" },
    { name: "Dylansdottir", meaning: "Daughter of Dylan" },
    { name: "Gabrielsdottir", meaning: "Daughter of Gabriel" },
    { name: "Henrysdottir", meaning: "Daughter of Henry" },
    { name: "Isaacsdottir", meaning: "Daughter of Isaac" },
    { name: "Jacksdottir", meaning: "Daughter of Jack" },
    { name: "Jacksonsdottir", meaning: "Daughter of Jackson" },
    { name: "Jamesdottir", meaning: "Daughter of James" },
    { name: "Jacobsdottir", meaning: "Daughter of Jacob" },
    { name: "Jaydensdottir", meaning: "Daughter of Jayden" },
    { name: "Liamsdottir", meaning: "Daughter of Liam" },
    { name: "Lucassdottir", meaning: "Daughter of Lucas" },
    { name: "Masonsdottir", meaning: "Daughter of Mason" },
    { name: "Matthewsdottir", meaning: "Daughter of Matthew" },
    { name: "Michaelsdottir", meaning: "Daughter of Michael" },
    { name: "Noahsdottir", meaning: "Daughter of Noah" },
    { name: "Oliversdottir", meaning: "Daughter of Oliver" },
    { name: "Owensdottir", meaning: "Daughter of Owen" },
    { name: "Samuelsdottir", meaning: "Daughter of Samuel" },
    { name: "Sebastiansdottir", meaning: "Daughter of Sebastian" },
    { name: "Williamsdottir", meaning: "Daughter of William" }
];

let currentMode = 'random';

function shuffleArray(array) {
    const shuffled = [...array];
    for (let i = shuffled.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
    }
    return shuffled;
}

function generateNames() {
    const grid = document.getElementById('namesGrid');
    let pool;
    
    if (currentMode === 'random') {
        pool = shuffleArray([...maleNames, ...femaleNames]);
    } else if (currentMode === 'male') {
        pool = shuffleArray([...maleNames]);
    } else {
        pool = shuffleArray([...femaleNames]);
    }
    
    const selected = pool.slice(0, 16);
    
    grid.innerHTML = selected.map(item => `
        <div class="name-card">
            <div class="name-text">${item.name}</div>
            <div class="name-gender">${currentMode === 'female' ? 'Female' : currentMode === 'male' ? 'Male' : 'Mixed'}</div>
            <div class="name-meaning">${item.meaning}</div>
        </div>
    `).join('');
}

document.querySelectorAll('.mode-btn').forEach(btn => {
    btn.addEventListener('click', function() {
        document.querySelectorAll('.mode-btn').forEach(b => b.classList.remove('active'));
        this.classList.add('active');
        currentMode = this.dataset.mode;
        generateNames();
    });
});