const maleNames = [
    { name: "Mortimer", meaning: "Dead Sea" },
    { name: "Necros", meaning: "Death Bringer" },
    { name: "Thanatos", meaning: "Personification of Death" },
    { name: "Lich", meaning: "Undead Mage" },
    { name: "Kael", meaning: "Dark Elf" },
    { name: "Valerius", meaning: "To Be Strong" },
    { name: "Grimm", meaning: "Masked One" },
    { name: "Mordecai", meaning: "Warrior" },
    { name: "Vladimir", meaning: "Great Ruler" },
    { name: "Draven", meaning: "Hunter of Shadows" },
    { name: "Raven", meaning: "Dark Bird" },
    { name: "Silas", meaning: "Of the Forest" },
    { name: "Orion", meaning: "Hunter" },
    { name: "Jareth", meaning: "He Who Rules" },
    { name: "Xander", meaning: "Defender" },
    { name: "Zane", meaning: "God is Gracious" },
    { name: "Lucius", meaning: "Light" },
    { name: "Marcus", meaning: "Warlike" },
    { name: "Julius", meaning: "Youthful" },
    { name: "Maximus", meaning: "Greatest" },
    { name: "Tiberius", meaning: "Of the Tiber" },
    { name: "Octavius", meaning: "Eighth" },
    { name: "Cassius", meaning: "Vain" },
    { name: "Brutus", meaning: "Heavy" },
    { name: "Cicero", meaning: "Chickpea" },
    { name: "Nero", meaning: "Strong" },
    { name: "Caligula", meaning: "Little Boot" },
    { name: "Commodus", meaning: "Pleasant" },
    { name: "Diocletian", meaning: "Double" },
    { name: "Constantine", meaning: "Steadfast" },
    { name: "Dracula", meaning: "Son of the Dragon" },
    { name: "Nosferatu", meaning: "Undead" },
    { name: "Strahd", meaning: "Dark Lord" },
    { name: "Mordenkainen", meaning: "Powerful Mage" },
    { name: "Vecna", meaning: "Whispered One" },
    { name: "Vecna", meaning: "The Chained God" },
    { name: "Morgoth", meaning: "Dark Enemy" },
    { name: "Sauron", meaning: "Abhorred" },
    { name: "Melkor", meaning: "He Who Arises in Might" },
    { name: "Saruman", meaning: "Man of Skill" },
    { name: "Wormtongue", meaning: "Deceiver" },
    { name: "Grima", meaning: "Mask" },
    { name: "Azazel", meaning: "Goat God" },
    { name: "Asmodeus", meaning: "Demon of Lust" },
    { name: "Beelzebub", meaning: "Lord of the Flies" },
    { name: "Belphegor", meaning: "Lord of Sloth" },
    { name: "Mammon", meaning: "Wealth" },
    { name: "Lucifer", meaning: "Light Bearer" },
    { name: "Satan", meaning: "Adversary" },
    { name: "Baal", meaning: "Lord" },
    { name: "Moloch", meaning: "King" },
    { name: "Dagon", meaning: "Fish God" },
    { name: "Orcus", meaning: "Underworld God" },
    { name: "Hades", meaning: "Unseen" },
    { name: "Pluto", meaning: "Rich" },
    { name: "Acheron", meaning: "River of Woe" },
    { name: "Styx", meaning: "Hateful" },
    { name: "Charon", meaning: "Ferryman" },
    { name: "Cerberus", meaning: "Spotted" },
    { name: "Thanatos", meaning: "Death" },
    { name: "Hypnos", meaning: "Sleep" },
    { name: "Morpheus", meaning: "Form" },
    { name: "Nyx", meaning: "Night" },
    { name: "Erebus", meaning: "Darkness" },
    { name: "Chaos", meaning: "Void" },
    { name: "Eris", meaning: "Strife" },
    { name: "Ares", meaning: "War" },
    { name: "Hades", meaning: "Underworld" },
    { name: "Poseidon", meaning: "Earth Shaker" },
    { name: "Zeus", meaning: "Sky Father" },
    { name: "Odin", meaning: "Fury" },
    { name: "Thor", meaning: "Thunder" },
    { name: "Loki", meaning: "Trickster" },
    { name: "Hela", meaning: "Death" },
    { name: "Baldur", meaning: "Bold" },
    { name: "Tyr", meaning: "God" },
    { name: "Fenrir", meaning: "Fen Wolf" },
    { name: "Jormungandr", meaning: "World Serpent" },
    { name: "Surtur", meaning: "Black" },
    { name: "Ymir", meaning: "Giant" },
    { name: "Mimir", meaning: "Remember" },
    { name: "Bragi", meaning: "Poet" },
    { name: "Heimdall", meaning: "World Bright" },
    { name: "Valkyrie", meaning: "Chooser of the Slain" },
    { name: "Odin", meaning: "All-Father" },
    { name: "Yggdrasil", meaning: "World Tree" },
    { name: "Midgard", meaning: "Middle Earth" },
    { name: "Asgard", meaning: "God Home" },
    { name: "Niflheim", meaning: "Mist Home" },
    { name: "Muspelheim", meaning: "Fire Home" },
    { name: "Jotunheim", meaning: "Giant Home" },
    { name: "Svartalfheim", meaning: "Dark Elf Home" },
    { name: "Alfheim", meaning: "Light Elf Home" },
    { name: "Helheim", meaning: "Death Home" },
    { name: "Vanaheim", meaning: "Vanir Home" },
    { name: "Nidavellir", meaning: "Dwarf Home" },
    { name: "Aesir", meaning: "Gods" },
    { name: "Vanir", meaning: "Old Gods" },
    { name: "Jotun", meaning: "Giants" },
    { name: "Dwarf", meaning: "Short Ones" },
    { name: "Elf", meaning: "White Ones" },
    { name: "Troll", meaning: "Monster" },
    { name: "Goblin", meaning: "Evil Spirit" },
    { name: "Orc", meaning: "Demon" },
    { name: "Witch", meaning: "Wise One" },
    { name: "Warlock", meaning: "Oath Breaker" },
    { name: "Sorcerer", meaning: "Magic User" },
    { name: "Wizard", meaning: "Wise One" },
    { name: "Mage", meaning: "Learned One" },
    { name: "Druid", meaning: "Knowledge" },
    { name: "Shaman", meaning: "Healer" },
    { name: "Priest", meaning: "Leader" },
    { name: "Cultist", meaning: "Believer" },
    { name: "Acolyte", meaning: "Follower" },
    { name: "Apprentice", meaning: "Learner" },
    { name: "Necromancer", meaning: "Death Mage" },
    { name: "Lich", meaning: "Undead" },
    { name: "Vampire", meaning: "Blood Drinker" },
    { name: "Ghoul", meaning: "Grave Robber" },
    { name: "Wight", meaning: "Ghost" },
    { name: "Skeleton", meaning: "Bones" },
    { name: "Zombie", meaning: "Living Dead" },
    { name: "Mummy", meaning: "Preserved Dead" },
    { name: "Wraith", meaning: "Ghost" },
    { name: "Phantom", meaning: "Apparition" },
    { name: "Specter", meaning: "Ghost" },
    { name: "Spirit", meaning: "Soul" },
    { name: "Ghost", meaning: "Spirit" },
    { name: "Shadow", meaning: "Darkness" },
    { name: "Darkness", meaning: "Absence of Light" },
    { name: "Night", meaning: "Dark Time" },
    { name: "Dusk", meaning: "Twilight" },
    { name: "Dawn", meaning: "Morning" },
    { name: "Midnight", meaning: "Darkest Hour" },
    { name: "Eclipse", meaning: "Hidden Sun" },
    { name: "Moon", meaning: "Night Light" },
    { name: "Star", meaning: "Heavenly Body" },
    { name: "Sun", meaning: "Day Light" },
    { name: "Fire", meaning: "Heat" },
    { name: "Ice", meaning: "Cold" },
    { name: "Storm", meaning: "Violent Weather" },
    { name: "Lightning", meaning: "Electricity" },
    { name: "Thunder", meaning: "Sound of Storm" },
    { name: "Wind", meaning: "Moving Air" },
    { name: "Rain", meaning: "Water Droplets" },
    { name: "Snow", meaning: "Frozen Water" },
    { name: "Hail", meaning: "Ice Balls" },
    { name: "Fog", meaning: "Cloud on Ground" },
    { name: "Mist", meaning: "Light Fog" },
    { name: "Smoke", meaning: "Fire Vapor" },
    { name: "Ash", meaning: "Fire Remains" },
    { name: "Cinder", meaning: "Small Coal" },
    { name: "Ember", meaning: "Smoldering Coal" },
    { name: "Flame", meaning: "Fire" },
    { name: "Blaze", meaning: "Bright Fire" },
    { name: "Inferno", meaning: "Large Fire" },
    { name: "Conflagration", meaning: "Big Fire" },
    { name: "Bonfire", meaning: "Outdoor Fire" },
    { name: "Pyre", meaning: "Funeral Fire" },
    { name: "Cremation", meaning: "Burning Dead" },
    { name: "Grave", meaning: "Burial Place" },
    { name: "Tomb", meaning: "Stone Grave" },
    { name: "Crypt", meaning: "Underground Grave" },
    { name: "Mausoleum", meaning: "Large Tomb" },
    { name: "Cemetery", meaning: "Graveyard" },
    { name: "Graveyard", meaning: "Place of Graves" },
    { name: "Catacomb", meaning: "Underground Cemetery" },
    { name: "Sepulcher", meaning: "Tomb" },
    { name: "Sarcophagus", meaning: "Stone Coffin" },
    { name: "Coffin", meaning: "Dead Box" },
    { name: "Casket", meaning: "Small Coffin" },
    { name: "Corpse", meaning: "Dead Body" },
    { name: "Remains", meaning: "Left Overs" },
    { name: "Ashes", meaning: "Burned Remains" },
    { name: "Bone", meaning: "Skeleton Part" },
    { name: "Skull", meaning: "Head Bone" },
    { name: "Skeleton", meaning: "Bones" },
    { name: "Rib", meaning: "Chest Bone" },
    { name: "Spine", meaning: "Back Bone" },
    { name: "Femur", meaning: "Thigh Bone" },
    { name: "Tibia", meaning: "Shin Bone" },
    { name: "Fibula", meaning: "Calf Bone" },
    { name: "Humerus", meaning: "Upper Arm Bone" },
    { name: "Radius", meaning: "Forearm Bone" },
    { name: "Ulna", meaning: "Forearm Bone" },
    { name: "Pelvis", meaning: "Hip Bone" },
    { name: "Vertebra", meaning: "Back Bone Segment" },
    { name: "Cranium", meaning: "Skull" },
    { name: "Mandible", meaning: "Jaw Bone" },
    { name: "Clavicle", meaning: "Collar Bone" },
    { name: "Scapula", meaning: "Shoulder Blade" },
    { name: "Sternum", meaning: "Breast Bone" },
    { name: "Patella", meaning: "Knee Cap" },
    { name: "Calcaneus", meaning: "Heel Bone" },
    { name: "Talus", meaning: "Ankle Bone" },
    { name: "Metatarsal", meaning: "Foot Bone" },
    { name: "Metacarpal", meaning: "Hand Bone" },
    { name: "Phalanx", meaning: "Finger Bone" },
    { name: "Tooth", meaning: "Mouth Bone" },
    { name: "Nail", meaning: "Finger Cover" },
    { name: "Skin", meaning: "Body Cover" },
    { name: "Flesh", meaning: "Body Tissue" },
    { name: "Blood", meaning: "Life Fluid" },
    { name: "Heart", meaning: "Life Pump" },
    { name: "Brain", meaning: "Thought Center" },
    { name: "Soul", meaning: "Spirit" },
    { name: "Spirit", meaning: "Essence" },
    { name: "Ghost", meaning: "Dead Spirit" },
    { name: "Wraith", meaning: "Ghost" },
    { name: "Specter", meaning: "Ghost" },
    { name: "Phantom", meaning: "Ghost" },
    { name: "Apparition", meaning: "Ghost" },
    { name: "Poltergeist", meaning: "Noisy Ghost" },
    { name: "Banshee", meaning: "Irish Ghost" },
    { name: "Witch", meaning: "Female Magic User" },
    { name: "Warlock", meaning: "Male Magic User" },
    { name: "Sorcerer", meaning: "Magic User" },
    { name: "Wizard", meaning: "Wise Magic User" },
    { name: "Mage", meaning: "Learned Magic User" },
    { name: "Enchanter", meaning: "Magic User" },
    { name: "Spellcaster", meaning: "Magic User" },
    { name: "Conjurer", meaning: "Summoner" },
    { name: "Illusionist", meaning: "Trickster" },
    { name: "Diviner", meaning: "Seer" },
    { name: "Prophet", meaning: "Future Seer" },
    { name: "Oracle", meaning: "Prophet" },
    { name: "Seer", meaning: "Visionary" },
    { name: "Mystic", meaning: "Mysterious" },
    { name: "Occultist", meaning: "Secret Knowledge" },
    { name: "Esoteric", meaning: "Secret" },
    { name: "Arcane", meaning: "Mysterious" },
    { name: "Mystery", meaning: "Unknown" },
    { name: "Secret", meaning: "Hidden" },
    { name: "Hidden", meaning: "Concealed" },
    { name: "Occult", meaning: "Secret" },
    { name: "Dark", meaning: "Shadowy" },
    { name: "Black", meaning: "Dark Color" },
    { name: "Shadow", meaning: "Dark Shape" },
    { name: "Gloom", meaning: "Darkness" },
    { name: "Dread", meaning: "Fear" },
    { name: "Fear", meaning: "Afraid" },
    { name: "Terror", meaning: "Great Fear" },
    { name: "Horror", meaning: "Fear" },
    { name: "Nightmare", meaning: "Bad Dream" },
    { name: "Nightmarish", meaning: "Like a Nightmare" },
    { name: "Sinister", meaning: "Evil" },
    { name: "Evil", meaning: "Bad" },
    { name: "Malevolent", meaning: "Wishing Evil" },
    { name: "Malicious", meaning: "Hateful" },
    { name: "Diabolical", meaning: "Devilish" },
    { name: "Demonic", meaning: "Like a Demon" },
    { name: "Hellish", meaning: "Like Hell" },
    { name: "Infernal", meaning: "Hellish" },
    { name: "Damned", meaning: "Condemned" },
    { name: "Cursed", meaning: "Hexed" },
    { name: "Doomed", meaning: "Fated to Die" },
    { name: "Destined", meaning: "Fated" },
    { name: "Fated", meaning: "Destined" },
    { name: "Predestined", meaning: "Fated" },
    { name: "Foreordained", meaning: "Fated" },
    { name: "Chosen", meaning: "Selected" },
    { name: "Elected", meaning: "Chosen" },
    { name: "Selected", meaning: "Chosen" },
    { name: "Picked", meaning: "Chosen" },
    { name: "Chosen One", meaning: "Special One" },
    { name: "Savior", meaning: "Rescuer" },
    { name: "Messiah", meaning: "Savior" },
    { name: "Redeemer", meaning: "Saver" },
    { name: "Deliverer", meaning: "Saver" },
    { name: "Hero", meaning: "Brave One" },
    { name: "Champion", meaning: "Winner" },
    { name: "Victory", meaning: "Win" },
    { name: "Triumph", meaning: "Victory" },
    { name: "Conqueror", meaning: "Winner" },
    { name: "Vanquisher", meaning: "Winner" },
    { name: "Master", meaning: "Ruler" },
    { name: "Lord", meaning: "Master" },
    { name: "King", meaning: "Ruler" },
    { name: "Emperor", meaning: "Great Ruler" },
    { name: "Sovereign", meaning: "Ruler" },
    { name: "Monarch", meaning: "Ruler" },
    { name: "Prince", meaning: "King's Son" },
    { name: "Duke", meaning: "Noble" },
    { name: "Earl", meaning: "Noble" },
    { name: "Baron", meaning: "Noble" },
    { name: "Count", meaning: "Noble" },
    { name: "Viscount", meaning: "Noble" },
    { name: "Marquis", meaning: "Noble" },
    { name: "Lord", meaning: "Noble" },
    { name: "Sir", meaning: "Knight" },
    { name: "Knight", meaning: "Warrior" },
    { name: "Paladin", meaning: "Holy Warrior" },
    { name: "Crusader", meaning: "Holy Warrior" },
    { name: "Templar", meaning: "Holy Warrior" },
    { name: "Crusader", meaning: "Fighter" },
    { name: "Warrior", meaning: "Fighter" },
    { name: "Soldier", meaning: "Fighter" },
    { name: "Fighter", meaning: "Warrior" },
    { name: "Combatant", meaning: "Fighter" },
    { name: "Gladiator", meaning: "Arena Fighter" },
    { name: "Battler", meaning: "Fighter" },
    { name: "Challenger", meaning: "Fighter" },
    { name: "Opponent", meaning: "Enemy" },
    { name: "Enemy", meaning: "Opponent" },
    { name: "Foe", meaning: "Enemy" },
    { name: "Adversary", meaning: "Enemy" },
    { name: "Antagonist", meaning: "Enemy" },
    { name: "Villain", meaning: "Bad Guy" },
    { name: "Bad Guy", meaning: "Villain" },
    { name: "Evil One", meaning: "Bad One" },
    { name: "Dark Lord", meaning: "Evil Ruler" },
    { name: "Dark Master", meaning: "Evil Master" },
    { name: "Dark Lord", meaning: "Evil Lord" },
    { name: "Overlord", meaning: "Ruler" },
    { name: "Despot", meaning: "Tyrant" },
    { name: "Tyrant", meaning: "Cruel Ruler" },
    { name: "Dictator", meaning: "Absolute Ruler" },
    { name: "Autocrat", meaning: "Absolute Ruler" },
    { name: "Monarch", meaning: "Ruler" },
    { name: "Ruler", meaning: "Leader" },
    { name: "Leader", meaning: "Guide" },
    { name: "Guide", meaning: "Leader" },
    { name: "Mentor", meaning: "Teacher" },
    { name: "Teacher", meaning: "Educator" },
    { name: "Educator", meaning: "Teacher" },
    { name: "Master", meaning: "Teacher" },
    { name: "Sage", meaning: "Wise One" },
    { name: "Wise One", meaning: "Sage" },
    { name: "Scholar", meaning: "Learned One" },
    { name: "Learned One", meaning: "Scholar" },
    { name: "Academic", meaning: "Scholar" },
    { name: "Professor", meaning: "Teacher" },
    { name: "Doctor", meaning: "Learned One" },
    { name: "PhD", meaning: "Doctor" },
    { name: "Expert", meaning: "Knowledgeable" },
    { name: "Authority", meaning: "Expert" },
    { name: "Specialist", meaning: "Expert" },
    { name: "Professional", meaning: "Expert" },
    { name: "Veteran", meaning: "Experienced" },
    { name: "Experienced", meaning: "Knowledgeable" },
    { name: "Knowledgeable", meaning: "Smart" },
    { name: "Smart", meaning: "Intelligent" },
    { name: "Intelligent", meaning: "Smart" },
    { name: "Brilliant", meaning: "Very Smart" },
    { name: "Genius", meaning: "Very Smart" },
    { name: "Clever", meaning: "Smart" },
    { name: "Witty", meaning: "Clever" },
    { name: "Shrewd", meaning: "Clever" },
    { name: "Astute", meaning: "Clever" },
    { name: "Perceptive", meaning: "Aware" },
    { name: "Aware", meaning: "Conscious" },
    { name: "Conscious", meaning: "Aware" },
    { name: "Awake", meaning: "Not Sleeping" },
    { name: "Alert", meaning: "Aware" },
    { name: "Vigilant", meaning: "Watchful" },
    { name: "Watchful", meaning: "Alert" },
    { name: "Observant", meaning: "Watchful" },
    { name: "Attentive", meaning: "Watchful" },
    { name: "Careful", meaning: "Watchful" },
    { name: "Cautious", meaning: "Careful" },
    { name: "Prudent", meaning: "Careful" },
    { name: "Wary", meaning: "Careful" },
    { name: "Suspicious", meaning: "Distrustful" },
    { name: "Distrustful", meaning: "Suspicious" },
    { name: "Paranoid", meaning: "Very Suspicious" },
    { name: "Fearful", meaning: "Afraid" },
    { name: "Timid", meaning: "Shy" },
    { name: "Shy", meaning: "Timid" },
    { name: "Introverted", meaning: "Shy" },
    { name: "Reserved", meaning: "Shy" },
    { name: "Quiet", meaning: "Not Loud" },
    { name: "Silent", meaning: "Not Speaking" },
    { name: "Mute", meaning: "Cannot Speak" },
    { name: "Speechless", meaning: "Cannot Speak" },
    { name: "Taciturn", meaning: "Quiet" },
    { name: "Reticent", meaning: "Quiet" },
    { name: "Uncommunicative", meaning: "Quiet" },
    { name: "Withdrawn", meaning: "Quiet" },
    { name: "Solitary", meaning: "Alone" },
    { name: "Alone", meaning: "By Oneself" },
    { name: "Lonely", meaning: "Alone" },
    { name: "Isolated", meaning: "Alone" },
    { name: "Reclusive", meaning: "Alone" },
    { name: "Hermit", meaning: "Alone" },
    { name: "Solitude", meaning: "Alone" },
    { name: "Secluded", meaning: "Alone" },
    { name: "Remote", meaning: "Far Away" },
    { name: "Far", meaning: "Distant" },
    { name: "Distant", meaning: "Far" },
    { name: "Faraway", meaning: "Far" },
    { name: "Distant", meaning: "Remote" },
    { name: "Remote", meaning: "Isolated" },
    { name: "Isolated", meaning: "Separate" },
    { name: "Separate", meaning: "Apart" },
    { name: "Apart", meaning: "Separated" },
    { name: "Divided", meaning: "Separated" },
    { name: "Split", meaning: "Separated" },
    { name: "Broken", meaning: "Not Whole" },
    { name: "Shattered", meaning: "Broken" },
    { name: "Fractured", meaning: "Broken" },
    { name: "Cracked", meaning: "Broken" },
    { name: "Damaged", meaning: "Broken" },
    { name: "Ruined", meaning: "Destroyed" },
    { name: "Destroyed", meaning: "Ruined" },
    { name: "Demolished", meaning: "Destroyed" },
    { name: "Razed", meaning: "Destroyed" },
    { name: "Devastated", meaning: "Destroyed" },
    { name: "Wrecked", meaning: "Destroyed" },
    { name: "Smashed", meaning: "Destroyed" },
    { name: "Crushed", meaning: "Destroyed" },
    { name: "Pulverized", meaning: "Destroyed" },
    { name: "Annihilated", meaning: "Destroyed" },
    { name: "Erased", meaning: "Destroyed" },
    { name: "Eliminated", meaning: "Destroyed" },
    { name: "Exterminated", meaning: "Destroyed" },
    { name: "Extinguished", meaning: "Destroyed" },
    { name: "Vanished", meaning: "Disappeared" },
    { name: "Disappeared", meaning: "Gone" },
    { name: "Gone", meaning: "Not Present" },
    { name: "Missing", meaning: "Not Present" },
    { name: "Lost", meaning: "Missing" },
    { name: "Absent", meaning: "Not Present" },
    { name: "Absentee", meaning: "Absent" },
    { name: "Missing Person", meaning: "Lost" },
    { name: "Lost Soul", meaning: "Missing Spirit" },
    { name: "Ghost", meaning: "Lost Spirit" },
    { name: "Spirit", meaning: "Soul" },
    { name: "Soul", meaning: "Spirit" },
    { name: "Essence", meaning: "Core" },
    { name: "Core", meaning: "Center" },
    { name: "Center", meaning: "Middle" },
    { name: "Middle", meaning: "Center" },
    { name: "Heart", meaning: "Center" },
    { name: "Mind", meaning: "Thoughts" },
    { name: "Thoughts", meaning: "Ideas" },
    { name: "Ideas", meaning: "Thoughts" },
    { name: "Concepts", meaning: "Ideas" },
    { name: "Notions", meaning: "Ideas" },
    { name: "Thought", meaning: "Idea" },
    { name: "Idea", meaning: "Thought" },
    { name: "Plan", meaning: "Idea" },
    { name: "Scheme", meaning: "Plan" },
    { name: "Plot", meaning: "Plan" },
    { name: "Design", meaning: "Plan" },
    { name: "Strategy", meaning: "Plan" },
    { name: "Tactic", meaning: "Plan" },
    { name: "Method", meaning: "Plan" },
    { name: "Approach", meaning: "Plan" },
    { name: "Way", meaning: "Method" },
    { name: "Path", meaning: "Way" },
    { name: "Route", meaning: "Way" },
    { name: "Road", meaning: "Way" },
    { name: "Street", meaning: "Way" },
    { name: "Avenue", meaning: "Way" },
    { name: "Boulevard", meaning: "Way" },
    { name: "Lane", meaning: "Way" },
    { name: "Drive", meaning: "Way" },
    { name: "Place", meaning: "Location" },
    { name: "Location", meaning: "Place" },
    { name: "Position", meaning: "Place" },
    { name: "Site", meaning: "Place" },
    { name: "Spot", meaning: "Place" },
    { name: "Point", meaning: "Place" },
    { name: "Area", meaning: "Place" },
    { name: "Region", meaning: "Place" },
    { name: "Zone", meaning: "Place" },
    { name: "Territory", meaning: "Place" },
    { name: "Land", meaning: "Place" },
    { name: "Ground", meaning: "Place" },
    { name: "Earth", meaning: "Planet" },
    { name: "World", meaning: "Planet" },
    { name: "Planet", meaning: "World" },
    { name: "Globe", meaning: "World" },
    { name: "Sphere", meaning: "World" },
    { name: "Orb", meaning: "Sphere" },
    { name: "Ball", meaning: "Sphere" },
    { name: "Circle", meaning: "Round" },
    { name: "Round", meaning: "Circle" },
    { name: "Circular", meaning: "Round" },
    { name: "Ring", meaning: "Circle" },
    { name: "Loop", meaning: "Circle" },
    { name: "Cycle", meaning: "Circle" },
    { name: "Cycle", meaning: "Loop" },
    { name: "Cycle", meaning: "Round" },
    { name: "Circle of Life", meaning: "Life Cycle" },
    { name: "Life Cycle", meaning: "Birth to Death" },
    { name: "Birth", meaning: "Start of Life" },
    { name: "Death", meaning: "End of Life" },
    { name: "Rebirth", meaning: "New Life" },
    { name: "Reincarnation", meaning: "Rebirth" },
    { name: "Transmigration", meaning: "Rebirth" },
    { name: "Resurrection", meaning: "Come Back" },
    { name: "Risen", meaning: "Come Back" },
    { name: "Undead", meaning: "Not Dead" },
    { name: "Living Dead", meaning: "Undead" },
    { name: "Zombie", meaning: "Living Dead" },
    { name: "Walking Dead", meaning: "Zombie" },
    { name: "Corpse", meaning: "Dead Body" },
    { name: "Dead", meaning: "Not Alive" },
    { name: "Deceased", meaning: "Dead" },
    { name: "Departed", meaning: "Dead" },
    { name: "Late", meaning: "Dead" },
    { name: "Passed Away", meaning: "Dead" },
    { name: "Gone", meaning: "Dead" },
    { name: "Lost", meaning: "Dead" },
    { name: "Perished", meaning: "Dead" },
    { name: "Slain", meaning: "Killed" },
    { name: "Killed", meaning: "Dead" },
    { name: "Murdered", meaning: "Killed" },
    { name: "Assassinated", meaning: "Killed" },
    { name: "Executed", meaning: "Killed" },
    { name: "Slaughtered", meaning: "Killed" },
    { name: "Butchered", meaning: "Killed" },
    { name: "Massacred", meaning: "Killed" },
    { name: "Annihilated", meaning: "Killed" },
    { name: "Eliminated", meaning: "Killed" },
    { name: "Destroyed", meaning: "Killed" },
    { name: "Wiped Out", meaning: "Killed" },
    { name: "Eradicated", meaning: "Killed" },
    { name: "Exterminated", meaning: "Killed" },
    { name: "Extinguished", meaning: "Killed" },
    { name: "Snuffed Out", meaning: "Killed" },
    { name: "Cut Down", meaning: "Killed" },
    { name: "Taken", meaning: "Killed" },
    { name: "Taken Away", meaning: "Killed" },
    { name: "Taken from Us", meaning: "Killed" },
    { name: "Lost to Us", meaning: "Killed" },
    { name: "Gone Forever", meaning: "Killed" },
    { name: "Never to Return", meaning: "Killed" },
    { name: "Eternal Rest", meaning: "Dead" },
    { name: "Rest in Peace", meaning: "Dead" },
    { name: "RIP", meaning: "Dead" },
    { name: "In Memoriam", meaning: "Dead" },
    { name: "Memorial", meaning: "Remember" },
    { name: "Memory", meaning: "Remember" },
    { name: "Remember", meaning: "Recall" },
    { name: "Recall", meaning: "Remember" },
    { name: "Remembrance", meaning: "Memory" },
    { name: "Memories", meaning: "Recollections" },
    { name: "Recollections", meaning: "Memories" },
    { name: "Thoughts", meaning: "Memories" },
    { name: "Mind", meaning: "Thoughts" },
    { name: "Brain", meaning: "Thoughts" },
    { name: "Head", meaning: "Brain" },
    { name: "Skull", meaning: "Head" },
    { name: "Cranium", meaning: "Skull" },
    { name: "Bone", meaning: "Skeleton" },
    { name: "Skeleton", meaning: "Bones" },
    { name: "Frame", meaning: "Skeleton" },
    { name: "Structure", meaning: "Frame" },
    { name: "Form", meaning: "Shape" },
    { name: "Shape", meaning: "Form" },
    { name: "Appearance", meaning: "Form" },
    { name: "Look", meaning: "Appearance" },
    { name: "Visage", meaning: "Face" },
    { name: "Face", meaning: "Visage" },
    { name: "Countenance", meaning: "Face" },
    { name: "Expression", meaning: "Face" },
    { name: "Mien", meaning: "Expression" },
    { name: "Demeanor", meaning: "Expression" },
    { name: "Presence", meaning: "Feeling" },
    { name: "Aura", meaning: "Presence" },
    { name: "Vibe", meaning: "Feeling" },
    { name: "Feeling", meaning: "Emotion" },
    { name: "Emotion", meaning: "Feeling" },
    { name: "Mood", meaning: "Feeling" },
    { name: "Sentiment", meaning: "Feeling" },
    { name: "Sensation", meaning: "Feeling" },
    { name: "Feeling", meaning: "Sensation" },
    { name: "Touch", meaning: "Sensation" },
    { name: "Sense", meaning: "Feeling" },
    { name: "Perception", meaning: "Sense" },
    { name: "Awareness", meaning: "Perception" },
    { name: "Consciousness", meaning: "Awareness" },
    { name: "Mind", meaning: "Consciousness" },
    { name: "Spirit", meaning: "Consciousness" },
    { name: "Soul", meaning: "Spirit" },
    { name: "Ghost", meaning: "Soul" },
    { name: "Wraith", meaning: "Ghost" },
    { name: "Specter", meaning: "Ghost" },
    { name: "Phantom", meaning: "Ghost" },
    { name: "Apparition", meaning: "Ghost" },
    { name: "Shadow", meaning: "Ghost" },
    { name: "Silhouette", meaning: "Shadow" },
    { name: "Outline", meaning: "Silhouette" },
    { name: "Shape", meaning: "Outline" },
    { name: "Form", meaning: "Shape" },
    { name: "Figure", meaning: "Shape" },
    { name: "Image", meaning: "Figure" },
    { name: "Picture", meaning: "Image" },
    { name: "Portrait", meaning: "Picture" },
    { name: "Painting", meaning: "Picture" },
    { name: "Art", meaning: "Painting" },
    { name: "Creation", meaning: "Art" },
    { name: "Work", meaning: "Creation" },
    { name: "Piece", meaning: "Work" },
    { name: "Masterpiece", meaning: "Great Work" },
    { name: "Great Work", meaning: "Masterpiece" },
    { name: "Magnum Opus", meaning: "Masterpiece" },
    { name: "Opus", meaning: "Work" },
    { name: "Composition", meaning: "Work" },
    { name: "Creation", meaning: "Work" },
    { name: "Product", meaning: "Creation" },
    { name: "Result", meaning: "Product" },
    { name: "Outcome", meaning: "Result" },
    { name: "Consequence", meaning: "Result" },
    { name: "Effect", meaning: "Result" },
    { name: "Impact", meaning: "Effect" },
    { name: "Influence", meaning: "Impact" },
    { name: "Power", meaning: "Influence" },
    { name: "Strength", meaning: "Power" },
    { name: "Force", meaning: "Power" },
    { name: "Energy", meaning: "Power" },
    { name: "Vitality", meaning: "Energy" },
    { name: "Life", meaning: "Vitality" },
    { name: "Living", meaning: "Life" },
    { name: "Alive", meaning: "Living" },
    { name: "Breathing", meaning: "Alive" },
    { name: "Conscious", meaning: "Alive" },
    { name: "Awake", meaning: "Conscious" },
    { name: "Aware", meaning: "Awake" },
    { name: "Present", meaning: "Aware" },
    { name: "Here", meaning: "Present" },
    { name: "Existing", meaning: "Here" },
    { name: "Being", meaning: "Existing" },
    { name: "Entity", meaning: "Being" },
    { name: "Thing", meaning: "Entity" },
    { name: "Object", meaning: "Thing" },
    { name: "Item", meaning: "Object" },
    { name: "Article", meaning: "Item" },
    { name: "Piece", meaning: "Item" },
    { name: "Unit", meaning: "Piece" },
    { name: "Element", meaning: "Piece" },
    { name: "Component", meaning: "Piece" },
    { name: "Part", meaning: "Component" },
    { name: "Portion", meaning: "Part" },
    { name: "Section", meaning: "Part" },
    { name: "Segment", meaning: "Part" },
    { name: "Fragment", meaning: "Part" },
    { name: "Bit", meaning: "Small Part" },
    { name: "Piece", meaning: "Bit" },
    { name: "Chunk", meaning: "Bit" },
    { name: "Block", meaning: "Chunk" },
    { name: "Mass", meaning: "Block" },
    { name: "Body", meaning: "Mass" },
    { name: "Structure", meaning: "Body" },
    { name: "Frame", meaning: "Structure" },
    { name: "Skeleton", meaning: "Frame" },
    { name: "Bones", meaning: "Skeleton" },
    { name: "Remains", meaning: "Bones" },
    { name: "Corpse", meaning: "Remains" },
    { name: "Dead Body", meaning: "Corpse" },
    { name: "Cadaver", meaning: "Dead Body" },
    { name: "Stiff", meaning: "Dead Body" },
    { name: "Rigor Mortis", meaning: "Stiff" },
    { name: "Death Stiffness", meaning: "Rigor Mortis" },
    { name: "Cold", meaning: "Dead" },
    { name: "Cold as Ice", meaning: "Dead" },
    { name: "Stone Cold", meaning: "Dead" },
    { name: "Dead Cold", meaning: "Dead" },
    { name: "Pale", meaning: "Dead" },
    { name: "Ashen", meaning: "Pale" },
    { name: "Gray", meaning: "Pale" },
    { name: "Grey", meaning: "Pale" },
    { name: "Wan", meaning: "Pale" },
    { name: "Pallid", meaning: "Pale" },
    { name: "Sallow", meaning: "Pale" },
    { name: "Yellowish", meaning: "Sallow" },
    { name: "Jaundiced", meaning: "Yellowish" },
    { name: "Greenish", meaning: "Sick" },
    { name: "Sickly", meaning: "Greenish" },
    { name: "Unhealthy", meaning: "Sickly" },
    { name: "Ill", meaning: "Unhealthy" },
    { name: "Sick", meaning: "Ill" },
    { name: "Diseased", meaning: "Sick" },
    { name: "Ailing", meaning: "Sick" },
    { name: "Infirm", meaning: "Sick" },
    { name: "Weak", meaning: "Infirm" },
    { name: "Feeble", meaning: "Weak" },
    { name: "Frail", meaning: "Weak" },
    { name: "Delicate", meaning: "Weak" },
    { name: "Fragile", meaning: "Weak" },
    { name: "Brittle", meaning: "Weak" },
    { name: "Breakable", meaning: "Weak" },
    { name: "Fragile", meaning: "Breakable" },
    { name: "Tender", meaning: "Fragile" },
    { name: "Soft", meaning: "Tender" },
    { name: "Gentle", meaning: "Soft" },
    { name: "Mild", meaning: "Gentle" },
    { name: "Kind", meaning: "Gentle" },
    { name: "Nice", meaning: "Kind" },
    { name: "Good", meaning: "Nice" },
    { name: "Fine", meaning: "Good" },
    { name: "Well", meaning: "Good" },
    { name: "Excellent", meaning: "Well" },
    { name: "Great", meaning: "Excellent" },
    { name: "Wonderful", meaning: "Great" },
    { name: "Amazing", meaning: "Wonderful" },
    { name: "Awesome", meaning: "Amazing" },
    { name: "Fantastic", meaning: "Awesome" },
    { name: "Incredible", meaning: "Fantastic" },
    { name: "Unbelievable", meaning: "Incredible" },
    { name: "Impossible", meaning: "Unbelievable" },
    { name: "Unreal", meaning: "Impossible" },
    { name: "Surreal", meaning: "Unreal" },
    { name: "Dreamlike", meaning: "Surreal" },
    { name: "Fantasy", meaning: "Dreamlike" },
    { name: "Imagination", meaning: "Fantasy" },
    { name: "Fancy", meaning: "Imagination" },
    { name: "Whim", meaning: "Fancy" },
    { name: "Caprice", meaning: "Whim" },
    { name: "Mood", meaning: "Caprice" },
    { name: "Temperament", meaning: "Mood" },
    { name: "Disposition", meaning: "Temperament" },
    { name: "Nature", meaning: "Disposition" },
    { name: "Character", meaning: "Nature" },
    { name: "Personality", meaning: "Character" },
    { name: "Self", meaning: "Personality" },
    { name: "Identity", meaning: "Self" },
    { name: "Whole", meaning: "Self" },
    { name: "Complete", meaning: "Whole" },
    { name: "Entire", meaning: "Complete" },
    { name: "Full", meaning: "Entire" },
    { name: "Total", meaning: "Full" },
    { name: "All", meaning: "Total" },
    { name: "Everything", meaning: "All" },
    { name: "Every", meaning: "Everything" },
    { name: "Each", meaning: "Every" },
    { name: "Individual", meaning: "Each" },
    { name: "Single", meaning: "Individual" },
    { name: "One", meaning: "Single" },
    { name: "Solitary", meaning: "One" },
    { name: "Alone", meaning: "Solitary" },
    { name: "Lonely", meaning: "Alone" },
    { name: "Isolated", meaning: "Lonely" },
    { name: "Remote", meaning: "Isolated" },
    { name: "Distant", meaning: "Remote" },
    { name: "Far", meaning: "Distant" },
    { name: "Faraway", meaning: "Far" },
    { name: "Far Off", meaning: "Faraway" },
    { name: "Out of Reach", meaning: "Far Off" },
    { name: "Unattainable", meaning: "Out of Reach" },
    { name: "Impossible", meaning: "Unattainable" },
    { name: "Hopeless", meaning: "Impossible" },
    { name: "Despair", meaning: "Hopeless" },
    { name: "Desperate", meaning: "Hopeless" },
    { name: "Hopelessness", meaning: "Despair" },
    { name: "Misery", meaning: "Hopelessness" },
    { name: "Woe", meaning: "Misery" },
    { name: "Sorrow", meaning: "Woe" },
    { name: "Grief", meaning: "Sorrow" },
    { name: "Mourning", meaning: "Grief" },
    { name: "Lament", meaning: "Mourning" },
    { name: "Weeping", meaning: "Lament" },
    { name: "Crying", meaning: "Weeping" },
    { name: "Tears", meaning: "Crying" },
    { name: "Sadness", meaning: "Tears" },
    { name: "Unhappiness", meaning: "Sadness" },
    { name: "Sorrow", meaning: "Unhappiness" },
    { name: "Gloom", meaning: "Sorrow" },
    { name: "Melancholy", meaning: "Gloom" },
    { name: "Depression", meaning: "Melancholy" },
    { name: "Despondency", meaning: "Depression" },
    { name: "Dejection", meaning: "Despondency" },
    { name: "Discouragement", meaning: "Dejection" },
    { name: "Disheartenment", meaning: "Discouragement" },
    { name: "Hopelessness", meaning: "Disheartenment" },
    { name: "Helplessness", meaning: "Hopelessness" },
    { name: "Powerlessness", meaning: "Helplessness" },
    { name: "Inability", meaning: "Powerlessness" },
    { name: "Incapacity", meaning: "Inability" },
    { name: "Incompetence", meaning: "Incapacity" },
    { name: "Inadequacy", meaning: "Incompetence" },
    { name: "Insufficiency", meaning: "Inadequacy" },
    { name: "Deficiency", meaning: "Insufficiency" },
    { name: "Shortage", meaning: "Deficiency" },
    { name: "Lack", meaning: "Shortage" },
    { name: "Absence", meaning: "Lack" },
    { name: "Want", meaning: "Absence" },
    { name: "Need", meaning: "Want" },
    { name: "Requirement", meaning: "Need" },
    { name: "Demand", meaning: "Requirement" },
    { name: "Desire", meaning: "Demand" },
    { name: "Wish", meaning: "Desire" },
    { name: "Hope", meaning: "Wish" },
    { name: "Expectation", meaning: "Hope" },
    { name: "Anticipation", meaning: "Expectation" },
    { name: "Looking Forward", meaning: "Anticipation" },
    { name: "Excitement", meaning: "Looking Forward" },
    { name: "Eagerness", meaning: "Excitement" },
    { name: "Enthusiasm", meaning: "Eagerness" },
    { name: "Zeal", meaning: "Enthusiasm" },
    { name: "Passion", meaning: "Zeal" },
    { name: "Ardor", meaning: "Passion" },
    { name: "Fervor", meaning: "Ardor" },
    { name: "Intensity", meaning: "Fervor" },
    { name: "Strength", meaning: "Intensity" },
    { name: "Power", meaning: "Strength" },
    { name: "Force", meaning: "Power" },
    { name: "Energy", meaning: "Force" },
    { name: "Drive", meaning: "Energy" },
    { name: "Motivation", meaning: "Drive" },
    { name: "Inspiration", meaning: "Motivation" },
    { name: "Encouragement", meaning: "Inspiration" },
    { name: "Support", meaning: "Encouragement" },
    { name: "Help", meaning: "Support" },
    { name: "Assistance", meaning: "Help" },
    { name: "Aid", meaning: "Assistance" },
    { name: "Relief", meaning: "Aid" },
    { name: "Comfort", meaning: "Relief" },
    { name: "Solace", meaning: "Comfort" },
    { name: "Consolation", meaning: "Solace" },
    { name: "Reassurance", meaning: "Consolation" },
    { name: "Security", meaning: "Reassurance" },
    { name: "Safety", meaning: "Security" },
    { name: "Protection", meaning: "Safety" },
    { name: "Guardianship", meaning: "Protection" },
    { name: "Care", meaning: "Guardianship" },
    { name: "Concern", meaning: "Care" },
    { name: "Interest", meaning: "Concern" },
    { name: "Attention", meaning: "Interest" },
    { name: "Focus", meaning: "Attention" },
    { name: "Concentration", meaning: "Focus" },
    { name: "Intensity", meaning: "Concentration" },
    { name: "Depth", meaning: "Intensity" },
    { name: "Profundity", meaning: "Depth" },
    { name: "Wisdom", meaning: "Profundity" },
    { name: "Knowledge", meaning: "Wisdom" },
    { name: "Understanding", meaning: "Knowledge" },
    { name: "Comprehension", meaning: "Understanding" },
    { name: "Insight", meaning: "Comprehension" },
    { name: "Perception", meaning: "Insight" },
    { name: "Awareness", meaning: "Perception" },
    { name: "Consciousness", meaning: "Awareness" },
    { name: "Mindfulness", meaning: "Consciousness" },
    { name: "Presence", meaning: "Mindfulness" },
    { name: "Attention", meaning: "Presence" },
    { name: "Alertness", meaning: "Attention" },
    { name: "Vigilance", meaning: "Alertness" },
    { name: "Watchfulness", meaning: "Vigilance" },
    { name: "Caution", meaning: "Watchfulness" },
    { name: "Prudence", meaning: "Caution" },
    { name: "Wisdom", meaning: "Prudence" },
    { name: "Judgment", meaning: "Wisdom" },
    { name: "Discernment", meaning: "Judgment" },
    { name: "Perception", meaning: "Discernment" },
    { name: "Understanding", meaning: "Perception" },
    { name: "Knowledge", meaning: "Understanding" },
    { name: "Learning", meaning: "Knowledge" },
    { name: "Education", meaning: "Learning" },
    { name: "Training", meaning: "Education" },
    { name: "Instruction", meaning: "Training" },
    { name: "Teaching", meaning: "Instruction" },
    { name: "Schooling", meaning: "Teaching" },
    { name: "Education", meaning: "Schooling" },
    { name: "Scholarship", meaning: "Education" },
    { name: "Academic", meaning: "Scholarship" },
    { name: "Intellectual", meaning: "Academic" },
    { name: "Mental", meaning: "Intellectual" },
    { name: "Cerebral", meaning: "Mental" },
    { name: "Brainy", meaning: "Cerebral" },
    { name: "Smart", meaning: "Brainy" },
    { name: "Intelligent", meaning: "Smart" },
    { name: "Brilliant", meaning: "Intelligent" },
    { name: "Genius", meaning: "Brilliant" },
    { name: "Gifted", meaning: "Genius" },
    { name: "Talented", meaning: "Gifted" },
    { name: "Skilled", meaning: "Talented" },
    { name: "Proficient", meaning: "Skilled" },
    { name: "Expert", meaning: "Proficient" },
    { name: "Master", meaning: "Expert" },
    { name: "Professional", meaning: "Master" },
    { name: "Competent", meaning: "Professional" },
    { name: "Capable", meaning: "Competent" },
    { name: "Able", meaning: "Capable" },
    { name: "Effective", meaning: "Able" },
    { name: "Efficient", meaning: "Effective" },
    { name: "Productive", meaning: "Efficient" },
    { name: "Successful", meaning: "Productive" },
    { name: "Victorious", meaning: "Successful" },
    { name: "Triumphant", meaning: "Victorious" },
    { name: "Winner", meaning: "Triumphant" },
    { name: "Champion", meaning: "Winner" },
    { name: "Hero", meaning: "Champion" },
    { name: "Legend", meaning: "Hero" },
    { name: "Myth", meaning: "Legend" },
    { name: "Fable", meaning: "Myth" },
    { name: "Tale", meaning: "Fable" },
    { name: "Story", meaning: "Tale" },
    { name: "Narrative", meaning: "Story" },
    { name: "Account", meaning: "Narrative" },
    { name: "Chronicle", meaning: "Account" },
    { name: "History", meaning: "Chronicle" },
    { name: "Past", meaning: "History" },
    { name: "Yesterday", meaning: "Past" },
    { name: "Before", meaning: "Yesterday" },
    { name: "Prior", meaning: "Before" },
    { name: "Former", meaning: "Prior" },
    { name: "Previous", meaning: "Former" },
    { name: "Earlier", meaning: "Previous" },
    { name: "Ancient", meaning: "Earlier" },
    { name: "Old", meaning: "Ancient" },
    { name: "Age-Old", meaning: "Old" },
    { name: "Vintage", meaning: "Age-Old" },
    { name: "Antique", meaning: "Vintage" },
    { name: "Primitive", meaning: "Antique" },
    { name: "Primeval", meaning: "Primitive" },
    { name: "Primal", meaning: "Primeval" },
    { name: "Elemental", meaning: "Primal" },
    { name: "Basic", meaning: "Elemental" },
    { name: "Fundamental", meaning: "Basic" },
    { name: "Essential", meaning: "Fundamental" },
    { name: "Core", meaning: "Essential" },
    { name: "Central", meaning: "Core" },
    { name: "Main", meaning: "Central" },
    { name: "Primary", meaning: "Main" },
    { name: "Principal", meaning: "Primary" },
    { name: "Leading", meaning: "Principal" },
    { name: "Foremost", meaning: "Leading" },
    { name: "First", meaning: "Foremost" },
    { name: "Initial", meaning: "First" },
    { name: "Beginning", meaning: "Initial" },
    { name: "Start", meaning: "Beginning" },
    { name: "Origin", meaning: "Start" },
    { name: "Source", meaning: "Origin" },
    { name: "Root", meaning: "Source" },
    { name: "Base", meaning: "Root" },
    { name: "Foundation", meaning: "Base" },
    { name: "Groundwork", meaning: "Foundation" },
    { name: "Underpinning", meaning: "Groundwork" },
    { name: "Support", meaning: "Underpinning" },
    { name: "Backing", meaning: "Support" },
    { name: "Assistance", meaning: "Backing" },
    { name: "Help", meaning: "Assistance" },
    { name: "Aid", meaning: "Help" },
    { name: "Relief", meaning: "Aid" },
    { name: "Succor", meaning: "Relief" },
    { name: "Comfort", meaning: "Succor" },
    { name: "Solace", meaning: "Comfort" },
    { name: "Consolation", meaning: "Solace" },
    { name: "Reassurance", meaning: "Consolation" },
    { name: "Encouragement", meaning: "Reassurance" },
    { name: "Inspiration", meaning: "Encouragement" },
    { name: "Motivation", meaning: "Inspiration" },
    { name: "Drive", meaning: "Motivation" },
    { name: "Ambition", meaning: "Drive" },
    { name: "Aspiration", meaning: "Ambition" },
    { name: "Goal", meaning: "Aspiration" },
    { name: "Target", meaning: "Goal" },
    { name: "Objective", meaning: "Target" },
    { name: "Aim", meaning: "Objective" },
    { name: "Purpose", meaning: "Aim" },
    { name: "Intent", meaning: "Purpose" },
    { name: "Intention", meaning: "Intent" },
    { name: "Plan", meaning: "Intention" },
    { name: "Scheme", meaning: "Plan" },
    { name: "Design", meaning: "Scheme" },
    { name: "Strategy", meaning: "Design" },
    { name: "Tactic", meaning: "Strategy" },
    { name: "Method", meaning: "Tactic" },
    { name: "Way", meaning: "Method" },
    { name: "Approach", meaning: "Way" },
    { name: "Technique", meaning: "Approach" },
    { name: "Skill", meaning: "Technique" },
    { name: "Ability", meaning: "Skill" },
    { name: "Capability", meaning: "Ability" },
    { name: "Capacity", meaning: "Capability" },
    { name: "Potential", meaning: "Capacity" },
    { name: "Possibility", meaning: "Potential" },
    { name: "Opportunity", meaning: "Possibility" },
    { name: "Chance", meaning: "Opportunity" },
    { name: "Luck", meaning: "Chance" },
    { name: "Fortune", meaning: "Luck" },
    { name: "Destiny", meaning: "Fortune" },
    { name: "Fate", meaning: "Destiny" },
    { name: "Kismet", meaning: "Fate" },
    { name: "Providence", meaning: "Kismet" },
    { name: "Divine Will", meaning: "Providence" },
    { name: "God's Plan", meaning: "Divine Will" },
    { name: "Higher Power", meaning: "God's Plan" },
    { name: "Supernatural", meaning: "Higher Power" },
    { name: "Mystical", meaning: "Supernatural" },
    { name: "Occult", meaning: "Mystical" },
    { name: "Esoteric", meaning: "Occult" },
    { name: "Arcane", meaning: "Esoteric" },
    { name: "Secret", meaning: "Arcane" },
    { name: "Hidden", meaning: "Secret" },
    { name: "Concealed", meaning: "Hidden" },
    { name: "Covert", meaning: "Concealed" },
    { name: "Clandestine", meaning: "Covert" },
    { name: "Surreptitious", meaning: "Clandestine" },
    { name: "Stealthy", meaning: "Surreptitious" },
    { name: "Sneaky", meaning: "Stealthy" },
    { name: "Cunning", meaning: "Sneaky" },
    { name: "Crafty", meaning: "Cunning" },
    { name: "Wily", meaning: "Crafty" },
    { name: "Artful", meaning: "Wily" },
    { name: "Sly", meaning: "Artful" },
    { name: "Tricky", meaning: "Sly" },
    { name: "Deceptive", meaning: "Tricky" },
    { name: "Misleading", meaning: "Deceptive" },
    { name: "Beguiling", meaning: "Misleading" },
    { name: "Enticing", meaning: "Beguiling" },
    { name: "Tempting", meaning: "Enticing" },
   { name: "Alluring", meaning: "Tempting" }
];

const femaleNames = [
    { name: "Lilith", meaning: "Night Monster" },
    { name: "Morgana", meaning: "Sea Witch" },
    { name: "Belladonna", meaning: "Beautiful Woman" },
    { name: "Vespera", meaning: "Evening" },
    { name: "Nocturna", meaning: "Night" },
    { name: "Seraphina", meaning: "Fiery Ones" },
    { name: "Luna", meaning: "Moon" },
    { name: "Selene", meaning: "Moon" },
    { name: "Nyx", meaning: "Night" },
    { name: "Hecate", meaning: "Goddess of Witchcraft" },
    { name: "Persephone", meaning: "Bringer of Death" },
    { name: "Demeter", meaning: "Earth Mother" },
    { name: "Hera", meaning: "Queen of Gods" },
    { name: "Athena", meaning: "Wisdom" },
    { name: "Artemis", meaning: "Hunter" },
    { name: "Aphrodite", meaning: "Love" },
    { name: "Hestia", meaning: "Hearth" },
    { name: "Eris", meaning: "Strife" },
    { name: "Nemesis", meaning: "Retribution" },
    { name: "Fury", meaning: "Anger" },
    { name: "Medusa", meaning: "Guardian" },
    { name: "Circe", meaning: "Bird" },
    { name: "Calypso", meaning: "Hidden" },
    { name: "Ariadne", meaning: "Most Holy" },
    { name: "Psyche", meaning: "Soul" },
    { name: "Eurydice", meaning: "Wide Justice" },
    { name: "Andromeda", meaning: "Ruler of Men" },
    { name: "Cassandra", meaning: "Shining" },
    { name: "Helen", meaning: "Light" },
    { name: "Penelope", meaning: "Weaver" },
    { name: "Clotho", meaning: "Spinner" },
    { name: "Lachesis", meaning: "Apportioner" },
    { name: "Atropos", meaning: "Unbending" },
    { name: "Moira", meaning: "Fate" },
    { name: "Norn", meaning: "Fate" },
    { name: "Skuld", meaning: "Future" },
    { name: "Urd", meaning: "Past" },
    { name: "Verdandi", meaning: "Present" },
    { name: "Freya", meaning: "Lady" },
    { name: "Frigga", meaning: "Beloved" },
    { name: "Sif", meaning: "Bride" },
    { name: "Idun", meaning: "Ever Young" },
    { name: "Hel", meaning: "Death" },
    { name: "Skadi", meaning: "Damage" },
    { name: "Sigyn", meaning: "Victory Friend" },
    { name: "Brynhildr", meaning: "Armor Battle" },
    { name: "Gudrun", meaning: "Divine Secret" },
    { name: "Hilda", meaning: "Battle" },
    { name: "Ravenna", meaning: "Raven" },
    { name: "Corvina", meaning: "Raven" },
    { name: "Stella", meaning: "Star" },
    { name: "Astra", meaning: "Star" },
    { name: "Nova", meaning: "New" },
    { name: "Lirael", meaning: "Night Song" },
    { name: "Morrigan", meaning: "Phantom Queen" },
    { name: "Badb", meaning: "Battle Crow" },
    { name: "Macha", meaning: "Battle" },
    { name: "Danu", meaning: "Mother" },
    { name: "Arianrhod", meaning: "Silver Wheel" },
    { name: "Rhiannon", meaning: "Divine Queen" },
    { name: "Blodeuwedd", meaning: "Flower Face" },
    { name: "Ceridwen", meaning: "Blessed" },
    { name: "Bridget", meaning: "Exalted" },
    { name: "Brigid", meaning: "High" },
    { name: "Aine", meaning: "Splendor" },
    { name: "Cliodhna", meaning: "Shapely" },
    { name: "Deirdre", meaning: "Sorrow" },
    { name: "Niamh", meaning: "Bright" },
    { name: "Aoife", meaning: "Radiance" },
    { name: "Grainne", meaning: "Love" },
    { name: "Mairead", meaning: "Pearl" },
    { name: "Siobhan", meaning: "God is Gracious" },
    { name: "Eithne", meaning: "Kernel" },
    { name: "Saoirse", meaning: "Freedom" },
    { name: "Orla", meaning: "Golden Princess" },
    { name: "Una", meaning: "One" },
    { name: "Roisin", meaning: "Little Rose" },
    { name: "Caoimhe", meaning: "Gentle" },
    { name: "Maeve", meaning: "Intoxicating" },
    { name: "Fiona", meaning: "Fair" },
    { name: "Brianna", meaning: "Strong" },
    { name: "Sorcha", meaning: "Bright" },
    { name: "Megan", meaning: "Pearl" },
    { name: "Katie", meaning: "Pure" },
    { name: "Lauren", meaning: "Laurel" },
    { name: "Rachel", meaning: "Ewe" },
    { name: "Sarah", meaning: "Princess" },
    { name: "Emma", meaning: "Universal" },
    { name: "Olivia", meaning: "Olive" },
    { name: "Sophia", meaning: "Wisdom" },
    { name: "Isabella", meaning: "God is My Oath" },
    { name: "Mia", meaning: "Mine" },
    { name: "Ava", meaning: "Birdlike" },
    { name: "Lily", meaning: "Pure" },
    { name: "Zoe", meaning: "Life" },
    { name: "Evelyn", meaning: "Wished for Child" },
    { name: "Abigail", meaning: "Father's Joy" },
    { name: "Emily", meaning: "Industrious" },
    { name: "Harper", meaning: "Harp Player" },
    { name: "Amelia", meaning: "Industrious" },
    { name: "Elizabeth", meaning: "God is My Oath" },
    { name: "Sofia", meaning: "Wisdom" },
    { name: "Madison", meaning: "Son of Maud" },
    { name: "Avery", meaning: "Elf Ruler" },
    { name: "Ella", meaning: "Light" },
    { name: "Scarlett", meaning: "Red" },
    { name: "Victoria", meaning: "Victory" },
    { name: "Grace", meaning: "Elegance" },
    { name: "Chloe", meaning: "Young Green Shoot" },
    { name: "Camila", meaning: "Young Priestess" },
    { name: "Penelope", meaning: "Weaver" },
    { name: "Riley", meaning: "Courageous" },
    { name: "Aria", meaning: "Air" },
    { name: "Luna", meaning: "Moon" },
    { name: "Layla", meaning: "Night" },
    { name: "Mila", meaning: "Gracious" },
    { name: "Nora", meaning: "Honor" },
    { name: "Hazel", meaning: "Light Brown" },
    { name: "Ella", meaning: "Beautiful Fairy Woman" },
    { name: "Ellie", meaning: "Light" },
    { name: "Avery", meaning: "Ruler of Elves" },
    { name: "Sofia", meaning: "Wisdom" },
    { name: "Aurora", meaning: "Dawn" },
    { name: "Savannah", meaning: "Treeless Plain" },
    { name: "Brooklyn", meaning: "Broken Land" },
    { name: "Bella", meaning: "Beautiful" },
    { name: "Claire", meaning: "Clear" },
    { name: "Lucy", meaning: "Light" },
    { name: "Eleanor", meaning: "Light" },
    { name: "Hannah", meaning: "Favor" },
    { name: "Lillian", meaning: "Pure" },
    { name: "Addison", meaning: "Son of Adam" },
    { name: "Aubrey", meaning: "Elf Ruler" },
    { name: "Stella", meaning: "Star" },
    { name: "Natalie", meaning: "Birthday" },
    { name: "Zara", meaning: "Princess" },
    { name: "Leah", meaning: "Delicate" },
    { name: "Audrey", meaning: "Noble Strength" },
    { name: "Eva", meaning: "Life" },
    { name: "Ruby", meaning: "Red Gem" },
    { name: "Lila", meaning: "Night" },
    { name: "Piper", meaning: "Flute Player" },
    { name: "Maya", meaning: "Great" },
    { name: "Avery", meaning: "Elf Counsel" },
    { name: "Isla", meaning: "Island" },
    { name: "Violet", meaning: "Purple" },
    { name: "Mackenzie", meaning: "Child of the Wise Leader" },
    { name: "Madeline", meaning: "High Tower" },
    { name: "Lily", meaning: "Lily Flower" },
    { name: "Charlotte", meaning: "Free Man" },
    { name: "Isabelle", meaning: "God is My Oath" },
    { name: "Emma", meaning: "Whole" },
    { name: "Grace", meaning: "Charm" },
    { name: "Olivia", meaning: "Peace" },
    { name: "Sophie", meaning: "Wisdom" },
    { name: "Chloe", meaning: "Bloom" },
    { name: "Amelia", meaning: "Work" },
    { name: "Mia", meaning: "My" },
    { name: "Lola", meaning: "Sorrow" },
    { name: "Zoe", meaning: "Life" },
    { name: "Ella", meaning: "Fairy Woman" },
    { name: "Ruby", meaning: "Red" },
    { name: "Lily", meaning: "Lily" },
    { name: "Evie", meaning: "Life" },
    { name: "Poppy", meaning: "Red Flower" },
    { name: "Freya", meaning: "Noble" },
    { name: "Ava", meaning: "Bird" },
    { name: "Isla", meaning: "Island" },
    { name: "Mia", meaning: "Mine" },
    { name: "Sophia", meaning: "Wisdom" },
    { name: "Grace", meaning: "Elegance" },
    { name: "Olivia", meaning: "Olive Tree" },
    { name: "Emily", meaning: "Industrious" },
    { name: "Amelia", meaning: "Hardworking" },
    { name: "Isabella", meaning: "Devoted to God" },
    { name: "Victoria", meaning: "Victory" },
    { name: "Charlotte", meaning: "Strong" },
    { name: "Harriet", meaning: "Ruler" },
    { name: "Alice", meaning: "Noble" },
    { name: "Daisy", meaning: "Day's Eye" },
    { name: "Eleanor", meaning: "Light" },
    { name: "Beatrice", meaning: "Happy" },
    { name: "Clara", meaning: "Clear" },
    { name: "Mabel", meaning: "Lovely" },
    { name: "Matilda", meaning: "Mighty" },
    { name: "Ethel", meaning: "Noble" },
    { name: "Agnes", meaning: "Pure" },
    { name: "Edith", meaning: "Rich" },
    { name: "Florence", meaning: "Flowering" },
    { name: "Gertrude", meaning: "Spear Strength" },
    { name: "Hilda", meaning: "Battle" },
    { name: "Ida", meaning: "Hardworking" },
    { name: "Josephine", meaning: "God Will Increase" },
    { name: "Katherine", meaning: "Pure" },
    { name: "Louise", meaning: "Renowned Warrior" },
    { name: "Margaret", meaning: "Pearl" },
    { name: "Nancy", meaning: "Grace" },
    { name: "Olive", meaning: "Olive Tree" },
    { name: "Patricia", meaning: "Noble" },
    { name: "Queenie", meaning: "Queen" },
    { name: "Rachel", meaning: "Ewe" },
    { name: "Sally", meaning: "Princess" },
    { name: "Theresa", meaning: "Reaper" },
    { name: "Ursula", meaning: "Little Bear" },
    { name: "Vera", meaning: "True" },
    { name: "Wendy", meaning: "Friend" },
    { name: "Xenia", meaning: "Hospitality" },
    { name: "Yvonne", meaning: "Yew" },
    { name: "Zelda", meaning: "Gray Fighting Maid" },
    { name: "Anastasia", meaning: "Resurrection" },
    { name: "Beatrice", meaning: "Blessed" },
    { name: "Cecilia", meaning: "Blind" },
    { name: "Diana", meaning: "Divine" },
    { name: "Eugenia", meaning: "Noble" },
    { name: "Francesca", meaning: "Free" },
    { name: "Gabriella", meaning: "God is My Strength" },
    { name: "Henrietta", meaning: "Ruler" },
    { name: "Ivy", meaning: "Climbing Plant" },
    { name: "Jacqueline", meaning: "Supplanter" },
    { name: "Katherine", meaning: "Pure" },
    { name: "Larissa", meaning: "Citadel" },
    { name: "Monica", meaning: "Advisor" },
    { name: "Nicole", meaning: "Victory" },
    { name: "Olivia", meaning: "Olive" },
    { name: "Penelope", meaning: "Weaver" },
    { name: "Quinn", meaning: "Fifth" },
    { name: "Ruth", meaning: "Compassionate" },
    { name: "Serena", meaning: "Calm" },
    { name: "Tessa", meaning: "Harvester" },
    { name: "Una", meaning: "Unity" },
    { name: "Valerie", meaning: "Strong" },
    { name: "Wanda", meaning: "Wanderer" },
    { name: "Xandra", meaning: "Protector" },
    { name: "Yvette", meaning: "Yew" },
    { name: "Zinnia", meaning: "Flower" }
];

let currentMode = 'random';

function shuffleArray(array) {
    const shuffled = [...array];
    for (let i = shuffled.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
    }
    return shuffled;
}

function generateNames() {
    const grid = document.getElementById('namesGrid');
    let pool;
    
    if (currentMode === 'random') {
        pool = shuffleArray([...maleNames, ...femaleNames]);
    } else if (currentMode === 'male') {
        pool = shuffleArray([...maleNames]);
    } else {
        pool = shuffleArray([...femaleNames]);
    }
    
    const selected = pool.slice(0, 16);
    
    grid.innerHTML = selected.map(item => `
        <div class="name-card">
            <div class="name-text">${item.name}</div>
            <div class="name-gender">${currentMode === 'female' ? 'Female' : currentMode === 'male' ? 'Male' : 'Mixed'}</div>
            <div class="name-meaning">${item.meaning}</div>
        </div>
    `).join('');
}

document.querySelectorAll('.mode-btn').forEach(btn => {
    btn.addEventListener('click', function() {
        document.querySelectorAll('.mode-btn').forEach(b => b.classList.remove('active'));
        this.classList.add('active');
        currentMode = this.dataset.mode;
        generateNames();
    });
});

