const maleNames = [
    { name: "Artorias", meaning: "Bearer of the Abyss" },
    { name: "Gwyn", meaning: "Lord of Sunlight" },
    { name: "Ornstein", meaning: "Dragon Slayer" },
    { name: "Smough", meaning: "Royal Executioner" },
    { name: "Siegmeyer", meaning: "Fearless Knight" },
    { name: "Solaire", meaning: "Warrior of Sunlight" },
    { name: "Oscar", meaning: "Knight of Astora" },
    { name: "Andre", meaning: "Blacksmith of Anor Londo" },
    { name: "Nito", meaning: "First of the Dead" },
    { name: "Seath", meaning: "Scaleless Dragon" },
    { name: "Manus", meaning: "Father of the Abyss" },
    { name: "Gwyndolin", meaning: "Dark Sun" },
    { name: "Havel", meaning: "Stone Guardian" },
    { name: "Laurentius", meaning: "Pyromancer" },
    { name: "Griggs", meaning: "Sorcerer of Vinheim" },
    { name: "Logan", meaning: "Big Hat Wizard" },
    { name: "Shiva", meaning: "Dragon Warrior" },
    { name: "Lautrec", meaning: "Sinister Knight" },
    { name: "Hawkwood", meaning: "Deserter Knight" },
    { name: "Sirris", meaning: "Mound-Maker" },
    { name: "Yhorm", meaning: "Giant Lord" },
    { name: "Sulyvahn", meaning: "Pontiff of Irithyll" },
    { name: "Aldrich", meaning: "Devourer of Gods" },
    { name: "Lothric", meaning: "Young Prince" },
    { name: "Lorian", meaning: "Elder Prince" },
    { name: "Gundyr", meaning: "Champion of Ash" },
    { name: "Wolnir", meaning: "High Lord of Undead" },
    { name: "Oceiros", meaning: "Consumed King" },
    { name: "Vordt", meaning: "Beast of Boreal Valley" },
    { name: "Dancer", meaning: "Dancer of Boreal Valley" },
    { name: "Crystal Sage", meaning: "Master of Crystal Magic" },
    { name: "Darkwraith", meaning: "Servant of the Abyss" },
    { name: "Black Knight", meaning: "Fallen Warrior" },
    { name: "Silver Knight", meaning: "Guardian of Anor Londo" },
    { name: "Hollow", meaning: "Lost Soul" },
    { name: "Undead", meaning: "Cursed Being" },
    { name: "Ashen One", meaning: "Bearer of the Flame" },
    { name: "Unkindled", meaning: "One Who Failed" },
    { name: "Tarnished", meaning: "Banished Warrior" },
    { name: "Gravelord", meaning: "Lord of Death" },
    { name: "Necromancer", meaning: "Raiser of the Dead" },
    { name: "Hexer", meaning: "Dark Mage" },
    { name: "Cleric", meaning: "Healer of the Faith" },
    { name: "Paladin", meaning: "Holy Warrior" },
    { name: "Faraam", meaning: "Legendary Warrior" },
    { name: "Velstadt", meaning: "Royal Aegis" },
    { name: "Aldia", meaning: "Royal Scholar" },
    { name: "Vendrick", meaning: "Undead King" },
    { name: "Darklurker", meaning: "Abyss Guardian" },
    { name: "Sinh", meaning: "Slumbering Dragon" },
    { name: "Tyrant", meaning: "Oppressive Ruler" },
    { name: "Gargoyle", meaning: "Stone Guardian" },
    { name: "Hellkite", meaning: "Fire Dragon" },
    { name: "Pinwheel", meaning: "Mad Clown" },
    { name: "Capra Demon", meaning: "Twin-Headed Beast" },
    { name: "Asylum Demon", meaning: "Guardian of the Asylum" },
    { name: "Demon Firesage", meaning: "Master of Fire" },
    { name: "Centipede Demon", meaning: "Hellish Creature" },
    { name: "Four Kings", meaning: "Rulers of New Londo" },
    { name: "Great Grey Wolf", meaning: "Sif, Guardian" },
    { name: "Primal Demon", meaning: "Ancient Evil" },
    { name: "Butcher", meaning: "Carnage Bringer" },
    { name: "Executioner", meaning: "Royal Headsman" },
    { name: "Skeleton", meaning: "Risen Dead" },
    { name: "Ghost", meaning: "Restless Spirit" },
    { name: "Phantom", meaning: "Haunting Presence" },
    { name: "Wraith", meaning: "Vengeful Spirit" },
    { name: "Shade", meaning: "Dark Reflection" },
    { name: "Shadow", meaning: "Darkness Made Flesh" },
    { name: "Dark Lord", meaning: "Master of Darkness" },
    { name: "Lich King", meaning: "Undead Monarch" },
    { name: "Death Knight", meaning: "Knight of the Damned" },
    { name: "Doom Lord", meaning: "Bringer of Destruction" },
    { name: "Dreadnought", meaning: "Fearless Warrior" },
    { name: "Stormcaller", meaning: "Master of Weather" },
    { name: "Bloodletter", meaning: "Bringer of Bloodshed" },
    { name: "Ironclad", meaning: "Unbreakable Warrior" },
    { name: "Void Walker", meaning: "Traveler of Darkness" },
    { name: "Nightmare", meaning: "Living Horror" },
    { name: "Apocalypse", meaning: "End of Days" },
    { name: "Raven", meaning: "Bird of Omens" },
    { name: "Wolf", meaning: "Wild Predator" },
    { name: "Bear", meaning: "Fierce Warrior" },
    { name: "Tiger", meaning: "Striped Hunter" },
    { name: "Lion", meaning: "King of Beasts" },
    { name: "Eagle", meaning: "Sky Warrior" },
    { name: "Viper", meaning: "Deadly Serpent" },
    { name: "Dragon", meaning: "Ancient Beast" },
    { name: "Phoenix", meaning: "Reborn from Ashes" },
    { name: "Griffin", meaning: "Mythical Beast" },
    { name: "Cerberus", meaning: "Three-Headed Hound" },
    { name: "Hydra", meaning: "Many-Headed Monster" },
    { name: "Minotaur", meaning: "Bull-Man" },
    { name: "Golem", meaning: "Stone Guardian" },
    { name: "Behemoth", meaning: "Huge Monster" },
    { name: "Titan", meaning: "Giant of Old" },
    { name: "Colossus", meaning: "Massive Statue" },
    { name: "Warden", meaning: "Guardian of the Gate" },
    { name: "Sentinel", meaning: "Eternal Watcher" },
    { name: "Champion", meaning: "Victorious Warrior" },
    { name: "Conqueror", meaning: "Subduer of Nations" },
    { name: "Warlord", meaning: "Leader of Armies" },
    { name: "Overlord", meaning: "Supreme Ruler" },
    { name: "Emperor", meaning: "Absolute Monarch" },
    { name: "Sovereign", meaning: "Self-Ruler" },
    { name: "Monarch", meaning: "King of Kings" },
    { name: "Protector", meaning: "Guardian of the Weak" },
    { name: "Defender", meaning: "Shield of the People" },
    { name: "Challenger", meaning: "One Who Tests" },
    { name: "Avenger", meaning: "Seeker of Vengeance" },
    { name: "Vindicator", meaning: "Righteous Punisher" },
    { name: "Crusader", meaning: "Holy Warrior" },
    { name: "Inquisitor", meaning: "Hunter of Heretics" },
    { name: "Exorcist", meaning: "Banisher of Evil" },
    { name: "Purifier", meaning: "Cleaner of Corruption" },
    { name: "Redeemer", meaning: "Saver of Souls" },
    { name: "Savior", meaning: "Deliverer from Darkness" },
    { name: "Prophet", meaning: "Seer of Things to Come" },
    { name: "Oracle", meaning: "Speaker of the Gods" },
    { name: "Sage", meaning: "Wise One" },
    { name: "Scholar", meaning: "Learned One" },
    { name: "Lorekeeper", meaning: "Guardian of Knowledge" },
    { name: "Archivist", meaning: "Keeper of Records" },
    { name: "Chronicler", meaning: "Writer of History" },
    { name: "Bard", meaning: "Singer of Tales" },
    { name: "Minstrel", meaning: "Traveling Musician" },
    { name: "Jester", meaning: "Entertainer" },
    { name: "Madman", meaning: "Insane One" },
    { name: "Outcast", meaning: "Banished One" },
    { name: "Wanderer", meaning: "Traveler Without Home" },
    { name: "Nomad", meaning: "Roaming Soul" },
    { name: "Vagabond", meaning: "Homeless Traveler" },
    { name: "Rogue", meaning: "Cunning Thief" },
    { name: "Bandit", meaning: "Lawless Robber" },
    { name: "Pirate", meaning: "Sea Robber" },
    { name: "Assassin", meaning: "Silent Killer" },
    { name: "Hitman", meaning: "Contract Killer" },
    { name: "Slayer", meaning: "Monster Hunter" },
    { name: "Hunter", meaning: "Tracker of Beasts" },
    { name: "Ranger", meaning: "Wanderer of the Woods" },
    { name: "Scout", meaning: "Forward Observer" },
    { name: "Spy", meaning: "Secret Agent" },
    { name: "Mage", meaning: "Master of Magic" },
    { name: "Sorcerer", meaning: "Dark Wizard" },
    { name: "Warlock", meaning: "Dark Mage" },
    { name: "Wizard", meaning: "Learned Mage" },
    { name: "Conjurer", meaning: "Summoner of Spirits" },
    { name: "Enchanter", meaning: "Master of Enchantments" },
    { name: "Illusionist", meaning: "Master of Deception" },
    { name: "Alchemist", meaning: "Master of Transformation" },
    { name: "Artisan", meaning: "Skilled Craftsman" },
    { name: "Smith", meaning: "Metal Worker" },
    { name: "Armorer", meaning: "Maker of Armor" },
    { name: "Weaponsmith", meaning: "Maker of Weapons" },
    { name: "Blacksmith", meaning: "Iron Worker" },
    { name: "Healer", meaning: "Curer of Wounds" },
    { name: "Physician", meaning: "Doctor of the Body" },
    { name: "Herbalist", meaning: "Master of Plants" },
    { name: "Apothecary", meaning: "Maker of Medicines" },
    { name: "Gravekeeper", meaning: "Keeper of the Dead" },
    { name: "Priest", meaning: "Man of the Cloth" },
    { name: "Monk", meaning: "Religious Ascetic" },
    { name: "Abbot", meaning: "Leader of Monastery" },
    { name: "Bishop", meaning: "High Priest" },
    { name: "Cardinal", meaning: "Prince of the Church" },
    { name: "Evangelist", meaning: "Preacher of the Word" },
    { name: "Mercenary", meaning: "Soldier for Hire" },
    { name: "Soldier", meaning: "Fighter for the Crown" },
    { name: "Knight", meaning: "Noble Warrior" },
    { name: "Squire", meaning: "Apprentice Knight" },
    { name: "Sergeant", meaning: "Leader of Men" },
    { name: "Captain", meaning: "Commander of a Company" },
    { name: "Major", meaning: "Officer of Rank" },
    { name: "Colonel", meaning: "Leader of a Regiment" },
    { name: "General", meaning: "Leader of an Army" },
    { name: "Admiral", meaning: "Leader of the Navy" },
    { name: "Commander", meaning: "Leader of Forces" },
    { name: "Strategist", meaning: "Master of War Plans" },
    { name: "Tactician", meaning: "Master of Battle" },
    { name: "Warrior", meaning: "Skilled Fighter" },
    { name: "Gladiator", meaning: "Arena Fighter" },
    { name: "Hero", meaning: "Savior of Many" },
    { name: "Legend", meaning: "Famous Warrior" },
    { name: "Myth", meaning: "Stories of Greatness" },
    { name: "Icon", meaning: "Symbol of Power" },
    { name: "Demigod", meaning: "Half-God Being" },
    { name: "Godslayer", meaning: "Killer of Gods" },
    { name: "Dragon Slayer", meaning: "Killer of Dragons" },
    { name: "Demon Slayer", meaning: "Killer of Demons" },
    { name: "Undead Slayer", meaning: "Killer of the Undead" },
    { name: "Ghost Hunter", meaning: "Hunter of Spirits" },
    { name: "Monster Hunter", meaning: "Hunter of Beasts" },
    { name: "Beast Master", meaning: "Tamer of Creatures" },
    { name: "Falconer", meaning: "Master of Birds" },
    { name: "Horse Master", meaning: "Master of Horses" },
    { name: "Fire Starter", meaning: "Bringer of Flame" },
    { name: "Ice Master", meaning: "Master of Cold" },
    { name: "Storm Master", meaning: "Master of Weather" },
    { name: "Shadow Master", meaning: "Master of Darkness" },
    { name: "Light Master", meaning: "Master of Light" },
    { name: "Life Master", meaning: "Master of Healing" },
    { name: "Death Master", meaning: "Master of Destruction" },
    { name: "Time Master", meaning: "Master of Temporal" },
    { name: "Dream Master", meaning: "Master of Dreams" },
    { name: "Nightmare Master", meaning: "Master of Fear" },
    { name: "Chaos Master", meaning: "Master of Disorder" },
    { name: "Order Master", meaning: "Master of Structure" },
    { name: "Balance Master", meaning: "Master of Equilibrium" },
    { name: "Truth Master", meaning: "Master of Honesty" },
    { name: "Luck Master", meaning: "Master of Fortune" },
    { name: "Fate Master", meaning: "Master of Destiny" },
    { name: "Reality Master", meaning: "Master of Existence" },
    { name: "Space Master", meaning: "Master of Dimension" },
    { name: "War Master", meaning: "Master of Conflict" },
    { name: "Love Master", meaning: "Master of Affection" },
    { name: "Hate Master", meaning: "Master of Loathing" },
    { name: "Joy Master", meaning: "Master of Happiness" },
    { name: "Sorrow Master", meaning: "Master of Sadness" },
    { name: "Anger Master", meaning: "Master of Wrath" },
    { name: "Fear Master", meaning: "Master of Terror" },
    { name: "Courage Master", meaning: "Master of Bravery" },
    { name: "Wisdom Master", meaning: "Master of Knowledge" },
    { name: "Strength Master", meaning: "Master of Power" },
    { name: "Speed Master", meaning: "Master of Quickness" },
    { name: "Beauty Master", meaning: "Master of Aesthetics" },
    { name: "Good", meaning: "Righteous One" },
    { name: "Evil", meaning: "Dark One" },
    { name: "Neutral", meaning: "Balanced One" },
    { name: "Lawful", meaning: "Orderly One" },
    { name: "Chaotic", meaning: "Unpredictable One" },
    { name: "True", meaning: "Honest One" },
    { name: "False", meaning: "Deceptive One" },
    { name: "Pure", meaning: "Uncorrupted One" },
    { name: "Corrupt", meaning: "Tainted One" },
    { name: "Holy", meaning: "Sacred One" },
    { name: "Unholy", meaning: "Damned One" },
    { name: "Divine", meaning: "Godly One" },
    { name: "Demonic", meaning: "Devilish One" },
    { name: "Angelic", meaning: "Angel-like One" },
    { name: "Diabolic", meaning: "Devil-like One" },
    { name: "Celestial", meaning: "Heavenly One" },
    { name: "Infernal", meaning: "Hellish One" },
    { name: "Ethereal", meaning: "Spirit-like One" },
    { name: "Material", meaning: "Physical One" },
    { name: "Spiritual", meaning: "Soulful One" },
    { name: "Mortal", meaning: "Earthly One" },
    { name: "Immortal", meaning: "Undying One" },
    { name: "Eternal", meaning: "Everlasting One" },
    { name: "Temporary", meaning: "Short-Lived One" },
    { name: "Permanent", meaning: "Lasting One" },
    { name: "Transient", meaning: "Passing One" },
    { name: "Enduring", meaning: "Long-Lasting One" },
    { name: "Fleeting", meaning: "Brief One" },
    { name: "Constant", meaning: "Unchanging One" },
    { name: "Variable", meaning: "Changing One" },
    { name: "Stable", meaning: "Steady One" },
    { name: "Unstable", meaning: "Unsteady One" },
    { name: "Reliable", meaning: "Trustworthy One" },
    { name: "Unreliable", meaning: "Untrustworthy One" },
    { name: "Faithful", meaning: "Loyal One" },
    { name: "Faithless", meaning: "Disloyal One" },
    { name: "Loyal", meaning: "True One" },
    { name: "Disloyal", meaning: "False One" },
    { name: "Honest", meaning: "Truthful One" },
    { name: "Dishonest", meaning: "Deceitful One" },
    { name: "Sincere", meaning: "Genuine One" },
    { name: "Insincere", meaning: "Fake One" },
    { name: "Kind", meaning: "Caring One" },
    { name: "Cruel", meaning: "Heartless One" },
    { name: "Gentle", meaning: "Soft One" },
    { name: "Harsh", meaning: "Severe One" },
    { name: "Merciful", meaning: "Forgiving One" },
    { name: "Merciless", meaning: "Unforgiving One" },
    { name: "Compassionate", meaning: "Understanding One" },
    { name: "Unfeeling", meaning: "Cold One" },
    { name: "Generous", meaning: "Giving One" },
    { name: "Greedy", meaning: "Selfish One" },
    { name: "Humble", meaning: "Modest One" },
    { name: "Proud", meaning: "Arrogant One" },
    { name: "Modest", meaning: "Unassuming One" },
    { name: "Boastful", meaning: "Bragging One" },
    { name: "Shy", meaning: "Timid One" },
    { name: "Bold", meaning: "Courageous One" },
    { name: "Timid", meaning: "Fearful One" },
    { name: "Brave", meaning: "Fearless One" },
    { name: "Cowardly", meaning: "Yellow One" },
    { name: "Confident", meaning: "Self-Assured One" },
    { name: "Insecure", meaning: "Unsure One" },
    { name: "Strong", meaning: "Powerful One" },
    { name: "Weak", meaning: "Powerless One" },
    { name: "Smart", meaning: "Intelligent One" },
    { name: "Dumb", meaning: "Stupid One" },
    { name: "Clever", meaning: "Witty One" },
    { name: "Foolish", meaning: "Silly One" },
    { name: "Wise", meaning: "Knowledgeable One" },
    { name: "Ignorant", meaning: "Unknowing One" },
    { name: "Skilled", meaning: "Talented One" },
    { name: "Unskilled", meaning: "Untalented One" },
    { name: "Talented", meaning: "Gifted One" },
    { name: "Creative", meaning: "Imaginative One" },
    { name: "Innovative", meaning: "Inventive One" },
    { name: "Modern", meaning: "Current One" },
    { name: "Progressive", meaning: "Forward-Thinking One" },
    { name: "Radical", meaning: "Extreme One" },
    { name: "Mild", meaning: "Gentle One" },
    { name: "Wild", meaning: "Untamed One" },
    { name: "Tame", meaning: "Domesticated One" },
    { name: "Free", meaning: "Unbound One" },
    { name: "Captive", meaning: "Bound One" },
    { name: "Independent", meaning: "Self-Reliant One" },
    { name: "Dependent", meaning: "Needy One" },
    { name: "Autonomous", meaning: "Self-Governing One" },
    { name: "Subservient", meaning: "Obedient One" },
    { name: "Rebellious", meaning: "Defiant One" },
    { name: "Obedient", meaning: "Compliant One" },
    { name: "Defiant", meaning: "Resistant One" },
    { name: "Compliant", meaning: "Agreeable One" },
    { name: "Resistant", meaning: "Unwilling One" },
    { name: "Willing", meaning: "Ready One" },
    { name: "Eager", meaning: "Excited One" },
    { name: "Reluctant", meaning: "Hesitant One" },
    { name: "Enthusiastic", meaning: "Excited One" },
    { name: "Apathetic", meaning: "Uninterested One" },
    { name: "Interested", meaning: "Curious One" },
    { name: "Uninterested", meaning: "Bored One" },
    { name: "Curious", meaning: "Inquisitive One" },
    { name: "Active", meaning: "Energetic One" },
    { name: "Inactive", meaning: "Sluggish One" },
    { name: "Energetic", meaning: "Vibrant One" },
    { name: "Lethargic", meaning: "Tired One" },
    { name: "Vibrant", meaning: "Alive One" },
    { name: "Dull", meaning: "Boring One" },
    { name: "Exciting", meaning: "Thrilling One" },
    { name: "Boring", meaning: "Dull One" },
    { name: "Thrilling", meaning: "Exciting One" },
    { name: "Mundane", meaning: "Ordinary One" },
    { name: "Extraordinary", meaning: "Special One" },
    { name: "Ordinary", meaning: "Common One" },
    { name: "Special", meaning: "Unique One" },
    { name: "Common", meaning: "Ordinary One" },
    { name: "Unique", meaning: "One of a Kind" },
    { name: "Generic", meaning: "Typical One" },
    { name: "Rare", meaning: "Uncommon One" },
    { name: "Commonplace", meaning: "Everyday One" },
    { name: "Exceptional", meaning: "Outstanding One" },
    { name: "Mediocre", meaning: "Average One" },
    { name: "Outstanding", meaning: "Excellent One" },
    { name: "Poor", meaning: "Bad One" },
    { name: "Excellent", meaning: "Great One" },
    { name: "Terrible", meaning: "Awful One" },
    { name: "Great", meaning: "Wonderful One" },
    { name: "Awful", meaning: "Horrible One" },
    { name: "Wonderful", meaning: "Amazing One" },
    { name: "Horrible", meaning: "Terrible One" },
    { name: "Amazing", meaning: "Incredible One" },
    { name: "Dreadful", meaning: "Frightful One" },
    { name: "Incredible", meaning: "Unbelievable One" },
    { name: "Appalling", meaning: "Shocking One" },
    { name: "Unbelievable", meaning: "Incredible One" },
    { name: "Shocking", meaning: "Surprising One" },
    { name: "Surprising", meaning: "Unexpected One" },
    { name: "Expected", meaning: "Anticipated One" },
    { name: "Unexpected", meaning: "Surprising One" },
    { name: "Anticipated", meaning: "Expected One" },
    { name: "Predictable", meaning: "Expected One" },
    { name: "Unpredictable", meaning: "Surprising One" },
    { name: "Certain", meaning: "Sure One" },
    { name: "Uncertain", meaning: "Doubtful One" },
    { name: "Sure", meaning: "Confident One" },
    { name: "Doubtful", meaning: "Unsure One" },
    { name: "Confident", meaning: "Certain One" },
    { name: "Unsure", meaning: "Uncertain One" },
    { name: "Positive", meaning: "Optimistic One" },
    { name: "Negative", meaning: "Pessimistic One" },
    { name: "Optimistic", meaning: "Hopeful One" },
    { name: "Pessimistic", meaning: "Gloomy One" },
    { name: "Hopeful", meaning: "Positive One" },
    { name: "Gloomy", meaning: "Depressed One" },
    { name: "Happy", meaning: "Joyful One" },
    { name: "Sad", meaning: "Unhappy One" },
    { name: "Joyful", meaning: "Happy One" },
    { name: "Unhappy", meaning: "Sad One" },
    { name: "Cheerful", meaning: "Happy One" },
    { name: "Miserable", meaning: "Unhappy One" },
    { name: "Content", meaning: "Satisfied One" },
    { name: "Dissatisfied", meaning: "Uncontent One" },
    { name: "Satisfied", meaning: "Happy One" },
    { name: "Frustrated", meaning: "Annoyed One" },
    { name: "Pleased", meaning: "Happy One" },
    { name: "Annoyed", meaning: "Irritated One" },
    { name: "Delighted", meaning: "Very Happy One" },
    { name: "Irritated", meaning: "Annoyed One" },
    { name: "Ecstatic", meaning: "Overjoyed One" },
    { name: "Angry", meaning: "Furious One" },
    { name: "Overjoyed", meaning: "Extremely Happy One" },
    { name: "Furious", meaning: "Very Angry One" },
    { name: "Calm", meaning: "Peaceful One" },
    { name: "Anxious", meaning: "Worried One" },
    { name: "Peaceful", meaning: "Calm One" },
    { name: "Worried", meaning: "Anxious One" },
    { name: "Serene", meaning: "Calm One" },
    { name: "Stressed", meaning: "Pressured One" },
    { name: "Tranquil", meaning: "Peaceful One" },
    { name: "Tense", meaning: "Stressed One" },
    { name: "Relaxed", meaning: "Calm One" },
    { name: "Nervous", meaning: "Anxious One" },
    { name: "Composed", meaning: "Calm One" },
    { name: "Jittery", meaning: "Nervous One" },
    { name: "Cool", meaning: "Calm One" },
    { name: "Panicked", meaning: "Scared One" },
    { name: "Collected", meaning: "Calm One" },
    { name: "Scared", meaning: "Afraid One" },
    { name: "Fearless", meaning: "Brave One" },
    { name: "Afraid", meaning: "Scared One" },
    { name: "Brave", meaning: "Courageous One" },
    { name: "Terrified", meaning: "Very Scared One" },
    { name: "Courageous", meaning: "Brave One" },
    { name: "Frightened", meaning: "Scared One" },
    { name: "Bold", meaning: "Brave One" },
    { name: "Horror-stricken", meaning: "Terrified One" },
    { name: "Daring", meaning: "Brave One" },
    { name: "Petrified", meaning: "Frozen in Fear" },
    { name: "Audacious", meaning: "Bold One" },
    { name: "Paralyzed", meaning: "Unable to Move" },
    { name: "Valiant", meaning: "Brave One" },
    { name: "Shaken", meaning: "Disturbed One" },
    { name: "Gallant", meaning: "Brave One" },
    { name: "Disturbed", meaning: "Uneasy One" },
    { name: "Heroic", meaning: "Brave One" },
    { name: "Uneasy", meaning: "Unsettled One" },
    { name: "Noble", meaning: "Honorable One" },
    { name: "Dishonorable", meaning: "Shameful One" },
    { name: "Honorable", meaning: "Noble One" },
    { name: "Shameful", meaning: "Disgraceful One" },
    { name: "Virtuous", meaning: "Moral One" },
    { name: "Immoral", meaning: "Unethical One" },
    { name: "Moral", meaning: "Good One" },
    { name: "Unethical", meaning: "Wrong One" },
    { name: "Ethical", meaning: "Right One" },
    { name: "Wrong", meaning: "Bad One" },
    { name: "Righteous", meaning: "Just One" },
    { name: "Unjust", meaning: "Unfair One" },
    { name: "Just", meaning: "Fair One" },
    { name: "Unfair", meaning: "Biased One" },
    { name: "Fair", meaning: "Just One" },
    { name: "Biased", meaning: "Prejudiced One" },
    { name: "Impartial", meaning: "Unbiased One" },
    { name: "Prejudiced", meaning: "Biased One" },
    { name: "Unbiased", meaning: "Fair One" },
    { name: "Partial", meaning: "Favoring One" },
    { name: "Neutral", meaning: "Unbiased One" },
    { name: "Favoring", meaning: "Partial One" },
    { name: "Objective", meaning: "Neutral One" },
    { name: "Subjective", meaning: "Personal One" },
    { name: "Detached", meaning: "Unemotional One" },
    { name: "Involved", meaning: "Engaged One" },
    { name: "Disinterested", meaning: "Unbiased One" },
    { name: "Engaged", meaning: "Involved One" },
    { name: "Indifferent", meaning: "Unconcerned One" },
    { name: "Concerned", meaning: "Caring One" },
    { name: "Unconcerned", meaning: "Indifferent One" },
    { name: "Caring", meaning: "Kind One" },
    { name: "Uncaring", meaning: "Cold One" },
    { name: "Attentive", meaning: "Observant One" },
    { name: "Inattentive", meaning: "Unobservant One" },
    { name: "Observant", meaning: "Watchful One" },
    { name: "Unobservant", meaning: "Unaware One" },
    { name: "Watchful", meaning: "Alert One" },
    { name: "Unaware", meaning: "Ignorant One" },
    { name: "Alert", meaning: "Aware One" },
    { name: "Ignorant", meaning: "Unknowing One" },
    { name: "Aware", meaning: "Conscious One" },
    { name: "Unconscious", meaning: "Not Aware One" },
    { name: "Conscious", meaning: "Aware One" },
    { name: "Asleep", meaning: "Resting One" },
    { name: "Awake", meaning: "Alert One" },
    { name: "Resting", meaning: "Sleeping One" },
    { name: "Active", meaning: "Moving One" },
    { name: "Sleeping", meaning: "Unconscious One" },
    { name: "Moving", meaning: "Active One" },
    { name: "Still", meaning: "Not Moving One" },
    { name: "Dynamic", meaning: "Changing One" },
    { name: "Static", meaning: "Unchanging One" },
    { name: "Changing", meaning: "Dynamic One" },
    { name: "Fixed", meaning: "Unchanging One" },
    { name: "Fluid", meaning: "Changing One" },
    { name: "Rigid", meaning: "Stiff One" },
    { name: "Flexible", meaning: "Bending One" },
    { name: "Stiff", meaning: "Inflexible One" },
    { name: "Bending", meaning: "Flexible One" },
    { name: "Inflexible", meaning: "Rigid One" },
    { name: "Adaptable", meaning: "Flexible One" },
    { name: "Unadaptable", meaning: "Rigid One" },
    { name: "Versatile", meaning: "Multi-talented One" },
    { name: "Specialized", meaning: "Focused One" },
    { name: "Multi-talented", meaning: "Versatile One" },
    { name: "Focused", meaning: "Concentrated One" },
    { name: "Concentrated", meaning: "Focused One" },
    { name: "Scattered", meaning: "Distracted One" },
    { name: "Distracted", meaning: "Unfocused One" },
    { name: "Focused", meaning: "Concentrated One" },
    { name: "Unfocused", meaning: "Distracted One" },
    { name: "Attentive", meaning: "Focused One" },
    { name: "Distracted", meaning: "Unattentive One" },
    { name: "Engaged", meaning: "Involved One" },
    { name: "Disengaged", meaning: "Uninvolved One" },
    { name: "Involved", meaning: "Participating One" },
    { name: "Uninvolved", meaning: "Not Participating One" },
    { name: "Participating", meaning: "Taking Part One" },
    { name: "Not Participating", meaning: "Spectator One" },
    { name: "Taking Part", meaning: "Participating One" },
    { name: "Spectator", meaning: "Watcher One" },
    { name: "Participant", meaning: "One Taking Part" },
    { name: "Watcher", meaning: "Observer One" },
    { name: "Observer", meaning: "Watcher One" },
    { name: "Actor", meaning: "Doer One" },
    { name: "Doer", meaning: "Actor One" },
    { name: "Observer", meaning: "Watcher One" },
    { name: "Performer", meaning: "Actor One" },
    { name: "Audience", meaning: "Watchers One" },
    { name: "Actor", meaning: "Performer One" },
    { name: "Watcher", meaning: "Observer One" },
    { name: "Player", meaning: "Participant One" },
    { name: "Viewer", meaning: "Watcher One" },
    { name: "Contestant", meaning: "Competitor One" },
    { name: "Judge", meaning: "Evaluator One" },
    { name: "Competitor", meaning: "Contestant One" },
    { name: "Evaluator", meaning: "Judge One" },
    { name: "Challenger", meaning: "Competitor One" },
    { name: "Referee", meaning: "Official One" },
    { name: "Opponent", meaning: "Enemy One" },
    { name: "Friend", meaning: "Ally One" },
    { name: "Enemy", meaning: "Opponent One" },
    { name: "Ally", meaning: "Friend One" },
    { name: "Foe", meaning: "Enemy One" },
    { name: "Companion", meaning: "Friend One" },
    { name: "Adversary", meaning: "Enemy One" },
    { name: "Friend", meaning: "Pal One" },
    { name: "Rival", meaning: "Competitor One" },
    { name: "Pal", meaning: "Friend One" },
    { name: "Competitor", meaning: "Rival One" },
    { name: "Buddy", meaning: "Friend One" },
    { name: "Antagonist", meaning: "Enemy One" },
    { name: "Amigo", meaning: "Friend One" },
    { name: "Villain", meaning: "Bad Guy One" },
    { name: "Comrade", meaning: "Friend One" },
    { name: "Bad Guy", meaning: "Villain One" },
    { name: "Partner", meaning: "Friend One" },
    { name: "Evil One", meaning: "Bad One" },
    { name: "Associate", meaning: "Friend One" },
    { name: "Dark One", meaning: "Evil One" },
    { name: "Confidant", meaning: "Trusted Friend One" },
    { name: "Shadow One", meaning: "Dark One" },
    { name: "Trustee", meaning: "Trusted One" },
    { name: "Darkness", meaning: "Shadow One" },
    { name: "Ally", meaning: "Friend One" },
    { name: "Abyss", meaning: "Darkness One" },
    { name: "Collaborator", meaning: "Partner One" },
    { name: "Void", meaning: "Empty One" },
    { name: "Co-worker", meaning: "Colleague One" },
    { name: "Emptiness", meaning: "Void One" },
    { name: "Colleague", meaning: "Co-worker One" },
    { name: "Nothingness", meaning: "Void One" },
    { name: "Team Member", meaning: "Partner One" },
    { name: "Chaos", meaning: "Disorder One" },
    { name: "Teammate", meaning: "Team Member One" },
    { name: "Disorder", meaning: "Chaos One" },
    { name: "Member", meaning: "Part of Group One" },
    { name: "Confusion", meaning: "Chaos One" },
    { name: "Group Member", meaning: "Member One" },
    { name: "Anarchy", meaning: "Chaos One" },
    { name: "Leader", meaning: "Head of Group One" },
    { name: "Chaos", meaning: "Anarchy One" },
    { name: "Head", meaning: "Leader One" },
    { name: "Order", meaning: "Structure One" },
    { name: "Chief", meaning: "Leader One" },
    { name: "Structure", meaning: "Order One" },
    { name: "Boss", meaning: "Leader One" },
    { name: "Organization", meaning: "Order One" },
    { name: "Manager", meaning: "Leader One" },
    { name: "System", meaning: "Order One" },
    { name: "Director", meaning: "Leader One" },
    { name: "Method", meaning: "Order One" },
    { name: "Supervisor", meaning: "Leader One" },
    { name: "Plan", meaning: "Order One" },
    { name: "Controller", meaning: "Leader One" },
    { name: "Strategy", meaning: "Plan One" },
    { name: "Ruler", meaning: "Leader One" },
    { name: "Tactics", meaning: "Strategy One" },
    { name: "Governor", meaning: "Leader One" },
    { name: "Approach", meaning: "Method One" },
    { name: "King", meaning: "Monarch One" },
    { name: "Way", meaning: "Method One" },
    { name: "Queen", meaning: "Monarch One" },
    { name: "Path", meaning: "Way One" },
    { name: "Monarch", meaning: "King One" },
    { name: "Route", meaning: "Path One" },
    { name: "Sovereign", meaning: "Monarch One" },
    { name: "Direction", meaning: "Path One" },
    { name: "Lord", meaning: "Ruler One" },
    { name: "Destination", meaning: "End Point One" },
    { name: "Lady", meaning: "Ruler One" },
    { name: "End Point", meaning: "Destination One" },
    { name: "Master", meaning: "Ruler One" },
    { name: "Goal", meaning: "End Point One" },
    { name: "Mistress", meaning: "Ruler One" },
    { name: "Objective", meaning: "Goal One" },
    { name: "Owner", meaning: "Ruler One" },
    { name: "Target", meaning: "Goal One" },
    { name: "Proprietor", meaning: "Owner One" },
    { name: "Aim", meaning: "Goal One" },
    { name: "Holder", meaning: "Owner One" },
    { name: "Intention", meaning: "Goal One" },
    { name: "Bearer", meaning: "Holder One" },
    { name: "Purpose", meaning: "Goal One" },
    { name: "Carrier", meaning: "Bearer One" },
    { name: "Reason", meaning: "Purpose One" },
    { name: "Possessor", meaning: "Owner One" },
    { name: "Motivation", meaning: "Reason One" },
    { name: "Keeper", meaning: "Guardian One" },
    { name: "Inspiration", meaning: "Motivation One" },
    { name: "Guardian", meaning: "Protector One" },
    { name: "Drive", meaning: "Motivation One" },
    { name: "Protector", meaning: "Guardian One" },
    { name: "Ambition", meaning: "Drive One" },
    { name: "Defender", meaning: "Protector One" },
    { name: "Aspiration", meaning: "Ambition One" },
    { name: "Champion", meaning: "Defender One" },
    { name: "Desire", meaning: "Ambition One" },
    { name: "Advocate", meaning: "Supporter One" },
    { name: "Wish", meaning: "Desire One" },
    { name: "Supporter", meaning: "Advocate One" },
    { name: "Want", meaning: "Desire One" },
    { name: "Backer", meaning: "Supporter One" },
    { name: "Need", meaning: "Want One" },
    { name: "Patron", meaning: "Supporter One" },
    { name: "Requirement", meaning: "Need One" },
    { name: "Sponsor", meaning: "Supporter One" },
    { name: "Demand", meaning: "Need One" },
    { name: "Benefactor", meaning: "Supporter One" },
    { name: "Necessity", meaning: "Need One" },
    { name: "Helper", meaning: "Supporter One" },
    { name: "Essential", meaning: "Necessity One" },
    { name: "Assistant", meaning: "Helper One" },
    { name: "Vital", meaning: "Essential One" },
    { name: "Aide", meaning: "Helper One" },
    { name: "Crucial", meaning: "Vital One" },
    { name: "Supporter", meaning: "Helper One" },
    { name: "Important", meaning: "Crucial One" },
    { name: "Friend", meaning: "Helper One" },
    { name: "Key", meaning: "Important One" },
    { name: "Companion", meaning: "Friend One" },
    { name: "Significant", meaning: "Important One" },
    { name: "Partner", meaning: "Friend One" },
    { name: "Notable", meaning: "Important One" },
    { name: "Mate", meaning: "Friend One" },
    { name: "Memorable", meaning: "Notable One" },
    { name: "Pal", meaning: "Friend One" },
    { name: "Famous", meaning: "Notable One" },
    { name: "Buddy", meaning: "Friend One" },
    { name: "Renowned", meaning: "Famous One" },
    { name: "Amigo", meaning: "Friend One" },
    { name: "Celebrated", meaning: "Famous One" },
    { name: "Comrade", meaning: "Friend One" },
    { name: "Well-known", meaning: "Famous One" },
    { name: "Ally", meaning: "Friend One" },
    { name: "Infamous", meaning: "Famous One" },
    { name: "Collaborator", meaning: "Friend One" },
    { name: "Notorious", meaning: "Infamous One" },
    { name: "Co-worker", meaning: "Friend One" },
    { name: "Famous", meaning: "Well-known One" },
    { name: "Colleague", meaning: "Friend One" },
    { name: "Legendary", meaning: "Famous One" },
    { name: "Team Member", meaning: "Friend One" },
    { name: "Mythic", meaning: "Legendary One" },
    { name: "Teammate", meaning: "Friend One" },
    { name: "Epic", meaning: "Legendary One" },
    { name: "Member", meaning: "Friend One" },
    { name: "Heroic", meaning: "Legendary One" },
    { name: "Group Member", meaning: "Friend One" },
    { name: "Glorious", meaning: "Legendary One" },
    { name: "Leader", meaning: "Friend One" },
    { name: "Magnificent", meaning: "Legendary One" },
    { name: "Head", meaning: "Leader One" },
    { name: "Splendid", meaning: "Legendary One" },
    { name: "Chief", meaning: "Leader One" },
    { name: "Stunning", meaning: "Legendary One" },
    { name: "Boss", meaning: "Leader One" },
    { name: "Breathtaking", meaning: "Legendary One" },
    { name: "Manager", meaning: "Leader One" },
    { name: "Awe-inspiring", meaning: "Legendary One" },
    { name: "Director", meaning: "Leader One" },
    { name: "Incredible", meaning: "Legendary One" },
    { name: "Supervisor", meaning: "Leader One" },
    { name: "Amazing", meaning: "Legendary One" },
    { name: "Controller", meaning: "Leader One" },
    { name: "Extraordinary", meaning: "Legendary One" },
    { name: "Ruler", meaning: "Leader One" },
    { name: "Exceptional", meaning: "Legendary One" },
    { name: "Governor", meaning: "Leader One" },
    { name: "Outstanding", meaning: "Legendary One" },
    { name: "King", meaning: "Leader One" },
    { name: "Remarkable", meaning: "Legendary One" },
    { name: "Queen", meaning: "Leader One" },
    { name: "Noteworthy", meaning: "Legendary One" },
    { name: "Monarch", meaning: "Leader One" },
    { name: "Distinguished", meaning: "Legendary One" },
    { name: "Sovereign", meaning: "Leader One" },
    { name: "Eminent", meaning: "Legendary One" },
    { name: "Lord", meaning: "Leader One" },
    { name: "Illustrious", meaning: "Legendary One" },
    { name: "Lady", meaning: "Leader One" },
    { name: "Honorable", meaning: "Legendary One" },
    { name: "Master", meaning: "Leader One" },
    { name: "Respected", meaning: "Legendary One" },
    { name: "Mistress", meaning: "Leader One" },
    { name: "Admired", meaning: "Legendary One" },
    { name: "Owner", meaning: "Leader One" },
    { name: "Revered", meaning: "Legendary One" },
    { name: "Proprietor", meaning: "Leader One" },
    { name: "Venerated", meaning: "Legendary One" },
    { name: "Holder", meaning: "Leader One" },
    { name: "Worshiped", meaning: "Legendary One" },
    { name: "Bearer", meaning: "Leader One" },
    { name: "Idolized", meaning: "Legendary One" },
    { name: "Carrier", meaning: "Leader One" },
    { name: "Celebrated", meaning: "Legendary One" },
    { name: "Possessor", meaning: "Leader One" },
    { name: "Famous", meaning: "Legendary One" },
    { name: "Keeper", meaning: "Leader One" },
    { name: "Renowned", meaning: "Legendary One" },
    { name: "Guardian", meaning: "Leader One" },
    { name: "Well-known", meaning: "Legendary One" },
    { name: "Protector", meaning: "Leader One" },
    { name: "Infamous", meaning: "Legendary One" },
    { name: "Defender", meaning: "Leader One" },
    { name: "Notorious", meaning: "Legendary One" },
    { name: "Champion", meaning: "Leader One" },
    { name: "Famous", meaning: "Legendary One" },
    { name: "Advocate", meaning: "Leader One" },
    { name: "Legendary", meaning: "Legendary One" },
    { name: "Supporter", meaning: "Leader One" },
    { name: "Mythic", meaning: "Legendary One" },
    { name: "Backer", meaning: "Leader One" },
    { name: "Epic", meaning: "Legendary One" },
    { name: "Patron", meaning: "Leader One" },
    { name: "Heroic", meaning: "Legendary One" },
    { name: "Sponsor", meaning: "Leader One" },
    { name: "Glorious", meaning: "Legendary One" },
    { name: "Benefactor", meaning: "Leader One" },
    { name: "Magnificent", meaning: "Legendary One" },
    { name: "Helper", meaning: "Leader One" },
    { name: "Splendid", meaning: "Legendary One" },
    { name: "Assistant", meaning: "Leader One" },
    { name: "Stunning", meaning: "Legendary One" },
    { name: "Aide", meaning: "Leader One" },
    { name: "Breathtaking", meaning: "Legendary One" },
    { name: "Supporter", meaning: "Leader One" },
    { name: "Awe-inspiring", meaning: "Legendary One" },
    { name: "Friend", meaning: "Leader One" },
    { name: "Incredible", meaning: "Legendary One" },
    { name: "Companion", meaning: "Leader One" },
    { name: "Amazing", meaning: "Legendary One" },
    { name: "Partner", meaning: "Leader One" },
    { name: "Extraordinary", meaning: "Legendary One" },
    { name: "Mate", meaning: "Leader One" },
    { name: "Exceptional", meaning: "Legendary One" },
    { name: "Pal", meaning: "Leader One" },
    { name: "Outstanding", meaning: "Legendary One" },
    { name: "Buddy", meaning: "Leader One" },
    { name: "Remarkable", meaning: "Legendary One" },
    { name: "Amigo", meaning: "Leader One" },
    { name: "Noteworthy", meaning: "Legendary One" },
    { name: "Comrade", meaning: "Leader One" },
    { name: "Distinguished", meaning: "Legendary One" },
    { name: "Ally", meaning: "Leader One" },
    { name: "Eminent", meaning: "Legendary One" },
    { name: "Collaborator", meaning: "Leader One" },
    { name: "Illustrious", meaning: "Legendary One" },
    { name: "Co-worker", meaning: "Leader One" },
    { name: "Honorable", meaning: "Legendary One" },
    { name: "Colleague", meaning: "Leader One" },
    { name: "Respected", meaning: "Legendary One" },
    { name: "Team Member", meaning: "Leader One" },
    { name: "Admired", meaning: "Legendary One" },
    { name: "Teammate", meaning: "Leader One" },
    { name: "Revered", meaning: "Legendary One" },
    { name: "Member", meaning: "Leader One" },
    { name: "Venerated", meaning: "Legendary One" },
    { name: "Group Member", meaning: "Leader One" },
    { name: "Worshiped", meaning: "Legendary One" },
    { name: "Leader", meaning: "Leader One" },
    { name: "Idolized", meaning: "Legendary One" },
    { name: "Head", meaning: "Leader One" },
    { name: "Celebrated", meaning: "Legendary One" },
    { name: "Chief", meaning: "Leader One" },
    { name: "Famous", meaning: "Legendary One" },
    { name: "Boss", meaning: "Leader One" },
    { name: "Renowned", meaning: "Legendary One" },
    { name: "Manager", meaning: "Leader One" },
    { name: "Well-known", meaning: "Legendary One" },
    { name: "Director", meaning: "Leader One" },
    { name: "Infamous", meaning: "Legendary One" },
    { name: "Supervisor", meaning: "Leader One" },
    { name: "Notorious", meaning: "Legendary One" },
    { name: "Controller", meaning: "Leader One" },
    { name: "Famous", meaning: "Legendary One" },
    { name: "Ruler", meaning: "Leader One" },
    { name: "Legendary", meaning: "Legendary One" },
    { name: "Governor", meaning: "Leader One" },
    { name: "Mythic", meaning: "Legendary One" },
    { name: "King", meaning: "Leader One" },
    { name: "Epic", meaning: "Legendary One" },
    { name: "Queen", meaning: "Leader One" },
    { name: "Heroic", meaning: "Legendary One" },
    { name: "Monarch", meaning: "Leader One" },
    { name: "Glorious", meaning: "Legendary One" },
    { name: "Sovereign", meaning: "Leader One" },
    { name: "Magnificent", meaning: "Legendary One" },
    { name: "Lord", meaning: "Leader One" },
    { name: "Splendid", meaning: "Legendary One" },
    { name: "Lady", meaning: "Leader One" },
    { name: "Stunning", meaning: "Legendary One" },
    { name: "Master", meaning: "Leader One" },
    { name: "Breathtaking", meaning: "Legendary One" },
    { name: "Mistress", meaning: "Leader One" },
    { name: "Awe-inspiring", meaning: "Legendary One" },
    { name: "Owner", meaning: "Leader One" },
    { name: "Incredible", meaning: "Legendary One" },
    { name: "Proprietor", meaning: "Leader One" },
    { name: "Amazing", meaning: "Legendary One" },
    { name: "Holder", meaning: "Leader One" },
    { name: "Extraordinary", meaning: "Legendary One" },
    { name: "Bearer", meaning: "Leader One" },
    { name: "Exceptional", meaning: "Legendary One" },
    { name: "Carrier", meaning: "Leader One" },
    { name: "Outstanding", meaning: "Legendary One" },
    { name: "Possessor", meaning: "Leader One" },
    { name: "Remarkable", meaning: "Legendary One" },
    { name: "Keeper", meaning: "Leader One" },
    { name: "Noteworthy", meaning: "Legendary One" },
    { name: "Guardian", meaning: "Leader One" },
    { name: "Distinguished", meaning: "Legendary One" },
    { name: "Protector", meaning: "Leader One" },
    { name: "Eminent", meaning: "Legendary One" },
    { name: "Defender", meaning: "Leader One" },
    { name: "Illustrious", meaning: "Legendary One" },
    { name: "Champion", meaning: "Leader One" },
    { name: "Honorable", meaning: "Legendary One" },
    { name: "Advocate", meaning: "Leader One" },
    { name: "Respected", meaning: "Legendary One" },
    { name: "Supporter", meaning: "Leader One" },
    { name: "Admired", meaning: "Legendary One" },
    { name: "Backer", meaning: "Leader One" },
    { name: "Revered", meaning: "Legendary One" },
    { name: "Patron", meaning: "Leader One" },
    { name: "Venerated", meaning: "Legendary One" },
    { name: "Sponsor", meaning: "Leader One" },
    { name: "Worshiped", meaning: "Legendary One" },
    { name: "Benefactor", meaning: "Leader One" },
    { name: "Idolized", meaning: "Legendary One" },
    { name: "Helper", meaning: "Leader One" },
    { name: "Celebrated", meaning: "Legendary One" },
    { name: "Assistant", meaning: "Leader One" },
    { name: "Famous", meaning: "Legendary One" },
    { name: "Aide", meaning: "Leader One" },
    { name: "Renowned", meaning: "Legendary One" },
    { name: "Supporter", meaning: "Leader One" },
    { name: "Well-known", meaning: "Legendary One" },
    { name: "Friend", meaning: "Leader One" },
    { name: "Infamous", meaning: "Legendary One" },
    { name: "Companion", meaning: "Leader One" },
    { name: "Notorious", meaning: "Legendary One" },
    { name: "Partner", meaning: "Leader One" },
    { name: "Famous", meaning: "Legendary One" },
    { name: "Mate", meaning: "Leader One" },
    { name: "Legendary", meaning: "Legendary One" },
    { name: "Pal", meaning: "Leader One" },
    { name: "Mythic", meaning: "Legendary One" },
    { name: "Buddy", meaning: "Leader One" },
    { name: "Epic", meaning: "Legendary One" },
    { name: "Amigo", meaning: "Leader One" },
    { name: "Heroic", meaning: "Legendary One" },
    { name: "Comrade", meaning: "Leader One" },
    { name: "Glorious", meaning: "Legendary One" },
    { name: "Ally", meaning: "Leader One" },
    { name: "Magnificent", meaning: "Legendary One" },
    { name: "Collaborator", meaning: "Leader One" },
    { name: "Splendid", meaning: "Legendary One" },
    { name: "Co-worker", meaning: "Leader One" },
    { name: "Stunning", meaning: "Legendary One" },
    { name: "Colleague", meaning: "Leader One" },
    { name: "Breathtaking", meaning: "Legendary One" },
    { name: "Team Member", meaning: "Leader One" },
    { name: "Awe-inspiring", meaning: "Legendary One" },
    { name: "Teammate", meaning: "Leader One" },
    { name: "Incredible", meaning: "Legendary One" },
    { name: "Member", meaning: "Leader One" },
    { name: "Amazing", meaning: "Legendary One" },
    { name: "Group Member", meaning: "Leader One" },
    { name: "Extraordinary", meaning: "Legendary One" },
    { name: "Leader", meaning: "Leader One" },
    { name: "Exceptional", meaning: "Legendary One" },
    { name: "Head", meaning: "Leader One" },
    { name: "Outstanding", meaning: "Legendary One" },
    { name: "Chief", meaning: "Leader One" },
    { name: "Remarkable", meaning: "Legendary One" },
    { name: "Boss", meaning: "Leader One" },
    { name: "Noteworthy", meaning: "Legendary One" },
    { name: "Manager", meaning: "Leader One" },
    { name: "Distinguished", meaning: "Legendary One" },
    { name: "Director", meaning: "Leader One" },
    { name: "Eminent", meaning: "Legendary One" },
    { name: "Supervisor", meaning: "Leader One" },
    { name: "Illustrious", meaning: "Legendary One" },
    { name: "Controller", meaning: "Leader One" },
    { name: "Honorable", meaning: "Legendary One" },
    { name: "Ruler", meaning: "Leader One" },
    { name: "Respected", meaning: "Legendary One" },
    { name: "Governor", meaning: "Leader One" },
    { name: "Admired", meaning: "Legendary One" },
    { name: "King", meaning: "Leader One" },
    { name: "Revered", meaning: "Legendary One" },
    { name: "Queen", meaning: "Leader One" },
    { name: "Venerated", meaning: "Legendary One" },
    { name: "Monarch", meaning: "Leader One" },
    { name: "Worshiped", meaning: "Legendary One" },
    { name: "Sovereign", meaning: "Leader One" },
    { name: "Idolized", meaning: "Legendary One" },
    { name: "Lord", meaning: "Leader One" },
    { name: "Celebrated", meaning: "Legendary One" },
    { name: "Lady", meaning: "Leader One" },
    { name: "Famous", meaning: "Legendary One" },
    { name: "Renowned", meaning: "Legendary One" }
];

const femaleNames = [
    { name: "Gwynnevere", meaning: "Princess of Sunlight" },
    { name: "Darkmoon", meaning: "Daughter of Dark" },
    { name: "Quelaag", meaning: "Witch of Quelaag" },
    { name: "The Fair Lady", meaning: "Lord of Quelaag" },
    { name: "Sif", meaning: "Guardian of Artorias" },
    { name: "Shira", meaning: "Knight of Filianore" },
    { name: "Filianore", meaning: "Princess of the Ringed City" },
    { name: "Malenia", meaning: "Blade of Miquella" },
    { name: "Miquella", meaning: "Eternal Child" },
    { name: "Marika", meaning: "Eternal Queen" },
    { name: "Ranni", meaning: "Embrace of the Dark Moon" },
    { name: "Rennala", meaning: "Queen of the Full Moon" },
    { name: "Fia", meaning: "Deathbed Companion" },
    { name: "Blaidd", meaning: "Wolf of Ranni" },
    { name: "Iji", meaning: "Blacksmith of Ranni" },
    { name: "Sellen", meaning: "Primal Sorceress" },
    { name: "Millicent", meaning: "Daughter of Malenia" },
    { name: "Melina", meaning: "Blade of Destined Death" },
    { name: "Rya", meaning: "Daughter of Patches" },
    { name: "Roderika", meaning: "Spirit Caller" },
    { name: "Gostoc", meaning: "Gatekeeper" },
    { name: "Boc", meaning: "Seamster" },
    { name: "Miriel", meaning: "Pastor of Vows" },
    { name: "Gideon", meaning: "All-Knowing" },
    { name: "Gowry", meaning: "Rot Priest" },
    { name: "Hyetta", meaning: "Youth of Fran" },
    { name: "Luna", meaning: "Moon Goddess" },
    { name: "Selene", meaning: "Moon Maiden" },
    { name: "Eowyn", meaning: "Horse Lord" },
    { name: "Arwen", meaning: "Maiden of the Elves" },
    { name: "Galadriel", meaning: "Lady of Light" },
    { name: "Eleanor", meaning: "Bright Shining One" },
    { name: "Morgana", meaning: "Sea Bright" },
    { name: "Morgause", meaning: "Sea Circle" },
    { name: "Guinevere", meaning: "White Wave" },
    { name: "Vivienne", meaning: "Alive" },
    { name: "Nimue", meaning: "Lady of the Lake" },
    { name: "Morrigan", meaning: "Phantom Queen" },
    { name: "Badb", meaning: "Battle Crow" },
    { name: "Macha", meaning: "Battle Goddess" },
    { name: "Anu", meaning: "Goddess of Sky" },
    { name: "Danu", meaning: "Mother of Gods" },
    { name: "Arianrhod", meaning: "Silver Wheel" },
    { name: "Rhiannon", meaning: "Divine Queen" },
    { name: "Blodeuwedd", meaning: "Flower Face" },
    { name: "Ceridwen", meaning: "Blessed Corner" },
    { name: "Bridget", meaning: "Exalted One" },
    { name: "Brigid", meaning: "High Queen" },
    { name: "Ayla", meaning: "Oak" },
    { name: "Isolde", meaning: "Ice ruler" },
    { name: "Katherine", meaning: "Pure" },
    { name: "Rosalind", meaning: "Pretty rose" },
    { name: "Evelyn", meaning: "Wished for child" },
    { name: "Vivian", meaning: "Alive" },
    { name: "Rowena", meaning: "Counsel of the people" },
    { name: "Moira", meaning: "Bitter" },
    { name: "Cliodhna", meaning: "Beautiful" },
    { name: "Aisling", meaning: "Dream vision" },
    { name: "Bronwyn", meaning: "White raven" },
    { name: "Epona", meaning: "Great queen" },
    { name: "Andraste", meaning: "Victory" },
    { name: "Victoria", meaning: "Victory" },
    { name: "Valentina", meaning: "Strong" },
    { name: "Valeria", meaning: "Strong" },
    { name: "Valkyrie", meaning: "Dead chooser" },
    { name: "Shieldmaiden", meaning: "Norse warrior" },
    { name: "Freya", meaning: "Noble woman" },
    { name: "Frigga", meaning: "Beloved" },
    { name: "Sif", meaning: "Bride" },
    { name: "Idun", meaning: "Ever young" },
    { name: "Hel", meaning: "Hidden" },
    { name: "Skadi", meaning: "Huntress" },
    { name: "Sigyn", meaning: "Victory friend" },
    { name: "Hild", meaning: "Battle" },
    { name: "Raven", meaning: "Dark bird" },
    { name: "Swan", meaning: "White bird" },
    { name: "Wolf", meaning: "Wild animal" },
    { name: "Bear", meaning: "Strong creature" },
    { name: "Fox", meaning: "Clever creature" },
    { name: "Huntress", meaning: "Hunter female" },
    { name: "Amazon", meaning: "Warrior woman" },
    { name: "Maiden", meaning: "Young woman" },
    { name: "Matriarch", meaning: "Female leader" },
    { name: "Elder", meaning: "Wise one" },
    { name: "Sage", meaning: "Wise one" },
    { name: "Seer", meaning: "Visionary" },
    { name: "Oracle", meaning: "Prophet" },
    { name: "Prophet", meaning: "Speaker of truth" },
    { name: "Witch", meaning: "Magic user" },
    { name: "Wiccan", meaning: "Nature follower" },
    { name: "Enchantress", meaning: "Magic weaver" },
    { name: "Sorceress", meaning: "Magic caster" },
    { name: "Spellcaster", meaning: "Magic user" },
    { name: "Mage", meaning: "Magic expert" },
    { name: "Spellweaver", meaning: "Magic creator" },
    { name: "Nightshade", meaning: "Dark flower" },
    { name: "Moonshadow", meaning: "Moon darkness" },
    { name: "Starlight", meaning: "Star glow" },
    { name: "Sunfire", meaning: "Sun flame" },
    { name: "Frost", meaning: "Ice cold" },
    { name: "Ember", meaning: "Fire coal" },
    { name: "Ash", meaning: "Fire remains" },
    { name: "Shadow", meaning: "Darkness" },
    { name: "Serpent", meaning: "Snake" },
    { name: "Viper", meaning: "Poison snake" },
    { name: "Cobra", meaning: "Hooded snake" },
    { name: "Basilisk", meaning: "King of snakes" },
    { name: "Dragon", meaning: "Fire lizard" },
    { name: "Wyvern", meaning: "Two-legged dragon" },
    { name: "Hydra", meaning: "Water monster" },
    { name: "Phoenix", meaning: "Fire bird" },
    { name: "Griffin", meaning: "Lion eagle" },
    { name: "Sphinx", meaning: "Riddle creature" },
    { name: "Chimera", meaning: "Fire monster" },
    { name: "Siren", meaning: "Sea singer" },
    { name: "Nymph", meaning: "Nature spirit" },
    { name: "Dryad", meaning: "Tree spirit" },
    { name: "Naiad", meaning: "Water spirit" },
    { name: "Oread", meaning: "Mountain spirit" },
    { name: "Aura", meaning: "Wind spirit" },
    { name: "Lightning", meaning: "Electric spirit" },
    { name: "Thunder", meaning: "Storm spirit" },
    { name: "Wind", meaning: "Air spirit" },
    { name: "Earth", meaning: "Ground spirit" },
    { name: "Water", meaning: "Sea spirit" },
    { name: "Fire", meaning: "Flame spirit" },
    { name: "Ice", meaning: "Frost spirit" },
    { name: "Dark", meaning: "Shadow spirit" },
    { name: "Light", meaning: "Sun spirit" },
    { name: "Moon", meaning: "Night light" },
    { name: "Sun", meaning: "Day light" },
    { name: "Star", meaning: "Night sky light" },
    { name: "Night", meaning: "Dark time" },
    { name: "Day", meaning: "Light time" },
    { name: "Dawn", meaning: "Morning light" },
    { name: "Dusk", meaning: "Evening dark" },
    { name: "Twilight", meaning: "Between light dark" },
    { name: "Midnight", meaning: "Darkest hour" },
    { name: "Noon", meaning: "Brightest day" },
    { name: "Eclipse", meaning: "Hidden light" },
    { name: "Phantom", meaning: "Ghost spirit" },
    { name: "Specter", meaning: "Ghost" },
    { name: "Wraith", meaning: "Death spirit" },
    { name: "Ghost", meaning: "Dead spirit" },
    { name: "Spirit", meaning: "Soul" },
    { name: "Soul", meaning: "Life essence" },
    { name: "Essence", meaning: "Core being" },
    { name: "Heart", meaning: "Life center" },
    { name: "Mind", meaning: "Thought center" },
    { name: "Body", meaning: "Physical form" },
    { name: "Being", meaning: "Existence" },
    { name: "Life", meaning: "Living state" },
    { name: "Death", meaning: "End of life" },
    { name: "Rebirth", meaning: "New life" },
    { name: "Immortal", meaning: "Never dying" },
    { name: "Eternal", meaning: "Forever" },
    { name: "Undying", meaning: "Never dead" },
    { name: "Everlasting", meaning: "Always" },
    { name: "Endless", meaning: "Without end" },
    { name: "Boundless", meaning: "Without limit" },
    { name: "Infinite", meaning: "Without end" },
    { name: "Timeless", meaning: "Outside time" },
    { name: "Ancient", meaning: "Very old" },
    { name: "Eldritch", meaning: "Otherworldly" },
    { name: "Abyssal", meaning: "Deep darkness" },
    { name: "Void", meaning: "Empty space" },
    { name: "Chaos", meaning: "Disorder" },
    { name: "Order", meaning: "Structure" },
    { name: "Balance", meaning: "Equilibrium" },
    { name: "Harmony", meaning: "Peace" },
    { name: "Discord", meaning: "Conflict" },
    { name: "Strife", meaning: "Battle" },
    { name: "War", meaning: "Armed conflict" },
    { name: "Peace", meaning: "No war" },
    { name: "Hope", meaning: "Positive outlook" },
    { name: "Despair", meaning: "Hopelessness" },
    { name: "Faith", meaning: "Belief" },
    { name: "Doubt", meaning: "Uncertainty" },
    { name: "Trust", meaning: "Confidence" },
    { name: "Fear", meaning: "Afraid" },
    { name: "Courage", meaning: "Bravery" },
    { name: "Strength", meaning: "Power" },
    { name: "Wisdom", meaning: "Knowledge" },
    { name: "Truth", meaning: "Reality" },
    { name: "Justice", meaning: "Fairness" },
    { name: "Mercy", meaning: "Compassion" },
    { name: "Love", meaning: "Affection" },
    { name: "Joy", meaning: "Happiness" },
    { name: "Sorrow", meaning: "Sadness" },
    { name: "Guardian", meaning: "Protector" },
    { name: "Sentinel", meaning: "Watcher" },
    { name: "Warden", meaning: "Guard" },
    { name: "Keeper", meaning: "Preserver" },
    { name: "Champion", meaning: "Fighter" },
    { name: "Hero", meaning: "Great person" },
    { name: "Legend", meaning: "Famous story" },
    { name: "Fame", meaning: "Renown" },
    { name: "Glory", meaning: "Fame" },
    { name: "Honor", meaning: "Respect" },
    { name: "Victory", meaning: "Win" },
    { name: "Destiny", meaning: "Fate" },
    { name: "Fortune", meaning: "Luck" }
];

let currentMode = 'random';

function shuffleArray(array) {
    const shuffled = [...array];
    for (let i = shuffled.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
    }
    return shuffled;
}

function generateNames() {
    const grid = document.getElementById('namesGrid');
    let pool;
    
    if (currentMode === 'random') {
        pool = shuffleArray([...maleNames, ...femaleNames]);
    } else if (currentMode === 'male') {
        pool = shuffleArray([...maleNames]);
    } else {
        pool = shuffleArray([...femaleNames]);
    }
    
    const selected = pool.slice(0, 16);
    
    grid.innerHTML = selected.map(item => `
        <div class="name-card">
            <div class="name-text">${item.name}</div>
            <div class="name-gender">${currentMode === 'female' ? 'Female' : currentMode === 'male' ? 'Male' : 'Mixed'}</div>
            <div class="name-meaning">${item.meaning}</div>
        </div>
    `).join('');
}

document.querySelectorAll('.mode-btn').forEach(btn => {
    btn.addEventListener('click', function() {
        document.querySelectorAll('.mode-btn').forEach(b => b.classList.remove('active'));
        this.classList.add('active');
        currentMode = this.dataset.mode;
        generateNames();
    });
});