const maleNames = [
    { name: "AlphaStrike", meaning: "First assault leader" },
    { name: "BravoOne", meaning: "Second-in-command" },
    { name: "CharlieFoxtrot", meaning: "Tactical specialist" },
    { name: "DeltaWolverine", meaning: "Elite operator" },
    { name: "EchoKnight", meaning: "Stealth warrior" },
    { name: "FoxtrotZero", meaning: "Zero-hour specialist" },
    { name: "GolfRanger", meaning: "Long-range expert" },
    { name: "HotelSniper", meaning: "Precision shooter" },
    { name: "IndiaBlade", meaning: "Close combat expert" },
    { name: "JulietTango", meaning: "Communications lead" },
    { name: "KiloViking", meaning: "Fearless warrior" },
    { name: "LimaReaper", meaning: "Death from above" },
    { name: "MikeGhost", meaning: "Shadow operative" },
    { name: "NovemberRaven", meaning: "Night stalker" },
    { name: "OscarVengeance", meaning: "Justice seeker" },
    { name: "PapaHavoc", meaning: "Chaos bringer" },
    { name: "QuebecTitan", meaning: "Unstoppable force" },
    { name: "RomeoBlaze", meaning: "Fire specialist" },
    { name: "SierraCobra", meaning: "Deadly and agile" },
    { name: "TangoViper", meaning: "Poisonous strike" },
    { name: "UniformCrusher", meaning: "Armor breaker" },
    { name: "VictorStorm", meaning: "Unpredictable force" },
    { name: "WhiskeyPhantom", meaning: "Ghostly presence" },
    { name: "XraySpecter", meaning: "See-through enemy" },
    { name: "YankeeFury", meaning: "American rage" },
    { name: "ZuluDeath", meaning: "Final destination" },
    { name: "CaptainSoap", meaning: "Leader of operations" },
    { name: "MajorPrice", meaning: "Commanding officer" },
    { name: "SergeantGhost", meaning: "Silent leader" },
    { name: "LieutenantWoods", meaning: "Tactical officer" },
    { name: "ColonelRook", meaning: "Strategic master" },
    { name: "GeneralHawk", meaning: "Eagle eye" },
    { name: "CommanderZero", meaning: "Origin point" },
    { name: "OperatorGrim", meaning: "Dark warrior" },
    { name: "AssassinShadow", meaning: "Silent killer" },
    { name: "HunterWolf", meaning: "Predator instinct" },
    { name: "RangerSteel", meaning: "Unbreakable" },
    { name: "RaiderBone", meaning: "Hardcore fighter" },
    { name: "VanguardFury", meaning: "Frontline rage" },
    { name: "SentinelIron", meaning: "Guardian metal" },
    { name: "WraithKing", meaning: "Spirit ruler" },
    { name: "SpecterLord", meaning: "Ghost master" },
    { name: "PhantomKing", meaning: "Invisible leader" },
    { name: "ShadowKing", meaning: "Dark ruler" },
    { name: "NightHawk", meaning: "Night flyer" },
    { name: "DarkWolf", meaning: "Shadow beast" },
    { name: "BloodRaven", meaning: "Death messenger" },
    { name: "IronClaw", meaning: "Metal grip" },
    { name: "SteelFist", meaning: "Unstoppable punch" },
    { name: "FireBreath", meaning: "Flame thrower" },
    { name: "IceBreaker", meaning: "Cold destroyer" },
    { name: "StormChaser", meaning: "Weather warrior" },
    { name: "ThunderStrike", meaning: "Lightning fast" },
    { name: "BulletStorm", meaning: "Lead hail" },
    { name: "GrenadeKing", meaning: "Explosive expert" },
    { name: "SniperGod", meaning: "Headshot master" },
    { name: "KnifeMaster", meaning: "Melee expert" },
    { name: "RocketMan", meaning: "Explosive power" },
    { name: "TankBuster", meaning: "Armor killer" },
    { name: "PlaneHunter", meaning: "Air defense" },
    { name: "BoatSmasher", meaning: "Naval warfare" },
    { name: "MineSweeper", meaning: "Explosive expert" },
    { name: "BombDefuser", meaning: "Safety specialist" },
    { name: "MedicKiller", meaning: "No mercy" },
    { name: "SpyHunter", meaning: "Counter intel" },
    { name: "HackerPro", meaning: "Tech expert" },
    { name: "RadioMan", meaning: "Communications" },
    { name: "ScoutElite", meaning: "Recon expert" },
    { name: "Demolition", meaning: "Destruction specialist" },
    { name: "Sabotage", meaning: "Behind enemy lines" },
    { name: "Ambush", meaning: "Surprise attack" },
    { name: "FlankMaster", meaning: "Side attack" },
    { name: "HeadHunter", meaning: "Targeted kills" },
    { name: "BodyCount", meaning: "High kill count" },
    { name: "WarMachine", meaning: "Killing machine" },
    { name: "DeathDealer", meaning: "Bringer of death" },
    { name: "KillZone", meaning: "Area control" },
    { name: "BloodThirst", meaning: "Killing hunger" },
    { name: "CombatGod", meaning: "Battle master" },
    { name: "FightClub", meaning: "Close combat" },
    { name: "GunSlinger", meaning: "Fast draw" },
    { name: "TriggerHappy", meaning: "Quick shooter" },
    { name: "AmmoKing", meaning: "Never runs out" },
    { name: "ClipMaster", meaning: "Quick reload" },
    { name: "ScopeLord", meaning: "Precision aim" },
    { name: "CrossHair", meaning: "Perfect aim" },
    { name: "IronSight", meaning: "No scope needed" },
    { name: "Silencer", meaning: "Quiet killer" },
    { name: "Suppressor", meaning: "Stealth ops" },
    { name: "GrenadeLaunch", meaning: "Explosive range" },
    { name: "RPGMaster", meaning: "Rocket expert" },
    { name: "ShotgunSavage", meaning: "Close range beast" },
    { name: "SMGKing", meaning: "Fast fire" },
    { name: "LMGBeast", meaning: "Heavy fire" },
    { name: "ARMaster", meaning: "All around" },
    { name: "DMRPro", meaning: "Designated marksman" },
    { name: "PistolPete", meaning: "Sidearm expert" },
    { name: "KnifeEdge", meaning: "Sharp killer" },
    { name: "Bayonet", meaning: "Melee weapon" },
    { name: "CombatKnife", meaning: "Fighting blade" },
    { name: "Tomahawk", meaning: "Throwing axe" },
    { name: "Crossbow", meaning: "Silent weapon" },
    { name: "SwordMaster", meaning: "Blade expert" },
    { name: "ShieldWall", meaning: "Protector" },
    { name: "ArmorKing", meaning: "Heavy defense" },
    { name: "SpeedDemon", meaning: "Fast movement" },
    { name: "StealthMode", meaning: "Invisible" },
    { name: "CamoExpert", meaning: "Hidden" },
    { name: "NightVision", meaning: "See in dark" },
    { name: "ThermalVision", meaning: "Heat seeker" },
    { name: "UAVMaster", meaning: "Air support" },
    { name: "CounterUAV", meaning: "Anti-air" },
    { name: "CarePackage", meaning: "Supply drop" },
    { name: "Airstrike", meaning: "Air support" },
    { name: "Gunship", meaning: "Helicopter support" },
    { name: "AttackDog", meaning: "K-9 unit" },
    { name: "SentryGun", meaning: "Auto defense" },
    { name: "Claymore", meaning: "Mine expert" },
    { name: "TrophySystem", meaning: "Anti-projectile" },
    { name: "DeadSilence", meaning: "Quiet steps" },
    { name: "Lightweight", meaning: "Fast movement" },
    { name: "Scavenger", meaning: "Ammo collector" },
    { name: "Hardline", meaning: "Score streaks" },
    { name: "PerkMaster", meaning: "All perks" },
    { name: "LoadoutKing", meaning: "Best setup" },
    { name: "MetaGod", meaning: "Best strategy" },
    { name: "TryHard", meaning: "Competitive" },
    { name: "SweatLord", meaning: "Hardcore player" },
    { name: "ProPlayer", meaning: "Professional" },
    { name: "ClanLeader", meaning: "Team captain" },
    { name: "TeamPlayer", meaning: "Team oriented" },
    { name: "RankedPro", meaning: "Competitive player" },
    { name: "WarzoneKing", meaning: "BR expert" },
    { name: "MultiBeast", meaning: "MP expert" },
    { name: "ZombiesPro", meaning: "Undead slayer" },
    { name: "CampaignHero", meaning: "Story mode" },
    { name: "AllRound", meaning: "Versatile" },
    { name: "CODLegend", meaning: "Game master" },
    { name: "MWExpert", meaning: "Modern Warfare" },
    { name: "BlackOps", meaning: "Secret ops" },
    { name: "ColdWar", meaning: "Historical" },
    { name: "WWIIHero", meaning: "World War" },
    { name: "AdvancedWar", meaning: "Future combat" },
    { name: "InfiniteWar", meaning: "Space combat" },
    { name: "Ghosts", meaning: "Specter ops" },
    { name: "ModernWar", meaning: "Current ops" },
    { name: "Vanguard", meaning: "Frontline" },
    { name: "Warzone", meaning: "Battle Royale" },
    { name: "MobilePro", meaning: "Mobile player" },
    { name: "PCMaster", meaning: "Computer player" },
    { name: "ConsoleKing", meaning: "Console player" },
    { name: "ControllerGod", meaning: "Controller expert" },
    { name: "MouseMaster", meaning: "PC expert" },
    { name: "KeyboardKing", meaning: "Keyboards" },
    { name: "HeadsetPro", meaning: "Communication" },
    { name: "MonitorKing", meaning: "Visuals" },
    { name: "ChairMaster", meaning: "Comfort" },
    { name: "SetupGod", meaning: "Perfect rig" },
    { name: "GamingBeast", meaning: "Ultimate player" }
];

const femaleNames = [
    { name: "AlphaValkyrie", meaning: "Female assault leader" },
    { name: "BravoQueen", meaning: "Second-in-command" },
    { name: "CharliePhoenix", meaning: "Reborn warrior" },
    { name: "DeltaLuna", meaning: "Moon warrior" },
    { name: "EchoSiren", meaning: "Voice of battle" },
    { name: "FoxtrixViper", meaning: "Deadly female" },
    { name: "GolfDiamond", meaning: "Hard and beautiful" },
    { name: "HotelAngel", meaning: "Heavenly fighter" },
    { name: "IndiaRose", meaning: "Beautiful warrior" },
    { name: "JulietStorm", meaning: "Tempestuous" },
    { name: "KiloSapphire", meaning: "Precious fighter" },
    { name: "LimaNova", meaning: "New star" },
    { name: "MikeShadow", meaning: "Female ghost" },
    { name: "NovemberLuna", meaning: "Night moon" },
    { name: "OscarBlaze", meaning: "Female fire" },
    { name: "PapaAthena", meaning: "Goddess of war" },
    { name: "QuebecHera", meaning: "Queen of gods" },
    { name: "RomeoArtemis", meaning: "Hunter goddess" },
    { name: "SierraDiana", meaning: "Moon goddess" },
    { name: "TangoNike", meaning: "Victory" },
    { name: "UniformVenus", meaning: "Goddess of love and war" },
    { name: "VictorAtropos", meaning: "Fate weaver" },
    { name: "WhiskeyMedusa", meaning: "Stone gaze" },
    { name: "XrayPersephone", meaning: "Queen of underworld" },
    { name: "YankeeEcho", meaning: "American voice" },
    { name: "ZuluHecate", meaning: "Goddess of magic" },
    { name: "CaptainViper", meaning: "Female leader" },
    { name: "MajorBlaze", meaning: "Commanding fire" },
    { name: "SergeantRaven", meaning: "Silent leader" },
    { name: "LieutenantShadow", meaning: "Dark officer" },
    { name: "ColonelPhoenix", meaning: "Reborn leader" },
    { name: "GeneralLuna", meaning: "Moon commander" },
    { name: "CommanderStorm", meaning: "Tempest leader" },
    { name: "OperatorViper", meaning: "Female operative" },
    { name: "AssassinLuna", meaning: "Night killer" },
    { name: "HunterArtemis", meaning: "Moon hunter" },
    { name: "RangerDiamond", meaning: "Hard ranger" },
    { name: "RaiderBlaze", meaning: "Fire raider" },
    { name: "VanguardAthena", meaning: "Frontline goddess" },
    { name: "SentinelRose", meaning: "Guardian flower" },
    { name: "WraithLuna", meaning: "Spirit moon" },
    { name: "SpecterEcho", meaning: "Ghost voice" },
    { name: "PhantomNova", meaning: "Invisible star" },
    { name: "ShadowQueen", meaning: "Dark ruler" },
    { name: "NightOwl", meaning: "Night hunter" },
    { name: "DarkLuna", meaning: "Shadow moon" },
    { name: "BloodRose", meaning: "Deadly beauty" },
    { name: "IronLily", meaning: "Metal flower" },
    { name: "SteelRose", meaning: "Hard beauty" },
    { name: "FireLuna", meaning: "Flame moon" },
    { name: "IceQueen", meaning: "Cold ruler" },
    { name: "StormGoddess", meaning: "Weather queen" },
    { name: "ThunderLuna", meaning: "Lightning moon" },
    { name: "BulletRose", meaning: "Deadly flower" },
    { name: "GrenadeQueen", meaning: "Explosive expert" },
    { name: "SniperGoddess", meaning: "Headshot queen" },
    { name: "KnifeLuna", meaning: "Blade moon" },
    { name: "RocketGirl", meaning: "Explosive female" },
    { name: "TankBuster", meaning: "Armor killer" },
    { name: "PlaneHunter", meaning: "Air defense" },
    { name: "BoatSmasher", meaning: "Naval warfare" },
    { name: "MineSweeper", meaning: "Explosive expert" },
    { name: "BombDefuser", meaning: "Safety specialist" },
    { name: "MedicKiller", meaning: "No mercy" },
    { name: "SpyHunter", meaning: "Counter intel" },
    { name: "HackerQueen", meaning: "Tech expert" },
    { name: "RadioGirl", meaning: "Communications" },
    { name: "ScoutElite", meaning: "Recon expert" },
    { name: "Demolition", meaning: "Destruction specialist" },
    { name: "Sabotage", meaning: "Behind enemy lines" },
    { name: "Ambush", meaning: "Surprise attack" },
    { name: "FlankMaster", meaning: "Side attack" },
    { name: "HeadHunter", meaning: "Targeted kills" },
    { name: "BodyCount", meaning: "High kill count" },
    { name: "WarMachine", meaning: "Killing machine" },
    { name: "DeathDealer", meaning: "Bringer of death" },
    { name: "KillZone", meaning: "Area control" },
    { name: "BloodThirst", meaning: "Killing hunger" },
    { name: "CombatGoddess", meaning: "Battle queen" },
    { name: "FightClub", meaning: "Close combat" },
    { name: "GunSlinger", meaning: "Fast draw" },
    { name: "TriggerHappy", meaning: "Quick shooter" },
    { name: "AmmoQueen", meaning: "Never runs out" },
    { name: "ClipMaster", meaning: "Quick reload" },
    { name: "ScopeQueen", meaning: "Precision aim" },
    { name: "CrossHair", meaning: "Perfect aim" },
    { name: "IronSight", meaning: "No scope needed" },
    { name: "Silencer", meaning: "Quiet killer" },
    { name: "Suppressor", meaning: "Stealth ops" },
    { name: "GrenadeLaunch", meaning: "Explosive range" },
    { name: "RPGMaster", meaning: "Rocket expert" },
    { name: "ShotgunSavage", meaning: "Close range beast" },
    { name: "SMGQueen", meaning: "Fast fire" },
    { name: "LMGBeast", meaning: "Heavy fire" },
    { name: "ARMaster", meaning: "All around" },
    { name: "DMRPro", meaning: "Designated marksman" },
    { name: "PistolQueen", meaning: "Sidearm expert" },
    { name: "KnifeEdge", meaning: "Sharp killer" },
    { name: "Bayonet", meaning: "Melee weapon" },
    { name: "CombatKnife", meaning: "Fighting blade" },
    { name: "Tomahawk", meaning: "Throwing axe" },
    { name: "Crossbow", meaning: "Silent weapon" },
    { name: "SwordMaster", meaning: "Blade expert" },
    { name: "ShieldWall", meaning: "Protector" },
    { name: "ArmorQueen", meaning: "Heavy defense" },
    { name: "SpeedDemon", meaning: "Fast movement" },
    { name: "StealthMode", meaning: "Invisible" },
    { name: "CamoExpert", meaning: "Hidden" },
    { name: "NightVision", meaning: "See in dark" },
    { name: "ThermalVision", meaning: "Heat seeker" },
    { name: "UAVMaster", meaning: "Air support" },
    { name: "CounterUAV", meaning: "Anti-air" },
    { name: "CarePackage", meaning: "Supply drop" },
    { name: "Airstrike", meaning: "Air support" },
    { name: "Gunship", meaning: "Helicopter support" },
    { name: "AttackDog", meaning: "K-9 unit" },
    { name: "SentryGun", meaning: "Auto defense" },
    { name: "Claymore", meaning: "Mine expert" },
    { name: "TrophySystem", meaning: "Anti-projectile" },
    { name: "DeadSilence", meaning: "Quiet steps" },
    { name: "Lightweight", meaning: "Fast movement" },
    { name: "Scavenger", meaning: "Ammo collector" },
    { name: "Hardline", meaning: "Score streaks" },
    { name: "PerkMaster", meaning: "All perks" },
    { name: "LoadoutQueen", meaning: "Best setup" },
    { name: "MetaGoddess", meaning: "Best strategy" },
    { name: "TryHard", meaning: "Competitive" },
    { name: "SweatQueen", meaning: "Hardcore player" },
    { name: "ProPlayer", meaning: "Professional" },
    { name: "ClanLeader", meaning: "Team captain" },
    { name: "TeamPlayer", meaning: "Team oriented" },
    { name: "RankedPro", meaning: "Competitive player" },
    { name: "WarzoneQueen", meaning: "BR expert" },
    { name: "MultiBeast", meaning: "MP expert" },
    { name: "ZombiesPro", meaning: "Undead slayer" },
    { name: "CampaignHero", meaning: "Story mode" },
    { name: "AllRound", meaning: "Versatile" },
    { name: "CODLegend", meaning: "Game master" },
    { name: "MWExpert", meaning: "Modern Warfare" },
    { name: "BlackOps", meaning: "Secret ops" },
    { name: "ColdWar", meaning: "Historical" },
    { name: "WWIIHero", meaning: "World War" },
    { name: "AdvancedWar", meaning: "Future combat" },
    { name: "InfiniteWar", meaning: "Space combat" },
    { name: "Ghosts", meaning: "Specter ops" },
    { name: "ModernWar", meaning: "Current ops" },
    { name: "Vanguard", meaning: "Frontline" },
    { name: "Warzone", meaning: "Battle Royale" },
    { name: "MobilePro", meaning: "Mobile player" },
    { name: "PCMaster", meaning: "Computer player" },
    { name: "ConsoleQueen", meaning: "Console player" },
    { name: "ControllerGoddess", meaning: "Controller expert" },
    { name: "MouseMaster", meaning: "PC expert" },
    { name: "KeyboardQueen", meaning: "Keyboards" },
    { name: "HeadsetPro", meaning: "Communication" },
    { name: "MonitorQueen", meaning: "Visuals" },
    { name: "ChairMaster", meaning: "Comfort" },
    { name: "SetupGoddess", meaning: "Perfect rig" },
    { name: "GamingBeast", meaning: "Ultimate player" }
];

function shuffleArray(array) {
    const shuffled = [...array];
    for (let i = shuffled.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
    }
    return shuffled;
}

function generateNames() {
    const modeButtons = document.querySelectorAll('.mode-btn');
    let currentMode = 'random';
    
    modeButtons.forEach(btn => {
        if (btn.classList.contains('active')) {
            currentMode = btn.dataset.mode;
        }
    });
    
    let names;
    
    if (currentMode === 'male') {
        names = shuffleArray(maleNames).slice(0, 16);
    } else if (currentMode === 'female') {
        names = shuffleArray(femaleNames).slice(0, 16);
    } else {
        const combined = [...maleNames, ...femaleNames];
        names = shuffleArray(combined).slice(0, 16);
    }
    
    const namesGrid = document.getElementById('namesGrid');
    namesGrid.innerHTML = '';
    
    names.forEach(nameObj => {
        const card = document.createElement('div');
        card.className = 'name-card';
        
        const nameText = document.createElement('div');
        nameText.className = 'name-text';
        nameText.textContent = nameObj.name;
        
        const genderBadge = document.createElement('div');
        genderBadge.className = 'name-gender';
        genderBadge.textContent = currentMode === 'random' ? 'Random' : (currentMode === 'male' ? 'Male' : 'Female');
        
        const meaningText = document.createElement('div');
        meaningText.className = 'name-meaning';
        meaningText.textContent = nameObj.meaning;
        
        card.appendChild(nameText);
        card.appendChild(genderBadge);
        card.appendChild(meaningText);
        
        namesGrid.appendChild(card);
    });
}

document.querySelectorAll('.mode-btn').forEach(btn => {
    btn.addEventListener('click', () => {
        document.querySelectorAll('.mode-btn').forEach(b => b.classList.remove('active'));
        btn.classList.add('active');
    });
});