const maleNames = [
    { name: "Aidan O'Clover", meaning: "Little fire with luck" },
    { name: "Brendan Luckyfoot", meaning: "Prince of fortune" },
    { name: "Conor Goldenshoe", meaning: "Lover of gold" },
    { name: "Declan Greenleaf", meaning: "Man of the forest" },
    { name: "Eamon Sparkle", meaning: "Rich protector" },
    { name: "Finn Shamrock", meaning: "Fair-haired luck" },
    { name: "Gavin Rainbow", meaning: "White hawk" },
    { name: "Hugh Clovershield", meaning: "Intelligent guardian" },
    { name: "Ian Potofgold", meaning: "God is gracious" },
    { name: "James Lucky", meaning: "Supplanter of luck" },
    { name: "Kevin Goldfinder", meaning: "Handsome treasure seeker" },
    { name: "Liam Luckwell", meaning: "Strong-willed fortune" },
    { name: "Mickey Cloverson", meaning: "Who is like God" },
    { name: "Niall Goldhand", meaning: "Champion of treasure" },
    { name: "Owen Luckyheart", meaning: "Young warrior of luck" },
    { name: "Patrick Goldenshield", meaning: "Noble protector" },
    { name: "Quinn Rainbowchaser", meaning: "Wise seeker" },
    { name: "Ryan Clovernose", meaning: "Little king" },
    { name: "Sean Goldensmile", meaning: "God is gracious" },
    { name: "Tiernan Luckbringer", meaning: "Lord of luck" },
    { name: "Ulrich Goldfinder", meaning: "Prosperous ruler" },
    { name: "Vincent Cloverson", meaning: "Conqueror" },
    { name: "William Luckypants", meaning: "Resolute protector" },
    { name: "Xavier Goldtongue", meaning: "Bright treasure" },
    { name: "Yannick Luckyfellow", meaning: "God is gracious" },
    { name: "Zachary Goldenshine", meaning: "Remembered treasure" },
    { name: "Aodh O'Luck", meaning: "Fire of luck" },
    { name: "Barry Cloversworth", meaning: "Spear carrier" },
    { name: "Cian Goldenday", meaning: "Ancient treasure" },
    { name: "Damien Luckypatrick", meaning: "To tame" },
    { name: "Eoin Goldenglow", meaning: "Young warrior" },
    { name: "Fergus Luckyhand", meaning: "Man of strength" },
    { name: "Gearoid Goldensoul", meaning: "Spear ruler" },
    { name: "Harold Cloversmith", meaning: "Army ruler" },
    { name: "Ivor Goldentooth", meaning: "Bow warrior" },
    { name: "Jack Luckyfingers", meaning: "God is gracious" },
    { name: "Killian Goldenshield", meaning: "Church" },
    { name: "Lorcan Clovershield", meaning: "Little fierce one" },
    { name: "Malachy Goldenshine", meaning: "My kingdom" },
    { name: "Nathaniel Luckyfoot", meaning: "Gift of God" },
    { name: "Oliver Goldentouch", meaning: "Olive tree" },
    { name: "Peter Goldenshoe", meaning: "Rock" },
    { name: "Ronan Luckyheart", meaning: "Little seal" },
    { name: "Sullivan Goldendream", meaning: "Dark-eyed" },
    { name: "Thomas Goldensmile", meaning: "Twin" },
    { name: "Ulick Luckyspark", meaning: "Powerful" },
    { name: "Vaughn Goldenshine", meaning: "Small" },
    { name: "Walter Luckyway", meaning: "Rule of the army" },
    { name: "Xander Goldentrail", meaning: "Defender" },
    { name: "Yuri Luckystone", meaning: "Farmer" },
    { name: "Zane Goldendust", meaning: "God is gracious" },
    { name: "Adam O'Lucky", meaning: "Earth" },
    { name: "Brian Cloverson", meaning: "Strong" },
    { name: "Colin Goldenshield", meaning: "Young creature" },
    { name: "Dylan Goldenshine", meaning: "Son of the sea" },
    { name: "Eoghan Luckypatrick", meaning: "Young warrior" },
    { name: "Fintan Goldenday", meaning: "White fire" },
    { name: "Gary Cloversworth", meaning: "Spear" },
    { name: "Henry Luckyheart", meaning: "Ruler of the home" },
    { name: "Isaac Goldenshoe", meaning: "He laughs" },
    { name: "Jason Goldentouch", meaning: "Healer" },
    { name: "Kyle Goldensmile", meaning: "Narrow strait" },
    { name: "Luke Luckyfingers", meaning: "Light" },
    { name: "Michael Goldenglow", meaning: "Who is like God" },
    { name: "Noah Goldendream", meaning: "Rest" },
    { name: "Oran Luckyspark", meaning: "Little pale green one" },
    { name: "Paul Goldensoul", meaning: "Small" },
    { name: "Richard Goldenshield", meaning: "Strong ruler" },
    { name: "Sam Goldenshine", meaning: "Listener" },
    { name: "Tommy Luckyway", meaning: "Twin" },
    { name: "Umar Goldentrail", meaning: "Long-lived" },
    { name: "Victor Luckystone", meaning: "Conqueror" },
    { name: "Wesley Goldendust", meaning: "West meadow" },
    { name: "Xavier Goldenshield", meaning: "New house" },
    { name: "Youssef Luckyheart", meaning: "God increases" },
    { name: "Zach Goldensmile", meaning: "Remembrance" },
    { name: "Aaron Cloverson", meaning: "Mountain of strength" },
    { name: "Ben Goldenshoe", meaning: "Son of my right hand" },
    { name: "Chris Goldentouch", meaning: "Bearer of Christ" },
    { name: "Dan Goldenshine", meaning: "Judge" },
    { name: "Eddie Luckyspark", meaning: "Rich friend" },
    { name: "Fred Goldendream", meaning: "Peaceful ruler" },
    { name: "George Goldensoul", meaning: "Farmer" },
    { name: "Harry Goldenshield", meaning: "Home ruler" },
    { name: "Ivan Luckyway", meaning: "God is gracious" },
    { name: "John Goldentrail", meaning: "God is gracious" },
    { name: "Ken Luckystone", meaning: "Handsome" },
    { name: "Larry Goldendust", meaning: "Laurel" },
    { name: "Mark Goldenshield", meaning: "Warlike" },
    { name: "Nick Goldensmile", meaning: "Victory of the people" },
    { name: "Oscar Goldenshoe", meaning: "Divine spear" },
    { name: "Phil Goldentouch", meaning: "Lover of horses" },
    { name: "Rob Goldenshine", meaning: "Bright fame" },
    { name: "Steve Luckyspark", meaning: "Crown" },
    { name: "Tim Goldendream", meaning: "Honoring God" },
    { name: "Uri Goldensoul", meaning: "My light" },
    { name: "Vince Goldenshield", meaning: "Conqueror" },
    { name: "Will Luckyway", meaning: "Resolute protector" },
    { name: "Alex Goldentrail", meaning: "Defender" },
    { name: "Benny Luckystone", meaning: "Blessed" },
    { name: "Chad Goldendust", meaning: "Warrior" },
    { name: "Dave Goldenshield", meaning: "Beloved" },
    { name: "Eric Goldensmile", meaning: "Eternal ruler" },
    { name: "Frank Goldenshoe", meaning: "Free" },
    { name: "Greg Goldentouch", meaning: "Watchful" },
    { name: "Hal Goldenshine", meaning: "Rock" },
    { name: "Ian Goldenspark", meaning: "God is gracious" },
    { name: "Jeff Goldendream", meaning: "Peace" },
    { name: "Kenny Goldensoul", meaning: "Handsome" },
    { name: "Lee Goldenshield", meaning: "Meadow" },
    { name: "Matt Luckyway", meaning: "Gift of God" },
    { name: "Neil Goldentrail", meaning: "Champion" },
    { name: "Ollie Luckystone", meaning: "Olive tree" },
    { name: "Pete Goldendust", meaning: "Rock" },
    { name: "Ralph Goldenshield", meaning: "Wolf counsel" },
    { name: "Scott Goldensmile", meaning: "From Scotland" },
    { name: "Ted Goldenshoe", meaning: "Rich guard" },
    { name: "Uriah Goldentouch", meaning: "God is my light" },
    { name: "Vic Goldenshine", meaning: "Conqueror" },
    { name: "Walt Luckyspark", meaning: "Rule" },
    { name: "Andy Goldendream", meaning: "Manly" },
    { name: "Billy Goldensoul", meaning: "Resolute protector" },
    { name: "Cory Goldenshield", meaning: "From the hollow" },
    { name: "Danny Luckyway", meaning: "God is my judge" },
    { name: "Ernie Goldentrail", meaning: "Eagle ruler" },
    { name: "Floyd Luckystone", meaning: "Grey" },
    { name: "Gene Goldendust", meaning: "Well-born" },
    { name: "Hank Goldenshield", meaning: "Ruler of the home" },
    { name: "Ike Goldensmile", meaning: "He laughs" },
    { name: "Jake Goldenshoe", meaning: "Supplanter" },
    { name: "Kirk Goldentouch", meaning: "Church" },
    { name: "Lou Goldenshine", meaning: "Renowned warrior" },
    { name: "Mike Goldenspark", meaning: "Who is like God" },
    { name: "Norm Goldendream", meaning: "Northman" },
    { name: "Ozzie Goldensoul", meaning: "Divine spear" },
    { name: "Pat Goldenshield", meaning: "Noble" },
    { name: "Ray Luckyway", meaning: "Protector" },
    { name: "Sid Goldentrail", meaning: "Wide island" },
    { name: "Todd Luckystone", meaning: "Fox" },
    { name: "Wes Goldendust", meaning: "West meadow" },
    { name: "Al Goldenshield", meaning: "Noble" },
    { name: "Bo Goldensmile", meaning: "Handsome" },
    { name: "Chip Goldenshoe", meaning: "Free man" },
    { name: "Don Goldentouch", meaning: "World ruler" },
    { name: "Earl Goldenshine", meaning: "Nobleman" },
    { name: "Gus Goldenspark", meaning: "Great" },
    { name: "Guy Goldendream", meaning: "Guide" },
    { name: "Jesse Goldensoul", meaning: "Gift" },
    { name: "Marty Goldenshield", meaning: "Warrior" },
    { name: "Syd Luckyway", meaning: "Wide island" },
    { name: "Tyler Goldentrail", meaning: "Tile maker" },
    { name: "Val Luckystone", meaning: "Strong" },
    { name: "Bud Goldendust", meaning: "Friend" },
    { name: "Cal Goldenshield", meaning: "Bald" },
    { name: "Max Goldensmile", meaning: "Greatest" },
    { name: "Rex Goldenshoe", meaning: "King" }
];

const femaleNames = [
    { name: "Abby Clovershine", meaning: "Father rejoiced" },
    { name: "Bridget Goldensoul", meaning: "Strength" },
    { name: "Caitlin Luckystone", meaning: "Pure" },
    { name: "Daisy Goldendust", meaning: "Day's eye" },
    { name: "Erin Goldenshield", meaning: "From Ireland" },
    { name: "Fiona Luckyheart", meaning: "Fair" },
    { name: "Grace Goldensmile", meaning: "Elegance" },
    { name: "Hannah Goldentrail", meaning: "Favor" },
    { name: "Ivy Goldenshoe", meaning: "Faithfulness" },
    { name: "Jenny Luckypatrick", meaning: "God is gracious" },
    { name: "Kate Goldenspark", meaning: "Pure" },
    { name: "Lily Goldendream", meaning: "Pure" },
    { name: "Molly Goldenshield", meaning: "Star of the sea" },
    { name: "Nora Goldenshine", meaning: "Honor" },
    { name: "Olivia Luckyfoot", meaning: "Olive tree" },
    { name: "Penny Goldensoul", meaning: "Weaver" },
    { name: "Quinn Luckyheart", meaning: "Wise" },
    { name: "Rachel Goldensmile", meaning: "Ewe" },
    { name: "Sarah Goldentrail", meaning: "Princess" },
    { name: "Tara Goldenshoe", meaning: "Hill" },
    { name: "Una Luckyspark", meaning: "One" },
    { name: "Vera Goldendream", meaning: "True" },
    { name: "Winnie Goldenshield", meaning: "Friend of peace" },
    { name: "Xandra Goldenshine", meaning: "Defender" },
    { name: "Yvonne Luckyfoot", meaning: "Yew" },
    { name: "Zoe Goldensoul", meaning: "Life" },
    { name: "Aisling Luckystone", meaning: "Dream" },
    { name: "Brigid Goldendust", meaning: "Strong" },
    { name: "Ciara Goldenshield", meaning: "Dark" },
    { name: "Deirdre Goldensmile", meaning: "Sorrow" },
    { name: "Eileen Goldentrail", meaning: "Light" },
    { name: "Fiona Goldenshoe", meaning: "Fair" },
    { name: "Grainne Luckyspark", meaning: "Love" },
    { name: "Helena Goldendream", meaning: "Light" },
    { name: "Irene Goldenshield", meaning: "Peace" },
    { name: "Jane Goldenshine", meaning: "God is gracious" },
    { name: "Katherine Luckyfoot", meaning: "Pure" },
    { name: "Lorna Goldensoul", meaning: "From the laurel tree" },
    { name: "Maeve Luckystone", meaning: "Intoxicating" },
    { name: "Niamh Goldendust", meaning: "Bright" },
    { name: "Orla Goldenshield", meaning: "Golden princess" },
    { name: "Patricia Goldensmile", meaning: "Noble" },
    { name: "Rose Goldentrail", meaning: "Flower" },
    { name: "Sinead Goldenshoe", meaning: "God is gracious" },
    { name: "Theresa Luckyspark", meaning: "Harvester" },
    { name: "Una Goldendream", meaning: "Unity" },
    { name: "Vivian Goldenshield", meaning: "Alive" },
    { name: "Anne Goldenshine", meaning: "Grace" },
    { name: "Barbara Luckyfoot", meaning: "Stranger" },
    { name: "Carol Goldensoul", meaning: "Joy" },
    { name: "Diana Luckystone", meaning: "Divine" },
    { name: "Eve Goldendust", meaning: "Life" },
    { name: "Florence Goldenshield", meaning: "Flowering" },
    { name: "Gladys Goldensmile", meaning: "Princess" },
    { name: "Helen Goldentrail", meaning: "Light" },
    { name: "Iris Goldenshoe", meaning: "Rainbow" },
    { name: "Jean Luckyspark", meaning: "God is gracious" },
    { name: "Kerry Goldendream", meaning: "Black" },
    { name: "Laura Goldenshield", meaning: "Laurel" },
    { name: "Margaret Goldenshine", meaning: "Pearl" },
    { name: "Nancy Luckyfoot", meaning: "Grace" },
    { name: "Olive Goldensoul", meaning: "Olive tree" },
    { name: "Paula Luckystone", meaning: "Small" },
    { name: "Ruth Goldendust", meaning: "Compassionate" },
    { name: "Sally Goldenshield", meaning: "Princess" },
    { name: "Teresa Goldensmile", meaning: "Harvester" },
    { name: "Ursula Goldentrail", meaning: "Little bear" },
    { name: "Violet Goldenshoe", meaning: "Purple flower" },
    { name: "Alice Luckyspark", meaning: "Noble" },
    { name: "Betty Goldendream", meaning: "God is my oath" },
    { name: "Cathy Goldenshield", meaning: "Pure" },
    { name: "Debbie Goldenshine", meaning: "Bee" },
    { name: "Edna Luckyfoot", meaning: "Pleasure" },
    { name: "Frances Goldensoul", meaning: "Free" },
    { name: "Gloria Luckystone", meaning: "Glory" },
    { name: "Hilda Goldendust", meaning: "Battle woman" },
    { name: "Ingrid Goldenshield", meaning: "Beautiful" },
    { name: "Janet Goldensmile", meaning: "God is gracious" },
    { name: "Julie Goldentrail", meaning: "Youthful" },
    { name: "Karen Goldenshoe", meaning: "Pure" },
    { name: "Linda Luckyspark", meaning: "Pretty" },
    { name: "Mary Goldendream", meaning: "Wished-for child" },
    { name: "Nina Goldenshield", meaning: "Little girl" },
    { name: "Opal Goldenshine", meaning: "Gemstone" },
    { name: "Pamela Luckyfoot", meaning: "All sweetness" },
    { name: "Rita Goldensoul", meaning: "Pearl" },
    { name: "Sue Luckystone", meaning: "Lily" },
    { name: "Tina Goldendust", meaning: "Follower" },
    { name: "Viola Goldenshield", meaning: "Violet" },
    { name: "Amy Goldensmile", meaning: "Beloved" },
    { name: "Bonnie Goldentrail", meaning: "Pretty" },
    { name: "Cheryl Goldenshoe", meaning: "Beloved" },
    { name: "Donna Luckyspark", meaning: "Lady" },
    { name: "Elsie Goldendream", meaning: "God is my oath" },
    { name: "Georgia Goldenshield", meaning: "Farmer" },
    { name: "Holly Goldenshine", meaning: "Holly tree" },
    { name: "Ida Luckyfoot", meaning: "Hardworking" },
    { name: "Joan Goldensoul", meaning: "God is gracious" },
    { name: "Kelly Luckystone", meaning: "Warrior" },
    { name: "Lisa Goldendust", meaning: "God is my oath" },
    { name: "Marcia Goldenshield", meaning: "Warlike" },
    { name: "Nellie Goldensmile", meaning: "Light" },
    { name: "Oprah Goldentrail", meaning: "Faerie noblewoman" },
    { name: "Phyllis Goldenshoe", meaning: "Green bough" },
    { name: "Roxanne Luckyspark", meaning: "Dawn" },
    { name: "Stacy Goldendream", meaning: "Resurrection" },
    { name: "Tracy Goldenshield", meaning: "Warrior" },
    { name: "Vanessa Goldenshine", meaning: "Butterfly" },
    { name: "Angie Luckyfoot", meaning: "Messenger" },
    { name: "Brandy Goldensoul", meaning: "Fire" },
    { name: "Crystal Luckystone", meaning: "Ice" },
    { name: "Diane Goldendust", meaning: "Divine" },
    { name: "Erica Goldenshield", meaning: "Ruler" },
    { name: "Faith Goldensmile", meaning: "Trust" },
    { name: "Hope Goldentrail", meaning: "Desire" },
    { name: "Ivy Goldenshoe", meaning: "Climbing plant" },
    { name: "Jackie Luckyspark", meaning: "Supplanter" },
    { name: "Kim Goldendream", meaning: "Royal fortress" },
    { name: "Leslie Goldenshield", meaning: "Joy" },
    { name: "Mandy Goldenshine", meaning: "Love" },
    { name: "Nicole Luckyfoot", meaning: "Victory of the people" },
    { name: "Olivia Goldensoul", meaning: "Olive tree" },
    { name: "Peggy Luckystone", meaning: "Pearl" },
    { name: "Rebecca Goldendust", meaning: "Bind" },
    { name: "Samantha Goldenshield", meaning: "Listener" },
    { name: "Tammy Goldensmile", meaning: "Palm tree" },
    { name: "Valerie Goldentrail", meaning: "Strong" },
    { name: "Angela Goldenshoe", meaning: "Messenger" },
    { name: "Bernice Luckyspark", meaning: "Victory bringer" },
    { name: "Cindy Goldendream", meaning: "Moon" },
    { name: "Denise Goldenshield", meaning: "Dionysus" },
    { name: "Elaine Goldenshine", meaning: "Light" },
    { name: "Ethel Luckyfoot", meaning: "Noble" },
    { name: "Faye Goldensoul", meaning: "Faith" },
    { name: "Gail Luckystone", meaning: "Joy" },
    { name: "Hazel Goldendust", meaning: "Hazel tree" },
    { name: "Irma Goldenshield", meaning: "Universal" },
    { name: "Judy Goldensmile", meaning: "Praise" },
    { name: "Kay Goldentrail", meaning: "Pure" },
    { name: "Louise Goldenshoe", meaning: "Renowned warrior" },
    { name: "Marge Luckyspark", meaning: "Pearl" },
    { name: "Mia Goldendream", meaning: "Mine" },
    { name: "Nell Goldenshield", meaning: "Light" },
    { name: "Ona Goldenshine", meaning: "One" },
    { name: "Patsy Luckyfoot", meaning: "Noble" },
    { name: "Renee Goldensoul", meaning: "Reborn" },
    { name: "Sandy Luckystone", meaning: "Defender" },
    { name: "Tess Goldendust", meaning: "Harvester" },
    { name: "Willow Goldenshield", meaning: "Slender tree" },
    { name: "Dora Goldensmile", meaning: "Gift" },
    { name: "Ella Goldentrail", meaning: "Light" },
    { name: "Gwen Goldenshoe", meaning: "Blessed ring" },
    { name: "May Luckyspark", meaning: "Great" },
    { name: "Rose Goldendream", meaning: "Flower" },
    { name: "Lila Goldenshield", meaning: "Night" },
    { name: "Ruby Goldenshine", meaning: "Red gem" },
    { name: "Clara Luckyfoot", meaning: "Clear" },
    { name: "Etta Goldensoul", meaning: "Ruler" },
    { name: "Lulu Luckystone", meaning: "Pearl" },
    { name: "Maisie Goldendust", meaning: "Pearl" },
    { name: "Sadie Goldenshield", meaning: "Princess" },
    { name: "Effie Goldensmile", meaning: "Well-spoken" },
    { name: "Lottie Goldentrail", meaning: "Free man" },
    { name: "Mabel Goldenshoe", meaning: "Lovable" },
    { name: "Nellie Luckyspark", meaning: "Light" },
    { name: "Queenie Goldendream", meaning: "Queen" },
    { name: "Dot Goldenshield", meaning: "Gift of God" },
    { name: "Kitty Goldenshine", meaning: "Pure" },
    { name: "Betty Luckyfoot", meaning: "God is my oath" },
    { name: "Flo Goldensoul", meaning: "Flowering" },
    { name: "Aggie Luckystone", meaning: "Good" },
    { name: "Annie Goldendust", meaning: "Grace" },
    { name: "Bess Goldenshield", meaning: "God is my oath" },
    { name: "Nell Goldensmile", meaning: "Light" },
    { name: "Hattie Goldentrail", meaning: "Ruler" },
    { name: "Mollie Goldenshoe", meaning: "Star of the sea" },
    { name: "Lizzie Luckyspark", meaning: "God is my oath" },
    { name: "Tilly Goldendream", meaning: "Battle" },
    { name: "Polly Goldenshield", meaning: "Star of the sea" },
    { name: "Dolly Goldenshine", meaning: "Gift of God" },
    { name: "Sally Luckyfoot", meaning: "Princess" },
    { name: "Nelly Goldensoul", meaning: "Light" },
    { name: "Winnie Luckystone", meaning: "Friend of peace" },
    { name: "Gerty Goldendust", meaning: "Spear" },
    { name: "Hettie Goldenshield", meaning: "Ruler" },
    { name: "Lily Goldensmile", meaning: "Pure" },
    { name: "Millie Goldentrail", meaning: "Strength" },
    { name: "Tessie Goldenshoe", meaning: "Harvester" },
    { name: "Effie Luckyspark", meaning: "Well-spoken" },
    { name: "Belle Goldendream", meaning: "Beautiful" },
    { name: "Cora Goldenshield", meaning: "Maiden" },
    { name: "Ella Goldenshine", meaning: "Light" },
    { name: "Hilda Luckyfoot", meaning: "Battle woman" },
    { name: "Ida Goldensoul", meaning: "Hardworking" },
    { name: "Maggie Luckystone", meaning: "Pearl" },
    { name: "Ruth Goldendust", meaning: "Compassionate" },
    { name: "Susie Goldenshield", meaning: "Lily" },
    { name: "Annie Goldensmile", meaning: "Grace" },
    { name: "Daisy Goldentrail", meaning: "Day's eye" },
    { name: "Kitty Goldenshoe", meaning: "Pure" },
    { name: "Maisie Luckyspark", meaning: "Pearl" },
    { name: "Rose Goldendream", meaning: "Flower" }
];

let currentMode = 'random';

document.querySelectorAll('.mode-btn').forEach(btn => {
    btn.addEventListener('click', function() {
        document.querySelectorAll('.mode-btn').forEach(b => b.classList.remove('active'));
        this.classList.add('active');
        currentMode = this.dataset.mode;
    });
});

function generateNames() {
    const grid = document.getElementById('namesGrid');
    grid.innerHTML = '';
    
    let names = [];
    
    if (currentMode === 'male') {
        names = shuffleArray([...maleNames]).slice(0, 16).map(n => ({...n, gender: 'Male'}));
    } else if (currentMode === 'female') {
        names = shuffleArray([...femaleNames]).slice(0, 16).map(n => ({...n, gender: 'Female'}));
    } else {
        const allNames = [
            ...maleNames.map(n => ({...n, gender: 'Male'})),
            ...femaleNames.map(n => ({...n, gender: 'Female'}))
        ];
        names = shuffleArray(allNames).slice(0, 16);
    }
    
    names.forEach((item, index) => {
        const card = document.createElement('div');
        card.className = 'name-card';
        card.style.opacity = '0';
        card.style.transform = 'translateY(20px)';
        card.innerHTML = `
            <div class="name-text">${item.name}</div>
            <div class="name-gender">${item.gender}</div>
            <div class="name-meaning">${item.meaning}</div>
        `;
        grid.appendChild(card);
        
        setTimeout(() => {
            card.style.transition = 'all 0.3s ease';
            card.style.opacity = '1';
            card.style.transform = 'translateY(0)';
        }, index * 40);
    });
}

function shuffleArray(array) {
    for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]];
    }
    return array;
}