const maleNames = [
    { name: "Arthyn", meaning: "Noble light" },
    { name: "Belerion", meaning: "Golden dawn" },
    { name: "Calwen", meaning: "Star song" },
    { name: "Darien", meaning: "Moon guardian" },
    { name: "Eldarion", meaning: "Ancient king" },
    { name: "Falion", meaning: "Sun's flame" },
    { name: "Glorfindel", meaning: "Golden hair" },
    { name: "Hirion", meaning: "Eagle eye" },
    { name: "Ildarion", meaning: "Star child" },
    { name: "Jorunn", meaning: "Storm ruler" },
    { name: "Kaelon", meaning: "Eternal flame" },
    { name: "Lothir", meaning: "Flower prince" },
    { name: "Marethon", meaning: "Sea lord" },
    { name: "Nurion", meaning: "Holy light" },
    { name: "Orodreth", meaning: "Golden crown" },
    { name: "Phaelion", meaning: "Radiant one" },
    { name: "Quelthar", meaning: "Silver hand" },
    { name: "Rilion", meaning: "Dream walker" },
    { name: "Sarethon", meaning: "Sharp mind" },
    { name: "Thalion", meaning: "Strong heart" },
    { name: "Utharion", meaning: "High king" },
    { name: "Valerion", meaning: "Valiant one" },
    { name: "Welthar", meaning: "Wise guardian" },
    { name: "Xyron", meaning: "Mystic seer" },
    { name: "Yavonn", meaning: "Eternal voice" },
    { name: "Zirion", meaning: "Star dancer" },
    { name: "Ancalimon", meaning: "Light bringer" },
    { name: "Belegorn", meaning: "Great warrior" },
    { name: "Celeborn", meaning: "Silver tree" },
    { name: "Diorion", meaning: "Divine light" },
    { name: "Earendil", meaning: "Morning star" },
    { name: "Finrod", meaning: "Fair voice" },
    { name: "Gildor", meaning: "Golden one" },
    { name: "Haldir", meaning: "Hidden lord" },
    { name: "Inglor", meaning: "Great glory" },
    { name: "Legolas", meaning: "Green leaf" },
    { name: "Maglor", meaning: "Great singer" },
    { name: "Nimrodel", meaning: "White pillar" },
    { name: "Orodruin", meaning: "Red mountain" },
    { name: "Peredhel", meaning: "Half-elven" },
    { name: "Quenya", meaning: "High speech" },
    { name: "Rivendel", meaning: "Deep valley" },
    { name: "Sauron", meaning: "Abhorred" },
    { name: "Thranduil", meaning: "Silvan king" },
    { name: "Ungoliant", meaning: "Spider queen" },
    { name: "Varda", meaning: "Sublime" },
    { name: "Celebrimbor", meaning: "Silver fist" },
    { name: "Curufin", meaning: "Skillful one" },
    { name: "Daeron", meaning: "Dark singer" },
    { name: "Ecthelion", meaning: "Glorious" },
    { name: "Fingolfin", meaning: "Strong finder" },
    { name: "Glorfindel", meaning: "Golden hair" },
    { name: "Huor", meaning: "Heart" },
    { name: "Idril", meaning: "Sparkling" },
    { name: "Tuor", meaning: "Strength" },
    { name: "Aegnor", meaning: "Fell fire" },
    { name: "Angrod", meaning: "Iron foot" },
    { name: "Beren", meaning: "Bold" },
    { name: "Caranthir", meaning: "Red face" },
    { name: "Dagor", meaning: "Battle" },
    { name: "Eldar", meaning: "People of starlight" },
    { name: "Fingon", meaning: "Strong finder" },
    { name: "Gimli", meaning: "Fire" },
    { name: "Haldir", meaning: "Hidden" },
    { name: "Irmo", meaning: "Desire" },
    { name: "Luthien", meaning: "Enchantress" },
    { name: "Mandos", meaning: "Doom" },
    { name: "Namo", meaning: "Judge" },
    { name: "Orome", meaning: "Hunter" },
    { name: "Pallando", meaning: "Far wanderer" },
    { name: "Radagast", meaning: "Tender of beasts" },
    { name: "Salmar", meaning: "Instrument maker" },
    { name: "Tulkas", meaning: "Strong" },
    { name: "Ulmo", meaning: "Water" },
    { name: "Vairë", meaning: "Weaver" },
    { name: "Yavanna", meaning: "Giver of fruits" },
    { name: "Aman", meaning: "Blessed realm" },
    { name: "Beleriand", meaning: "Land of Balar" },
    { name: "Calaquendi", meaning: "Elves of light" },
    { name: "Doriath", meaning: "Land of the fence" },
    { name: "Eregion", meaning: "Hollow land" },
    { name: "Formenos", meaning: "Northern fortress" },
    { name: "Gondolin", meaning: "Hidden rock" },
    { name: "Hithlum", meaning: "Mist shadow" },
    { name: "Imladris", meaning: "Deep valley" },
    { name: "Kôr", meaning: "The mansion" },
    { name: "Lindon", meaning: "Land of song" },
    { name: "Mithrim", meaning: "Grey peaks" },
    { name: "Nargothrond", meaning: "Fortress of Nargothrond" },
    { name: "Ossiriand", meaning: "Land of seven rivers" },
    { name: "Pithon", meaning: "Perseverance" },
    { name: "Quintus", meaning: "Fifth" },
    { name: "Raven", meaning: "Dark bird" },
    { name: "Styr", meaning: "Storm" },
    { name: "Talion", meaning: "Vengeance" },
    { name: "Urien", meaning: "Noble ruler" },
    { name: "Valandil", meaning: "Friend of the Valar" },
    { name: "Wingil", meaning: "Friend of wings" },
    { name: "Xenon", meaning: "Stranger" },
    { name: "Yurik", meaning: "Farmer" },
    { name: "Zevran", meaning: "Silver" },
    { name: "Aldric", meaning: "Old ruler" },
    { name: "Bailyn", meaning: "Fair lord" },
    { name: "Casimir", meaning: "Peace bringer" },
    { name: "Darian", meaning: "Upholder" },
    { name: "Eamon", meaning: "Wealthy protector" },
    { name: "Fintan", meaning: "White fire" },
    { name: "Gareth", meaning: "Spear ruler" },
    { name: "Hugh", meaning: "Heart, mind, spirit" },
    { name: "Ivan", meaning: "God is gracious" },
    { name: "Jasper", meaning: "Treasurer" },
    { name: "Kael", meaning: "Slender" },
    { name: "Liam", meaning: "Strong willed" },
    { name: "Milo", meaning: "Soldier" },
    { name: "Nolan", meaning: "Champion" },
    { name: "Owen", meaning: "Young warrior" },
    { name: "Piers", meaning: "Rock" },
    { name: "Quinn", meaning: "Counsel" },
    { name: "Ronan", meaning: "Little seal" },
    { name: "Seamus", meaning: "Supplanter" },
    { name: "Tiernan", meaning: "Lord" },
    { name: "Uriah", meaning: "God is my light" },
    { name: "Vaughn", meaning: "Small" },
    { name: "Wesley", meaning: "Western meadow" },
    { name: "Xavier", meaning: "Bright" },
    { name: "Yannick", meaning: "God is gracious" },
    { name: "Zachary", meaning: "Remembered by God" },
    { name: "Arwenion", meaning: "Noble maiden" },
    { name: "Beleg", meaning: "Swift" },
    { name: "Cirdan", meaning: "Shipwright" },
    { name: "Dior", meaning: "Beautiful" },
    { name: "Eldarion", meaning: "Star son" },
    { name: "Faramir", meaning: "Hunter of secrets" },
    { name: "Glorfindel", meaning: "Golden haired" },
    { name: "Haldir", meaning: "Hidden" },
    { name: "Idril", meaning: "Sparkling" },
    { name: "Legolas", meaning: "Green leaf" },
    { name: "Maglor", meaning: "Great singer" },
    { name: "Nimrodel", meaning: "White pillar" },
    { name: "Orodreth", meaning: "Golden head" },
    { name: "Peredhel", meaning: "Half-elven" },
    { name: "Quelthalas", meaning: "High forest" },
    { name: "Rivendell", meaning: "Deep valley" },
    { name: "Sauron", meaning: "Abhorred" },
    { name: "Thalion", meaning: "Strong" },
    { name: "Uldor", meaning: "Evil" },
    { name: "Valimar", meaning: "Home of the Valar" },
    { name: "Yavanna", meaning: "Giver of fruits" },
    { name: "Zirakzigil", meaning: "Silver peak" },
    { name: "Annon", meaning: "Gate" },
    { name: "Bragollach", meaning: "Battle of sudden flame" },
    { name: "Celebrimbor", meaning: "Silver fist" },
    { name: "Durin", meaning: "Sleeping" },
    { name: "Ecthelion", meaning: "Glorious" },
    { name: "Fingolfin", meaning: "Strong finder" },
    { name: "Grond", meaning: "Hammer" },
    { name: "Huan", meaning: "Great hound" },
    { name: "Isildur", meaning: "Devoted to the moon" },
    { name: "Khamûl", meaning: "Black" },
    { name: "Lothlorien", meaning: "Dream flower" },
    { name: "Morgoth", meaning: "Dark enemy" },
    { name: "Nienna", meaning: "Sorrow" },
    { name: "Orcrist", meaning: "Goblin cleaver" },
    { name: "Pallando", meaning: "Far wanderer" },
    { name: "Radagast", meaning: "Tender of beasts" },
    { name: "Sauron", meaning: "The abhorred" },
    { name: "Tauriel", meaning: "Daughter of the forest" },
    { name: "Ungoliant", meaning: "Spider" },
    { name: "Varda", meaning: "Sublime" },
    { name: "Ylmir", meaning: "Jewel of the world" },
    { name: "Aranion", meaning: "King's son" },
    { name: "Belegorn", meaning: "Great fighter" },
    { name: "Celeborn", meaning: "Silver tree" },
    { name: "Darien", meaning: "Moon" },
    { name: "Eldar", meaning: "Star people" },
    { name: "Finrod", meaning: "Fair voice" },
    { name: "Gildor", meaning: "Golden" },
    { name: "Haldir", meaning: "Hidden" },
    { name: "Inglor", meaning: "Great glory" },
    { name: "Legolas", meaning: "Green leaf" },
    { name: "Maglor", meaning: "Great singer" },
    { name: "Nimrodel", meaning: "White pillar" },
    { name: "Orodruin", meaning: "Red mountain" },
    { name: "Peredhel", meaning: "Half-elven" },
    { name: "Quenya", meaning: "High speech" },
    { name: "Rivendel", meaning: "Deep valley" },
    { name: "Sauron", meaning: "Abhorred" },
    { name: "Thranduil", meaning: "Silvan king" },
    { name: "Ungoliant", meaning: "Spider queen" },
    { name: "Varda", meaning: "Sublime" },
    { name: "Celebrimbor", meaning: "Silver fist" },
    { name: "Curufin", meaning: "Skillful" },
    { name: "Daeron", meaning: "Dark singer" },
    { name: "Ecthelion", meaning: "Glorious" },
    { name: "Fingolfin", meaning: "Strong finder" },
    { name: "Glorfindel", meaning: "Golden hair" },
    { name: "Huor", meaning: "Heart" },
    { name: "Idril", meaning: "Sparkling" },
    { name: "Tuor", meaning: "Strength" },
    { name: "Aegnor", meaning: "Fell fire" },
    { name: "Angrod", meaning: "Iron foot" },
    { name: "Beren", meaning: "Bold" },
    { name: "Caranthir", meaning: "Red face" },
    { name: "Dagor", meaning: "Battle" },
    { name: "Eldar", meaning: "People of starlight" },
    { name: "Fingon", meaning: "Strong finder" },
    { name: "Gimli", meaning: "Fire" },
    { name: "Haldir", meaning: "Hidden" },
    { name: "Irmo", meaning: "Desire" },
    { name: "Luthien", meaning: "Enchantress" },
    { name: "Mandos", meaning: "Doom" },
    { name: "Namo", meaning: "Judge" },
    { name: "Orome", meaning: "Hunter" },
    { name: "Pallando", meaning: "Far wanderer" },
    { name: "Radagast", meaning: "Tender of beasts" },
    { name: "Salmar", meaning: "Instrument maker" },
    { name: "Tulkas", meaning: "Strong" },
    { name: "Ulmo", meaning: "Water" },
    { name: "Vairë", meaning: "Weaver" },
    { name: "Yavanna", meaning: "Giver of fruits" },
    { name: "Aman", meaning: "Blessed realm" },
    { name: "Beleriand", meaning: "Land of Balar" },
    { name: "Calaquendi", meaning: "Elves of light" },
    { name: "Doriath", meaning: "Land of the fence" },
    { name: "Eregion", meaning: "Hollow land" },
    { name: "Formenos", meaning: "Northern fortress" },
    { name: "Gondolin", meaning: "Hidden rock" },
    { name: "Hithlum", meaning: "Mist shadow" },
    { name: "Imladris", meaning: "Deep valley" },
    { name: "Kôr", meaning: "The mansion" },
    { name: "Lindon", meaning: "Land of song" },
    { name: "Mithrim", meaning: "Grey peaks" },
    { name: "Nargothrond", meaning: "Fortress" },
    { name: "Ossiriand", meaning: "Land of seven rivers" },
    { name: "Arthyn", meaning: "Noble light" },
    { name: "Belerion", meaning: "Golden dawn" },
    { name: "Calwen", meaning: "Star song" },
    { name: "Darien", meaning: "Moon guardian" },
    { name: "Eldarion", meaning: "Ancient king" },
    { name: "Falion", meaning: "Sun's flame" },
    { name: "Glorfindel", meaning: "Golden hair" },
    { name: "Hirion", meaning: "Eagle eye" },
    { name: "Ildarion", meaning: "Star child" },
    { name: "Jorunn", meaning: "Storm ruler" },
    { name: "Kaelon", meaning: "Eternal flame" },
    { name: "Lothir", meaning: "Flower prince" },
    { name: "Marethon", meaning: "Sea lord" },
    { name: "Nurion", meaning: "Holy light" },
    { name: "Orodreth", meaning: "Golden crown" },
    { name: "Phaelion", meaning: "Radiant one" },
    { name: "Quelthar", meaning: "Silver hand" },
    { name: "Rilion", meaning: "Dream walker" },
    { name: "Sarethon", meaning: "Sharp mind" },
    { name: "Thalion", meaning: "Strong heart" },
    { name: "Utharion", meaning: "High king" },
    { name: "Valerion", meaning: "Valiant one" },
    { name: "Welthar", meaning: "Wise guardian" },
    { name: "Xyron", meaning: "Mystic seer" },
    { name: "Yavonn", meaning: "Eternal voice" },
    { name: "Zirion", meaning: "Star dancer" },
    { name: "Ancalimon", meaning: "Light bringer" },
    { name: "Belegorn", meaning: "Great warrior" },
    { name: "Celeborn", meaning: "Silver tree" },
    { name: "Diorion", meaning: "Divine light" },
    { name: "Earendil", meaning: "Morning star" },
    { name: "Finrod", meaning: "Fair voice" },
    { name: "Gildor", meaning: "Golden one" },
    { name: "Haldir", meaning: "Hidden lord" },
    { name: "Inglor", meaning: "Great glory" },
    { name: "Legolas", meaning: "Green leaf" },
    { name: "Maglor", meaning: "Great singer" },
    { name: "Nimrodel", meaning: "White pillar" },
    { name: "Orodruin", meaning: "Red mountain" },
    { name: "Peredhel", meaning: "Half-elven" },
    { name: "Quenya", meaning: "High speech" },
    { name: "Rivendel", meaning: "Deep valley" },
    { name: "Sauron", meaning: "Abhorred" },
    { name: "Thranduil", meaning: "Silvan king" },
    { name: "Ungoliant", meaning: "Spider queen" },
    { name: "Varda", meaning: "Sublime" },
    { name: "Celebrimbor", meaning: "Silver fist" },
    { name: "Curufin", meaning: "Skillful one" },
    { name: "Daeron", meaning: "Dark singer" },
    { name: "Ecthelion", meaning: "Glorious" },
    { name: "Fingolfin", meaning: "Strong finder" },
    { name: "Glorfindel", meaning: "Golden hair" },
    { name: "Huor", meaning: "Heart" },
    { name: "Idril", meaning: "Sparkling" },
    { name: "Tuor", meaning: "Strength" },
    { name: "Aegnor", meaning: "Fell fire" },
    { name: "Angrod", meaning: "Iron foot" },
    { name: "Beren", meaning: "Bold" },
    { name: "Caranthir", meaning: "Red face" },
    { name: "Dagor", meaning: "Battle" },
    { name: "Eldar", meaning: "People of starlight" },
    { name: "Fingon", meaning: "Strong finder" },
    { name: "Gimli", meaning: "Fire" },
    { name: "Haldir", meaning: "Hidden" },
    { name: "Irmo", meaning: "Desire" },
    { name: "Luthien", meaning: "Enchantress" },
    { name: "Mandos", meaning: "Doom" },
    { name: "Namo", meaning: "Judge" },
    { name: "Orome", meaning: "Hunter" },
    { name: "Pallando", meaning: "Far wanderer" },
    { name: "Radagast", meaning: "Tender of beasts" },
    { name: "Salmar", meaning: "Instrument maker" },
    { name: "Tulkas", meaning: "Strong" },
    { name: "Ulmo", meaning: "Water" },
    { name: "Vairë", meaning: "Weaver" },
    { name: "Yavanna", meaning: "Giver of fruits" },
    { name: "Aman", meaning: "Blessed realm" },
    { name: "Beleriand", meaning: "Land of Balar" },
    { name: "Calaquendi", meaning: "Elves of light" },
    { name: "Doriath", meaning: "Land of the fence" },
    { name: "Eregion", meaning: "Hollow land" },
    { name: "Formenos", meaning: "Northern fortress" },
    { name: "Gondolin", meaning: "Hidden rock" },
    { name: "Hithlum", meaning: "Mist shadow" },
    { name: "Imladris", meaning: "Deep valley" },
    { name: "Kôr", meaning: "The mansion" },
    { name: "Lindon", meaning: "Land of song" },
    { name: "Mithrim", meaning: "Grey peaks" },
    { name: "Nargothrond", meaning: "Fortress of Nargothrond" },
    { name: "Ossiriand", meaning: "Land of seven rivers" },
    { name: "Arthyn", meaning: "Noble light" },
    { name: "Belerion", meaning: "Golden dawn" },
    { name: "Calwen", meaning: "Star song" },
    { name: "Darien", meaning: "Moon guardian" },
    { name: "Eldarion", meaning: "Ancient king" },
    { name: "Falion", meaning: "Sun's flame" },
    { name: "Glorfindel", meaning: "Golden hair" },
    { name: "Hirion", meaning: "Eagle eye" },
    { name: "Ildarion", meaning: "Star child" },
    { name: "Jorunn", meaning: "Storm ruler" },
    { name: "Kaelon", meaning: "Eternal flame" },
    { name: "Lothir", meaning: "Flower prince" },
    { name: "Marethon", meaning: "Sea lord" },
    { name: "Nurion", meaning: "Holy light" },
    { name: "Orodreth", meaning: "Golden crown" },
    { name: "Phaelion", meaning: "Radiant one" },
    { name: "Quelthar", meaning: "Silver hand" },
    { name: "Rilion", meaning: "Dream walker" },
    { name: "Sarethon", meaning: "Sharp mind" },
    { name: "Thalion", meaning: "Strong heart" },
    { name: "Utharion", meaning: "High king" },
    { name: "Valerion", meaning: "Valiant one" },
    { name: "Welthar", meaning: "Wise guardian" },
    { name: "Xyron", meaning: "Mystic seer" },
    { name: "Yavonn", meaning: "Eternal voice" },
    { name: "Zirion", meaning: "Star dancer" },
    { name: "Ancalimon", meaning: "Light bringer" },
    { name: "Belegorn", meaning: "Great warrior" },
    { name: "Celeborn", meaning: "Silver tree" },
    { name: "Diorion", meaning: "Divine light" },
    { name: "Earendil", meaning: "Morning star" },
    { name: "Finrod", meaning: "Fair voice" },
    { name: "Gildor", meaning: "Golden one" },
    { name: "Haldir", meaning: "Hidden lord" },
    { name: "Inglor", meaning: "Great glory" },
    { name: "Legolas", meaning: "Green leaf" },
    { name: "Maglor", meaning: "Great singer" },
    { name: "Nimrodel", meaning: "White pillar" },
    { name: "Orodruin", meaning: "Red mountain" },
    { name: "Peredhel", meaning: "Half-elven" },
    { name: "Quenya", meaning: "High speech" },
    { name: "Rivendel", meaning: "Deep valley" },
    { name: "Sauron", meaning: "Abhorred" },
    { name: "Thranduil", meaning: "Silvan king" },
    { name: "Ungoliant", meaning: "Spider queen" },
    { name: "Varda", meaning: "Sublime" },
    { name: "Celebrimbor", meaning: "Silver fist" },
    { name: "Curufin", meaning: "Skillful one" },
    { name: "Daeron", meaning: "Dark singer" },
    { name: "Ecthelion", meaning: "Glorious" },
    { name: "Fingolfin", meaning: "Strong finder" },
    { name: "Glorfindel", meaning: "Golden hair" },
    { name: "Huor", meaning: "Heart" },
    { name: "Idril", meaning: "Sparkling" },
    { name: "Tuor", meaning: "Strength" },
    { name: "Aegnor", meaning: "Fell fire" },
    { name: "Angrod", meaning: "Iron foot" },
    { name: "Beren", meaning: "Bold" },
    { name: "Caranthir", meaning: "Red face" },
    { name: "Dagor", meaning: "Battle" },
    { name: "Eldar", meaning: "People of starlight" },
    { name: "Fingon", meaning: "Strong finder" },
    { name: "Gimli", meaning: "Fire" },
    { name: "Haldir", meaning: "Hidden" },
    { name: "Irmo", meaning: "Desire" },
    { name: "Luthien", meaning: "Enchantress" },
    { name: "Mandos", meaning: "Doom" },
    { name: "Namo", meaning: "Judge" },
    { name: "Orome", meaning: "Hunter" },
    { name: "Pallando", meaning: "Far wanderer" },
    { name: "Radagast", meaning: "Tender of beasts" },
    { name: "Salmar", meaning: "Instrument maker" },
    { name: "Tulkas", meaning: "Strong" },
    { name: "Ulmo", meaning: "Water" },
    { name: "Vairë", meaning: "Weaver" },
    { name: "Yavanna", meaning: "Giver of fruits" },
    { name: "Aman", meaning: "Blessed realm" },
    { name: "Beleriand", meaning: "Land of Balar" },
    { name: "Calaquendi", meaning: "Elves of light" },
    { name: "Doriath", meaning: "Land of the fence" },
    { name: "Eregion", meaning: "Hollow land" },
    { name: "Formenos", meaning: "Northern fortress" },
    { name: "Gondolin", meaning: "Hidden rock" },
    { name: "Hithlum", meaning: "Mist shadow" },
    { name: "Imladris", meaning: "Deep valley" },
    { name: "Kôr", meaning: "The mansion" },
    { name: "Lindon", meaning: "Land of song" },
    { name: "Mithrim", meaning: "Grey peaks" },
    { name: "Nargothrond", meaning: "Fortress of Nargothrond" },
    { name: "Ossiriand", meaning: "Land of seven rivers" }
];

const femaleNames = [
    { name: "Arwen", meaning: "Noble maiden" },
    { name: "Beleriand", meaning: "Beautiful land" },
    { name: "Calen", meaning: "Fair one" },
    { name: "Dior", meaning: "Beautiful" },
    { name: "Eldarwen", meaning: "Star maiden" },
    { name: "Falion", meaning: "Sun's flame" },
    { name: "Galadriel", meaning: "Maiden crowned with a radiant garland" },
    { name: "Hirwen", meaning: "Eagle maiden" },
    { name: "Idril", meaning: "Sparkling" },
    { name: "Jolene", meaning: "Fair one" },
    { name: "Kaelis", meaning: "Eternal beauty" },
    { name: "Luthien", meaning: "Enchantress" },
    { name: "Mareth", meaning: "Sea maiden" },
    { name: "Nimrodel", meaning: "White pillar" },
    { name: "Orien", meaning: "Golden one" },
    { name: "Phael", meaning: "Radiant" },
    { name: "Quelwen", meaning: "Silver maiden" },
    { name: "Rilion", meaning: "Dream maiden" },
    { name: "Sareth", meaning: "Sharp mind" },
    { name: "Thalion", meaning: "Strong heart" },
    { name: "Uthwen", meaning: "High maiden" },
    { name: "Valerwen", meaning: "Valiant maiden" },
    { name: "Welwen", meaning: "Wise maiden" },
    { name: "Xyra", meaning: "Mystic" },
    { name: "Yavanna", meaning: "Giver of fruits" },
    { name: "Zira", meaning: "Star" },
    { name: "Ancalime", meaning: "Light maiden" },
    { name: "Belegwen", meaning: "Swift maiden" },
    { name: "Celebrian", meaning: "Silver queen" },
    { name: "Diamir", meaning: "Jewel" },
    { name: "Earwen", meaning: "Sea maiden" },
    { name: "Fingon", meaning: "Strong finder" },
    { name: "Gilwen", meaning: "Golden maiden" },
    { name: "Haldwen", meaning: "Hidden maiden" },
    { name: "Ingwen", meaning: "Great glory" },
    { name: "Legolas", meaning: "Green leaf" },
    { name: "Maglor", meaning: "Great singer" },
    { name: "Nienna", meaning: "Sorrow" },
    { name: "Orodreth", meaning: "Golden crown" },
    { name: "Peredhel", meaning: "Half-elven" },
    { name: "Quenya", meaning: "High speech" },
    { name: "Rivendell", meaning: "Deep valley" },
    { name: "Sauron", meaning: "Abhorred" },
    { name: "Thranduil", meaning: "Silvan king" },
    { name: "Ungoliant", meaning: "Spider queen" },
    { name: "Varda", meaning: "Sublime" },
    { name: "Celebrimbor", meaning: "Silver fist" },
    { name: "Curufin", meaning: "Skillful one" },
    { name: "Daeron", meaning: "Dark singer" },
    { name: "Ecthelion", meaning: "Glorious" },
    { name: "Fingolfin", meaning: "Strong finder" },
    { name: "Glorfindel", meaning: "Golden hair" },
    { name: "Huor", meaning: "Heart" },
    { name: "Idril", meaning: "Sparkling" },
    { name: "Tuor", meaning: "Strength" },
    { name: "Aegnor", meaning: "Fell fire" },
    { name: "Angrod", meaning: "Iron foot" },
    { name: "Beren", meaning: "Bold" },
    { name: "Caranthir", meaning: "Red face" },
    { name: "Dagor", meaning: "Battle" },
    { name: "Eldar", meaning: "People of starlight" },
    { name: "Fingon", meaning: "Strong finder" },
    { name: "Gimli", meaning: "Fire" },
    { name: "Haldir", meaning: "Hidden" },
    { name: "Irmo", meaning: "Desire" },
    { name: "Luthien", meaning: "Enchantress" },
    { name: "Mandos", meaning: "Doom" },
    { name: "Namo", meaning: "Judge" },
    { name: "Orome", meaning: "Hunter" },
    { name: "Pallando", meaning: "Far wanderer" },
    { name: "Radagast", meaning: "Tender of beasts" },
    { name: "Salmar", meaning: "Instrument maker" },
    { name: "Tulkas", meaning: "Strong" },
    { name: "Ulmo", meaning: "Water" },
    { name: "Vairë", meaning: "Weaver" },
    { name: "Yavanna", meaning: "Giver of fruits" },
    { name: "Aman", meaning: "Blessed realm" },
    { name: "Beleriand", meaning: "Land of Balar" },
    { name: "Calaquendi", meaning: "Elves of light" },
    { name: "Doriath", meaning: "Land of the fence" },
    { name: "Eregion", meaning: "Hollow land" },
    { name: "Formenos", meaning: "Northern fortress" },
    { name: "Gondolin", meaning: "Hidden rock" },
    { name: "Hithlum", meaning: "Mist shadow" },
    { name: "Imladris", meaning: "Deep valley" },
    { name: "Kôr", meaning: "The mansion" },
    { name: "Lindon", meaning: "Land of song" },
    { name: "Mithrim", meaning: "Grey peaks" },
    { name: "Nargothrond", meaning: "Fortress of Nargothrond" },
    { name: "Ossiriand", meaning: "Land of seven rivers" },
    { name: "Arwen", meaning: "Noble maiden" },
    { name: "Belegwen", meaning: "Swift maiden" },
    { name: "Celebrian", meaning: "Silver queen" },
    { name: "Diamir", meaning: "Jewel" },
    { name: "Earwen", meaning: "Sea maiden" },
    { name: "Fingon", meaning: "Strong finder" },
    { name: "Gilwen", meaning: "Golden maiden" },
    { name: "Haldwen", meaning: "Hidden maiden" },
    { name: "Ingwen", meaning: "Great glory" },
    { name: "Legolas", meaning: "Green leaf" },
    { name: "Maglor", meaning: "Great singer" },
    { name: "Nienna", meaning: "Sorrow" },
    { name: "Orodreth", meaning: "Golden crown" },
    { name: "Peredhel", meaning: "Half-elven" },
    { name: "Quenya", meaning: "High speech" },
    { name: "Rivendell", meaning: "Deep valley" },
    { name: "Sauron", meaning: "Abhorred" },
    { name: "Thranduil", meaning: "Silvan king" },
    { name: "Ungoliant", meaning: "Spider queen" },
    { name: "Varda", meaning: "Sublime" },
    { name: "Celebrimbor", meaning: "Silver fist" },
    { name: "Curufin", meaning: "Skillful one" },
    { name: "Daeron", meaning: "Dark singer" },
    { name: "Ecthelion", meaning: "Glorious" },
    { name: "Fingolfin", meaning: "Strong finder" },
    { name: "Glorfindel", meaning: "Golden hair" },
    { name: "Huor", meaning: "Heart" },
    { name: "Idril", meaning: "Sparkling" },
    { name: "Tuor", meaning: "Strength" },
    { name: "Aegnor", meaning: "Fell fire" },
    { name: "Angrod", meaning: "Iron foot" },
    { name: "Beren", meaning: "Bold" },
    { name: "Caranthir", meaning: "Red face" },
    { name: "Dagor", meaning: "Battle" },
    { name: "Eldar", meaning: "People of starlight" },
    { name: "Fingon", meaning: "Strong finder" },
    { name: "Gimli", meaning: "Fire" },
    { name: "Haldir", meaning: "Hidden" },
    { name: "Irmo", meaning: "Desire" },
    { name: "Luthien", meaning: "Enchantress" },
    { name: "Mandos", meaning: "Doom" },
    { name: "Namo", meaning: "Judge" },
    { name: "Orome", meaning: "Hunter" },
    { name: "Pallando", meaning: "Far wanderer" },
    { name: "Radagast", meaning: "Tender of beasts" },
    { name: "Salmar", meaning: "Instrument maker" },
    { name: "Tulkas", meaning: "Strong" },
    { name: "Ulmo", meaning: "Water" },
    { name: "Vairë", meaning: "Weaver" },
    { name: "Yavanna", meaning: "Giver of fruits" },
    { name: "Aman", meaning: "Blessed realm" },
    { name: "Beleriand", meaning: "Land of Balar" },
    { name: "Calaquendi", meaning: "Elves of light" },
    { name: "Doriath", meaning: "Land of the fence" },
    { name: "Eregion", meaning: "Hollow land" },
    { name: "Formenos", meaning: "Northern fortress" },
    { name: "Gondolin", meaning: "Hidden rock" },
    { name: "Hithlum", meaning: "Mist shadow" },
    { name: "Imladris", meaning: "Deep valley" },
    { name: "Kôr", meaning: "The mansion" },
    { name: "Lindon", meaning: "Land of song" },
    { name: "Mithrim", meaning: "Grey peaks" },
    { name: "Nargothrond", meaning: "Fortress of Nargothrond" },
    { name: "Ossiriand", meaning: "Land of seven rivers" },
    { name: "Arwen", meaning: "Noble maiden" },
    { name: "Belegwen", meaning: "Swift maiden" },
    { name: "Celebrian", meaning: "Silver queen" },
    { name: "Diamir", meaning: "Jewel" },
    { name: "Earwen", meaning: "Sea maiden" },
    { name: "Fingon", meaning: "Strong finder" },
    { name: "Gilwen", meaning: "Golden maiden" },
    { name: "Haldwen", meaning: "Hidden maiden" },
    { name: "Ingwen", meaning: "Great glory" },
    { name: "Legolas", meaning: "Green leaf" },
    { name: "Maglor", meaning: "Great singer" },
    { name: "Nienna", meaning: "Sorrow" },
    { name: "Orodreth", meaning: "Golden crown" },
    { name: "Peredhel", meaning: "Half-elven" },
    { name: "Quenya", meaning: "High speech" },
    { name: "Rivendell", meaning: "Deep valley" },
    { name: "Sauron", meaning: "Abhorred" },
    { name: "Thranduil", meaning: "Silvan king" },
    { name: "Ungoliant", meaning: "Spider queen" },
    { name: "Varda", meaning: "Sublime" },
    { name: "Celebrimbor", meaning: "Silver fist" },
    { name: "Curufin", meaning: "Skillful one" },
    { name: "Daeron", meaning: "Dark singer" },
    { name: "Ecthelion", meaning: "Glorious" },
    { name: "Fingolfin", meaning: "Strong finder" },
    { name: "Glorfindel", meaning: "Golden hair" },
    { name: "Huor", meaning: "Heart" },
    { name: "Idril", meaning: "Sparkling" },
    { name: "Tuor", meaning: "Strength" },
    { name: "Aegnor", meaning: "Fell fire" },
    { name: "Angrod", meaning: "Iron foot" },
    { name: "Beren", meaning: "Bold" },
    { name: "Caranthir", meaning: "Red face" },
    { name: "Dagor", meaning: "Battle" },
    { name: "Eldar", meaning: "People of starlight" },
    { name: "Fingon", meaning: "Strong finder" },
    { name: "Gimli", meaning: "Fire" },
    { name: "Haldir", meaning: "Hidden" },
    { name: "Irmo", meaning: "Desire" },
    { name: "Luthien", meaning: "Enchantress" },
    { name: "Mandos", meaning: "Doom" },
    { name: "Namo", meaning: "Judge" },
    { name: "Orome", meaning: "Hunter" },
    { name: "Pallando", meaning: "Far wanderer" },
    { name: "Radagast", meaning: "Tender of beasts" },
    { name: "Salmar", meaning: "Instrument maker" },
    { name: "Tulkas", meaning: "Strong" },
    { name: "Ulmo", meaning: "Water" },
    { name: "Vairë", meaning: "Weaver" },
    { name: "Yavanna", meaning: "Giver of fruits" },
    { name: "Aman", meaning: "Blessed realm" },
    { name: "Beleriand", meaning: "Land of Balar" },
    { name: "Calaquendi", meaning: "Elves of light" },
    { name: "Doriath", meaning: "Land of the fence" },
    { name: "Eregion", meaning: "Hollow land" },
    { name: "Formenos", meaning: "Northern fortress" },
    { name: "Gondolin", meaning: "Hidden rock" },
    { name: "Hithlum", meaning: "Mist shadow" },
    { name: "Imladris", meaning: "Deep valley" },
    { name: "Kôr", meaning: "The mansion" },
    { name: "Lindon", meaning: "Land of song" },
    { name: "Mithrim", meaning: "Grey peaks" },
    { name: "Nargothrond", meaning: "Fortress of Nargothrond" },
    { name: "Ossiriand", meaning: "Land of seven rivers" },
    { name: "Arwen", meaning: "Noble maiden" },
    { name: "Belegwen", meaning: "Swift maiden" },
    { name: "Celebrian", meaning: "Silver queen" },
    { name: "Diamir", meaning: "Jewel" },
    { name: "Earwen", meaning: "Sea maiden" },
    { name: "Fingon", meaning: "Strong finder" },
    { name: "Gilwen", meaning: "Golden maiden" },
    { name: "Haldwen", meaning: "Hidden maiden" },
    { name: "Ingwen", meaning: "Great glory" },
    { name: "Legolas", meaning: "Green leaf" },
    { name: "Maglor", meaning: "Great singer" },
    { name: "Nienna", meaning: "Sorrow" },
    { name: "Orodreth", meaning: "Golden crown" },
    { name: "Peredhel", meaning: "Half-elven" },
    { name: "Quenya", meaning: "High speech" },
    { name: "Rivendell", meaning: "Deep valley" },
    { name: "Sauron", meaning: "Abhorred" },
    { name: "Thranduil", meaning: "Silvan king" },
    { name: "Ungoliant", meaning: "Spider queen" },
    { name: "Varda", meaning: "Sublime" },
    { name: "Celebrimbor", meaning: "Silver fist" },
    { name: "Curufin", meaning: "Skillful one" },
    { name: "Daeron", meaning: "Dark singer" },
    { name: "Ecthelion", meaning: "Glorious" },
    { name: "Fingolfin", meaning: "Strong finder" },
    { name: "Glorfindel", meaning: "Golden hair" },
    { name: "Huor", meaning: "Heart" },
    { name: "Idril", meaning: "Sparkling" },
    { name: "Tuor", meaning: "Strength" },
    { name: "Aegnor", meaning: "Fell fire" },
    { name: "Angrod", meaning: "Iron foot" },
    { name: "Beren", meaning: "Bold" },
    { name: "Caranthir", meaning: "Red face" },
    { name: "Dagor", meaning: "Battle" },
    { name: "Eldar", meaning: "People of starlight" },
    { name: "Fingon", meaning: "Strong finder" },
    { name: "Gimli", meaning: "Fire" },
    { name: "Haldir", meaning: "Hidden" },
    { name: "Irmo", meaning: "Desire" },
    { name: "Luthien", meaning: "Enchantress" },
    { name: "Mandos", meaning: "Doom" },
    { name: "Namo", meaning: "Judge" },
    { name: "Orome", meaning: "Hunter" },
    { name: "Pallando", meaning: "Far wanderer" },
    { name: "Radagast", meaning: "Tender of beasts" },
    { name: "Salmar", meaning: "Instrument maker" },
    { name: "Tulkas", meaning: "Strong" },
    { name: "Ulmo", meaning: "Water" },
    { name: "Vairë", meaning: "Weaver" },
    { name: "Yavanna", meaning: "Giver of fruits" },
    { name: "Aman", meaning: "Blessed realm" },
    { name: "Beleriand", meaning: "Land of Balar" },
    { name: "Calaquendi", meaning: "Elves of light" },
    { name: "Doriath", meaning: "Land of the fence" },
    { name: "Eregion", meaning: "Hollow land" },
    { name: "Formenos", meaning: "Northern fortress" },
    { name: "Gondolin", meaning: "Hidden rock" },
    { name: "Hithlum", meaning: "Mist shadow" },
    { name: "Imladris", meaning: "Deep valley" },
    { name: "Kôr", meaning: "The mansion" },
    { name: "Lindon", meaning: "Land of song" },
    { name: "Mithrim", meaning: "Grey peaks" },
    { name: "Nargothrond", meaning: "Fortress of Nargothrond" },
    { name: "Ossiriand", meaning: "Land of seven rivers" },
    { name: "Arwen", meaning: "Noble maiden" },
    { name: "Belegwen", meaning: "Swift maiden" },
    { name: "Celebrian", meaning: "Silver queen" },
    { name: "Diamir", meaning: "Jewel" },
    { name: "Earwen", meaning: "Sea maiden" },
    { name: "Fingon", meaning: "Strong finder" },
    { name: "Gilwen", meaning: "Golden maiden" },
    { name: "Haldwen", meaning: "Hidden maiden" },
    { name: "Ingwen", meaning: "Great glory" },
    { name: "Legolas", meaning: "Green leaf" },
    { name: "Maglor", meaning: "Great singer" },
    { name: "Nienna", meaning: "Sorrow" },
    { name: "Orodreth", meaning: "Golden crown" },
    { name: "Peredhel", meaning: "Half-elven" },
    { name: "Quenya", meaning: "High speech" },
    { name: "Rivendell", meaning: "Deep valley" },
    { name: "Sauron", meaning: "Abhorred" },
    { name: "Thranduil", meaning: "Silvan king" },
    { name: "Ungoliant", meaning: "Spider queen" },
    { name: "Varda", meaning: "Sublime" },
    { name: "Celebrimbor", meaning: "Silver fist" },
    { name: "Curufin", meaning: "Skillful one" },
    { name: "Daeron", meaning: "Dark singer" },
    { name: "Ecthelion", meaning: "Glorious" },
    { name: "Fingolfin", meaning: "Strong finder" },
    { name: "Glorfindel", meaning: "Golden hair" },
    { name: "Huor", meaning: "Heart" },
    { name: "Idril", meaning: "Sparkling" },
    { name: "Tuor", meaning: "Strength" },
    { name: "Aegnor", meaning: "Fell fire" },
    { name: "Angrod", meaning: "Iron foot" },
    { name: "Beren", meaning: "Bold" },
    { name: "Caranthir", meaning: "Red face" },
    { name: "Dagor", meaning: "Battle" },
    { name: "Eldar", meaning: "People of starlight" },
    { name: "Fingon", meaning: "Strong finder" },
    { name: "Gimli", meaning: "Fire" },
    { name: "Haldir", meaning: "Hidden" },
    { name: "Irmo", meaning: "Desire" },
    { name: "Luthien", meaning: "Enchantress" },
    { name: "Mandos", meaning: "Doom" },
    { name: "Namo", meaning: "Judge" },
    { name: "Orome", meaning: "Hunter" },
    { name: "Pallando", meaning: "Far wanderer" },
    { name: "Radagast", meaning: "Tender of beasts" },
    { name: "Salmar", meaning: "Instrument maker" },
    { name: "Tulkas", meaning: "Strong" },
    { name: "Ulmo", meaning: "Water" },
    { name: "Vairë", meaning: "Weaver" },
    { name: "Yavanna", meaning: "Giver of fruits" },
    { name: "Aman", meaning: "Blessed realm" },
    { name: "Beleriand", meaning: "Land of Balar" },
    { name: "Calaquendi", meaning: "Elves of light" },
    { name: "Doriath", meaning: "Land of the fence" },
    { name: "Eregion", meaning: "Hollow land" },
    { name: "Formenos", meaning: "Northern fortress" },
    { name: "Gondolin", meaning: "Hidden rock" },
    { name: "Hithlum", meaning: "Mist shadow" },
    { name: "Imladris", meaning: "Deep valley" },
    { name: "Kôr", meaning: "The mansion" },
    { name: "Lindon", meaning: "Land of song" },
    { name: "Mithrim", meaning: "Grey peaks" },
    { name: "Nargothrond", meaning: "Fortress of Nargothrond" },
    { name: "Ossiriand", meaning: "Land of seven rivers" }
];

function shuffleArray(array) {
    const shuffled = [...array];
    for (let i = shuffled.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
    }
    return shuffled;
}

function generateNames() {
    const modeButtons = document.querySelectorAll('.mode-btn');
    let currentMode = 'random';
    
    modeButtons.forEach(btn => {
        if (btn.classList.contains('active')) {
            currentMode = btn.dataset.mode;
        }
    });
    
    let names;
    
    if (currentMode === 'male') {
        names = shuffleArray(maleNames).slice(0, 16);
    } else if (currentMode === 'female') {
        names = shuffleArray(femaleNames).slice(0, 16);
    } else {
        const combined = [...maleNames, ...femaleNames];
        names = shuffleArray(combined).slice(0, 16);
    }
    
    const namesGrid = document.getElementById('namesGrid');
    namesGrid.innerHTML = '';
    
    names.forEach(nameObj => {
        const card = document.createElement('div');
        card.className = 'name-card';
        
        const nameText = document.createElement('div');
        nameText.className = 'name-text';
        nameText.textContent = nameObj.name;
        
        const genderBadge = document.createElement('div');
        genderBadge.className = 'name-gender';
        genderBadge.textContent = currentMode === 'random' ? 'Random' : (currentMode === 'male' ? 'Male' : 'Female');
        
        const meaningText = document.createElement('div');
        meaningText.className = 'name-meaning';
        meaningText.textContent = nameObj.meaning;
        
        card.appendChild(nameText);
        card.appendChild(genderBadge);
        card.appendChild(meaningText);
        
        namesGrid.appendChild(card);
    });
}

document.querySelectorAll('.mode-btn').forEach(btn => {
    btn.addEventListener('click', () => {
        document.querySelectorAll('.mode-btn').forEach(b => b.classList.remove('active'));
        btn.classList.add('active');
    });
});